### ISSUE TITLE
awq 微调后如何推理

### ISSUE THREAD

**Issue by hehuang139** [modelscope/swift#1002]
qwen1.5-14b-chat-awq量化后，查文档得知是不支持合并的，但是推理部分又都是要求merge的模型，推理的文档都查看过了，没有找到方法，是不支持推理吗？

**Comment by hehuang139** [comment]
![image](https://github.com/modelscope/swift/assets/9929843/5aa2b99d-3171-4263-9702-ec5ac1c12649)

**Comment by Jintao-Huang** [comment]
没有懂，你是qlora微调过了吗

**Comment by hehuang139** [comment]
我改成qlora再试了，之前是awq的模型做微调，无法merge

**Comment by Greywan** [comment]
> 我改成qlora再试了，之前是awq的模型做微调，无法merge

所以你是 qlora 微调原始模型，然后再 merge 的吗？
