### ISSUE TITLE
微调qwen后会循环输出

### ISSUE THREAD

**Issue by sherry085** [modelscope/swift#1009]
![image](https://github.com/modelscope/swift/assets/52395960/67da5e9c-915d-4cd9-9f18-950110309bb2)
![image](https://github.com/modelscope/swift/assets/52395960/67da5e9c-915d-4cd9-9f18-950110309bb2)
![Uploading image.png…]()

**Comment by Jintao-Huang** [comment]
多训练几个epoch. 你现在是微调了几个epoch

**Comment by sherry085** [comment]
> 多训练几个epoch. 你现在是微调了几个epoch

您好，感谢解答。我是针对一个自定义数据集（56个问答对）加上自我认知，以及两个开源进行微调的，
![image](https://github.com/modelscope/swift/assets/52395960/f6ab2273-3fa0-4037-a6a3-990afb5d1c8c)
我尝试了微调1～3个epoch，学习率和warm_up尝试了两组，[learning_rate=1e-4,warmup_ratio=0.03], [learning_rate=5e-5, warmup_ratio=0.4,]自我认知和其他问题回答都没有问题，只针对自定义（tab_des)会出问题，一是重复输出，二是没有学习到这个表，回答说不知道。

**Comment by sherry085** [comment]
@Jintao-Huang

**Comment by liuhuan-gl** [comment]
我多训几个轮次后,有效果

**Comment by sherry085** [comment]
> 我多训几个轮次后,有效果

@liuhuan-gl 你好，想请教下你的数据集体量和训练轮数，我试了5轮还是不太行，有时候不循环了，但是胡说八道，问数据集里的原问题都答不上来，只有自定义数据集出问题，其他数据集（如自我认知）相关的问题没什么问题。

**Comment by liuhuan-gl** [comment]
我刚开始训练1轮测试结果和你的问题一样，也会重复，1200组对话，然后训练了110轮次效果好了很多

**Comment by sherry085** [comment]
> 我刚开始训练1轮测试结果和你的问题一样，也会重复，1200组对话，然后训练了110轮次效果好了很多
@liuhuan-gl 谢谢你的解答～不过110轮会不会过拟合，出现基础知识的遗忘呀

**Comment by liuhuan-gl** [comment]
也许会，我还没测试其余数据，测完以后告诉你

**Comment by sherry085** [comment]
> 也许会，我还没测试其余数据，测完以后告诉你

好呀，谢谢 @liuhuan-gl
