### ISSUE TITLE
Multimodal Deployment question

### ISSUE THREAD

**Issue by babla9** [modelscope/swift#1042]
Thanks so much for adding the multimodal deployment work! I had the following questions: 
1. Can all multimodal models supported by SWIFT be deployed using this framework? (eg Phi-Vision, InternXLM-Composer2, and other models [listed here](https://github.com/modelscope/swift/tree/main/docs/source_en/Multi-Modal)?
2. What are the deployment GPU requirements? Are they the same as single-sample inference requirements in the docs? (eg 21gb for [this example](https://github.com/modelscope/swift/tree/main/docs/source_en/Multi-Modal) is enough to deploy this model?

**Comment by Jintao-Huang** [comment]
1. Yes, all multimodal models are deployable, but they use PyTorch as the inference backend. Faster inference acceleration frameworks will be integrated later.
2. Yes.
