### ISSUE TITLE
The operator 'aten::isin.Tensor_Tensor_out' is not currently supported on the NPU backend

### ISSUE THREAD

**Issue by askcs517** [modelscope/swift#1047]
The operator 'aten::isin.Tensor_Tensor_out' is not currently supported on the NPU backend and will fall back to run on CPU

**Comment by Jintao-Huang** [comment]
Please use a different model or replace it with the source code of the model.

**Comment by askcs517** [comment]
您好，您的邮件我已经收到，我会及时查收。麻烦您了。

**Comment by askcs517** [comment]
您好，您的邮件我已经收到，我会及时查收。麻烦您了。
