### ISSUE TITLE
mini_internvl_chat_4b_v1_5 Template需要更新

### ISSUE THREAD

**Issue by FoolishMao** [modelscope/swift#1049]
**Describe the bug**
What the bug is, and how to reproduce, better with screenshots(描述bug以及复现过程，最好有截图)
![image](https://github.com/modelscope/swift/assets/36061157/addbc274-a97c-43fb-9e30-d958a4c4767b)

**Your hardware and system info**
Write your system info like CUDA version/system/GPU/torch version here(在这里给出硬件信息和系统信息，如CUDA版本，系统，GPU型号和torch版本等)

**Additional context**
Add any other context about the problem here(在这里补充其他信息)

**Comment by hjh0119** [comment]
fixed https://github.com/modelscope/swift/pull/1053
