### ISSUE TITLE
size mismatch when loading deepseek-vl for sft

### ISSUE THREAD

**Issue by Liu0329** [modelscope/swift#1058]
```
# Experimental Environment: 4 * Ascend 910B3
# GPU Memory Requirement: 4 * 25GB
# Runtime: 8.5 hours
NPROC_PER_NODE=4 \
ASCEND_RT_VISIBLE_DEVICES=0,1,2,3 \
swift sft \
    --local_repo_path /path/to/DeepSeek-VL \
    --model_type deepseek-vl-7b-chat \
    --model_id_or_path /path/to/deepseek-vl-7b-chat \
    --dataset coco-en-mini \
    --num_train_epochs 5 \
    --sft_type full \
    --output_dir output \
    --deepspeed default-zero3 \
```

I also tried sft_type of lora, same problem:

RuntimeError: Error(s) in loading state_dict for MultiModalityCausalLM:
        size mismatch for vision_model.vision_tower_high.vision_tower.neck_hd.0.weight: copying a param with shape torch.Size([256, 768, 1, 1]) from checkpoint, the shape in current model is torch.Size([0]).
        size mismatch for vision_model.vision_tower_high.vision_tower.neck_hd.1.weight: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([0]).
        size mismatch for vision_model.vision_tower_high.vision_tower.neck_hd.1.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([0]).
        size mismatch for vision_model.vision_tower_high.vision_tower.neck_hd.2.weight: copying a param with shape torch.Size([256, 256, 3, 3]) from checkpoint, the shape in current model is torch.Size([0]).
        size mismatch for vision_model.vision_tower_high.vision_tower.neck_hd.3.weight: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([0]).
        size mismatch for vision_model.vision_tower_high.vision_tower.neck_hd.3.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([0]).
        You may consider adding `ignore_mismatched_sizes=True` in the model `from_pretrained` method.

**Comment by Jintao-Huang** [comment]
不支持zero3, 请使用zero2

**Comment by Liu0329** [comment]
@Jintao-Huang Thanks, zero2 worked. Another question is can I resume training from lora ckpts without merging ?

**Comment by Jintao-Huang** [comment]
You can use the resume_from_checkpointing interface provided by the transformers Trainer. However, it seems that it is not very user-friendly.

**Comment by Liu0329** [comment]
@Jintao-Huang I use these two args, both to the same ckpt
```
--model_id_or_path output/full/deepseek-vl-7b-chat/v0-20240605-145918/checkpoint-19000 \
--resume_from_checkpoint output/full/deepseek-vl-7b-chat/v0-20240605-145918/checkpoint-19000 \
```
shows
ValueError: Can't find a valid checkpoint at the location

**Comment by Jintao-Huang** [comment]
model_id_or_path 使用  /path/to/deepseek-vl-7b-chat \
