### ISSUE TITLE
batch_size默认使用1 数据集为1800多条 epoch为3 为什么step是351呢？

### ISSUE THREAD

**Issue by GuoXu-booo** [modelscope/swift#1067]
您好！我在sft internlm-xcomposer2模型 ；batch_size默认使用1 数据集为1800多条 epoch为3 为什么step是351呢？ 计算了一下batch_size 应该是 16 ；还有哪些参数影响step呢？ @Jintao-Huang 
![17174996586496](https://github.com/modelscope/swift/assets/54988783/2eeefe9a-b9e1-4b53-845a-47d2fda7069c)

**Comment by hjh0119** [comment]
--gradient_accumulation_steps: 梯度累加, 默认值为None, 设置为math.ceil(16 / self.batch_size / world_size). total_batch_size =  batch_size * gradient_accumulation_steps * world_size.

**Comment by GuoXu-booo** [comment]
> --gradient_accumulation_steps： 梯度累加， 默认值为None， 设置为math.ceil（16 / self.batch_size / world_size）.total_batch_size = batch_size * gradient_accumulation_steps * world_size。

万分感谢您的回复！
