### ISSUE TITLE
使用SimPO算法加载数据集很慢

### ISSUE THREAD

**Issue by zhangfan-algo** [modelscope/swift#1073]
**Describe the bug**
Parameter 'function'=<bound method SimPOTrainer.tokenize_row of <swift.trainers.simpo_trainers.SimPOTrainer object at 0x7fa21c10f280>> of the transform datasets.arrow_dataset.Dataset._map_single couldn't be hashed properly, a random hash was used instead. Make sure your transforms and parameters are serializable with pickle or dill for the dataset fingerprinting and caching to work. If you reuse this transform, the caching mechanism will consider it to be different from the previous calls and recompute everything. This warning is only showed once. Subsequent hashing failures won't be showed.
**Your hardware and system info**
下拉最新代码后 运行SimPO无法使用lazy tokenizer

**Comment by hjh0119** [comment]
对齐系算法会在trainer内部做统一的encode，这块不好修改
