### ISSUE TITLE
internvl-chat-v1_5部署成功，但是接口调用失败

### ISSUE THREAD

**Issue by zhengzehong** [modelscope/swift#1076]
**Describe the bug**

CUDA_VISIBLE_DEVICES=0 
swift deploy --model_type internvl-chat-v1_5
 --model_id_or_path /root/autodl-tmp/models/InternVL-Chat-V1-5
 --dtype bf16
  --port 6006

使用上述命令部署internvl-chat-v1_5成功

![bug](https://github.com/modelscope/swift/assets/23031565/85dc380c-7d8d-4d05-b353-3847f8753efe)
使用上述方式调用

![image](https://github.com/modelscope/swift/assets/23031565/fb4cc0a8-a3ad-43b0-aa0f-07aadb78bd18)
报错 
ValueError: Input length of input_ids is 0, but `max_length` is set to -271. This can lead to unexpected behavior. You should consider increasing `max_length` or, better yet, setting `max_new_tokens`.

后续在启动命令添加 --max_length 6000，也是不行

**Your hardware and system info**
Write your system info like CUDA version/system/GPU/torch version here(在这里给出硬件信息和系统信息，如CUDA版本，系统，GPU型号和torch版本等)
torch 2.3.0 GPU 单卡A800

**Additional context**
Add any other context about the problem here(在这里补充其他信息)

**Comment by DWCTOD** [comment]
你好，这个问题好像还是存在
