### ISSUE TITLE
请教双4090 lora glm3-6b-32k 显存溢出问题

### ISSUE THREAD

**Issue by zzisbeauty** [modelscope/swift#1085]
【**Describe the bug**】

请问老师

问题：RT

这科学吗？ 我的句子（prompt） max-length 确实较长，长的有 1W多个字符长度， 我一开始以为是我数据过长导致

所以我设置 max length 短一些，但是又出现这个问题：

![image](https://github.com/modelscope/swift/assets/137602905/ddb664d6-8028-4209-aca9-52f20fa5e1e0)

因此我进一步在 max-length 很长的情况下，添加参数：`truncation_strategy` = delete
但是依然会爆出显存溢出

也就是说，我设置短了， 爆出截图的错误；设置长了，显存溢出

我是双卡 4090， lora 一个 6B的模型，  显存溢出，这科学吗？

- 另外我想知道的是，max-length 代表的是最大 tokens  数吧，如果是，它换算成字符的话，大概是多少个呢？ 我知道不同模型分词过程不太一样，但是大致呢？ 或者说平均水平呢？

【**我的启动脚本**】

```
# Experimental environment: A10, 3090, V100, ...
# 20GB GPU memory
import os

os.environ['CUDA_VISIBLE_DEVICES'] = '3'

import torch

from swift.llm import (DatasetName, InferArguments, ModelType, SftArguments,infer_main, sft_main, app_ui_main)


sft_args = SftArguments(
    # 模型设置
    model_type=ModelType.chatglm3_6b_32k,
    model_id_or_path='/home/train_infer_quanti_vllm/untrackfiles/old-model-chatglm3-6b-32k-base',

    # 注册数据集
    # dataset=[f'{DatasetName.blossom_math_zh}#2000'],
    # 本地数据集
    # dataset=['/home/train_infer_quanti_vllm/datasets/trainconv240101-0529/train-data-base-p3-no-url.jsonl'],
    dataset='/home/train_infer_quanti_vllm/datasets/std-data/demo-std.jsonl',
    max_length=5000,
    # truncation_strategy='delete',

    # 训练参数
    # dtype='bf16',
    # deepspeed='/home/train_infer_quanti_vllm/swift/llm/ds_config/zero3_offload.json',
    # save_only_model=True,

    num_train_epochs=5,
    gradient_checkpointing=True,
    sft_type='lora', # 设定 lora 后，关于 lora 的其它参数保持默认
    learning_rate=1e-4,
    tuner_backend='peft',
    output_dir='/home/train_infer_quanti_vllm/untrackfiles/output',
)
result = sft_main(sft_args)
best_model_checkpoint = result['best_model_checkpoint']
print(f'best_model_checkpoint: {best_model_checkpoint}')
torch.cuda.empty_cache()

# infer_args = InferArguments(
#     ckpt_dir=best_model_checkpoint,
#     load_dataset_config=True)
# # merge_lora(infer_args, device_map='cpu')
# result = infer_main(infer_args)
# torch.cuda.empty_cache()
# app_ui_main(infer_args)

```

@Jintao-Huang  期待尽快得到老师的答复。

**Comment by Jintao-Huang** [comment]
你先将 max_length 设置为-1看看 数据集的统计量, 会在命令后打印

**Comment by zzisbeauty** [comment]
> 你先将 max_length 设置为-1看看 数据集的统计量, 会在命令后打印

我之前尝试过，刚才我又设置 -1 运行，但是依然是显存错误。 我觉得有价值的信息在这里：

![image](https://github.com/modelscope/swift/assets/137602905/1666868f-7903-4adf-b9e0-6a554114a120)

![image](https://github.com/modelscope/swift/assets/137602905/c3ff5011-730f-4757-99c6-ad55b01e87ad)

请问老师，是否有问题呢？ 或者说哪里存在问题呢？

**Comment by zzisbeauty** [comment]
就是序列太长了。淦~   缩短一下就OK了。  但是我很奇怪的是：

当我缩减完数据，最长的编程不到 10000； 我之前也尝试设置了 max-length == 10000； 且设置了查过这个长度的数据 `delete` 的参数， 为什么就会报出显存异常呢？

也就是说，swift 不允许训练集中有过长的数据，即使设置了 max-length 以及数据切割方案的参数。

**Comment by Jintao-Huang** [comment]
你找一下 命令行输出中的 tokens统计量

**Comment by Jintao-Huang** [comment]
如果是超过max_length 会进行删除

**Comment by Jintao-Huang** [comment]
句子长度越长, 显存要求越大
