### ISSUE TITLE
InternVL-v1.5微调时报错以及爆显存

### ISSUE THREAD

**Issue by McCarthyjfq** [modelscope/swift#1086]
我现在用的是4张A100的40G显卡，跑InternVL-v1.5的lora微调，当我不使用deepspeed时，全部调用这四张卡也会爆显存。当我使用教程里给的default-zero2时会有以下报错，UserWarning: None of the inputs have requires_grad=True. Gradients will be None以及
AttributeError: 'DummyOptim' object has no attribute 'step'。当我使用在官方微调时成功跑下来的deepspeed文件zero3时虽然我脚本写的用4张显卡跑，但实际会只使用一张显卡然后爆内存，zero3代码如下：
{
    "fp16": {
        "enabled": "auto",
        "loss_scale": 0,
        "loss_scale_window": 1000,
        "initial_scale_power": 16,
        "hysteresis": 2,
        "min_loss_scale": 1
    },
    "bf16": {
        "enabled": "auto"
    },
    "train_micro_batch_size_per_gpu": "auto",
    "train_batch_size": "auto",
    "gradient_accumulation_steps": "auto",
    "zero_optimization": {
        "stage": 3,
        "overlap_comm": true,
        "contiguous_gradients": true,
        "sub_group_size": 1e9,
        "reduce_bucket_size": 1e9,
        "stage3_prefetch_bucket_size": 1e9,
        "stage3_param_persistence_threshold": 1e7,
        "stage3_max_live_parameters": 1e9,
        "stage3_max_reuse_distance": 1e9,
        "stage3_gather_16bit_weights_on_model_save": true
    }
}
请问有什么办法可以解决这些问题或者其中之一，非常感谢！

**Comment by hjh0119** [comment]
是用最新的代码吗 我这边测试显存是正常的
```
CUDA_VISIBLE_DEVICES=0,1,2,3 swift sft \
    --model_type internvl-chat-v1_5 \
    --dataset coco-en-2-mini \
```
![image](https://github.com/modelscope/swift/assets/112739147/5b2318bb-0839-4341-b116-162b57f8f792)

**Comment by hjh0119** [comment]
deepspeed显存占用介于ddp和mp之间，40G不够是正常的，走mp吧。

**Comment by McCarthyjfq** [comment]
> 是用最新的代码吗 我这边测试显存是正常的
> 
> ```
> CUDA_VISIBLE_DEVICES=0,1,2,3 swift sft \
>     --model_type internvl-chat-v1_5 \
>     --dataset coco-en-2-mini \
>     --max_length 4096
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/112739147/337549276-5b2318bb-0839-4341-b116-162b57f8f792.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwNjk4NzIsIm5iZiI6MTcxODA2OTU3MiwicGF0aCI6Ii8xMTI3MzkxNDcvMzM3NTQ5Mjc2LTViMjMxOGJiLTA4MzktNDM0MS1iMTE2LTE2MmI1N2Y4Zjc5Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxMVQwMTMyNTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNzAwMWI0Yjc5N2MwN2YxZjU2MDAwNmIzZTE3NjA1OTc4YjcyOTRiMTRjYTk3MTMyYTViNDYyMGVmNWQwM2FiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.M0RoqyTAYvTKnWhXaynkckuNKUHQ7vACaPMA9GfHnvA)

我把你的脚本的dataset换成我自己的dataset的path了，maxlength对应修改了，然后加了一行--model_id_or_path，对应我本地的model路径，这个是我的内存占用情况，还是会爆内存，请问老师为什么会这样，有什么办法吗？

CUDA_VISIBLE_DEVICES=0,1,2,3 swift sft \
    --model_type internvl-chat-v1_5 \
    --model_id_or_path "/.../InternVL-Chat-V1-5" \
    --dataset /..../swift_data_v2.jsonl \
    --max_length 11801 \

![image](https://github.com/modelscope/swift/assets/144629782/e8bb0b92-9077-4641-bc49-656927cce624)

**Comment by McCarthyjfq** [comment]
> deepspeed显存占用介于ddp和mp之间，40G不够是正常的，走mp吧。

mp是只要改deepspeed文件就可以了是吗？刚刚改了一下还是会爆，而且还是只调用了一张卡，很奇怪

**Comment by hjh0119** [comment]
> mp是只要改deepspeed文件就可以了是吗？刚刚改了一下还是会爆，而且还是只调用了一张卡，很奇怪

这个已经是mp了
> ```
> CUDA_VISIBLE_DEVICES=0,1,2,3 swift sft \
>     --model_type internvl-chat-v1_5 \
>     --model_id_or_path "/.../InternVL-Chat-V1-5" \
>     --dataset /..../swift_data_v2.jsonl \
>     --max_length 11801 \
> ```
试下 `--use_flash_attn true` 然后控制下max_length吧

**Comment by hjh0119** [comment]
@McCarthyjfq gradient_checkpoting 之前有修复过，源码安装下swift再试下？

**Comment by McCarthyjfq** [comment]
> @McCarthyjfq gradient_checkpoting 之前有修复过，源码安装下swift再试下？

重新装了一下swift，现在加上gradient_checkpoint true参数之后可以训练了但还是会报这个错：UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn("None of the inputs have requires_grad=True. Gradients will be None")。但我看了一下loss在下降，acc是在上升的，所以训练应该没什么问题。非常感谢前辈的指导！
