### ISSUE TITLE
glm4v在Merge lora后推理报错

### ISSUE THREAD

**Issue by Wimen** [modelscope/swift#1091]
使用自建数据集对glm4v进行微调，完成后ckpt指定output/glm4v-9b-chat/vx-xxx/checkpoint-xxx可正常进行推理，若先进行export，再指定ckpt为output/glm4v-9b-chat/vx-xxx/checkpoint-xxx-merged时，模型推理会有以下错误：
![6351717682256_ pic](https://github.com/modelscope/swift/assets/47681766/96774c96-7d58-4522-9b17-bc58169086c9)

**Comment by Wimen** [comment]
@Jintao-Huang 请问这个问题有复现到吗

**Comment by Jintao-Huang** [comment]
复现了

**Comment by Jintao-Huang** [comment]
fixed

**Comment by Wimen** [comment]
cool，已验证

**Comment by chensiqin** [comment]
@XuRui314 请问你的微调参数设置是怎么样的？我这边也有和你类似的情况。

**Comment by XuRui314** [comment]
@chensiqin 你好，我这边基本上都试了各种学习率、warmup rate、freeze vit、train vit、全参/lora/adapter，好像基本上都会出现这样的情况，这批数据在llava1.5上微调都是正常的，上面的图片的参数lr=2e-4，batch_size=256，我数据量有1.3M

**Comment by chensiqin** [comment]
@Jintao-Huang 大佬，麻烦帮忙看下这个问题哈

**Comment by hyyuan123** [comment]
> 使用自建数据集对glm4v进行微调，完成后ckpt指定output/glm4v-9b-chat/vx-xxx/checkpoint-xxx可正常进行推理，若先进行export，再指定ckpt为output/glm4v-9b-chat/vx-xxx/checkpoint-xxx-merged时，模型推理会有以下错误： ![6351717682256_ pic](https://private-user-images.githubusercontent.com/47681766/337295724-96774c96-7d58-4522-9b17-bc58169086c9.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4NDYyODgsIm5iZiI6MTcxODg0NTk4OCwicGF0aCI6Ii80NzY4MTc2Ni8zMzcyOTU3MjQtOTY3NzRjOTYtN2Q1OC00NTIyLTliMTctYmM1ODE2OTA4NmM5LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIwVDAxMTMwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRmMDc4NTc2ZDgwNzQyYzBlMmY4M2IwMWNmZTUyZmM0OGRlMjk1YTk4OGFlZTRmY2I1YTI3ODVhMzAyYmFmMmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._jRQWVQ7Alx-KEiGkKo4MHf1sNG87_k8I6WbvdtEP-w)

想问一下，这个问题解决了吗？是什么原因导致的，直接使用ckpt指定output/glm4v-9b-chat/vx-xxx/checkpoint-xxx可进行推理的结果会和merge后的结果一致吗？直接使用ckpt指定output/glm4v-9b-chat/vx-xxx/checkpoint-xxx进行推理的结果就是微调Lora模型的效果吗？我直接使用ckpt指定output/glm4v-9b-chat/vx-xxx/checkpoint-xxx进行推理的效果不佳
但是之前使用同样的数据训练InternVL-v1.5版本的模型，测试后没问题

**Comment by Jintao-Huang** [comment]
尝试拉取一下最新的代码 (main分支)
