### ISSUE TITLE
GLM4v-9b lora微调，fp16一直grad_norm显示nan

### ISSUE THREAD

**Issue by moyans** [modelscope/swift#1099]

**Comment by HuggingAha** [comment]
[官方仓库有个issue，说glm4微调需要用bf16](https://github.com/THUDM/GLM-4/issues/96#issuecomment-2153757179)

**Comment by moyans** [comment]
> [官方仓库有个issue，说glm4微调需要用bf16](https://github.com/THUDM/GLM-4/issues/96#issuecomment-2153757179)

好的，感谢
