### ISSUE TITLE
swift web-ui设置端口和ip生效

### ISSUE THREAD

**Issue by zhangfan-algo** [modelscope/swift#1102]
**Additional cntext**
swift web-ui -host 0.0.0.0 --port 8005

**Comment by zhangfan-algo** [comment]
设置之后还是这样的Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.

**Comment by loong1118** [comment]
> 设置之后还是这样的Running on local URL: http://127.0.0.1:7860
> 
> To create a public link, set `share=True` in `launch()`.

解决了么，我也遇到了这个问题

**Comment by zhangfan-algo** [comment]
没有我现在还这样

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: loong1118 ***@***.***>
发送时间: Tuesday, June 18, 2024 10:12:30 AM
收件人: modelscope/swift ***@***.***>
抄送: zhangfan-algo ***@***.***>; Author ***@***.***>
主题: Re: [modelscope/swift] swift web-ui设置端口和ip生效 (Issue #1102)


设置之后还是这样的Running on local URL: http://127.0.0.1:7860

To create a public link, set share=True in launch().

解决了么，我也遇到了这个问题

―

**Comment by tastelikefeet** [comment]
参考下文档：https://github.com/modelscope/swift/blob/main/docs/source/GetStarted/%E7%95%8C%E9%9D%A2%E8%AE%AD%E7%BB%83%E6%8E%A8%E7%90%86.md
