### ISSUE TITLE
get_model_list_client  for Qwen2-72B-Instruct missing value for field "data.is_chat"

### ISSUE THREAD

**Issue by phoenixbai** [modelscope/swift#1103]
**Describe the bug**
我跑了下面的代码，报错：
```
>>> swift.__version__
'2.2.0.dev0'
>>> from swift.llm import get_model_list_client, XRequestConfig, inference_client
>>> model_list = get_model_list_client(host=Host, port=Port)
```
我直接curl时，模型信息如下，似乎模型信息里缺个is_chat的属性
```
$curl 'http://33.121.11.4:8000/v1/models'
{"object":"list","data":[{"id":"Qwen2-72B-Instruct","object":"model","created":1717753475,"owned_by":"vllm","root":"Qwen2-72B-Instruct","parent":null,"permission":[{"id":"modelperm-96b9cdeb0fe54cddbe85ff4e14f394f0","object":"model_permission","created":1717753475,"allow_create_engine":false,"allow_sampling":true,"allow_logprobs":true,"allow_search_indices":false,"allow_view":true,"allow_fine_tuning":false,"organization":"*","group":null,"is_blocking":false}]}]}
```

**Your hardware and system info**
Write your system info like CUDA version/system/GPU/torch version here(在这里给出硬件信息和系统信息，如CUDA版本，系统，GPU型号和torch版本等)

**Additional context**
报错信息如保，is_chat这个属性在

> Traceback (most recent call last):
>   File "/mnt/bmz/llm/anaconda3/lib/python3.11/site-packages/dacite/core.py", line 72, in from_dict
>     value = get_default_value_for_field(field, field_type)
>             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/mnt/bmz/llm/anaconda3/lib/python3.11/site-packages/dacite/dataclasses.py", line 21, in get_default_value_for_field
>     raise DefaultValueNotFoundError()
> dacite.dataclasses.DefaultValueNotFoundError
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/mnt/bmz/llm/swift-main/swift/llm/utils/client_utils.py", line 23, in get_model_list_client
>     return from_dict(ModelList, resp_obj)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/mnt/bmz/llm/anaconda3/lib/python3.11/site-packages/dacite/core.py", line 64, in from_dict
>     value = _build_value(type_=field_type, data=field_data, config=config)
>             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/mnt/bmz/llm/anaconda3/lib/python3.11/site-packages/dacite/core.py", line 97, in _build_value
>     data = _build_value_for_collection(collection=type_, data=data, config=config)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/mnt/bmz/llm/anaconda3/lib/python3.11/site-packages/dacite/core.py", line 154, in _build_value_for_collection
>     return data_type(_build_value(type_=item_type, data=item, config=config) for item in data)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/mnt/bmz/llm/anaconda3/lib/python3.11/site-packages/dacite/core.py", line 154, in <genexpr>
>     return data_type(_build_value(type_=item_type, data=item, config=config) for item in data)
>                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/mnt/bmz/llm/anaconda3/lib/python3.11/site-packages/dacite/core.py", line 99, in _build_value
>   File "/mnt/bmz/llm/anaconda3/lib/python3.11/site-packages/dacite/core.py", line 99, in _build_value
>   data = from_dict(data_class=type_, data=data, config=config)
>          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> File "/mnt/bmz/llm/anaconda3/lib/python3.11/site-packages/dacite/core.py", line 76, in from_dict
>   raise MissingValueError(field.name)
> dacite.exceptions.MissingValueError: missing value for field "data.is_chat"

**Comment by Jintao-Huang** [comment]
服务端是如何启动的呢

**Comment by phoenixbai** [comment]
我用这个命令部署的：
`python -m vllm.entrypoints.openai.api_server --served-model-name Qwen2-72B-Instruct --model /mnt/workspace/share/models/Qwen2-72B-Instruct --tensor-parallel-size 8`

我是不是用swift deploy就会正常了？

**Comment by Jintao-Huang** [comment]
是的, 不过这个bug修复了, vllm启动应该也可以了

**Comment by Jintao-Huang** [comment]
main分支
