### ISSUE TITLE
新手求问使用自己本地自定义多轮对话数据集，在dataset.py这个函数该怎么写呀

### ISSUE THREAD

**Issue by liuliu1024** [modelscope/swift#111]
新手求问使用自己本地自定义多轮对话数据集，在dataset.py构建get_*_dataset()函数该怎么写呀

**Comment by Jintao-Huang** [comment]
可以看一下文档的部分哈

我这里复制一下文档中相关的内容：

[DATASET_MAPPING 介绍 (数据集拓展)](https://github.com/Jintao-Huang/swift/blob/main/examples/pytorch/llm/README_CN.md#dataset_mapping-%E4%BB%8B%E7%BB%8D-%E6%95%B0%E6%8D%AE%E9%9B%86%E6%8B%93%E5%B1%95)
DATASET_MAPPING定义在utils/dataset.py中, 用于加载各种类型的数据, 例如: 单轮指令微调数据集, 多轮chat数据集, 多模态数据集等. 如果你需要拓展数据集, 你可以在这里面添加. 其中key表示dataset的唯一id, 例如: alpaca-en, alpaca-zh等. value是获取数据集的函数. 该函数不需要传入任何参数, 需要返回HfDataset或Tuple[HfDataset, HfDataset]. 第一种情况下, 数据集处理函数会切分一部分的数据集作为验证集 (根据命令行超参数dataset_test_ratio); 第二种情况下, 返回的两个数据集分别作为其训练集和验证集. 我们支持使用多个数据集进行微调. 我们会将各个子数据集的训练集和验证集部分分别进行拼接, 最终返回合并后的训练集和验证集.

函数返回的HfDataset需要符合一定的规范. 如果是指令微调(单轮对话)的情况下, 需包含query, response字段, 分别代表指令微调的用户询问和AI助手的回答, 具体可以参考alpaca-zh数据集. 如果是多轮对话, 则需要额外加上history字段, 代表对话的历史信息, 具体可以参考damo-agent-mini-zh数据集. 如果每个数据集样例具有不同的system, 则需要额外加上system字段, 具体你也可以参考damo-agent-mini-zh数据集. 我们只会对response部分进行loss的计算和优化.

**Comment by liuliu1024** [comment]
> 可以看一下文档的部分哈
> 
> 我这里复制一下文档中相关的内容：
> 
> [DATASET_MAPPING 介绍 (数据集拓展)](https://github.com/Jintao-Huang/swift/blob/main/examples/pytorch/llm/README_CN.md#dataset_mapping-%E4%BB%8B%E7%BB%8D-%E6%95%B0%E6%8D%AE%E9%9B%86%E6%8B%93%E5%B1%95) DATASET_MAPPING定义在utils/dataset.py中, 用于加载各种类型的数据, 例如: 单轮指令微调数据集, 多轮chat数据集, 多模态数据集等. 如果你需要拓展数据集, 你可以在这里面添加. 其中key表示dataset的唯一id, 例如: alpaca-en, alpaca-zh等. value是获取数据集的函数. 该函数不需要传入任何参数, 需要返回HfDataset或Tuple[HfDataset, HfDataset]. 第一种情况下, 数据集处理函数会切分一部分的数据集作为验证集 (根据命令行超参数dataset_test_ratio); 第二种情况下, 返回的两个数据集分别作为其训练集和验证集. 我们支持使用多个数据集进行微调. 我们会将各个子数据集的训练集和验证集部分分别进行拼接, 最终返回合并后的训练集和验证集.
> 
> 函数返回的HfDataset需要符合一定的规范. 如果是指令微调(单轮对话)的情况下, 需包含query, response字段, 分别代表指令微调的用户询问和AI助手的回答, 具体可以参考alpaca-zh数据集. 如果是多轮对话, 则需要额外加上history字段, 代表对话的历史信息, 具体可以参考damo-agent-mini-zh数据集. 如果每个数据集样例具有不同的system, 则需要额外加上system字段, 具体你也可以参考damo-agent-mini-zh数据集. 我们只会对response部分进行loss的计算和优化.

有看过这个文档，用线上的官方数据集能damo-agent-mini-zh够跑通，但用本地自定义数据集，读取数据集后输出什么数据作为训练，以及历史信息怎么加入，这个函数不太会写

**Comment by Jintao-Huang** [comment]
后面会尽量支持常见的数据集格式, 避免用户手动写函数哈～ 应该会更友好一些, 估计feat支持时间大概在10.23左右

**Comment by mockyd** [comment]
> 可以看一下文档的部分哈
> 
> 我这里复制一下文档中相关的内容：
> 
> [DATASET_MAPPING 介绍 (数据集拓展)](https://github.com/Jintao-Huang/swift/blob/main/examples/pytorch/llm/README_CN.md#dataset_mapping-%E4%BB%8B%E7%BB%8D-%E6%95%B0%E6%8D%AE%E9%9B%86%E6%8B%93%E5%B1%95) DATASET_MAPPING定义在utils/dataset.py中, 用于加载各种类型的数据, 例如: 单轮指令微调数据集, 多轮chat数据集, 多模态数据集等. 如果你需要拓展数据集, 你可以在这里面添加. 其中key表示dataset的唯一id, 例如: alpaca-en, alpaca-zh等. value是获取数据集的函数. 该函数不需要传入任何参数, 需要返回HfDataset或Tuple[HfDataset, HfDataset]. 第一种情况下, 数据集处理函数会切分一部分的数据集作为验证集 (根据命令行超参数dataset_test_ratio); 第二种情况下, 返回的两个数据集分别作为其训练集和验证集. 我们支持使用多个数据集进行微调. 我们会将各个子数据集的训练集和验证集部分分别进行拼接, 最终返回合并后的训练集和验证集.
> 
> 函数返回的HfDataset需要符合一定的规范. 如果是指令微调(单轮对话)的情况下, 需包含query, response字段, 分别代表指令微调的用户询问和AI助手的回答, 具体可以参考alpaca-zh数据集. 如果是多轮对话, 则需要额外加上history字段, 代表对话的历史信息, 具体可以参考damo-agent-mini-zh数据集. 如果每个数据集样例具有不同的system, 则需要额外加上system字段, 具体你也可以参考damo-agent-mini-zh数据集. 我们只会对response部分进行loss的计算和优化.

您好，我在damo-agent-mini-zh数据集中没找到history相关的内容，请问这个字段到底应该怎么加呀？

**Comment by Jintao-Huang** [comment]
现在数据集可以支持两种方式的拓展的，1种是通过命令行参数的`custom_train_dataset_path`, `custom_val_dataset_path`的方式传入支持更加方便的本地数据集支持, 第二种是通过注册数据集的方式, 更具有拓展性. 具体可以查看文档哈～

**Comment by yuyiheng-eu** [comment]
<img width="348" alt="image" src="https://github.com/modelscope/swift/assets/83455623/a9d69213-6731-49b6-be61-e2e9cb1f0e3f">
为什么不支持custom_train_dataset_path

**Comment by yuyiheng-eu** [comment]
<img width="358" alt="image" src="https://github.com/modelscope/swift/assets/83455623/b86b8d0d-9673-4d6f-a57b-1c546c3d6944">
用custom_train_dataset_path为什么会报这个错

**Comment by Jintao-Huang** [comment]
> <img alt="image" width="358" src="https://user-images.githubusercontent.com/83455623/279318743-b86b8d0d-9673-4d6f-a57b-1c546c3d6944.png"> 用custom_train_dataset_path为什么会报这个错

你尝试拉取一下最新的代码, 并安装. 可以参考一下README的准备实验环境的部分哦
