### ISSUE TITLE
swift deploy mini-internvl-chat-2b-v1_5 能部署成功，但是调用会失败

### ISSUE THREAD

**Issue by moyans** [modelscope/swift#1114]
参照mutlimodal-deployment.md，

curl http://localhost:8000/v1/chat/completions \ -H "Content-Type: application/json" \ -d '{ "model": "mini-internvl-chat-2b-v1_5", "messages": [{"role": "user", "content": "Picture 1:<img>https://modelscope-open.oss-cn-hangzhou.aliyuncs.com/images/rose.jpg</img>\nWhat kind of flower is in the picture and how many are there?"}], "max_tokens": 256, "temperature": 0 }',   

报错内容:    local variable 'labels' referenced before assignment

**Comment by hjh0119** [comment]
fixed
