### ISSUE TITLE
glm4v加载保存的checkpoint继续训练时报错

### ISSUE THREAD

**Issue by Marcovaldon** [modelscope/swift#1115]
**Describe the bug**
What the bug is, and how to reproduce, better with screenshots(描述bug以及复现过程，最好有截图)
如题，用swift进行glmv4的微调，训练一段时间后因OOM断掉了，因此想接着上一个checkpoint来继续训练，但会有报错信息。

训练命令如下：
`NPROC_PER_NODE=2 \
CUDA_VISIBLE_DEVICES=6,7 swift sft \
    --model_type glm4v-9b-chat \
    --model_id_or_path /Multimodal/checkpoints/glm-4v-9b/ \
    --model_id_or_path /Multimodal/swift/us_desc/train0607/glm4v-9b-chat/v0-20240607-170819/fuck/ \
    --model_id_or_path /Multimodal/checkpoints/glm-4v-9b/ \
    --model_id_or_path /Multimodal/swift/us_desc/train0610/glm4v-9b-chat/v0-20240610-100012/checkpoint-16000/ \
    --custom_train_dataset_path /Multimodal/orig_data/data_240308_tot305w_swift.json \
    --custom_train_dataset_path /Multimodal/orig_data/data_240527_tot515w_swift.json \
    --sft_type full \
    --dtype bf16 \
    --batch_size 1 \
    --gradient_accumulation_steps 8 \
    --learning_rate 1e-6 \
    --eval_steps 50000 \
    --save_steps 1000 \
    --logging_steps 1 \
    --save_total_limit 10 \
    --num_train_epochs 1 \
    --output_dir us_desc/train0611 \
    --ddp_find_unused_parameters true \
    --deepspeed zero_config/zero2.json \
    --deepspeed default-zero2 \
    --dataloader_num_workers 4 \
    --seed 2024 \`

报错信息如下，看起来是在读取图片的时候报的错。
`[rank1]: Traceback (most recent call last):
[rank1]:   File "/Multimodal/dongshiqi/swift/swift/cli/sft.py", line 5, in <module>
[rank1]:     sft_main()
[rank1]:   File "/Multimodal/dongshiqi/swift/swift/utils/run_utils.py", line 27, in x_main
[rank1]:     result = llm_x(args, **kwargs)
[rank1]:   File "/Multimodal/dongshiqi/swift/swift/llm/sft.py", line 244, in llm_sft
[rank1]:     td0, tkwargs0 = template.encode(train_dataset[0])
[rank1]:   File "/Multimodal/dongshiqi/swift/swift/llm/utils/template.py", line 720, in encode
[rank1]:     inputs2 = self.tokenizer.apply_chat_template(messages, return_dict=True)
[rank1]:   File "/root/.cache/huggingface/modules/transformers_modules/checkpoint-16000/tokenization_chatglm.py", line 236, in apply_chat_template
[rank1]:     result = handle_single_conversation(conversation)
[rank1]:   File "/root/.cache/huggingface/modules/transformers_modules/checkpoint-16000/tokenization_chatglm.py", line 210, in handle_single_conversation
[rank1]:     input_image = transform(item["image"])
[rank1]:   File "/root/anaconda3/envs/swift/lib/python3.10/site-packages/torchvision/transforms/transforms.py", line 95, in __call__
[rank1]:     img = t(img)
[rank1]:   File "/root/anaconda3/envs/swift/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
[rank1]:     return self._call_impl(*args, **kwargs)
[rank1]:   File "/root/anaconda3/envs/swift/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
[rank1]:     return forward_call(*args, **kwargs)
[rank1]:   File "/root/anaconda3/envs/swift/lib/python3.10/site-packages/torchvision/transforms/transforms.py", line 354, in forward
[rank1]:     return F.resize(img, self.size, self.interpolation, self.max_size, self.antialias)
[rank1]:   File "/root/anaconda3/envs/swift/lib/python3.10/site-packages/torchvision/transforms/functional.py", line 468, in resize
[rank1]:     return F_pil.resize(img, size=output_size, interpolation=pil_interpolation)
[rank1]:   File "/root/anaconda3/envs/swift/lib/python3.10/site-packages/torchvision/transforms/_functional_pil.py", line 250, in resize
[rank1]:     return img.resize(tuple(size[::-1]), interpolation)
[rank1]:   File "/root/anaconda3/envs/swift/lib/python3.10/site-packages/PIL/Image.py", line 2222, in resize
[rank1]:     return self._new(self.im.resize(size, resample, box))
[rank1]: TypeError: 'NoneType' object cannot be interpreted as an integer`

**Your hardware and system info**
Write your system info like CUDA version/system/GPU/torch version here(在这里给出硬件信息和系统信息，如CUDA版本，系统，GPU型号和torch版本等)
A100
torch 2.3.1
deepspeed 0.14.2
transformers 4.41.2

看了一下，保存的checkpoint和原始的huggingface下载的checkpoint文件夹，除去参数文件外有diff的文件如下：
config.json

想问一下大佬@jinhao-huang可以复现这个问题吗？可能的原因是什么呢？（用原始的huggingface文件夹是没问题的）

**Comment by Jintao-Huang** [comment]
拉取一下最新main分支的代码, 这个bug已经修复了
你现在需要修改一下checkpoint中的config.json, 加一个"image_size": 1120, 之前的代码忘存了.
https://modelscope.cn/models/ZhipuAI/glm-4v-9b/file/view/master?fileName=config.json&status=1

**Comment by Marcovaldon** [comment]
还可能会有其它原因吗，我看我的checkpoint中已经有了image_size: 1120这个配置    代码刚刚又拉了一下，~/.cache/huggingface/modules/transformers_modules路径下的checkpoint文件夹删掉了。但还是一样的报错信息...

**Comment by Marcovaldon** [comment]
又试了一下，最新代码可以了
