### ISSUE TITLE
SimPO后的模型会出现遗忘问题吗？

### ISSUE THREAD

**Issue by mst272** [modelscope/swift#1126]
看到你们SimPO的md文件中的效果展示了，请问测没测会不会有遗忘灾难？常规指标与未SimPO之前对比过嘛。

**Comment by tastelikefeet** [comment]
微调都会有遗忘问题，具体可以参见：https://github.com/modelscope/modelscope-classroom/blob/main/LLM-tutorial/M.%E4%BA%BA%E7%B1%BB%E5%81%8F%E5%A5%BD%E5%AF%B9%E9%BD%90%E8%AE%AD%E7%BB%83.md
