### ISSUE TITLE
GLM4V多轮对话数据预处理问题

### ISSUE THREAD

**Issue by yycuc** [modelscope/swift#1130]
感激各位对Swift开发和维护，这是一个非常好用的项目！想请教一个关于GLM4V多轮对话数据处理的问题。

基于glm4v最佳实践文档，多轮对话的构成格式为
{"query": "EEEEE", "response": "FFFFF", "history": [["AAAAA", "BBBBB"], ["CCCCC", "DDDDD"]], "images": ["image_path"]}
请问下history中的answer会进行损失计算吗，需要对单条多轮对话数据进行拆分吗～

类似于拆成：
{"query": "AAAAA", "response": "BBBBB",  "images": ["image_path"]}
{"query": "CCCCC", "response": "DDDDD",  , "history": [["AAAAA", "BBBBB"]]"images": ["image_path"]}
{"query": "EEEEE", "response": "FFFFF", "history": [["AAAAA", "BBBBB"], ["CCCCC", "DDDDD"]], "images": ["image_path"]}

**Comment by Jintao-Huang** [comment]
history中的answer会进行损失计算的. 


计算损失的部分是: history中response, response和suffix(结束符)
