### ISSUE TITLE
8-V100 微调Qwen2-7B-Instruct模型时问题

### ISSUE THREAD

**Issue by caliba** [modelscope/swift#1131]
**Describe the bug**
使用如下脚本对Qwen2-7B-Instruct模型进行微调：
```
# Experimental environment: 8 * V100
# 8 * 16GB GPU memory
PYTHONPATH=../../.. \
CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 \
python llm_sft.py \
    --model_type qwen2-7b-instruct \
    --model_revision master \
    --sft_type lora \
    --tuner_backend swift \
    --template_type qwen \
    --dtype AUTO \
    --output_dir output_gjh \
    --dataset train.jsonl \
    --train_dataset_sample -1 \
    --num_train_epochs 100 \
    --max_length 2048 \
    --check_dataset_strategy warning \
    --lora_rank 8 \
    --lora_alpha 32 \
    --lora_dropout_p 0.05 \
    --lora_target_modules DEFAULT \
    --gradient_checkpointing is true.
    --batch_size 4 \
    --weight_decay 0.01 \
    --learning_rate 1e-4 \
    --gradient_accumulation_steps 8 \
    --max_grad_norm 0.5 \
    --warmup_ratio 0.03 \
    --eval_steps 100000 \
    --save_steps 30 \
    --save_total_limit -1 \
    --logging_steps 10 \
    --use_flash_attn false \
```

模型可正常训练，但是多轮训练其acc、loss均为0
<img width="727" alt="image" src="https://github.com/modelscope/swift/assets/56266244/ae82799e-1b2d-4fe9-beb3-38e7bf7cb1d7">

GPU使用情况如下：第7块卡的GPU-Util一直为0 ：
<img width="715" alt="image" src="https://github.com/modelscope/swift/assets/56266244/55a61a09-ab09-49db-96bc-2bbe90d78ddc">

**Your hardware and system info**

```
CUDA version: 12.1
transformers: 4.39.2
vllm: 0.4.0.post1
torch: 2.1.0
ms-swift: 2.2.0.dev0
```
**Additional context**

**当使用Qwen1或Qwen1.5能够正常训练**，请问这个该如何解决？

**Comment by zkyredstart** [comment]
@Jintao-Huang 我这边V100可以正常推理，用fp16训练，为何loss还是0

**Comment by ArlanCooper** [comment]
请问一下，我这边为什么不能用qwen2呢，我代码更新是最新仓库的，提示没有这个model_id:
ValueError: model_type: 'qwen2-7b-instruct' is not registered.

**Comment by qingfengcss** [comment]
> @Jintao-Huang 我这边V100可以正常推理，用fp16训练，为何loss还是0
你好，正常推理的pytorch版本和transformers版本是多少呢，能发一下么，我v100推理出现了问题

**Comment by Jintao-Huang** [comment]
需要使用bf16训练

**Comment by hitszxs** [comment]
> 需要使用bf16训练

那可以使用float32训练吗？

**Comment by Jintao-Huang** [comment]
当然可以啊

> > 需要使用bf16训练
> 
> 那可以使用float32训练吗？
