### ISSUE TITLE
如何控制Qwen大模型重复输出

### ISSUE THREAD

**Issue by QDPeng** [modelscope/swift#1139]
**Describe the bug**
![qwen-infer](https://github.com/modelscope/swift/assets/8101396/96f0dcea-6524-47e1-8fcd-7448970c9771)

使用Qwen1.5-4b-Chat模型测试，得到重复的回复。如何控制大模型的重复输出？
```shell
CUDA_VISIBLE_DEVICES=0 swift infer --model_type qwen1half-4b-chat
```

**Your hardware and system info**
pytorch：2.3
Qwen: Qwen1.5-4b-Chat
ubuntu：18.04
gpu: RTX3090

**Comment by changqingla** [comment]
相同问题

**Comment by tastelikefeet** [comment]
模型太小了，建议使用qwen2系列模型，这是模型侧的问题
