### ISSUE TITLE
一样的配置，微调速度莫名其妙速度慢了4倍

### ISSUE THREAD

**Issue by woshixiaobai2019** [modelscope/swift#1142]
**微调过程中发现微调速度慢了4倍**
![image](https://github.com/modelscope/swift/assets/57052600/f3df35c3-aa57-4528-9a1b-b2e15612ad7f)

**Your hardware and system info**
Ubuntu 22.04.4 torch2.3.0 cuda 12.1

**可以看到结果一样，就是速度变慢了**
不知道什么情况，求解

**Comment by Jintao-Huang** [comment]
已沟通是服务器散热原因
