### ISSUE TITLE
训练Phi3vision时只能选择lora，若选择full会报错。

### ISSUE THREAD

**Issue by HUANXES** [modelscope/swift#1144]
**Describe the bug**
What the bug is, and how to reproduce, better with screenshots(描述bug以及复现过程，最好有截图)
选择lora可以单机单卡，单机多卡；但选full时，单机多卡会出现ddp报错：
grad.sizes() = [1, 1, 4096], strides() = [10276864, 4096, 1]
bucket_view.sizes() = [1, 1, 4096], strides() = [4096, 4096, 1] (Triggered internally at ../torch/csrc/distributed/c10d/reducer.cpp:325.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
[rank0]: RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing loss. You can enable unused parameter detection by passing the keyword argument `find_unused_parameters=True` to `torch.nn.parallel.DistributedDataParallel`, and by
[rank0]: making sure all `forward` function outputs participate in calculating loss.
[rank0]: If you already have done the above, then the distributed data parallel module wasn't able to locate the output tensors in the return value of your module's `forward` function. Please include the loss function and the structure of the return value of `forward` of your module when reporting this issue (e.g. list, dict, iterable).
[rank0]: Parameter indices which did not receive grad for rank 0: 376 377 378 379 380 381 382 383 384 385 386 387 388 389 390 391 392 393
[rank0]:  In addition, you can set the environment variable TORCH_DISTRIBUTED_DEBUG to either INFO or DETAIL to print out information about which particular parameters did not receive gradient on this rank as part of this error
选择full+冻结参数时，ddp不报错，但save model的时候会报错：
[rank0]: RuntimeError: The weights trying to be saved contained shared tensors [{'model.vision_embed_tokens.wte.weight', 'model.embed_tokens.weight'}] that are mismatching the transformers base configuration. Try saving using `safe_serialization=False` or remove this tensor sharing.

**Your hardware and system info**
Write your system info like CUDA version/system/GPU/torch version here(在这里给出硬件信息和系统信息，如CUDA版本，系统，GPU型号和torch版本等)
硬件：4卡A800  环境啥的和phi3v在huggingface上要求的一样。

**Additional context**
Add any other context about the problem here(在这里补充其他信息)

**Comment by airkid** [comment]
@HUANXES 您方便分享下训练command吗，我这训练会报错FlashAttention only supports Ampere GPUs or newer
`NPROC_PER_NODE=4 \
CUDA_VISIBLE_DEVICES=0,1,2,3 swift sft \
    --model_type phi3-vision-128k-instruct \
    --dataset coco-en-2-mini \
    --sft_type lora`
我用的4*V100

**Comment by HUANXES** [comment]
> @HUANXES 您方便分享下训练command吗，我这训练会报错FlashAttention only supports Ampere GPUs or newer `NPROC_PER_NODE=4 \ CUDA_VISIBLE_DEVICES=0,1,2,3 swift sft \ --model_type phi3-vision-128k-instruct \ --dataset coco-en-2-mini \ --sft_type lora` 我用的4*V100

CUDA_VISIBLE_DEVICES=1,2 NPROC_PER_NODE=2  swift sft     --model_type phi3-vision-128k-instruct     --dataset /data1/hmy/generatechart/LineEchartsDemo4formated/Demo4f10TDataset.json     --num_train_epochs 1     --sft_type lora     --o
utput_dir /data1/hmy/generatechart/phi3v10t     --use_flash_attn True     --save_only_model False     --save_steps 250     --learning_rate 5e-5     --eval_steps 1000     --batch_size 5    --save_tot
al_limit 5 --lora_rank 16 --lora_alpha 64

**Comment by airkid** [comment]
感谢回复，看起来我的问题是V100不支持flash attention

**Comment by HUANXES** [comment]
> 感谢回复，看起来我的问题是V100不支持flash attention

swift的flash attn默认是关闭的

**Comment by airkid** [comment]
看起来phi3-v的code即使特别指定--use_flash_attn False还是会强制用

**Comment by Jintao-Huang** [comment]
> **Describe the bug** What the bug is, and how to reproduce, better with screenshots(描述bug以及复现过程，最好有截图) 选择lora可以单机单卡，单机多卡；但选full时，单机多卡会出现ddp报错： grad.sizes() = [1, 1, 4096], strides() = [10276864, 4096, 1] bucket_view.sizes() = [1, 1, 4096], strides() = [4096, 4096, 1] (Triggered internally at ../torch/csrc/distributed/c10d/reducer.cpp:325.) return Variable._execution_engine.run_backward( # Calls into the C++ engine to run the backward pass [rank0]: RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing loss. You can enable unused parameter detection by passing the keyword argument `find_unused_parameters=True` to `torch.nn.parallel.DistributedDataParallel`, and by [rank0]: making sure all `forward` function outputs participate in calculating loss. [rank0]: If you already have done the above, then the distributed data parallel module wasn't able to locate the output tensors in the return value of your module's `forward` function. Please include the loss function and the structure of the return value of `forward` of your module when reporting this issue (e.g. list, dict, iterable). [rank0]: Parameter indices which did not receive grad for rank 0: 376 377 378 379 380 381 382 383 384 385 386 387 388 389 390 391 392 393 [rank0]: In addition, you can set the environment variable TORCH_DISTRIBUTED_DEBUG to either INFO or DETAIL to print out information about which particular parameters did not receive gradient on this rank as part of this error 选择full+冻结参数时，ddp不报错，但save model的时候会报错： [rank0]: RuntimeError: The weights trying to be saved contained shared tensors [{'model.vision_embed_tokens.wte.weight', 'model.embed_tokens.weight'}] that are mismatching the transformers base configuration. Try saving using `safe_serialization=False` or remove this tensor sharing.
> 
> **Your hardware and system info** Write your system info like CUDA version/system/GPU/torch version here(在这里给出硬件信息和系统信息，如CUDA版本，系统，GPU型号和torch版本等) 硬件：4卡A800 环境啥的和phi3v在huggingface上要求的一样。
> 
> **Additional context** Add any other context about the problem here(在这里补充其他信息)

是不是用了zero3呀

**Comment by HUANXES** [comment]
> > **Describe the bug** What the bug is, and how to reproduce, better with screenshots(描述bug以及复现过程，最好有截图) 选择lora可以单机单卡，单机多卡；但选full时，单机多卡会出现ddp报错： grad.sizes() = [1, 1, 4096], strides() = [10276864, 4096, 1] bucket_view.sizes() = [1, 1, 4096], strides() = [4096, 4096, 1] (Triggered internally at ../torch/csrc/distributed/c10d/reducer.cpp:325.) return Variable._execution_engine.run_backward( # Calls into the C++ engine to run the backward pass [rank0]: RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing loss. You can enable unused parameter detection by passing the keyword argument `find_unused_parameters=True` to `torch.nn.parallel.DistributedDataParallel`, and by [rank0]: making sure all `forward` function outputs participate in calculating loss. [rank0]: If you already have done the above, then the distributed data parallel module wasn't able to locate the output tensors in the return value of your module's `forward` function. Please include the loss function and the structure of the return value of `forward` of your module when reporting this issue (e.g. list, dict, iterable). [rank0]: Parameter indices which did not receive grad for rank 0: 376 377 378 379 380 381 382 383 384 385 386 387 388 389 390 391 392 393 [rank0]: In addition, you can set the environment variable TORCH_DISTRIBUTED_DEBUG to either INFO or DETAIL to print out information about which particular parameters did not receive gradient on this rank as part of this error 选择full+冻结参数时，ddp不报错，但save model的时候会报错： [rank0]: RuntimeError: The weights trying to be saved contained shared tensors [{'model.vision_embed_tokens.wte.weight', 'model.embed_tokens.weight'}] that are mismatching the transformers base configuration. Try saving using `safe_serialization=False` or remove this tensor sharing.
> > **Your hardware and system info** Write your system info like CUDA version/system/GPU/torch version here(在这里给出硬件信息和系统信息，如CUDA版本，系统，GPU型号和torch版本等) 硬件：4卡A800 环境啥的和phi3v在huggingface上要求的一样。
> > **Additional context** Add any other context about the problem here(在这里补充其他信息)
> 
> 是不是用了zero3呀

我没有用deepspeed呀，难道微软的模型都自带zero3？我没有专门设置这个

**Comment by Jintao-Huang** [comment]
加个--find_unused_parameters true 呢

**Comment by HUANXES** [comment]
> 加个--ddp_find_unused_parameters true 呢
不行，还是一样的报错RuntimeError: The weights trying to be saved contained shared tensors [{'model.embed_tokens.weight', 'model.vision_embed_tokens.wte.weight'}] that are mismatching the transformers base configuration. Try saving using `safe_serialization=False` or remove this tensor sharing.

**Comment by Jintao-Huang** [comment]
再加个 --safe_serialization false

**Comment by HUANXES** [comment]
> 再加个 --safe_serialization false

:744: UserWarning: Grad strides do not match bucket view strides. This may indicate grad was not created according to the gradient layout contract, or that the param's strides changed since DDP was constructed.  This is not an error, but may impair performance.
grad.sizes() = [1, 1, 4096], strides() = [9637888, 4096, 1]
bucket_view.sizes() = [1, 1, 4096], strides() = [4096, 4096, 1] (Triggered internally at ../torch/csrc/distributed/c10d/reducer.cpp:325.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
可以正常运行了，只是有警告
