### ISSUE TITLE
请问Swift可以实现多模态模型的dpo/simpo吗？

### ISSUE THREAD

**Issue by delian11** [modelscope/swift#1145]
如题，swift可以实现多模态模型，比如qwen-vl, internvl-v1.5等的dpo/simpo吗？
我目前按照llm的dpo格式会报错：
AttributeError: 'Seq2SeqTrainingArguments' object has no attribute 'model_init_kwargs'
![DX-20240615@2x](https://github.com/modelscope/swift/assets/36758049/1448684e-b5c2-430b-9ab0-489c24444e7b)

**Comment by delian11** [comment]
请问如果自己添加的话，有没有什么文档参考呢？

**Comment by hjh0119** [comment]
support
