### ISSUE TITLE
MLLM的web ui还没写好

### ISSUE THREAD

**Issue by 2catycm** [modelscope/swift#1146]
**Describe the bug**
What the bug is, and how to reproduce, better with screenshots(描述bug以及复现过程，最好有截图)

复现过程
1. 运行
```bash
swift app-ui  --model_type minicpm-v-v2_5-chat
```
2. 打开gradio网页

![image](https://github.com/modelscope/swift/assets/41530341/746cc903-c0b0-472d-bb91-e299cc2bbdba)

3. 报错
![image](https://github.com/modelscope/swift/assets/41530341/66ae9b70-1722-4bd8-addd-907d918a53dd)

**Your hardware and system info**
Write your system info like CUDA version/system/GPU/torch version here(在这里给出硬件信息和系统信息，如CUDA版本，系统，GPU型号和torch版本等)
无关

**Additional context**
Add any other context about the problem here(在这里补充其他信息)
infer可以在控制台infer，逻辑没有问题，但是webui逻辑不一样。

**Comment by Jintao-Huang** [comment]
`swift web-ui` 有一个多模态的web-ui

app-ui后面找时间升级一下

**Comment by wangdong1992** [comment]
没有上传图片的入口
