### ISSUE TITLE
swift deploy internvl-chat-v1_5 error

### ISSUE THREAD

**Issue by wangdong1992** [modelscope/swift#1149]
I used the swift deploy command to deploy internvl-chat-v1_5, and an error was reported. The command is as follows:
CUDA_VISIBLE_DEVICES=6,7 swift deploy --model_type internvl-chat-v1_5 --model_id_or_path /data/pretrained_models/AI-ModelScope/InternVL-Chat-V1-5  --port 23333  --infer_backend vllm
The error message is:
![image](https://github.com/modelscope/swift/assets/20061204/f9f92c0c-3398-4211-a260-14bc2e4c63bf)
But I changed --infer_backend from vllm to pt and it can be deployed normally.
The following is my installation environment:
ms-swift=2.1.0
torch=2.3.0+cu121
vllm=0.5.0.post1
vllm-flash-attn=2.5.9
flash-attn=2.5.9.post1
Is it because vllm does not support internvl-chat-v1_5 when the above error message appears?

**Comment by Jintao-Huang** [comment]
这个模型不支持vllm

**Comment by wangdong1992** [comment]
> 这个模型不支持vllm

请问是vllm不支持吗？
