### ISSUE TITLE
使用微调后的phi3-vision-128k模型进行推理出现错误

### ISSUE THREAD

**Issue by MindLostGuy** [modelscope/swift#1154]
**Describe the bug**
使用的命令：

> CUDA_VISIBLE_DEVICES=0 swift infer \
    --ckpt_dir xxxxxx \
    --dtype bf16 \
    --val_dataset_sample -1 \
    --val_dataset xxxxxx \
    --max_new_tokens 3072 \
    --temperature 0.2 \
    --top_k 0 \
    --top_p 1.0;"

出现的错误：
![image](https://github.com/modelscope/swift/assets/53077849/d3395ff6-bbb7-426e-91d3-da6616fb8614)

**Your hardware and system info**
4090D

**Comment by MindLostGuy** [comment]
这里使用的phi3时sft_type = full得到的中间模型

**Comment by MindLostGuy** [comment]
> Some weights of Phi3VForCausalLM were not initialized from the model checkpoint at ckpt_dir/checkpoint-10000 and are newly initialized: ['lm_head.weight', 'model.layers.0.mlp.down_proj.weight', 'model.layers.0.mlp.gate_up_proj.weight', 'model.layers.0.self_attn.o_proj.weight', 'model.layers.0.self_attn.qkv_proj.weight' ..........

这可能造成这个问题吗

**Comment by Jintao-Huang** [comment]
多机嘛

**Comment by MindLostGuy** [comment]
首先更新了transformer版本，然后删除了保存的model.safetensors文件后，可以正常推理
