### ISSUE TITLE
app-ui没有办法使用0.0.0.0吗，WEBUI_SERVER=0.0.0.0不管用

### ISSUE THREAD

**Issue by changqingla** [modelscope/swift#1157]
只有web-ui可以吗？

**Comment by Jintao-Huang** [comment]
--port

**Comment by Jintao-Huang** [comment]
--host

https://github.com/modelscope/swift/blob/main/docs/source/LLM/%E5%91%BD%E4%BB%A4%E8%A1%8C%E5%8F%82%E6%95%B0.md#app-ui-%E5%8F%82%E6%95%B0
