### ISSUE TITLE
可以支持一下DeepSeek-Coder-V2微调嘛 这个模型非常强!

### ISSUE THREAD

**Issue by zhangfan-algo** [modelscope/swift#1159]
**Describe the feature**
![image](https://github.com/modelscope/swift/assets/47747764/d0329d4b-aded-485a-af7a-c7cb7e5c78b6)
这个模型的推理能力和gpt4o非常接近了
强烈建议加入支持行列
这是git:https://github.com/deepseek-ai/DeepSeek-Coder-V2

**Comment by tastelikefeet** [comment]
Added in #1164

**Comment by zhangfan-algo** [comment]
(VllmWorkerProcess pid=571244) ERROR 06-19 17:34:04 multiproc_worker_utils.py:226] ValueError: Model architectures ['DeepseekV2ForCausalLM'] are not supported for now. Supported architectures: ['AquilaModel', 'AquilaForCausalLM', 'BaiChuanForCausalLM', 'BaichuanForCausalLM', 'BloomForCausalLM', 'ChatGLMModel', 'ChatGLMForConditionalGeneration', 'CohereForCausalLM', 'DbrxForCausalLM', 'DeciLMForCausalLM', 'DeepseekForCausalLM', 'FalconForCausalLM', 'GemmaForCausalLM', 'GPT2LMHeadModel', 'GPTBigCodeForCausalLM', 'GPTJForCausalLM', 'GPTNeoXForCausalLM', 'InternLMForCausalLM', 'InternLM2ForCausalLM', 'JAISLMHeadModel', 'LlamaForCausalLM', 'LlavaForConditionalGeneration', 'LlavaNextForConditionalGeneration', 'LLaMAForCausalLM', 'MistralForCausalLM', 'MixtralForCausalLM', 'QuantMixtralForCausalLM', 'MptForCausalLM', 'MPTForCausalLM', 'MiniCPMForCausalLM', 'OlmoForCausalLM', 'OPTForCausalLM', 'OrionForCausalLM', 'PhiForCausalLM', 'Phi3ForCausalLM', 'QWenLMHeadModel', 'Qwen2ForCausalLM', 'Qwen2MoeForCausalLM', 'RWForCausalLM', 'StableLMEpochForCausalLM', 'StableLmForCausalLM', 'Starcoder2ForCausalLM', 'ArcticForCausalLM', 'XverseForCausalLM', 'Phi3SmallForCausalLM', 'MistralModel']

**Comment by zhangfan-algo** [comment]
刚刚拉了最新的代码还是会有报错

**Comment by zhangfan-algo** [comment]
是不是vllm不支持这个模型的推理啊
