### ISSUE TITLE
在启动swift项目时候，有以下报错：AttributeError: `np.string_` was removed in the NumPy 2.0 release. Use `np.bytes_` instead.. Did you mean: 'strings'?

### ISSUE THREAD

**Issue by jiangzongjie** [modelscope/swift#1172]
**Describe the bug**
在启动swift项目时候，有以下报错：AttributeError: `np.string_` was removed in the NumPy 2.0 release. Use `np.bytes_` instead.. Did you mean: 'strings'?
说明代码中使用np.string_这个类型，但是在 NumPy 2.0 版本之后，np.string_ 已经被移除，取而代之的是 np.bytes_。这个变化是因为在 NumPy 中，np.string_ 是用来指代固定长度的字节字符串（byte strings）的，而 Python 3 默认使用 Unicode 字符串（unicode strings），并且 NumPy 推荐使用 np.bytes_ 来代替 np.string_ 以避免混淆。
依据报错中的信息，需要先找到对应报错的脚本中的具体代码行进行代码修改
1、cd /root/anaconda3/envs/swift/lib/python3.11/site-packages/numpy/目录下，找到__init__.py文件，使用vim编辑器打开，找到397行，将其中的np.string_替换为np.bytes_，np.unicode_替换为np.str_，然后保存退出

2、cd /root/anaconda3/envs/swift/lib/python3.11/site-packages/tensorboard/compat/tensorflow_stub/目录下，找到dtypes.py文件，使用vim编辑器打开，找到677行，将其中的np.string_替换为np.bytes_，np.unicode_替换为np.str_，然后保存退出

3、cd /root/anaconda3/envs/swift/lib/python3.11/site-packages/tensorboard/util/目录下，找到tensor_util.py文件,使用vim编辑器打开，找到140行, 将其中的np.string_替换为np.bytes_，np.unicode_替换为np.str_，然后保存退出

**Your hardware and system info**
ecs.gn6v-c8g1.2xlarge  (8 vCPU, 32 GiB, NVIDIA V100 * 1)
modelscope:1.15.0-pytorch2.3.0tensorflow2.16.1-gpu-py310-cu121-ubuntu22.04

**Additional context**
启动swift web_ui过程

**Comment by XiaoMaGe-hero** [comment]
我使用旧版本numpy，可以微调了

**Comment by jiangzongjie** [comment]
> 我使用旧版本numpy，可以微调了

你好，请问下具体是install哪个版本的numpy呢？谢谢

**Comment by XiaoMaGe-hero** [comment]
我用的 numpy    1.23.0

**Comment by Jintao-Huang** [comment]
已经加上numpy版本限制
