### ISSUE TITLE
单机多卡微调MiniCPM-V-V2报错

### ISSUE THREAD

**Issue by Uooga** [modelscope/swift#1177]
单卡A100跑的时候训练和推理均正常
换单机8卡V100的时候报下面这个错误
<img width="851" alt="image" src="https://github.com/modelscope/swift/assets/33107182/b5b95969-dd04-48da-8d72-b9206297a338">
运行命令是
<img width="702" alt="image" src="https://github.com/modelscope/swift/assets/33107182/3d652871-ffba-4542-88f5-2dbd99a99bf6">

**Comment by Jintao-Huang** [comment]
--ddp_find_unused_parameters true
