### ISSUE TITLE
多张4090机器上执行13b模型LORA微调提示显存不足

### ISSUE THREAD

**Issue by yaleimeng** [modelscope/swift#118]
在baichuan2-13-chat，qwen-14b-chat等模型上使用lora_ddp_ds/sft.sh实验，都是提示OOM显存不足。
已经配置了nproc_per_node = 显卡数， CUDA_VISIBLE_DEVICES也添加了对应的序号。
单张卡的显存不够，但主机上多张卡的总显存是足够的，怎样修改脚本或代码才能正常执行LORA微调？

问题出在loading checkpoint shards 环节，加载到单卡的显存放不下就失败了。
![image](https://github.com/modelscope/swift/assets/28124722/409784bb-b0d4-4a02-a9aa-ed796f3cbbca)

**Comment by Jintao-Huang** [comment]
启动脚本发一下呗

**Comment by yaleimeng** [comment]
以baichuan2为例，脚本就是项目目录中\examples\pytorch\llm\scripts\baichuan2_13b_chat\lora_ddp_ds\sft.sh
内容如下：
# Experimental environment: 2 * A100
# 2 * 35GB GPU memory
nproc_per_node=4

PYTHONPATH=../../.. \
CUDA_VISIBLE_DEVICES=0,1,2,3 \
torchrun \
    --nproc_per_node=$nproc_per_node \
    --master_port 29500 \
    src/llm_sft.py \
    --model_type baichuan2-13b-chat \
    --sft_type lora \
    --template_type baichuan \
    --dtype bf16 \
    --output_dir output \
    --ddp_backend nccl \
    --dataset damo-agent-mini-zh \
    --train_dataset_sample -1 \
    --num_train_epochs 1 \
    --max_length 4096 \
    --lora_rank 8 \
    --lora_alpha 32 \
    --lora_dropout_p 0. \
    --lora_target_modules ALL \
    --gradient_checkpointing true \
    --batch_size 1 \
    --weight_decay 0. \
    --learning_rate 1e-4 \
    --gradient_accumulation_steps $(expr 16 / $nproc_per_node) \
    --max_grad_norm 0.5 \
    --warmup_ratio 0.03 \
    --eval_steps 100 \
    --save_steps 100 \
    --save_total_limit 2 \
    --logging_steps 10 \
    --push_to_hub false \
    --hub_model_id baichuan2-13b-chat-lora \
    --hub_private_repo true \
    --hub_token 'your-sdk-token' \
    --deepspeed_config_path 'ds_config/zero2.json' \
    --only_save_model true \

**Comment by Jintao-Huang** [comment]
建议你使用mp或者mp+ddp的方式训练.

**Comment by Jintao-Huang** [comment]
你是8卡还是4卡

**Comment by yaleimeng** [comment]
mp+dpp 方式，是参考qwen7b 的相关脚本改一下就行了吗？

**Comment by Jintao-Huang** [comment]
```shell
# Experimental environment: 4 * 4090
# 2 * 22GB GPU memory
nproc_per_node=2

PYTHONPATH=../../.. \
CUDA_VISIBLE_DEVICES=0,1,2,3 \
torchrun \
    --nproc_per_node=$nproc_per_node \
    --master_port 29500 \
    src/llm_sft.py \
    --model_type baichuan2-13b-chat \
    --sft_type lora \
    --template_type baichuan \
    --dtype bf16 \
    --output_dir output \
    --ddp_backend nccl \
    --dataset blossom-math-zh \
    --train_dataset_sample -1 \
    --num_train_epochs 1 \
    --max_length 2048 \
    --lora_rank 8 \
    --lora_alpha 32 \
    --lora_dropout_p 0. \
    --lora_target_modules W_pack \
    --gradient_checkpointing true \
    --batch_size 1 \
    --weight_decay 0. \
    --learning_rate 1e-4 \
    --gradient_accumulation_steps $(expr 16 / $nproc_per_node) \
    --max_grad_norm 0.5 \
    --warmup_ratio 0.03 \
    --eval_steps 100 \
    --save_steps 100 \
    --save_total_limit 2 \
    --logging_steps 10 \
    --push_to_hub false \
    --hub_model_id baichuan2-13b-chat-lora \
    --hub_private_repo true \
    --hub_token 'your-sdk-token' \
```

你试试这个

**Comment by yaleimeng** [comment]
您给的脚本可以了。感谢答疑。
