### ISSUE TITLE
Florence-2 supp

### ISSUE THREAD

**Issue by betterftr** [modelscope/swift#1186]
**Describe the feature**
Please describe the feature requested here(请在这里描述需求)

https://huggingface.co/microsoft/Florence-2-large/ Support

**Paste any useful information**
Paste any useful information, including papers, github links, etc.(请在这里描述其他有用的信息，比如相关的论文地址，github链接等)

**Additional context**
Add any other context or information here(其他信息可以写在这里)

**Comment by tastelikefeet** [comment]
Already supported, please use the main branch
