### ISSUE TITLE
请问sft.sh中哪个参数是加载本机离线模型呀？修改model_type不正确

### ISSUE THREAD

**Issue by chiliuliu** [modelscope/swift#120]
nproc_per_node=2

#PYTHONPATH=/home/user/miniconda/envs/swift/bin/python \
PYTHONPATH=../../.. \
CUDA_VISIBLE_DEVICES=0,1 \
torchrun \
    --nproc_per_node=$nproc_per_node \
    --master_port 29500 \
    /root/swift/examples/pytorch/llm/src/llm_sft.py\
    --model_type qwen-14b-chat-int4\
    --sft_type lora \
    --template_type chatml \
    --dtype fp16 \
    --output_dir /root/swift_output \
    --ddp_backend nccl \
    --dataset csc-zh \
    --train_dataset_sample 20000 \
    --num_train_epochs 1 \
    --max_length 4096 \
    --lora_rank 8 \
    --lora_alpha 32 \
    --lora_dropout_p 0. \
    --lora_target_modules ALL \
    --gradient_checkpointing true \
    --batch_size 1 \
    --weight_decay 0. \
    --learning_rate 1e-4 \
    --gradient_accumulation_steps $(expr 16 / $nproc_per_node) \
    --max_grad_norm 0.5 \
    --warmup_ratio 0.03 \
    --eval_steps 100 \
    --save_steps 100 \
    --save_total_limit 2 \
    --logging_steps 10 \
    --use_flash_attn false \
    --push_to_hub false \
    --deepspeed_config_path 'ds_config/zero2.json' \
    --only_save_model true \

**Comment by Jintao-Huang** [comment]
如果模型已经下载是不会重复下载呀, 请问你的需求是什么呢?

**Comment by Jintao-Huang** [comment]
现在 支持了model_cache_dir参数在SftArguments, 可以使用这个参数哦, 参数的含义查看llm文件夹中的README😊

**Comment by isseptember** [comment]
> 现在 支持了model_cache_dir参数在SftArguments, 可以使用这个参数哦, 参数的含义查看llm文件夹中的README😊

请问 InferArguments 中有类似参数吗？指定模型路径，使用本地已经下载的模型

**Comment by isseptember** [comment]
> > 现在 支持了model_cache_dir参数在SftArguments, 可以使用这个参数哦, 参数的含义查看llm文件夹中的README😊
> 
> 请问 InferArguments 中有类似参数吗？指定模型路径，使用本地已经下载的模型。

可以提前将模型拷到modelscope默认下载路径 ~/.cache/modelscope/hub
