### ISSUE TITLE
Training 过程卡住

### ISSUE THREAD

**Issue by zkyredstart** [modelscope/swift#1204]
**Describe the bug**
What the bug is, and how to reproduce, better with screenshots(描述bug以及复现过程，最好有截图)
Qwen1.5用lora进行sft时候，训练日志一直处理不更新，GPU利用率为0
<img width="1508" alt="image" src="https://github.com/modelscope/swift/assets/171767364/d9aee00d-0557-4810-ab84-d293c225b9ee">
一直是这个状态，我将取数据集中前100个数据，就可以训练了，这是什么原因

**Your hardware and system info**
Write your system info like CUDA version/system/GPU/torch version here(在这里给出硬件信息和系统信息，如CUDA版本，系统，GPU型号和torch版本等)

**Additional context**
Add any other context about the problem here(在这里补充其他信息)

**Comment by zkyredstart** [comment]
数据集是train1.jaon, train2.json, train3.json 合成一个train.json,三个子集都可以正常训练，合成一个大的就不行了

**Comment by nku-zhichengzhang** [comment]
> 数据集是train1.jaon, train2.json, train3.json 合成一个train.json,三个子集都可以正常训练，合成一个大的就不行了

请问您是怎么解决的
