### ISSUE TITLE
Phi3-V Can Not Disable FlashAttention

### ISSUE THREAD

**Issue by airkid** [modelscope/swift#1209]
Not work to set `--use_flash_attn false`

https://github.com/modelscope/swift/blob/38e4d96bdab88f984b7f3bf8f94453f6ae63fac3/swift/llm/utils/model.py#L1255C24-L1255C59

**Comment by Jintao-Huang** [comment]
再试试 应该修复了
https://github.com/modelscope/swift/blob/main/swift/llm/utils/model.py#L2364
