### ISSUE TITLE
请问多模态大模型如何进行自我认知的微调

### ISSUE THREAD

**Issue by wangdong1992** [modelscope/swift#1211]
针对纯语言大模型有完整的自我认知微调文档，如下：https://github.com/modelscope/swift/blob/main/docs/source/LLM/%E8%87%AA%E6%88%91%E8%AE%A4%E7%9F%A5%E5%BE%AE%E8%B0%83%E6%9C%80%E4%BD%B3%E5%AE%9E%E8%B7%B5.md
请问多模态大模型如何进行自我认知微调？比如intern vl 1.5

**Comment by lukywangwang** [comment]
> 已解决
请问是怎么解决的？
@wangdong1992
