### ISSUE TITLE
MiniCPM-V-2 运行出错

### ISSUE THREAD

**Issue by Li-Lai** [modelscope/swift#1218]
**Describe the bug**
参考MiniCPM-V-2 最佳实践，运行：CUDA_VISIBLE_DEVICES=0 swift infer --model_type minicpm-v-v2-chat
提示如下错误：
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0
![image](https://github.com/modelscope/swift/assets/12853603/1a28800c-b635-4ae6-af10-91969660cf9c)

**Your hardware and system info**
NVIDIA-SMI 550.54.14              Driver Version: 550.54.14      CUDA Version: 12.4 
transformers                  4.37.2
torch                              2.2.2
swift 是昨天下载编译的版本

**Comment by Jintao-Huang** [comment]
--dtype bf16呢

**Comment by Li-Lai** [comment]
可以，谢谢！
