### ISSUE TITLE
glm-4v-9b模型微调出现OOM

### ISSUE THREAD

**Issue by jhrsya** [modelscope/swift#1225]
卡用的是L40S，45G显存，请问微调glm-4v-9b模型最低显存需要多少呢？

**Comment by tastelikefeet** [comment]
```shell
CUDA_VISIBLE_DEVICES=0 \
swift sft \
    --model_type glm4v-9b-chat \
    --dataset ocr-vqa#1000 \
    --num_train_epochs 1 \
    --sft_type lora \
    --ddp_find_unused_parameters true \
    --eval_steps 150 \
    --save_steps 150 \
```
在如上命令运行训练，显存占用约45551MiB

**Comment by jhrsya** [comment]
> ```shell
> CUDA_VISIBLE_DEVICES=0 \
> swift sft \
>     --model_type glm4v-9b-chat \
>     --dataset ocr-vqa#1000 \
>     --num_train_epochs 1 \
>     --sft_type lora \
>     --ddp_find_unused_parameters true \
>     --eval_steps 150 \
>     --save_steps 150 \
> ```
> 
> 在如上命令运行训练，显存占用约45551MiB

谢谢
