### ISSUE TITLE
微调glm-4v-9b模型的数据必须包含图片吗？可以不包含图片，纯文本进行微调吗？

### ISSUE THREAD

**Issue by jhrsya** [modelscope/swift#1231]
我看代码里有一个 `assert len(images) == 1`的断言，这里不用图片的话是否无法进行微调。

**Comment by Jintao-Huang** [comment]
用最新的代码 是可以的  main分支

**Comment by jhrsya** [comment]
> 用最新的代码 是可以的 main分支

好的，谢谢

**Comment by jhrsya** [comment]
> 用最新的代码 是可以的 main分支
你好！我用最新的main分支微调glm-4v-9b，一部分数据有图片，另一部分数据没有图片，微调后进行测试时出现乱码。用之前的版本进行微调时，全部微调数据都是带图片，测试时没有问题。
请问这个是最新main分支代码的问题还是微调数据都必须带有图片的原因呢？

输出的乱码如下：

**Comment by jhrsya** [comment]
已解决

**Comment by Mr-Loevan** [comment]
> 已解决

你好请问怎么解决的
