### ISSUE TITLE
Intern-VL多图任务微调以及推理方式

### ISSUE THREAD

**Issue by fourierer** [modelscope/swift#1235]
您好，我在intern-vl下看到您关于多图微调任务的描述，即按照逗号隔开来微调多图任务：
![image](https://github.com/modelscope/swift/assets/55837279/c2b98846-d414-45b9-be6f-8057af761c62)

请问按照这种方式微调完成后，推理的时候我可以按照intern-vl原有的的多图推理方式进行推理么 ，就是图中的torch.cat方式：
![image](https://github.com/modelscope/swift/assets/55837279/a553e20e-e6b9-4764-8e9c-f886bd15001e)

**Comment by hjh0119** [comment]
对多图我们也是这么处理的 https://github.com/modelscope/swift/blob/main/swift/llm/utils/template.py#L1231-L1236

**Comment by fourierer** [comment]
> 对多图我们也是这么处理的 https://github.com/modelscope/swift/blob/main/swift/llm/utils/template.py#L1231-L1236

感谢您的回复，我这边在微调多图任务时报了这个错误
![image](https://github.com/modelscope/swift/assets/55837279/3191d756-9802-42e2-ad3e-150e3ecca5c6)
我的数据格式是这样的，images对应一个列表，该列表中包括两张图像，这样写是否符合要求呢，还是说需要把两张图写在一个字符串元素里面，用逗号隔开
