### ISSUE TITLE
swift训练集和测试集如何划分

### ISSUE THREAD

**Issue by fourierer** [modelscope/swift#1238]
您好，打扰您一下，请问swift脚本里面训练集和测试集是在哪个脚本里面划分的呀，我这边想把108个测试集样本拿出来手动推理看一下结果，但不知道是哪108个
![image](https://github.com/modelscope/swift/assets/55837279/0a3a0593-e6b4-4536-a7da-27035f1a685c)

**Comment by Jintao-Huang** [comment]
get_dataset中 进行切分的
