### ISSUE TITLE
我看支持的模型列表文档里说A10支持flash_attention，是这里写错了么

### ISSUE THREAD

**Issue by pengwork** [modelscope/swift#1240]
https://github.com/modelscope/swift/blob/ff24d84cb16b07b7527619214344ba0da738a8f0/docs/source/LLM/DPO%E8%AE%AD%E7%BB%83%E6%96%87%E6%A1%A3.md?plain=1#L83C1-L84C1

**Comment by tastelikefeet** [comment]
从列表中移除了A10，不过需要注意在训练部分模型时A10并不支持flash-attn的backward，详见：https://github.com/Dao-AILab/flash-attention/issues/228
