### ISSUE TITLE
如何在训练qwen-audio时冻结参数？

### ISSUE THREAD

**Issue by Moht153** [modelscope/swift#1250]
我看了qwen-audio论文，想复现一下。不知道用swift怎么冻结qwen7B的参数，只训练whisper的编码器部分？
我看了一下文档，文档里只说了可以调整0~1百分比比值来冻结参数。请问我要怎样才能精确冻结参数呢？

**Comment by Jintao-Huang** [comment]
--freeze_parameters 1 \
--additional_trainable_parameters xxx \
