### ISSUE TITLE
可以写一些ui界面的参数说明吗

### ISSUE THREAD

**Issue by wstsr333** [modelscope/swift#1269]
可以写一些ui界面的参数说明吗，ui界面打开以后有很多参数不知道如何设置

**Comment by tastelikefeet** [comment]
命令行参数和UI参数相同，请参考：https://github.com/modelscope/swift/blob/main/docs/source/LLM/%E5%91%BD%E4%BB%A4%E8%A1%8C%E5%8F%82%E6%95%B0.md
