### ISSUE TITLE
微调自我认知后没有任何效果

### ISSUE THREAD

**Issue by wstsr333** [modelscope/swift#1273]
self_cognition_sample 参数一般要填多少啊，还有model_name和model_author参数的格式要加引号吗，用的官方那个self_cognition数据集，一共108条数据

**Comment by Jintao-Huang** [comment]
参考一下文档哈：https://github.com/modelscope/swift/blob/main/docs/source/LLM/%E8%87%AA%E6%88%91%E8%AE%A4%E7%9F%A5%E5%BE%AE%E8%B0%83%E6%9C%80%E4%BD%B3%E5%AE%9E%E8%B7%B5.md

**Comment by wstsr333** [comment]
self-cognition#500这个参数后面的#500代表什么

**Comment by wstsr333** [comment]
CUDA_VISIBLE_DEVICES=0 \
swift sft \
    --model_type glm4-9b-chat \
    --model_id_or_path /data/glm4-chat/glm-4-9b-chat/ \
    --sft_type lora \
    --dataset self-cognition#500 \
    --logging_steps 5 \
    --max_length 1024 \
    --save_steps "100" \
    --learning_rate 5e-5 \
    --gradient_accumulation_steps "8" \
    --batch_size "2" \
    --output_dir output \
    --max_grad_norm "1" \
    --lora_target_modules ALL \
    --model_name 小智 xiaozhi \
    --model_author  '' 这是微调的指令

**Comment by wstsr333** [comment]
微调之后还是没有效果

**Comment by Jintao-Huang** [comment]
微信上已经解决了, 我就关闭了
