### ISSUE TITLE
AQW量化模型失败

### ISSUE THREAD

**Issue by tt1121** [modelscope/swift#1274]
**Describe the bug**
AQW量化模型，最后一步报错，也没有提示错误在哪里。
怎么确认问题在哪里？

**Your hardware and system info**
cuda 12.2
unbuntu 24.0.3
GPU A6000
torch 2.3.0

**Additional context**
Add any other context about the problem here(在这里补充其他信息)

![image](https://github.com/modelscope/swift/assets/10417785/4de335e6-9b6c-4f5e-97ea-a0dc04f4926a)

**Comment by tastelikefeet** [comment]
是不是千问2-7b-instruct啊，这模型量化是会遇到问题的

**Comment by i-yoyocat** [comment]
> 是不是千问2-7b-instruct啊，这模型量化是会遇到问题的

Yes,我量化这个版本跟楼上一样。我再试试Qwen1.5-7B-Chat去

**Comment by i-yoyocat** [comment]
> > 是不是千问2-7b-instruct啊，这模型量化是会遇到问题的
> 
> Yes,我量化这个版本跟楼上一样。我再试试Qwen1.5-7B-Chat去

新的swift好了，Qwen2-7b-instruct也可以了
