### ISSUE TITLE
Qwen2-57B-A14B-Instruct

### ISSUE THREAD

**Issue by 22LP** [modelscope/swift#1282]
I encountered this issue while fine-tuning Qwen2-57B-A14B-Instruct and request assistance.
![1719992735380](https://github.com/modelscope/swift/assets/49529292/c2d405b9-7eda-491c-8f43-9d249e5721c2)

CUDA_VISIBLE_DEVICES=0,1 swift sft  --model_id_or_path qwen/Qwen2-57B-A14B-Instruct   --sft_type lora   --dtype AUTO  --dataset AI-ModelScope/alpaca-gpt4-data-zh#500 AI-ModelScope/alpaca-gpt4-data-en#500 swift/self-cognition#500 swift/self-cognition#500  --model_name 小胡 XiaoHu   --model_author 魔搭 ModelScope  --num_train_epochs 1  --lora_rank 8  --lora_alpha 32 --lora_dropout_p 0.05  --lora_target_modules ALL  --gradient_checkpointing true   --batch_size 1  --weight_decay 0.1   --learning_rate 1e-4  --gradient_accumulation_steps 16 --use_flash_attn false

**Comment by tastelikefeet** [comment]
Please try `--gradient_checkpointing False`, this model does not support gradient_checkpointing
