### ISSUE TITLE
Empty response when running inference on a finetuned model

### ISSUE THREAD

**Issue by babla9** [modelscope/swift#1302]
**Describe the bug**
What the bug is, and how to reproduce, better with screenshots(描述bug以及复现过程，最好有截图)

This issue occurs for me on both mini-internvl-chat-4b-v1_5 and cogvlm2-en-19b-chat. 

I finetuned the model using 

`USE_HF=1 CUDA_VISIBLE_DEVICES=0,1 swift sft --dataset filtered_image_only.jsonl --system "You are a helpful assistant"`

one line from my dataset looks like the following: 

`{
  "query": "How do I fix this broken bicycle frame?", 
  "response": "No quick fixes repairing aluminum frames. Way cheaper to get a new frame. If this is a sentimental frame and money is no object, yes it can be fixed, but the whole frame must be heat treated, because welding removes the heat treatment from the surrounding area, making it weaker and likely to quickly crack again.", 
  "images": ["images/s0do76.jpg"], 
  "id": "s0do76"
}`

then I merge the model using 

`USE_HF=1 CUDA_VISIBLE_DEVICES=0 swift export --ckpt_dir output/mini-internvl-chat-4b-v1_5/v4-20240703-061722/checkpoint-1800/ --merge_lora true`

Finally I run inference using 

`CUDA_VISIBLE_DEVICES=0 swift infer --ckpt_dir output/mini-internvl-chat-4b-v1_5/v4-20240703-061722/checkpoint-1800-merged/`

When I test using sample command from guide like 

`Write a poem based on the content of the picture.
Input a media path or URL <<< http://modelscope-open.oss-cn-hangzhou.aliyuncs.com/images/poem.png`

I get the following response 

"You are not running the flash-attention implementation, expect numerical differences.

--------------------------------------------------
" 

How do I address this issue, what could be wrong? 

**Your hardware and system info**
Write your system info like CUDA version/system/GPU/torch version here(在这里给出硬件信息和系统信息，如CUDA版本，系统，GPU型号和torch版本等)

Most recent branch of swift, using 2x NVIDIA L4 for mini-internvl-chat-4b-v1_5. 

**Additional context**
Add any other context about the problem here(在这里补充其他信息)

**Comment by Nina0109** [comment]
hi I met the same problem, have you solved this?
