### ISSUE TITLE
swift web-UI 提示：请选择或填入一个数据集

### ISSUE THREAD

**Issue by cjq345994512** [modelscope/swift#1316]
之前使用，不选择数据集(--dataset)，只填写外部数据集(--custom_dataset_info)地址，就可以进行训练
更新后，现在不选择数据集，只填写外部数据集链接，点击开始训练，就会提示：请选择或填入一个数据集
这个要怎么解决？

**Comment by tastelikefeet** [comment]
![image](https://github.com/modelscope/swift/assets/58414341/5509249d-1c9d-4673-bb1d-3d08f9db247d)
目前可以在数据集中直接便捷输入了
