### ISSUE TITLE
SFT速度非常慢：bash scripts/qwen_7b_chat_int4/sft.sh

### ISSUE THREAD

**Issue by dage0127** [modelscope/swift#132]
![image](https://github.com/modelscope/swift/assets/43975842/b175998d-9fe5-4311-9225-cf1cc7f9b70f)
bash scripts/qwen_7b_chat_int4/sft.sh 运行速度非常慢，一批大约需要60秒左右。
其中，batch_size = 1
请帮忙看看是啥问题？

**Comment by Jintao-Huang** [comment]
看起来确实有点慢, 我这里大概是10s/it. A100. max_length=2000

**Comment by Jintao-Huang** [comment]
你看看 显卡的利用率是多少
