### ISSUE TITLE
model_type: 'internvl2-8b' is not registered

### ISSUE THREAD

**Issue by Jiax323** [modelscope/swift#1324]
CUDA_VISIBLE_DEVICES=0 swift sft \
    --model_type internvl2-8b \
    --dataset /home/admin/workspace/aop_lab/inf_extr_data/train_dataset_ocr_pic_intern.json \
    --max_length 4096
    
    显示model_type: 'internvl2-8b' is not registered

**Comment by Jiax323** [comment]
[INFO:swift] Downloading the model from ModelScope Hub, model_id: OpenGVLab/InternVL2-8B
[ERROR:modelscope] The request model: OpenGVLab/InternVL2-8B does not exist!
会出现这个错误

**Comment by hjh0119** [comment]
该模型是申请制下载, 你需要申请下载后用[ModelScope Hub](https://www.modelscope.cn/docs/ModelScope%20Hub%E4%BD%BF%E7%94%A8%E6%96%87%E6%A1%A3)登录

**Comment by Jiax323** [comment]
下载之后如何在python代码中进行调用呢，有相关参考文档吗？

**Comment by GoudyGe** [comment]
我也遇到这个问题：我的是internvl2-1b 想微调提示模型没有注册，我snapshot download下载下来了之后，依然有这个提醒。

**Comment by hjh0119** [comment]
@GoudyGe 见FQA第一条 https://github.com/modelscope/swift/blob/main/docs/source/Multi-Modal/internvl%E6%9C%80%E4%BD%B3%E5%AE%9E%E8%B7%B5.md

**Comment by GoudyGe** [comment]
> @GoudyGe 见FQA第一条 https://github.com/modelscope/swift/blob/main/docs/source/Multi-Modal/internvl%E6%9C%80%E4%BD%B3%E5%AE%9E%E8%B7%B5.md
![image](https://github.com/user-attachments/assets/ef60e7a1-8041-4e33-bda2-e40d0fe0b0e2)

**Comment by hjh0119** [comment]
@GoudyGe hub_token的逻辑最近几天有更新, 你试下更新swift会不会还有问题

**Comment by GoudyGe** [comment]
> @GoudyGe hub_token的逻辑最近几天有更新, 你试下更新swift会不会还有问题

而且我看了微调命令的help里面是没有1b的模型的，但是文档里面写了有1b，2b的才有。

**Comment by hjh0119** [comment]
@GoudyGe  1b是昨天新支持的, 需要你用源码安装swift

**Comment by GoudyGe** [comment]
> @GoudyGe 1b是昨天新支持的, 需要你用源码安装swift

ok··· 明白了
