### ISSUE TITLE
internlm-xcomposer2_5-7b fine-tuning with multiple gpus reports an error "all tensors to be on the same device"

### ISSUE THREAD

**Issue by thonglv21** [modelscope/swift#1335]
`CUDA_VISIBLE_DEVICES=0,1 swift sft --model_type internlm-xcomposer2_5-7b-chat --dataset myData.jsonl`

Expected all tensors to be on the same device, but found at least two devices

Looking forward to your answer!

**Comment by Jintao-Huang** [comment]
NPROC_PER_NODE=2 CUDA_VISIBLE_DEVICES=0,1 swift sft --model_type internlm-xcomposer2_5-7b-chat --dataset myData.jsonl --deepspeed default-zero2
