### ISSUE TITLE
离线运行 InternLM 问题 需要再下载文件

### ISSUE THREAD

**Issue by fly-dragon211** [modelscope/swift#1346]
运行官方脚本：https://github.com/modelscope/swift/blob/main/docs/source/Multi-Modal/internlm-xcomposer2%E6%9C%80%E4%BD%B3%E5%AE%9E%E8%B7%B5.md#%E6%8E%A8%E7%90%86

手动指定 model_id_or_path
CUDA_VISIBLE_DEVICES=3 swift infer --model_type internlm-xcomposer2-7b-chat \
  --model_id_or_path modelscope_model/internlm-xcomposer2-7b/

但是出现报错，模型需要继续下载 internlm-xcomposer2d5-clip/ 文件，服务器无法联网，请问应该如何离线指定路径呢

**Comment by Jintao-Huang** [comment]
直接修改一下 internlm-xcomposer2-7b-chat 中的build_mlp.py文件

**Comment by fly-dragon211** [comment]
> 直接修改一下 internlm-xcomposer2-7b-chat 中的build_mlp.py文件

这样确实可以，但是希望能在命令行指定这个参数
