### ISSUE TITLE
please remove fnctl to support windows

### ISSUE THREAD

**Issue by tiandiweizun** [modelscope/swift#1350]
**Describe the bug**
What the bug is, and how to reproduce, better with screenshots(描述bug以及复现过程，最好有截图)
win10 cpu 提示ModuleNotFoundError: No module named 'fcntl'，请移除fnctl支持windows环境， 如果您正在尝试锁定文件，可以使用其他Python模块，如`portalocker`

![image](https://github.com/modelscope/swift/assets/13550295/b4542051-fd28-4502-824e-a62b14c45490)

**Comment by tastelikefeet** [comment]
Fixed by #1354
