### ISSUE TITLE
Yi-VL finetune error - KeyError: 'images'

### ISSUE THREAD

**Issue by tectal** [modelscope/swift#1357]
运行的脚本
`CUDA_VISIBLE_DEVICES=0 \

swift sft \
    --model_type yi-vl-6b-chat \
    --model_id_or_path E:/ygf/swift/Yi-VL-6B \
    --sft_type lora \
    --tuner_backend peft \
    --template_type AUTO \
    --dtype AUTO \
    --output_dir E:/ygf/swift/output \
    --dataset E:/ygf/swift/uav/1v1.json \
    --train_dataset_sample -1 \
    --num_train_epochs 1 \
    --max_length 2048 \
    --check_dataset_strategy warning \
    --lora_rank 8 \
    --lora_alpha 32 \
    --lora_dropout_p 0.05 \
    --lora_target_modules DEFAULT \
    --gradient_checkpointing true \
    --batch_size 1 \
    --weight_decay 0.1 \
    --learning_rate 1e-4 \
    --gradient_accumulation_steps 16 \
    --max_grad_norm 0.5 \
    --warmup_ratio 0.03 \
    --eval_steps 500 \
    --save_steps 500 \
    --save_total_limit 2 \
    --logging_steps 500 \
    --use_flash_attn false`

---
[INFO:swift] system: This is a chat between an inquisitive human and an AI assis
tant. Assume the role of the AI assistant. Read all the images carefully, and re
spond to the human's questions with informative, helpful, detailed and polite an
swers. 这是一个好奇的人类和一个人工智能助手之间的对话。假设你扮演这个AI助手的角 
色。仔细阅读所有的图像，并对人类的问题做出信息丰富、有帮助、详细的和礼貌的回答。
[INFO:swift] args.lazy_tokenize: True
Traceback (most recent call last):
  File "C:\Users\jxny02\anaconda3\envs\swift\lib\site-packages\swift\cli\sft.py"
, line 5, in <module>
    sft_main()
  File "C:\Users\jxny02\anaconda3\envs\swift\lib\site-packages\swift\utils\run_u
tils.py", line 27, in x_main
    result = llm_x(args, **kwargs)
  File "C:\Users\jxny02\anaconda3\envs\swift\lib\site-packages\swift\llm\sft.py"
, line 251, in llm_sft
    td0, tkwargs0 = template.encode(train_dataset[0])
  File "C:\Users\jxny02\anaconda3\envs\swift\lib\site-packages\swift\llm\utils\t
emplate.py", line 719, in encode
    images_path = example['images']
KeyError: 'images'

---
1v1.json文件
部分
...
{
        "id": "identity_41641",
        "conversations": [
            {
                "from": "user",
                "value": "Picture 1: <img>./1v1_2023.5.1/192.jpg</img>\n2022年11月9日天气是多少？"
            },
            {
                "from": "assistant",
                "value": "2022年11月9日天气是晴天。"
            }
        ]
    },
    {
        "id": "identity_41642",
        "conversations": [
            {
                "from": "user",
                "value": "Picture 1: <img>./1v1_2023.5.1/193.jpg</img>\n2022年11月10日天气是多少？"
            },
            {
                "from": "assistant",
                "value": "2022年11月10日天气是阴天。"
            }
        ]
    },
...

**Comment by tectal** [comment]
{"query": "55555", "response": "66666", "images": ["image_path"]}
{"query": "eeeee", "response": "fffff", "history": [], "images": ["image_path"]}
{"query": "EEEEE", "response": "FFFFF", "history": [["AAAAA", "BBBBB"], ["CCCCC", "DDDDD"]], "images": ["image_path", "image_path2", "image_path3"]}

数据集必须有"images": ["xxx"]，不能按[自定义数据集]格式。

**Comment by Jintao-Huang** [comment]
你把数据集格式转一下就好了

**Comment by tectal** [comment]
> 你把数据集格式转一下就好了

意思是只能上面三种的格式是吗
