### ISSUE TITLE
使用Swift deploy进行推理和使用vllm_inference接口推理结果不一致

### ISSUE THREAD

**Issue by caliba** [modelscope/swift#1373]
我是用两种方式同一数据集进行测试：
实验环境：V100 *4 微调后merge的qwen1模型，temperature = 0.0
实验对象：1k条case,分类任务,输出是json格式

方法1:使用swift deploy:
启动：
`RAY_memory_monitor_refresh_ms=0 CUDA_VISIBLE_DEVICES=0,1,2,3 swift deploy --model_type qwen-7b-chat --tensor_parallel_size 4 --ckpt_dir /root/my_lib/swift/examples/pytorch/llm/output_gjh/qwen-7b-chat/v4-20240704-175107/checkpoint-5490-merged --temperatue 0.0`

推理：
```
 req = """curl http://localhost:8000/v1/chat/completions \
                        -H "Content-Type: application/json" \
                        -d '{
                        "model": "qwen-7b-chat",
                        "temperature": 0.0,
                        "messages": [{"role": "user", "content": "%s"}]
                        }'
                """ % query
curl_result = subprocess.run(req, shell=True, capture_output=True, text=True)
#print(curl_result.stdout)
resp = json.loads(curl_result.stdout)["choices"][0]['message']['content']
if resp not in cls_list:
    resp = "空"
data[keywords] = resp
```

方法2:使用 inference_vllm 接口：
```
def llm_inference(query):
    test_template = """ """
    request_list = []
    prompt = test_template.format(query=query)
    request_list.append({"query":prompt})
    resp = inference_vllm(llm_engine, template, request_list)
    return resp[0]["response"]


def batch_infer(data_list):
    turns = 1
    cls_list = get_mapping()
    aim_file = open(args.data_name,'w',encoding="utf-8")
    for i in range(turns):
        keywords = "backend_"+str(i)
        cnt = 0
        for line in data_list:
            cnt += 1
            if cnt % 100==0:
                print("Having process {} items".format(cnt))
            dict_data = line
            query = dict_data["query"]
            ans = llm_inference(query)
            if ans not in cls_list:
                ans = "空"
            print(ans)
            dict_data[keywords] = str(ans)

    for dict_data in data_list:
        aim_file.write(json.dumps(dict_data, ensure_ascii=False)+"\n")
```

我进行了多次测试，发现对于每一种方法，其重复多次实验结果都相同；方法1和方法2之间始终有约30%的diff
请问一下这个情况出现的原因是什么？

**Comment by Jintao-Huang** [comment]
resp = inference_vllm(llm_engine, template, request_list) 设置一下 temperature

e.g.
llm_engine.generation_config.temperature = 0

**Comment by caliba** [comment]
> resp = inference_vllm(llm_engine, template, request_list) 设置一下 temperature
> 
> e.g. llm_engine.generation_config.temperature = 0

我之前是在generation_config里面改的：
```
{
  "chat_format": "chatml",
  "do_sample": true,
  "eos_token_id": 151645,
  "max_new_tokens": 2048,
  "max_window_size": 24000,
  "pad_token_id": 151645,
  "temperature": 0.0,
  "top_k": 20,
  "top_p": 0.7,
  "transformers_version": "4.39.2"
}
```
推理时log中显示的配置：
`SamplingParams(n=1, best_of=1, presence_penalty=0.0, frequency_penalty=0.0, repetition_penalty=1.0, temperature=0, top_p=1.0, top_k=-1, min_p=0.0, seed=None, use_beam_search=False, length_penalty=1.0, early_stopping=False, stop=['<|im_end|>'], stop_token_ids=[], include_stop_str_in_output=False, ignore_eos=False, max_tokens=2048, min_tokens=0, logprobs=None, prompt_logprobs=None, skip_special_tokens=True, spaces_between_special_tokens=True)`

结果仍然存在diff

**Comment by Jintao-Huang** [comment]
将swift升级到最新呢

**Comment by caliba** [comment]
swift版本升级为：ms-swift      2.2.0.dev0 后与上述实验结果一致，仍然存在上述差异

**Comment by Jintao-Huang** [comment]
部署的时候temperature 在客户端进行指定

服务端指定不生效的问题 我看看

**Comment by Jintao-Huang** [comment]
服务端指定不生效的情况在infer_backend='pt'时出现，已修复

infer_backend='vllm'没有复现

**Comment by caliba** [comment]
> 服务端指定不生效的情况在infer_backend='pt'时出现，已修复
> 
> infer_backend='vllm'没有复现

更新swift版本为：
ms-swift                                2.3.0.dev0

请问是这样修改吗？
`RAY_memory_monitor_refresh_ms=0 CUDA_VISIBLE_DEVICES=0,1,2,3 swift deploy --model_type qwen-7b-chat --tensor_parallel_size 4 --ckpt_dir /root/my_lib/swift/examples/pytorch/llm/lianjing/qwen-7b-chat/v6-20240527-175428/checkpoint-2500-merged --temperature 0.0 --infer_backend pt`

```
template_type = get_default_template_type(model_type)
llm_engine = get_vllm_engine(model_type, model_id_or_path=ckpt_dir, max_model_len=2048, torch_dtype=torch.float16, tensor_parallel_size=4, engine_kwargs={"max_num_seqs":8,  "seed":42},enforce_eager=True,infer_backend = "pt")
llm_engine.generation_config.temperature = 0
```

generation_config
```
{
  "chat_format": "chatml",
  "do_sample": true,
  "eos_token_id": 151645,
  "max_new_tokens": 2048,
  "max_window_size": 24000,
  "pad_token_id": 151645,
  "temperature": 0.0,
  "top_k": 20,
  "top_p": 0.7,
  "transformers_version": "4.39.2"
}
```


这样修改后两种方法仍然存在diff，占30%

**Comment by Jintao-Huang** [comment]
> > 服务端指定不生效的情况在infer_backend='pt'时出现，已修复
> > infer_backend='vllm'没有复现
> 
> 更新swift版本为： ms-swift 2.3.0.dev0
> 
> 请问是这样修改吗？ `RAY_memory_monitor_refresh_ms=0 CUDA_VISIBLE_DEVICES=0,1,2,3 swift deploy --model_type qwen-7b-chat --tensor_parallel_size 4 --ckpt_dir /root/my_lib/swift/examples/pytorch/llm/lianjing/qwen-7b-chat/v6-20240527-175428/checkpoint-2500-merged --temperature 0.0 --infer_backend pt`
> 
> ```
> template_type = get_default_template_type(model_type)
> llm_engine = get_vllm_engine(model_type, model_id_or_path=ckpt_dir, max_model_len=2048, torch_dtype=torch.float16, tensor_parallel_size=4, engine_kwargs={"max_num_seqs":8,  "seed":42},enforce_eager=True,infer_backend = "pt")
> llm_engine.generation_config.temperature = 0
> ```
> 
> generation_config
> 
> ```
> {
>   "chat_format": "chatml",
>   "do_sample": true,
>   "eos_token_id": 151645,
>   "max_new_tokens": 2048,
>   "max_window_size": 24000,
>   "pad_token_id": 151645,
>   "temperature": 0.0,
>   "top_k": 20,
>   "top_p": 0.7,
>   "transformers_version": "4.39.2"
> }
> ```
> 
> 这样修改后两种方法仍然存在diff，占30%

RAY_memory_monitor_refresh_ms=0 CUDA_VISIBLE_DEVICES=0,1,2,3 swift deploy --model_type qwen-7b-chat --tensor_parallel_size 4 --ckpt_dir /root/my_lib/swift/examples/pytorch/llm/lianjing/qwen-7b-chat/v6-20240527-175428/checkpoint-2500-merged --temperature 0.0 --infer_backend pt --dtype fp16

**Comment by Jintao-Huang** [comment]
试试这个加个 --dtype fp16
