### ISSUE TITLE
部署InternVL2-26B显存配比不均衡，无法完成推理，会直接报显存溢出

### ISSUE THREAD

**Issue by Halflifefa** [modelscope/swift#1376]
**Describe the bug**
What the bug is, and how to reproduce, better with screenshots(描述bug以及复现过程，最好有截图)
部署指令
```
CUDA_VISIBLE_DEVICES=0,1,2,3 swift deploy  --host 0.0.0.0 --port 23333 \
--model_id_or_path /data/hfd/InternVL2-26B --model_type internvl2-26b \
--dtype bf16 --max_length 4096
```
部署后，前两张卡跑满，后两张卡几乎无占用，推理就会报显存溢出。

**Your hardware and system info**
Write your system info like CUDA version/system/GPU/torch version here(在这里给出硬件信息和系统信息，如CUDA版本，系统，GPU型号和torch版本等)
版本：
```
ms-swift-2.3.0.dev0
Driver Version: 550.90.07
CUDA Version: 12.4
```
nvidia-smi信息：
![image](https://github.com/user-attachments/assets/0b8c10ef-64c8-4e0e-99bf-5fc0cc75a8f8)

**Additional context**
Add any other context about the problem here(在这里补充其他信息)

**Comment by tastelikefeet** [comment]
device_map对多模态模型的支持不太好，我们增加了一个参数：
```shell
--device_max_memory 15GB 15GB 15GB 15GB
```
这会在模型初始化时让device_map显存分配更均匀，拉最新的main分支试试
