### ISSUE TITLE
QwenVL  Expected all tensors to be on the same device 

### ISSUE THREAD

**Issue by wellhowtosay** [modelscope/swift#1389]
[rank4]:   File "/luka-work/miniconda3/envs/llm/lib/python3.11/site-packages/torch/amp/autocast_mode.py", line 16, in decorate_autocast
[rank4]:     return func(*args, **kwargs)
[rank4]:            ^^^^^^^^^^^^^^^^^^^^^
[rank4]:   File "/luka-work/miniconda3/envs/llm/lib/python3.11/site-packages/peft/peft_model.py", line 1430, in forward
[rank4]:     return self.base_model(
[rank4]:            ^^^^^^^^^^^^^^^^
[rank4]:   File "/luka-work/miniconda3/envs/llm/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
[rank4]:     return self._call_impl(*args, **kwargs)
[rank4]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank4]:   File "/luka-work/miniconda3/envs/llm/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
[rank4]:     return forward_call(*args, **kwargs)
[rank4]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank4]:   File "/luka-work/miniconda3/envs/llm/lib/python3.11/site-packages/peft/tuners/tuners_utils.py", line 179, in forward
[rank4]:     return self.model.forward(*args, **kwargs)
[rank4]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank4]:   File "/root/.cache/huggingface/modules/transformers_modules/Qwen-VL-Chat-Int4/modeling_qwen.py", line 856, in forward
[rank4]:     transformer_outputs = self.transformer(
[rank4]:                           ^^^^^^^^^^^^^^^^^
[rank4]:   File "/luka-work/miniconda3/envs/llm/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
[rank4]:     return self._call_impl(*args, **kwargs)
[rank4]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank4]:   File "/luka-work/miniconda3/envs/llm/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
[rank4]:     return forward_call(*args, **kwargs)
[rank4]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank4]:   File "/root/.cache/huggingface/modules/transformers_modules/Qwen-VL-Chat-Int4/modeling_qwen.py", line 662, in forward
[rank4]:     hidden_states = hidden_states + images.mean()*0
[rank4]:                     ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~
[rank4]: RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:4 and cuda:0!

**Comment by Jintao-Huang** [comment]
命令发一下

**Comment by wellhowtosay** [comment]
> 命令发一下

#!/bin/bash
export CUDA_VISIBLE_DEVICES=0,1,2,3,4,5
export NPROC_PER_NODE=6
MODEL="/xyq-t-work/Qwen-VL-master/Qwen-VL-Chat-Int4" # Qwen/Qwen-VL-Chat-Int4 Set the path if you do not want to load from huggingface directly
# ATTENTION: specify the path to your training data, which should be a json file consisting of a list of conversations.
# See the section for finetuning in README for more information.
DATA="xxx"


# Remember to use --fp16 instead of --bf16 due to autogptq
swift sft  \
    --model_id_or_path $MODEL \
    --model_type qwen-vl-chat-int4 \
    --model_revision master \
    --sft_type lora \
    --tuner_backend peft \
    --template_type AUTO \
    --dtype AUTO \
    --output_dir output \
    --dataset $DATA \
    --train_dataset_sample -1 \
    --num_train_epochs 2 \
    --max_length 2048 \
    --check_dataset_strategy warning \
    --lora_rank 32 \
    --lora_alpha 16 \
    --lora_dropout_p 0.05 \
    --gradient_checkpointing true \
    --batch_size 4 \
    --weight_decay 0.1 \
    --learning_rate 1e-4 \
    --gradient_accumulation_steps 30 \
    --max_grad_norm 0.5 \
    --warmup_ratio 0.03 \
    --eval_steps 200 \
    --save_steps 200 \
    --save_total_limit 2 \
    --logging_steps 100 \
    --use_flash_attn false

你把github玩成微信了

**Comment by wellhowtosay** [comment]
> 命令发一下

export CUDA_VISIBLE_DEVICES=0,1,2,3,4,5
export NPROC_PER_NODE=6
MODEL="/xyq-t-work/Qwen-VL-master/Qwen-VL-Chat-Int4" # Qwen/Qwen-VL-Chat-Int4 Set the path if you do not want to load from huggingface directly
DATA="xxx"


# Remember to use --fp16 instead of --bf16 due to autogptq
swift sft  \
    --model_id_or_path $MODEL \
    --model_type qwen-vl-chat-int4 \
    --model_revision master \
    --sft_type lora \
    --tuner_backend peft \
    --template_type AUTO \
    --dtype AUTO \
    --output_dir output \
    --dataset $DATA \
    --train_dataset_sample -1 \
    --num_train_epochs 2 \
    --max_length 2048 \
    --check_dataset_strategy warning \
    --lora_rank 32 \
    --lora_alpha 16 \
    --lora_dropout_p 0.05 \
    --gradient_checkpointing true \
    --batch_size 4 \
    --weight_decay 0.1 \
    --learning_rate 1e-4 \
    --gradient_accumulation_steps 30 \
    --max_grad_norm 0.5 \
    --warmup_ratio 0.03 \
    --eval_steps 200 \
    --save_steps 200 \
    --save_total_limit 2 \
    --logging_steps 100 \
    --use_flash_attn false

你把github玩成微信了

**Comment by Jintao-Huang** [comment]
感觉是 NPROC_PER_NODE 没有生效. 你查看一下是不是torchrun启动的

**Comment by liuyijiang1994** [comment]
借楼请教一下hidden_states = hidden_states + images.mean()*0这句话的目的是什么？不加的话会有什么影响吗？

**Comment by Jintao-Huang** [comment]
> 借楼请教一下hidden_states = hidden_states + images.mean()*0这句话的目的是什么？不加的话会有什么影响吗？

zero3 & 纯文本+图片 微调的情况

**Comment by liuyijiang1994** [comment]
> 
> zero3 & 纯文本+图片 微调的情况

了解，请问具体是其中的哪个部分影响呢，例如流水线并行？有什么参考材料可以学习下吗
