### ISSUE TITLE
VLLM deployment

### ISSUE THREAD

**Issue by ZhaoKangkang0572** [modelscope/swift#1390]
在以下文档中没有找到我需要的常规**部署指令**，请教一下
[Vllm推理部署](https://github.com/modelscope/swift/blob/main/docs/source/LLM/VLLM%E6%8E%A8%E7%90%86%E5%8A%A0%E9%80%9F%E4%B8%8E%E9%83%A8%E7%BD%B2.md#%E5%BE%AE%E8%B0%83%E5%90%8E%E6%A8%A1%E5%9E%8B-1)

我的部署基础是：
> 全量微调之后的模型
> 需要api部署以便和eval-scope对接
> 模型是qwen2系列

我尝试了**如下指令**：
CUDA_VISIBLE_DEVICES=0 swift deploy -- load_args_from_ckpt_dir true --ckpt_dir XXX/latest --model_type qwen2-1_5b-instruct
1. CUDA_VISIBLE_DEVICES=0 swift deploy --ckpt_dir XXX/latest  

> 报错 ： ValueError: Please use `--ckpt_dir vx-xxx/checkpoint-xxx` to use the checkpoint.

2. CUDA_VISIBLE_DEVICES=0 swift deploy --model_id_or_path XXX/latest  

> 报错：     raise ValueError('please setting `--model_type <model_type>`. ' + error_msg)

3. CUDA_VISIBLE_DEVICES=0 swift deploy --model_type qwen2-1_5b-instruct --model_id_or_path XXX/latest  
> 未报错，但是开始从modelscope下载官方版本的qwen2-1_5b-instruct 了

4.  CUDA_VISIBLE_DEVICES=0 swift deploy --model_type qwen2-1_5b-instruct --ckpt_dir XXX/latest  
> 报错： ValueError: Please use `--ckpt_dir vx-xxx/checkpoint-xxx` to use the checkpoint.

很奇怪的是，为什么指定了**model_type**之后就开始自动下载，但是不指定的话，推理怎么确认该用什么模板呢，难道是从**路径判断**吗？
我是从**eval-scope**跳过来的，没用过这个框架训练，请教一下

**Comment by Jintao-Huang** [comment]
CUDA_VISIBLE_DEVICES=0 swift deploy --model_type qwen2-1_5b-instruct --model_id_or_path XXX/latest

这种用法是正确的。如果出现异常情况，请升级ms-swift到最新版本 2.2.2

**Comment by ZhaoKangkang0572** [comment]
> CUDA_VISIBLE_DEVICES=0 swift deploy --model_type qwen2-1_5b-instruct --model_id_or_path XXX/latest
> 
> 这种用法是正确的。如果出现异常情况，请升级ms-swift到最新版本 2.2.2

感谢回复，确认了下版本是2.2.2，因为是刚装的

> pip show ms-swift
Name: ms-swift
Version: 2.2.2
Summary: Swift: Scalable lightWeight Infrastructure for Fine-Tuning
Home-page: https://github.com/modelscope/swift
 完成报错如下：

> Duplicate key in file PosixPath('anaconda3/envs/sft/lib/python3.10/site-packages/matplotlib/mpl-data/matplotlibrc'), line 805 ('font.family: sans-serif')
Duplicate key in file PosixPath('anaconda3/envs/sft/lib/python3.10/site-packages/matplotlib/mpl-data/matplotlibrc'), line 806 ('font.sans-serif: SimHei')
run sh: `python anaconda3/envs/sft/lib/python3.10/site-packages/swift/cli/deploy.py --model_type qwen2-1_5b-instruct --model_id_or_path /Qwen2-1___5B_dumplicated/latest`
Duplicate key in file PosixPath('anaconda3/envs/sft/lib/python3.10/site-packages/matplotlib/mpl-data/matplotlibrc'), line 805 ('font.family: sans-serif')
Duplicate key in file PosixPath('anaconda3/envs/sft/lib/python3.10/site-packages/matplotlib/mpl-data/matplotlibrc'), line 806 ('font.sans-serif: SimHei')
2024-07-15 16:36:21,221 - modelscope - INFO - PyTorch version 2.3.0 Found.
2024-07-15 16:36:21,232 - modelscope - INFO - Loading ast index from /home/.cache/modelscope/ast_indexer
2024-07-15 16:36:25,028 - modelscope - INFO - Loading done! Current index file version is 1.15.0, with md5 24e680bc11951da113c9bc7b81a16473 and a total number of 980 components indexed
[INFO:swift] Successfully registered `anaconda3/envs/sft/lib/python3.10/site-packages/swift/llm/data/dataset_info.json`
[INFO:swift] Start time of running main: 2024-07-15 16:36:32.587604
[INFO:swift] ckpt_dir: None
[INFO:swift] Due to `ckpt_dir` being `None`, `load_args_from_ckpt_dir` is set to `False`.
Traceback (most recent call last):
  File "anaconda3/envs/sft/lib/python3.10/site-packages/swift/cli/deploy.py", line 5, in <module>
    deploy_main()
  File "anaconda3/envs/sft/lib/python3.10/site-packages/swift/utils/run_utils.py", line 21, in x_main
    args, remaining_argv = parse_args(args_class, argv)
  File "anaconda3/envs/sft/lib/python3.10/site-packages/swift/utils/utils.py", line 130, in parse_args
    args, remaining_args = parser.parse_args_into_dataclasses(argv, return_remaining_strings=True)
  File "anaconda3/envs/sft/lib/python3.10/site-packages/transformers/hf_argparser.py", line 339, in parse_args_into_dataclasses
    obj = dtype(**inputs)
  File "<string>", line 82, in __init__
  File "anaconda3/envs/sft/lib/python3.10/site-packages/swift/llm/utils/argument.py", line 1330, in __post_init__
    super().__post_init__()
  File "anaconda3/envs/sft/lib/python3.10/site-packages/swift/llm/utils/argument.py", line 1184, in __post_init__
    self.set_model_type()
  File "anaconda3/envs/sft/lib/python3.10/site-packages/swift/llm/utils/argument.py", line 411, in set_model_type
    raise ValueError('Please use `--ckpt_dir vx-xxx/checkpoint-xxx` to use the checkpoint.')
ValueError: Please use `--ckpt_dir vx-xxx/checkpoint-xxx` to use the checkpoint.

**Comment by Jintao-Huang** [comment]
<img width="851" alt="截屏2024-07-15 16 51 16" src="https://github.com/user-attachments/assets/6686ed37-91cb-4ec2-91b3-093ae5ee492c">

怎么会跑到这个分支里去呢. 你看看打印一下model_id_or_path是啥, 是否含`checkpoint`

**Comment by ZhaoKangkang0572** [comment]
> > CUDA_VISIBLE_DEVICES=0 swift deploy --model_type qwen2-1_5b-instruct --model_id_or_path XXX/latest
> > 这种用法是正确的。如果出现异常情况，请升级ms-swift到最新版本 2.2.2
> 
> 感谢回复，确认了下版本是2.2.2，因为是刚装的
> 
> > pip show ms-swift
> > Name: ms-swift
> > Version: 2.2.2
> > Summary: Swift: Scalable lightWeight Infrastructure for Fine-Tuning
> > Home-page: https://github.com/modelscope/swift
> > 完成报错如下：
> 
> > Duplicate key in file PosixPath('anaconda3/envs/sft/lib/python3.10/site-packages/matplotlib/mpl-data/matplotlibrc'), line 805 ('font.family: sans-serif')
> > Duplicate key in file PosixPath('anaconda3/envs/sft/lib/python3.10/site-packages/matplotlib/mpl-data/matplotlibrc'), line 806 ('font.sans-serif: SimHei')
> > run sh: `python anaconda3/envs/sft/lib/python3.10/site-packages/swift/cli/deploy.py --model_type qwen2-1_5b-instruct --model_id_or_path /Qwen2-1___5B_dumplicated/latest`
> > Duplicate key in file PosixPath('anaconda3/envs/sft/lib/python3.10/site-packages/matplotlib/mpl-data/matplotlibrc'), line 805 ('font.family: sans-serif')
> > Duplicate key in file PosixPath('anaconda3/envs/sft/lib/python3.10/site-packages/matplotlib/mpl-data/matplotlibrc'), line 806 ('font.sans-serif: SimHei')
> > 2024-07-15 16:36:21,221 - modelscope - INFO - PyTorch version 2.3.0 Found.
> > 2024-07-15 16:36:21,232 - modelscope - INFO - Loading ast index from /home/.cache/modelscope/ast_indexer
> > 2024-07-15 16:36:25,028 - modelscope - INFO - Loading done! Current index file version is 1.15.0, with md5 24e680bc11951da113c9bc7b81a16473 and a total number of 980 components indexed
> > [INFO:swift] Successfully registered `anaconda3/envs/sft/lib/python3.10/site-packages/swift/llm/data/dataset_info.json`
> > [INFO:swift] Start time of running main: 2024-07-15 16:36:32.587604
> > [INFO:swift] ckpt_dir: None
> > [INFO:swift] Due to `ckpt_dir` being `None`, `load_args_from_ckpt_dir` is set to `False`.
> > Traceback (most recent call last):
> > File "anaconda3/envs/sft/lib/python3.10/site-packages/swift/cli/deploy.py", line 5, in 
> > deploy_main()
> > File "anaconda3/envs/sft/lib/python3.10/site-packages/swift/utils/run_utils.py", line 21, in x_main
> > args, remaining_argv = parse_args(args_class, argv)
> > File "anaconda3/envs/sft/lib/python3.10/site-packages/swift/utils/utils.py", line 130, in parse_args
> > args, remaining_args = parser.parse_args_into_dataclasses(argv, return_remaining_strings=True)
> > File "anaconda3/envs/sft/lib/python3.10/site-packages/transformers/hf_argparser.py", line 339, in parse_args_into_dataclasses
> > obj = dtype(**inputs)
> > File "", line 82, in **init**
> > File "anaconda3/envs/sft/lib/python3.10/site-packages/swift/llm/utils/argument.py", line 1330, in **post_init**
> > super().**post_init**()
> > File "anaconda3/envs/sft/lib/python3.10/site-packages/swift/llm/utils/argument.py", line 1184, in **post_init**
> > self.set_model_type()
> > File "anaconda3/envs/sft/lib/python3.10/site-packages/swift/llm/utils/argument.py", line 411, in set_model_type
> > raise ValueError('Please use `--ckpt_dir vx-xxx/checkpoint-xxx` to use the checkpoint.')
> > ValueError: Please use `--ckpt_dir vx-xxx/checkpoint-xxx` to use the checkpoint.

果然还是跟路径有关，看了下代码，

swift.llm.utils.argument 的409行：
if (isinstance(self, InferArguments) and 'checkpoint' in model_id_or_path
路径带了checkpoint就走到这里了，改掉就ok，感谢
