### ISSUE TITLE
请问指定多个数据集，那么多个数据集数据是随机混合，还是 dataset1, dateset2 这样拼接呢

### ISSUE THREAD

**Issue by fly-dragon211** [modelscope/swift#1391]
请问指定多个数据集，那么多个数据集数据是随机混合，还是 dataset1, dateset2 这样拼接呢

**Comment by Jintao-Huang** [comment]
get_dataset使用数据集拼接策略

数据集的随机打乱会在hf_trainer中进行

**Comment by fly-dragon211** [comment]
> get_dataset使用数据集拼接策略
> 
> 数据集的随机打乱会在hf_trainer中进行

感谢解答，那么可以手动设置数据集随机打乱或者不打乱吗，如果可以是哪个参数呢？
https://github.com/modelscope/swift/blob/main/docs/source/LLM/%E5%91%BD%E4%BB%A4%E8%A1%8C%E5%8F%82%E6%95%B0.md

**Comment by Jintao-Huang** [comment]
> > get_dataset使用数据集拼接策略
> > 数据集的随机打乱会在hf_trainer中进行
> 
> 感谢解答，那么可以手动设置数据集随机打乱或者不打乱吗，如果可以是哪个参数呢？ https://github.com/modelscope/swift/blob/main/docs/source/LLM/%E5%91%BD%E4%BB%A4%E8%A1%8C%E5%8F%82%E6%95%B0.md

get_dataset没有参数控制是否打乱. （切分训练集和测试集，以及数据集采样的时候存在随机打乱）

如果只是指定`--dataset <path1> <path2>` 则不会打乱

**Comment by fly-dragon211** [comment]
> > > get_dataset使用数据集拼接策略
> > > 数据集的随机打乱会在hf_trainer中进行
> > 
> > 
> > 感谢解答，那么可以手动设置数据集随机打乱或者不打乱吗，如果可以是哪个参数呢？ https://github.com/modelscope/swift/blob/main/docs/source/LLM/%E5%91%BD%E4%BB%A4%E8%A1%8C%E5%8F%82%E6%95%B0.md
> 
> get_dataset没有参数控制是否打乱. （切分训练集和测试集，以及数据集采样的时候存在随机打乱）
> 
> 如果只是指定`--dataset <path1> <path2>` 则不会打乱

如果训练多个 epoch，多个数据集采样的设置下，每个 epoch 都会随机重新采样吗：
`--dataset {dataset_name}#20000 {dataset_id}:{subset1}/{subset2}#20000 {dataset_path}#10000`

**Comment by Jintao-Huang** [comment]
> > > > get_dataset使用数据集拼接策略
> > > > 数据集的随机打乱会在hf_trainer中进行
> > > 
> > > 
> > > 感谢解答，那么可以手动设置数据集随机打乱或者不打乱吗，如果可以是哪个参数呢？ https://github.com/modelscope/swift/blob/main/docs/source/LLM/%E5%91%BD%E4%BB%A4%E8%A1%8C%E5%8F%82%E6%95%B0.md
> > 
> > 
> > get_dataset没有参数控制是否打乱. （切分训练集和测试集，以及数据集采样的时候存在随机打乱）
> > 如果只是指定`--dataset <path1> <path2>` 则不会打乱
> 
> 如果训练多个 epoch，多个数据集采样的设置下，每个 epoch 都会随机重新采样吗： `--dataset {dataset_name}#20000 {dataset_id}:{subset1}/{subset2}#20000 {dataset_path}#10000`

训练时每个epoch会对数据集进行随机采样. 参考torch.utils.data中的RandomSampler（传入dataloader）

**Comment by fly-dragon211** [comment]
> > > > > get_dataset使用数据集拼接策略
> > > > > 数据集的随机打乱会在hf_trainer中进行
> > > > 
> > > > 
> > > > 感谢解答，那么可以手动设置数据集随机打乱或者不打乱吗，如果可以是哪个参数呢？ https://github.com/modelscope/swift/blob/main/docs/source/LLM/%E5%91%BD%E4%BB%A4%E8%A1%8C%E5%8F%82%E6%95%B0.md
> > > 
> > > 
> > > get_dataset没有参数控制是否打乱. （切分训练集和测试集，以及数据集采样的时候存在随机打乱）
> > > 如果只是指定`--dataset <path1> <path2>` 则不会打乱
> > 
> > 
> > 如果训练多个 epoch，多个数据集采样的设置下，每个 epoch 都会随机重新采样吗： `--dataset {dataset_name}#20000 {dataset_id}:{subset1}/{subset2}#20000 {dataset_path}#10000`
> 
> 训练时每个epoch会对数据集进行随机采样. 参考torch.utils.data中的RandomSampler（传入dataloader）

哦哦这样子，所以我只需要设置多个 epoch 和 多个数据集采样，就可以每个 epoch 都重新各个数据集采样，达到混合多个数据集训练的目的？

**Comment by Jintao-Huang** [comment]
是的

**Comment by fly-dragon211** [comment]
> 是的

我发现并不是这样子的，按照您说的方法尝试，每个 epoch 好像并不会重新选择数据，还是之前的数据，导致 auc 后来变成 1：
```
{'loss': 1.236e-05, 'acc': 1.0, 'grad_norm': 0.00013958, 'learning_rate': 9.905e-05, 'memory(GiB)': 23.84, 'train_speed(iter/s)': 0.02646, 'epoch': 133.12, 'global_step': 355}
{'loss': 1.157e-05, 'acc': 1.0, 'grad_norm': 0.00016218, 'learning_rate': 9.896e-05, 'memory(GiB)': 23.84, 'train_speed(iter/s)': 0.026474, 'epoch': 135.0, 'global_step': 360}
Train:   6%|███████▎                                                                         Train:   6%|██▍                                      | 361/6000 [3:47:08<59:42:30, 38.12s/it]{'loss': 1.136e-05, 'acc': 1.0, 'grad_norm': 0.00016897, 'learning_rate': 9.888e-05, 'memory(GiB)': 23.84, 'train_speed(iter/s)': 0.026457, 'epoch': 136.88, 'global_step': 365}
```

我使用类似下面的命令
```bash
swift sft --model_type internlm-xcomposer2-7b-chat \
  --model_id_or_path ${base_dir}/internlm-xcomposer2-7b/ \
  --dataset ${dataset_pre}/20240712_train_truncation-4096-image-8.jsonl#16 \
  ${dataset_pre}/20240715_train_truncation-3000-image-8-to_understand_and_tag.jsonl#8 \
  ${dataset_pre}/20240715_train_truncation-3000-image-8-to_describe.jsonl#8 \
  ${dataset_pre}/20240715_train_truncation-3000-image-8-to_understand.jsonl#8 \
  ${dataset_pre}/20240715_train_truncation-3000-image-8-to_tag.jsonl#8 \
```

**Comment by goodstudent9** [comment]
> > 是的
> 
> 我发现并不是这样子的，按照您说的方法尝试，每个 epoch 好像并不会重新选择数据，还是之前的数据，导致 auc 后来变成 1：
> 
> ```
> {'loss': 1.236e-05, 'acc': 1.0, 'grad_norm': 0.00013958, 'learning_rate': 9.905e-05, 'memory(GiB)': 23.84, 'train_speed(iter/s)': 0.02646, 'epoch': 133.12, 'global_step': 355}
> {'loss': 1.157e-05, 'acc': 1.0, 'grad_norm': 0.00016218, 'learning_rate': 9.896e-05, 'memory(GiB)': 23.84, 'train_speed(iter/s)': 0.026474, 'epoch': 135.0, 'global_step': 360}
> Train:   6%|███████▎                                                                         Train:   6%|██▍                                      | 361/6000 [3:47:08<59:42:30, 38.12s/it]{'loss': 1.136e-05, 'acc': 1.0, 'grad_norm': 0.00016897, 'learning_rate': 9.888e-05, 'memory(GiB)': 23.84, 'train_speed(iter/s)': 0.026457, 'epoch': 136.88, 'global_step': 365}
> ```
> 
> 我使用类似下面的命令
> 
> ```shell
> swift sft --model_type internlm-xcomposer2-7b-chat \
>   --model_id_or_path ${base_dir}/internlm-xcomposer2-7b/ \
>   --dataset ${dataset_pre}/20240712_train_truncation-4096-image-8.jsonl#16 \
>   ${dataset_pre}/20240715_train_truncation-3000-image-8-to_understand_and_tag.jsonl#8 \
>   ${dataset_pre}/20240715_train_truncation-3000-image-8-to_describe.jsonl#8 \
>   ${dataset_pre}/20240715_train_truncation-3000-image-8-to_understand.jsonl#8 \
>   ${dataset_pre}/20240715_train_truncation-3000-image-8-to_tag.jsonl#8 \
> ```

这个问题解决了吗？现在是每个epoch重新选择数据吗？
