### ISSUE TITLE
InternVL自定义数据集微调支持多轮对话吗？

### ISSUE THREAD

**Issue by 1SingleFeng** [modelscope/swift#1392]
请问，InternVL自定义微调数据集支持多轮对话？我看官方文档上说不支持多轮对话，但是InternVL官方仓库（ https://github.com/OpenGVLab/InternVL ）是支持多轮对话的微调数据格式。

**Comment by 1SingleFeng** [comment]
并且我尝试了一下MiniCPM-V-2.5模型微调的多轮对话数据集格式 ，发现也是能启动InternVL的训练的
{"query": "EEEEE", "response": "FFFFF", "history": [["AAAAA", "BBBBB"], ["CCCCC", "DDDDD"]], "images": ["image_path"]}

**Comment by hjh0119** [comment]
支持的, 文档已修正 https://github.com/modelscope/swift/pull/1394

**Comment by 1SingleFeng** [comment]
> 支持的, 文档已修正 #1394

好的，非常感谢~
