### ISSUE TITLE
glm-4v-9b微调后如何转换成modelscope格式的模型文件

### ISSUE THREAD

**Issue by danxuan2022** [modelscope/swift#1393]
请问下是通过这种方式转换吗？

from peft import AutoPeftModelForCausalLM
model = AutoPeftModelForCausalLM.from_pretrained(
pretrained_model_name_or_path="/home/admin/ai-testing-platform/data/dx/swift/glm4v_output/glm4v-9b-chat/v0-20240715-152012/checkpoint-50",
device_map="auto",
trust_remote_code=True
).eval()
merged_model = model.merge_and_unload()
new_model_directory="./glm4v_model"
merged_model.save_pretrained(new_model_directory, max_shard_size="2048MB", safe_serialization=True)

**Comment by Jintao-Huang** [comment]
merge-lora


https://github.com/modelscope/swift/blob/main/docs/source/LLM/LLM%E9%87%8F%E5%8C%96%E6%96%87%E6%A1%A3.md#%E5%BE%AE%E8%B0%83%E5%90%8E%E6%A8%A1%E5%9E%8B
