### ISSUE TITLE
huangjintao/llava-v1.6-mistral-7b-hf does not exist!

### ISSUE THREAD

**Issue by danxuan2022** [modelscope/swift#1396]
**Describe the bug**
What the bug is, and how to reproduce, better with screenshots(描述bug以及复现过程，最好有截图)

requests.exceptions.HTTPError: The request model: huangjintao/llava-v1.6-mistral-7b-hf does not exist!
里面几乎所有模型都找不到 https://github.com/modelscope/swift/blob/main/docs/source/Multi-Modal/llava%E6%9C%80%E4%BD%B3%E5%AE%9E%E8%B7%B5.md

**Your hardware and system info**
Write your system info like CUDA version/system/GPU/torch version here(在这里给出硬件信息和系统信息，如CUDA版本，系统，GPU型号和torch版本等)

**Additional context**
Add any other context about the problem here(在这里补充其他信息)

**Comment by Jintao-Huang** [comment]
好的 稍等修复一下

移动到这里啦
https://modelscope.cn/organization/swift

**Comment by danxuan2022** [comment]
> 好的 稍等修复一下
> 
> 移动到这里啦 https://modelscope.cn/organization/swift

这个地方可以下载，但是我通过swift微调的时候需要指定model_type，通过model_type下载模型下载不下来
CUDA_VISIBLE_DEVICES=0 swift sft     --model_type llava-v1.6-vicuna-7b-hf   --dataset glm4v_data.jsonl     --num_train_epochs 50  --output_dir ./llava_outpu

**Comment by danxuan2022** [comment]
> 好的 稍等修复一下
> 
> 移动到这里啦 https://modelscope.cn/organization/swift

![image](https://github.com/user-attachments/assets/3c9d6b2b-d317-4153-bd8f-9aa1cfaa2843)
CUDA_VISIBLE_DEVICES=0 swift sft --model_type llava-v1.6-vicuna-7b-hf --dataset glm4v_data.jsonl --num_train_epochs 50 --output_dir ./llava_output

使用swift微调报错llava-v1.6-vicuna-7b-hf我看是在model_type里面的，是需要重新编译swift吗？
