### ISSUE TITLE
Qwen-Audio训练之后，输出结果不显示空格

### ISSUE THREAD

**Issue by Moht153** [modelscope/swift#1409]
我冻结了LLM的参数，只训练了前面whisper模型的编码器部分。现在的问题是，使用训练之后的模型，输出的结果内容是对的，但是单词语单词之间没有空格了。

![image](https://github.com/user-attachments/assets/54f66a39-6472-4cb2-af28-4f40757a3578)

之前还碰到了一个问题，加载训练后的tokenizer时的，显示没有self.AUDIO_ST这个属性。现在已经将self.AUDIO_ST转变成类属性解决了
![image](https://github.com/user-attachments/assets/2c0eca9e-90a7-40c6-8c9c-796ff0a57674)
请大佬们帮忙解决一下没有空格的问题，感谢！

**Comment by Jintao-Huang** [comment]
使用swift infer也不正常嘛

**Comment by Moht153** [comment]
是的，我试了一下swift infer，指定了--load_dataset_config true, 从输出的结果来看，这个验证数据集的label似乎也是将空格处理掉的。

![image](https://github.com/user-attachments/assets/d079b94a-a56f-4394-abf4-f2f5499bed76)
是不是分词器有问题？

**Comment by Moht153** [comment]
是的，我试了一下swift infer，指定了--load_dataset_config true, 从输出的结果来看，这个验证数据集的label似乎也是将空格处理掉的。

这个是输出的结果：
![image](https://github.com/user-attachments/assets/d079b94a-a56f-4394-abf4-f2f5499bed76)
是不是分词器有问题？

**Comment by Moht153** [comment]
问题找到了，是数据预处理函数把空格删了导致的。感谢！
