### ISSUE TITLE
InternVL1.5能否支持自定义纯文本数据集微调

### ISSUE THREAD

**Issue by shikimoon** [modelscope/swift#1415]
现在自定义数据集必须传入image。否则报错
![微信截图_20240716194450](https://github.com/user-attachments/assets/d8622352-27d6-4734-904e-29dd82fe5b6d)

**Comment by hjh0119** [comment]
马上支持了 https://github.com/modelscope/swift/pull/1426

**Comment by hjh0119** [comment]
done
