### ISSUE TITLE
InternVL2 customized fine-tuning for video-to-text

### ISSUE THREAD

**Issue by BillChan226** [modelscope/swift#1418]
Hi! Great works! I'm wondering if swift can support fine-tuning for InternVL2 on customized video-to-text dataset soon? Thanks!

**Comment by hjh0119** [comment]
you can specify the abs video path by key `videos` as follows
```json
{"query": "Describe this video in detail. Don't repeat", "response": "xxxxxxxxx", "history": [], "videos": ["video_path"]}
```

**Comment by BillChan226** [comment]
Hi Thanks for the reply! It works! However I'm wondering how to set the number of frames sampled for each video when ft internvlw?

**Comment by hjh0119** [comment]
modify  `num_segments` in https://github.com/modelscope/swift/blob/main/swift/llm/utils/vision_utils.py#L116
