### ISSUE TITLE
bash ./scripts/qwen_7b/lora_ddp_ds/sft.sh 报错

### ISSUE THREAD

**Issue by sxsxsx** [modelscope/swift#142]
你好，我运行 bash ./scripts/qwen_7b/lora_ddp_ds/sft.sh  报错如下
ile "/home/admin/.conda/envs/qwen/lib/python3.8/site-packages/transformers/trainer.py", line 1668, in _inner_training_loop
gradient_checkpointing_enable
self._set_gradient_checkpointing(enable=True, gradient_checkpointing_func=gradient_checkpointing_func)
TypeError: _set_gradient_checkpointing() got an unexpected keyword argument 'enable'

**Comment by sxsxsx** [comment]
gradient_checkpointing_enable
self._set_gradient_checkpointing(enable=True, gradient_checkpointing_func=gradient_checkpointing_func)
TypeError: _set_gradient_checkpointing() got an unexpected keyword argument 'enable'

**Comment by Jintao-Huang** [comment]
这个问题 你可以看下 https://github.com/huggingface/transformers/issues/27300
你先尝试回退transformers版本到4.33或者4.34

**Comment by Jintao-Huang** [comment]
该问题已经修复了, 您可以拉取最新的代码, 再跑一下😊
