### ISSUE TITLE
微调GLM4v报错（在今天更新github 仓库之前还没有报错）

### ISSUE THREAD

**Issue by ZhiyuYUE** [modelscope/swift#1427]
**Describe the bug**
[rank0]: Traceback (most recent call last):
[rank0]:   File "/mnt/code/yzy/swift/swift/cli/sft.py", line 5, in <module>
[rank0]:     sft_main()
[rank0]:   File "/mnt/code/yzy/swift/swift/utils/run_utils.py", line 27, in x_main
[rank0]:     result = llm_x(args, **kwargs)
[rank0]:   File "/mnt/code/yzy/swift/swift/llm/sft.py", line 210, in llm_sft
[rank0]:     template: Template = get_template(
[rank0]:   File "/mnt/code/yzy/swift/swift/llm/utils/template.py", line 2520, in get_template
[rank0]:     template._init_template(tokenizer, default_system, max_length, truncation_strategy, model=model, **kwargs)
[rank0]:   File "/mnt/code/yzy/swift/swift/llm/utils/template.py", line 1040, in _init_template
[rank0]:     token_list = tokenizer.encode('')
[rank0]:   File "/root/miniforge-pypy3/envs/swift/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 2654, in encode
[rank0]:     encoded_inputs = self.encode_plus(
[rank0]:   File "/root/miniforge-pypy3/envs/swift/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 3062, in encode_plus
[rank0]:     return self._encode_plus(
[rank0]:   File "/root/miniforge-pypy3/envs/swift/lib/python3.10/site-packages/transformers/tokenization_utils.py", line 722, in _encode_plus
[rank0]:     return self.prepare_for_model(
[rank0]:   File "/root/miniforge-pypy3/envs/swift/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 3541, in prepare_for_model
[rank0]:     encoded_inputs = self.pad(
[rank0]:   File "/root/miniforge-pypy3/envs/swift/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 3346, in pad
[rank0]:     encoded_inputs = self._pad(
[rank0]:   File "/root/.cache/huggingface/modules/transformers_modules/glm4v/tokenization_chatglm.py", line 332, in _pad
[rank0]:     assert self.padding_side == "left"
[rank0]: AssertionError
[rank2]: Traceback (most recent call last):
[rank2]:   File "/mnt/code/yzy/swift/swift/cli/sft.py", line 5, in <module>
[rank2]:     sft_main()
[rank2]:   File "/mnt/code/yzy/swift/swift/utils/run_utils.py", line 27, in x_main
[rank2]:     result = llm_x(args, **kwargs)
[rank2]:   File "/mnt/code/yzy/swift/swift/llm/sft.py", line 210, in llm_sft
[rank2]:     template: Template = get_template(
[rank2]:   File "/mnt/code/yzy/swift/swift/llm/utils/template.py", line 2520, in get_template
[rank2]:     template._init_template(tokenizer, default_system, max_length, truncation_strategy, model=model, **kwargs)
[rank2]:   File "/mnt/code/yzy/swift/swift/llm/utils/template.py", line 1040, in _init_template
[rank2]:     token_list = tokenizer.encode('')
[rank2]:   File "/root/miniforge-pypy3/envs/swift/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 2654, in encode
[rank2]:     encoded_inputs = self.encode_plus(
[rank2]:   File "/root/miniforge-pypy3/envs/swift/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 3062, in encode_plus
[rank2]:     return self._encode_plus(
[rank2]:   File "/root/miniforge-pypy3/envs/swift/lib/python3.10/site-packages/transformers/tokenization_utils.py", line 722, in _encode_plus
[rank2]:     return self.prepare_for_model(
[rank2]:   File "/root/miniforge-pypy3/envs/swift/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 3541, in prepare_for_model
[rank2]:     encoded_inputs = self.pad(
[rank2]:   File "/root/miniforge-pypy3/envs/swift/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 3346, in pad
[rank2]:     encoded_inputs = self._pad(
[rank2]:   File "/root/.cache/huggingface/modules/transformers_modules/glm4v/tokenization_chatglm.py", line 332, in _pad
[rank2]:     assert self.padding_side == "left"
[rank2]: AssertionError

**Your hardware and system info**
Write your system info like CUDA version/system/GPU/torch version here(在这里给出硬件信息和系统信息，如CUDA版本，系统，GPU型号和torch版本等)

**Additional context**
Add any other context about the problem here(在这里补充其他信息)

昨天微调一切正常，但是今天在更新github仓库之后就出现了上述报错。没有查出来原因

**Comment by Jintao-Huang** [comment]
重新拉取一下main分支呗

**Comment by ZhiyuYUE** [comment]
我就是早上拉了main分支之后报错了哈哈，我明天再试一下

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年07月17日 18:11 |
| 收件人 | modelscope/swift ***@***.***> |
| 抄送人 | Zhiyu ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [modelscope/swift] 微调GLM4v报错（在今天更新github 仓库之前还没有报错） (Issue #1427) |

重新拉取一下main分支呗

**Comment by ZhiyuYUE** [comment]
> 重新拉取一下main分支呗

重新拉取之后可以啦
