### ISSUE TITLE
现在支持vllm的多LoRA部署吗？

### ISSUE THREAD

**Issue by jidechao** [modelscope/swift#1428]
**Describe the feature**
Please describe the feature requested here(现在支持vllm的多LoRA部署吗？)

**Paste any useful information**
Paste any useful information, including papers, github links, etc.(请在这里描述其他有用的信息，比如相关的论文地址，github链接等)

**Additional context**
Add any other context or information here(其他信息可以写在这里)

**Comment by tastelikefeet** [comment]
支持的，参考：https://swift.readthedocs.io/zh-cn/latest/LLM/%E5%91%BD%E4%BB%A4%E8%A1%8C%E5%8F%82%E6%95%B0.html#deploy-%E5%8F%82%E6%95%B0

**Comment by zhangfan-algo** [comment]
@tastelikefeet 支持10个lora权重的 多lora推理服务吗
