### ISSUE TITLE
InternVL2支持多图对话？

### ISSUE THREAD

**Issue by voyageofsean** [modelscope/swift#1431]
**Describe the feature**
InternVL2的官方示例中，显示支持多图多轮对话，但InternVL最佳实践文档中显示“支持多轮对话, 但总的轮次对话只能包含一张图片”。后续可否考虑支持多图输入？

**Paste any useful information**
无

**Additional context**
无

**Comment by hjh0119** [comment]
work in process https://github.com/modelscope/swift/pull/1426

**Comment by hjh0119** [comment]
done 参考最佳实践文档
