### ISSUE TITLE
new bug of glm-4v infer 

### ISSUE THREAD

**Issue by Starfulllll** [modelscope/swift#1432]
**Describe the bug**
What the bug is, and how to reproduce, better with screenshots(描述bug以及复现过程，最好有截图)
按照https://github.com/THUDM/GLM-4/blob/main/basic_demo/requirements.txt 的说明，更新glm4v依赖后，使用swift的推理示例出现如下错误：ImportError: transformers<4.42 is required for a normal functioning of this module, but found transformers==4.42.4

命令：CUDA_VISIBLE_DEVICES=7 swift infer --model_type glm4v-9b-chat --model_id_or_path /data/modelscope/hub/ZhipuAI/glm-4v-9b

**Your hardware and system info**
Write your system info like CUDA version/system/GPU/torch version here(在这里给出硬件信息和系统信息，如CUDA版本，系统，GPU型号和torch版本等)
CUDA 12.1，80GB A100

**Additional context**
Add any other context about the problem here(在这里补充其他信息)
附GLM-4v-9b最新依赖信息
torch>=2.3.0
torchvision>=0.18.0
transformers==4.42.4
huggingface-hub>=0.23.1
sentencepiece>=0.2.0
pydantic>=2.8.2
timm>=1.0.7
tiktoken>=0.7.0
accelerate>=0.32.1
sentence_transformers>=3.0.1
gradio>=4.38.1 # web demo
openai>=1.35.0 # openai demo
einops>=0.8.0
sse-starlette>=2.1.2
bitsandbytes>=0.43.1 # INT4 Loading

vllm>=0.5.2
flash-attn>=2.5.9 # using with flash-attention 2
peft>=0.11.1

感谢回复！

**Comment by Starfulllll** [comment]
微调示例也会出现同样的错误提示：
命令：
CUDA_VISIBLE_DEVICES=7 swift sft --model_type glm4v-9b-chat --dataset coco-en-2-mini --model_id_or_path /data/modelscope/hub/ZhipuAI/glm-4v-9b

辛苦大佬维护了~

**Comment by Jintao-Huang** [comment]
拉一下最新的代码

**Comment by Starfulllll** [comment]
已解决，非常感谢！
