### ISSUE TITLE
image_process函数在源码中的位置

### ISSUE THREAD

**Issue by dszpr** [modelscope/swift#1437]
非常感谢作者的精彩工作！

请问如果使用自定义数据集进行InternVL2的微调，格式为
{"query": "55555", "response": "66666", "images": ["image_path"]}

InternVL2中采用了dynamic resolution，需要先对图片进行切分再token化再拼接，不知道swift中是否集成了这个功能？我在源码中没有找到自定义的多模态数据集图片处理相关的函数，请问Swift源码中对图片处理的函数定义在哪个位置呢？

期待回复！

**Comment by tastelikefeet** [comment]
该源码位置在：https://github.com/modelscope/swift/blob/main/swift/llm/utils/template.py#L1447
-----------
Please check the source code of:https://github.com/modelscope/swift/blob/main/swift/llm/utils/template.py#L1447

**Comment by dszpr** [comment]
十分感谢！
