### ISSUE TITLE
GLM4V模型的官方模型推理有问题

### ISSUE THREAD

**Issue by hyyuan123** [modelscope/swift#1442]
**Describe the bug**
What the bug is, and how to reproduce, better with screenshots(描述bug以及复现过程，最好有截图)
GLM4V模型的官方模型推理有问题

![捕获](https://github.com/user-attachments/assets/07be5729-a099-4c4a-b347-08ae295a4858)

**Comment by tastelikefeet** [comment]
用main分支的swift，并升级transformers到最新版
