### ISSUE TITLE
synthetic_text_to_sql_preprocesser use wrong dataset column for final answer sql

### ISSUE THREAD

**Issue by lordk911** [modelscope/swift#1443]
**Describe the bug**
![image](https://github.com/user-attachments/assets/299093fd-b7ae-4e92-b08e-02a6345f02d0)

https://github.com/modelscope/swift/blob/70b58b4155e956101b4f94cf344378e47f07fadf/swift/llm/utils/dataset.py#L1810-L1811

**Comment by tastelikefeet** [comment]
Thanks! This bug is fixed by #1448
