### ISSUE TITLE
qwen2 回归任务 'float' object is not iterable 报错

### ISSUE THREAD

**Issue by FredHuang16** [modelscope/swift#1445]
qwen2 lora sft时报错：swift-main/swift/llm/utils/template.py", line 524, in _encode_context_list
input_ids += token_list
TypeError: 'float' object is not iterable

任务类型：数值回归任务

sft数据集： query是中文文本，response是数值

**Comment by tastelikefeet** [comment]
回归任务可能不太支持啊，因为回归的loss什么的都不太一样

**Comment by Jintao-Huang** [comment]
这个问题 应该在main分支修复了

是使用自定义数据集 csv的问题嘛
