### ISSUE TITLE
2.2.3版本有自动在所有字符前加空格BUG

### ISSUE THREAD

**Issue by Value99** [modelscope/swift#1462]
**Describe the bug**
What the bug is, and how to reproduce, better with screenshots(描述bug以及复现过程，最好有截图)
训练的时候只要使用2.2.3版本就会出现
![890F1F8044A82DA8559EA191F59F71CE](https://github.com/user-attachments/assets/890d3d59-00db-47ae-9409-f3b335d0e214)
主要表现为，每段文字开头自动添加空格，标点符号后自动添加空格。

**Your hardware and system info**
Write your system info like CUDA version/system/GPU/torch version here(在这里给出硬件信息和系统信息，如CUDA版本，系统，GPU型号和torch版本等)
transformers-4.42.4（也可能是它的问题）
CUDA12.1

**Additional context**
Add any other context about the problem here(在这里补充其他信息)
退回2.2.1问题消失。

**Comment by Jintao-Huang** [comment]
可以给一下 复现的代码吗
哪个模型呢

**Comment by Jintao-Huang** [comment]
是在训练的时候 还是推理的时候

**Comment by Value99** [comment]
> 可以给一下 复现的代码吗 哪个模型呢

训练的代码如下：
CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 \
swift sft \
    --model_type yi-1_5-34b-chat-16k \
    --model_id_or_path /media/fangxin/Data/Yi-1.5-34B-Chat-16K \
    --template_type chatml \
    --dataset /home/fangxin/trail/20240721.json /home/fangxin/trail/38kxs.json  \
    --sft_type lora \
    --tuner_backend peft \
    --dtype AUTO \
    --max_length 3000 \
    --check_dataset_strategy warning \
    --lora_rank 256 \
    --num_train_epochs 1 \
    --lora_alpha 768 \
    --lora_dropout_p 0.12 \
    --lora_target_modules ALL \
    --gradient_checkpointing true \
    --output_dir /media/fangxin/Data/output \
    --batch_size 1 \
    --gradient_accumulation_steps 4 \
    --weight_decay 0.1 \
    --neftune_noise_alpha 10 \
    --save_total_limit 50 \
    --learning_rate 2e-5 \
    --truncation_strategy delete \
    --use_flash_attn false \
    --eval_steps 1000 \
    --save_steps 50
    
问题出现在训练的时候。推理的时候也有这个问题但不确定是不是在训练那一步已经出错了导致模型有问题。

**Comment by Jintao-Huang** [comment]
推理使用的是 swift infer还是 apply_chat_template

**Comment by Value99** [comment]
> 推理使用的是 swift infer还是 apply_chat_template

推理使用的是swift infer。但是问题是在训练阶段发现的。

训练log如下
[INFO:swift] Using num_proc: 1
100%|████████████████████████████████████| 12999/12999 [00:25<00:00, 503.70it/s]
100%|████████████████████████████████████████| 130/130 [00:00<00:00, 504.72it/s]
[INFO:swift] [INPUT_IDS] [6, 1328, 144, 51943, 4748, 13992, 44307, 7, 144, 6, 2942, 144, 51943, 98, 98, 98, 7, 144, 6, 14135, 144, 59568, 62573, 104, 24840, 1554, 59646, 101, 59568, 13961, 6690, 1554, 1650, 17297, 104, 7, 144, 6, 2942, 144, 59568, 1327, 7, 144, 6, 14135, 144, 59568, 15340, 59706, 101, 59568, 11381, 59725, 3027, 28800, 8153, 104, 7, 144, 6, 2942, 144, 59568, 1327, 7, 144, 6, 14135, 144, 59568, 59630, 28800, 41280, 10086, 59683, 59828, 5790, 12674, 60329, 101, 59568, 59924, 61134, 44861, 101, 59568, 13419, 28800, 4255, 40160, 60972, 14973, 60392, 102, 7, 144, 6, 2942, 144, 59568, 2410, 7, 144, 6, 14135, 144, 59568, 25902, 62457, 62177, 534, 455, 453, 101, 14629, 1977, 7021, 12568, 9807, 59708, 36077, 61332, 103, 7, 144, 6, 2942, 144, 59568, 57723, 7, 144, 6, 14135, 144, 98, 98, 98, 7, 144, 6, 2942, 144, 51943, 59683, 98, 98, 98, 59568, 1554, 7112, 7, 144, 6, 14135, 144, 59568, 20026, 59962, 62457, 62177, 2861, 59706, 59630, 61332, 102, 7, 144, 6, 2942, 144, 59568, 24058, 62457, 62177, 59725, 7, 144, 6, 14135, 144, 51943, 7653, 59725, 59544, 59674, 61724, 60117, 61724, 40638, 63227, 59646, 101, 59568, 47343, 1327, 62457, 62177, 101, 59568, 63056, 102, 7, 144, 6, 2942, 144, 59568, 13961, 6865, 3022, 59599, 19572, 58111, 7, 144, 6, 14135, 144, 24840, 103, 59568, 59630, 103, 38248, 103, 144, 144, 59568, 62457, 62177, 12568, 59711, 43379, 101, 59568, 2168, 47095, 59892, 12568, 61546, 61431, 102, 59568, 8536, 59600, 45097, 61332, 101, 59568, 1787, 27342, 58111, 103, 7]
[INFO:swift] [INPUT] <|im_start|> system
 你是一个人工智能助手<|im_end|>
<|im_start|> user
 你...<|im_end|>
<|im_start|> assistant
 嗯？ 我什么我， 你是遇到什么问题了吗？<|im_end|>
<|im_start|> user
 没有<|im_end|>
<|im_start|> assistant
 那就好， 看起来你比较无聊是不是？<|im_end|>
<|im_start|> user
 没有<|im_end|>
<|im_start|> assistant
 不无聊怎么会在这里发无意义的内容呢， 别骗我了， 既然无聊的话就来聊聊天吧。<|im_end|>

可以看到以上每个标点符号后面都会跟随一个空格。

**Comment by Jintao-Huang** [comment]
可以复现, 我看看

**Comment by Jintao-Huang** [comment]
该现象只会在yi1.5中会出现. 将tokenizer的参数 use_fast=False可以解决

**Comment by Jintao-Huang** [comment]
fixed, 拉取main分支
