### ISSUE TITLE
在使用llama7b-chat qlora的时候报错

### ISSUE THREAD

**Issue by zhangyuansen** [modelscope/swift#147]
<img width="801" alt="截屏2023-11-13 17 19 09" src="https://github.com/modelscope/swift/assets/44854079/019e9465-3010-47ba-a5cf-ebd53325ad75">
在运行过程中报了上面这个错误，这是为什么呢？
看起来好像是因为父类_Linear4bit定义的时候里面最多传入六个参数
<img width="854" alt="image" src="https://github.com/modelscope/swift/assets/44854079/47d3cb52-36e3-4bd6-ac45-f7373649ea08">
但是在子类继承的时候传入了七个参数
<img width="621" alt="image" src="https://github.com/modelscope/swift/assets/44854079/3e1b3d19-fcb4-4c60-9910-3f16473e5f98">
也就是说把in_features和out_features传入到base_model这一个参数里了，请问这是什么原因呢？
这样的操作在Python里是允许的吗，我使用的机器是3090，python版本是3.10.9

**Comment by Jintao-Huang** [comment]
你好，已经修复了这个问题了，请拉取一下最新的代码😊

**Comment by zhangyuansen** [comment]
> 你好，已经修复了这个问题了，请拉取一下最新的代码😊

好的谢谢🙏
