### ISSUE TITLE
swift/examples/pytorch/llm /README_CN.md   install .时候报冲突,好痛苦

### ISSUE THREAD

**Issue by chuanzhubin** [modelscope/swift#149]
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
torchvision 0.12.0+cu113 requires torch==1.11.0, but you have torch 2.1.0 which is incompatible.
Successfully installed ms-swift-1.2.0 torch-2.1.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
WARNING: There was an error checking the latest version of pip.

此时如果把torch版本降到1.11.0也不行, 因为:
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
peft 0.6.2 requires torch>=1.13.0, but you have torch 1.11.0 which is incompatible.

**Comment by chuanzhubin** [comment]
有辅导群吗? 求加swift群

**Comment by Jintao-Huang** [comment]
哈咯！readme的最后面有微信群哦. 你可以根据 pytorch的官方文档安装 最新版的pytorch. https://pytorch.org/get-started/locally/. 😊

**Comment by chuanzhubin** [comment]
早上在群里大佬帮助下, 终于跑通第一个sft.  遇到了以下问题, 供后来者借鉴:
1. V100 GPU和bitsandbytes有冲突. 暂时解决不了, 把它卸载掉,然后跑lora, qlora先搞不了.   pip uninstall bitsandbytes
2. V100等较老的GPU, 你需要设置--dtype fp16, 因为其不支持bf16.
