### ISSUE TITLE
CodeQwen1.5-7B-Chat微调时显示模型没有注册

### ISSUE THREAD

**Issue by z09-op** [modelscope/swift#1496]
微调CodeQwen1.5-7B-Chat时，sft.sh脚本中，--model_type=codeqwen1half-7b-chat，--model_id_or_path=存放模型的路径，sft_type=full/lora都试过，但都报错：model_type: 'codeqwen1half-7b-chat' is not registered.

**Comment by Jintao-Huang** [comment]
升级一下ms-swift呢
