### ISSUE TITLE
[BUG] response里需要生成空格's时，text会错误的输出

### ISSUE THREAD

**Issue by zhongtao93** [modelscope/swift#1537]
当response中有 's时，输出会丢失掉s,目前测试出相同的情况还包括字母m和v，注意还必须在'前面有一个空格时才会丢失
环境：lmdeploy==0.5.2.post1 (0.5.1和0.5.2也测试过，有相同的问题）, transformers==4.37.2
模型：internvl2-2b (其他未测试）
推理：
random_seed=42
backend_config = PytorchEngineConfig(session_len=8192)
pipe = pipeline(model_path=model_path, model_name=model_name, backend_config=backend_config)

输入query："这张图里面是否有人，有则返回{ 's'}，否则返回{ 'm'} "
结果：Response(text="{ '' }", generate_token_len=5, input_token_len=1863, session_id=0, finish_reason='stop', token_ids=[339, 495, 269, 259, 466], logprobs=None)

但如果将query改为没有空格："这张图里面是否有人，有则返回{'s'}，否则返回{'m'} "
结果：Response(text="{'s'}", generate_token_len=3, input_token_len=1861, session_id=0, finish_reason='stop', token_ids=[339, 725, 8407], logprobs=None)
{'error_code': 0, 'error_msg': '', 'res': "{'s'}"}

**Comment by zhongtao93** [comment]
和这位同学的情况是一样的，但那个issue close了，所以重新开了一个
https://github.com/InternLM/lmdeploy/issues/1951

**Comment by Jintao-Huang** [comment]
swift的也有这个问题嘛

**Comment by zhongtao93** [comment]
抱歉，发错issue了，是lmdeploy的bug
