### ISSUE TITLE
AttributeError: 'MiniCPMV' object has no attribute 'get_slice_image_placeholder'

### ISSUE THREAD

**Issue by qty0228** [modelscope/swift#1563]
It was running normally yesterday, but it keeps reporting this error today

**Comment by Jintao-Huang** [comment]
https://github.com/modelscope/swift/pull/1562

**Comment by devilleet** [comment]
@Jintao-Huang the fix seems to work for minicpm-v-2_5 only, currently same bug occurs for minicpm-v-4 also
