### ISSUE TITLE
The checkpoint is not saved

### ISSUE THREAD

**Issue by qty0228** [modelscope/swift#1576]
After updating Swift yesterday and fine-tuning the model again, the training process was normal, but the checkpoint was not saved.

**Comment by tastelikefeet** [comment]
Could you check if the training is over? and your --save_steps --eval_steps settings.
Meanwhile, if the save_steps reaches, there will be "Save checkpoint ..." in your log file.

**Comment by qty0228** [comment]
> Could you check if the training is over? and your --save_steps --eval_steps settings. Meanwhile, if the save_steps reaches, there will be "Save checkpoint ..." in your log file.

swift sft --model_type minicpm-v-v2_5-chat \
          --dataset /home/lyn/qty/scene_identity/datasets/st_traindata_3scene_shuffled.jsonl \
          --lora_target_modules ALL \
          --num_train_epochs 1 \
          --save_steps 10 \
          --evaluation_strategy no

We have finished training, and all log outputs are normal, except there are no checkpoints.

**Comment by qty0228** [comment]
> Could you check if the training is over? and your --save_steps --eval_steps settings. Meanwhile, if the save_steps reaches, there will be "Save checkpoint ..." in your log file.

Thank you, I have already resolved this issue. The default save_strategy was set to 'no', and I have changed it to 'steps'.
