### ISSUE TITLE
为什么增大显卡数量无法加快训练速度？

### ISSUE THREAD

**Issue by jhrsya** [modelscope/swift#1605]
qwen2全量微调
相关参数：
```
NPROC_PER_NODE=4  \
swift sft \
    --model_type qwen2-7b-instruct \
    --sft_type full \
    --dataset data.json \
    --model_id_or_path Qwen/Qwen2-7B-Instruct \
    --batch_size 2 \
    --use_flash_attn true \
    --eval_steps 2000
```
多机多卡，4台机器，每台机器8张显卡。我理解的global_batch_size = 4 * 4 * 2 = 32，使用了模型并行。

现在用8台机器，global_batch_size应该等于64，可是我看了运行时间，时间并没有节省，请问可能的原因是什么呢？

**Comment by tastelikefeet** [comment]
看下gradient_accumulation_steps设置是否是固定值

**Comment by jhrsya** [comment]
> 看下gradient_accumulation_steps设置是否是固定值

感谢提醒

**Comment by luyao-cv** [comment]
> 看下gradient_accumulation_steps设置是否是固定值

请问这个要怎么改，手动修改吗
