### ISSUE TITLE
运行!bash scripts/qwen_7b/qlora/sft.sh后在runs文件夹下没有checkpoint-xxx

### ISSUE THREAD

**Issue by fan-xh** [modelscope/swift#17]
提示`use_cache=True` is incompatible with gradient checkpointing. Setting `use_cache=False`...，是否需要设置use_cache=False，如果是的话在哪里可以设置呢

**Comment by Jintao-Huang** [comment]
你好！感谢你的issue. 不需要设置的, 这个会自动进行设置的.
