### ISSUE TITLE
ValueError: `model_id_or_path`: 'share_data/base_llms/Yi-6B-200K' is not registered.

### ISSUE THREAD

**Issue by Tendo33** [modelscope/swift#178]
我已经把模型权重保存下来了，为什么在推理的时候显示未注册了，我试了`model.py`里所有的模型，为什么都显示未注册啊

**Comment by Jintao-Huang** [comment]
您好, 可以参考对模型进行注册 https://github.com/modelscope/swift/blob/main/docs/source/LLM/%E8%87%AA%E5%AE%9A%E4%B9%89%E4%B8%8E%E6%8B%93%E5%B1%95.md

你看看是不是--model_type和--model_id_or_path误用了

**Comment by Tendo33** [comment]
> 您好, 可以参考对模型进行注册 https://github.com/modelscope/swift/blob/main/docs/source/LLM/%E8%87%AA%E5%AE%9A%E4%B9%89%E4%B8%8E%E6%8B%93%E5%B1%95.md
> 
> 你看看是不是--model_type和--model_id_or_path误用了

没有误用，我在启动行去除 --model_type 之后：``ValueError: `model_id_or_path`: '/share_data/base_llms/Yi-6B-200K' is not registered. Please use `model_cache_dir` to specify the local cache path for the model.``

**Comment by Jintao-Huang** [comment]
--model_id_or_path和--model_cache_dir需要一起指定的

**Comment by Tendo33** [comment]
> --model_id_or_path和--model_cache_dir需要一起指定的

哦哦哦明白了，感谢

**Comment by Jintao-Huang** [comment]
Yi-6B-200K和Yi-34B-200K之前需要自己注册. 现在已经增加: https://github.com/modelscope/swift/pull/207

**Comment by Tendo33** [comment]
> Yi-6B-200K和Yi-34B-200K之前需要自己注册. 现在已经增加: #207

好的谢谢、

**Comment by plutoda588** [comment]
> 您好, 可以参考对模型进行注册 https://github.com/modelscope/swift/blob/main/docs/source/LLM/%E8%87%AA%E5%AE%9A%E4%B9%89%E4%B8%8E%E6%8B%93%E5%B1%95.md
> 
> 你看看是不是--model_type和--model_id_or_path误用了
你好，我的命令如下，我cd examples/pytorch/llm到这个文件目录下去执行。
执行命令如下：
PYTHONPATH=../../.. \
    CUDA_VISIBLE_DEVICES=0,1 \
    python llm_sft.py \
    --model_id_or_path /T106/LLM_model/Mixtral-8x7B-v0.1 \
    --model_revision master \
    --sft_type lora \
    --tuner_backend swift \
    --dtype AUTO \
    --output_dir output \
    --ddp_backend nccl \
    --dataset dureader-robust-zh \
    --train_dataset_sample -1 \
    --num_train_epochs 2 \
    --max_length 512 \
    --check_dataset_strategy warning \
    --lora_rank 8 \
    --lora_alpha 32 \
    --lora_dropout_p 0.05 \
    --lora_target_modules ALL \
    --batch_size 1 \
    --weight_decay 0.01 \
    --learning_rate 1e-4 \
    --gradient_accumulation_steps 16 \
    --max_grad_norm 0.5 \
    --warmup_ratio 0.03 \
    --eval_steps 300 \
    --save_steps 300 \
    --save_total_limit 2 \
    --logging_steps 10 \
    --only_save_model true \
    --gradient_checkpointing false
    我想的是去微调mixtral模型，但是也出现同样的错误；
    
![微信图片_20240105212220](https://github.com/modelscope/swift/assets/135417137/a38ab1d7-9f4d-487b-85dc-a267ce8a93ed)

我的环境都配置好了，可以加载mixtral模型，用的两张A800

**Comment by plutoda588** [comment]
> 我已经把模型权重保存下来了，为什么在推理的时候显示未注册了，我试了`model.py`里所有的模型，为什么都显示未注册啊

你好，你解决了这个问题嘛？我也出现同样的错误。
