### ISSUE TITLE
请教batch_size设置问题

### ISSUE THREAD

**Issue by DerryChan** [modelscope/swift#182]
lora微调llama-7b 13b batch_size=1是总体训练时间是最短的，不过GPU 利用率很低，batch_size设置高一点GPU利用率能上来但是训练时间会变久不少。。

文档说明是：--batch_size: 训练时的batch_size, 默认为1. 增大batch_size可以增加GPU的利用率, 但不一定会增加训练速度, 因为在一个batch中, 需要对较短的句子按该batch中最长句子的长度进行padding, 从而引入无效的计算量.

是不是可以通过按照句子长度进行分组，句子长度相似的分为一组，来加速训练呢？

**Comment by Jintao-Huang** [comment]
好的 感谢您的建议
