### ISSUE TITLE
支持 DeepSeek-LLM  ？

### ISSUE THREAD

**Issue by Xu-Chen** [modelscope/swift#185]
如题

**Comment by Xu-Chen** [comment]
这个模型好像就是LlamaForCausalLM ，应该可以直接训练

**Comment by Jintao-Huang** [comment]
可以参考 这个进行自定义模型哈

https://github.com/modelscope/swift/blob/main/docs/source/LLM/%E8%87%AA%E5%AE%9A%E4%B9%89%E4%B8%8E%E6%8B%93%E5%B1%95.md#%E8%87%AA%E5%AE%9A%E4%B9%89%E6%A8%A1%E5%9E%8B
