### ISSUE TITLE
where is the 'extra_state_keys ' parameters saved in output dir

### ISSUE THREAD

**Issue by linzhenyuyuchen** [modelscope/swift#192]
1. where is the 'extra_state_keys ' parameters saved in output dir
2. how to load them while running inference

**Comment by tastelikefeet** [comment]
1. `extra_state_keys` is the extra module parameters to be saved into the output dir, usually it will be used like :
Swift.prepare_model(model, config, extra_state_keys=['model.transformer.layer.0.mlp.up_proj'])
2. It will be automatically loaded by the `Swift.from_pretrained` function

**Comment by linzhenyuyuchen** [comment]
from readme ` extra_state_keys is the extra module weights(like the linear head) to be trained and stored in the output dir.`
1. whether `extra_state_keys` means they will be trained or not?
2. what is the filename if `extra_state_keys`  is saved

**Comment by tastelikefeet** [comment]
1. extra_state_keys will be trained
2. in the checkpoint folder adapter_model.bin or adapter_model.safetensors
We suggest to use --modules_to_save parameter now
