### ISSUE TITLE
Yi-6B-200K部署问题

### ISSUE THREAD

**Issue by wangzhen38** [modelscope/swift#194]
请问sft后的模型用哪个部署服务比较好

**Comment by tastelikefeet** [comment]
建议使用vllm：https://docs.vllm.ai/en/latest/models/supported_models.html

**Comment by Jintao-Huang** [comment]
swift现在集成了vllm, 可以参考这里: https://github.com/modelscope/swift/blob/main/docs/source/LLM/VLLM%E6%8E%A8%E7%90%86%E5%8A%A0%E9%80%9F%E4%B8%8E%E9%83%A8%E7%BD%B2.md#%E9%83%A8%E7%BD%B2
