### ISSUE TITLE
无法处理较大的数据集

### ISSUE THREAD

**Issue by Dumail** [modelscope/swift#195]
使用本地数据集进行微调时，数据集太大会导致进程结束，提示如下：
`scripts/yi_6b/lora/sft.sh: line 34:  1917 Killed                  PYTHONPATH=../../.. CUDA_VISIBLE_DEVICES=0 python3 llm_sft.py --model_id_or_path 01ai/Yi-6B --model_cache_dir /home/user/models/Yi-6B --model_revision master --sft_type lora --tuner_backend swift --template_type default-generation --dtype AUTO --output_dir output --custom_train_dataset_path /home/user/.data/swift_pt_data/announcement_data.jsonl --train_dataset_sample -1 --num_train_epochs 1 --max_length 4096 --check_dataset_strategy warning --lora_rank 32 --lora_alpha 32 --lora_dropout_p 0.05 --lora_target_modules DEFAULT --gradient_checkpointing false --batch_size 4 --weight_decay 0.01 --learning_rate 1e-4 --gradient_accumulation_steps 8 --max_grad_norm 0.5 --warmup_ratio 0.03 --eval_steps 10000 --save_steps 10000 --save_total_limit 2 --logging_steps 10`

* 系统为Ubuntu 20.04，cuda版本11.2，8核CPU，32G内存，A100-80G 
* 数据集中每条数据的格式为{“response”: "xxxx"}
* 当数据集大小超过9G时会出现以上错误，但同样类型的数据集，大小为2.7 G却可以正常训练。

**Comment by Jintao-Huang** [comment]
好的 我这里加一个懒加载. 估计内存炸了

**Comment by Adam-fei** [comment]
> 好的 我这里加一个懒加载. 估计内存炸了
hello，我查到了这条历史 issue，请问数据的懒加载添加到最新的版本里了吗？

(我只检索到了‘lazy_tokenize’的相关字样，但爆内存的地方在 get_dataset() 函数，此时应该还没有走到判断 lazy_tokenize 的地方)

**Comment by jfy1016** [comment]
遇到同样的错误，800条数据的数据集可以训练，3300条显示cuda oom
