### ISSUE TITLE
如何使用自定义数据集？

### ISSUE THREAD

**Issue by Mike4Ellis** [modelscope/swift#20]
项目貌似暂时不支持自定义数据集？需要配置哪些地方才可以使用自己的数据呢？

**Comment by Jintao-Huang** [comment]
你好. 如果你想要拓展或使用自定义数据集, 你可以修改`utils/datasets.py`文件中的`DATASET_MAPPING`. 你需要自定义`get_*_dataset`函数, 并返回包含instruction, output两列的数据集.

**Comment by Mike4Ellis** [comment]
如果想要使用本地千问模型的话，也同样要修改代码是吗？我试着提供model_dir参数但是报错了。

**Comment by s861092982** [comment]
如果你想要拓展或使用自定义数据集, 你可以修改utils/datasets.py文件中的DATASET_MAPPING. 你需要自定义get_*_dataset函数, 并返回包含instruction, output两列的数据集.  需要修改3个地方
		#添加一个方法，导入数据集
		def et_hafeng_crm_dataset() -> HfDataset:
		dataset: HfDataset = MsDataset.load(
			'songxin/hafeng-crm01', subset_name='default', split='test').to_hf_dataset()
		return _processing_alpaca(dataset)
		
		#映射数据集
		DATASET_MAPPING = {		
		'hafeng-crm01': get_hafeng_crm_dataset,
		
		#数据集字段名 instruction = dataset['instruction']    'output': dataset['output']  input_ = dataset['input'] 这个需要和数据集的列名对应

**Comment by Jintao-Huang** [comment]
> 如果想要使用本地千问模型的话，也同样要修改代码是吗？我试着提供model_dir参数但是报错了。

如果要使用本地仓库模型的话, 也需要配置`utils/model.py`中的MODEL_MAPPING相关映射关系的.

**Comment by liuzhengzheng123** [comment]
@s861092982 
如果你想要拓展或使用自定义数据集, 你可以修改utils/datasets.py文件中的DATASET_MAPPING. 你需要自定义get_*_dataset函数, 并返回包含instruction, output两列的数据集. 需要修改3个地方
#添加一个方法，导入数据集
def et_hafeng_crm_dataset() -> HfDataset:
dataset: HfDataset = MsDataset.load(
'songxin/hafeng-crm01', subset_name='default', split='test').to_hf_dataset()
return _processing_alpaca(dataset)

你好，请教下大佬，这个详细的代码怎样的呀？数据集存放的位置是哪里哦？

**Comment by Jintao-Huang** [comment]
你先拉取一下新的代码哈, 现在返回的是query, response两列(为了兼容multi-round chat). 
数据集可以本地获取的, 不一定要调用MsDataset.load方法哈
