### ISSUE TITLE
有计划支持Qwen-7B-chat吗？

### ISSUE THREAD

**Issue by tclxmeng-jia** [modelscope/swift#21]
请问有计划什么时候支持Qwen-7B-chat吗？感谢

**Comment by Jintao-Huang** [comment]
会支持的哈, 这周叭

**Comment by Xu-Chen** [comment]
@tclxmeng-jia 最新版本支持了。不过我发现我全量训练的时候，8＊A800，速度上也不快，gpu 占用的话，几个都比较低
