### ISSUE TITLE
SWIFT能否支持同时微调Qwen-VL-chat中的vision encoder和LLM？

### ISSUE THREAD

**Issue by ZhuangPeiyu** [modelscope/swift#215]
我观察到Qwen-VL的代码都是针对后面的LLM使用lora\qlora或者全参数微调。当我想把Qwen-VL模型用到自己的数据集上并使用更大分辨率进行训练的时候，可能涉及到同时微调前面的ViT模型。请问在swift框架下，如何实现这个功能并把微调后的ViT和LLM的参数同时保存下来呢？

**Comment by Jintao-Huang** [comment]
在lora_target_modules中指定ViT中的layer就好啦, 保存和导入会自动处理的.

**Comment by ChingKwanCheung** [comment]
> 在lora_target_modules中指定ViT中的layer就好啦, 保存和导入会自动处理的.

请问是否支持微调模型的某几层，比如只微调最后10层的c_attn模块？

**Comment by Jintao-Huang** [comment]
现在只需要 `--lora_target_modules ALL`就可以了
