### ISSUE TITLE
微调时报错：`use_cache=True` is incompatible with gradient checkpointing. Setting `use_cache=False

### ISSUE THREAD

**Issue by s861092982** [modelscope/swift#22]
微调时报错：`use_cache=True` is incompatible with gradient checkpointing. Setting `use_cache=False，这个改怎么修改？

**Comment by s861092982** [comment]
已解决：数据集的问题，需要注意数据集格式和数量，数量太少可能会遇到这个问题

**Comment by conderls** [comment]
> 已解决：数据集的问题，需要注意数据集格式和数量，数量太少可能会遇到这个问题

这个是配置不兼容由数据量、格式引起？看着不太像呢，我也有这个 warning，能正常跑，还没跑完。

**Comment by Jintao-Huang** [comment]
没影响的, 不用管这个warning

**Comment by Jintao-Huang** [comment]
这个warning的问题已经修复了
