### ISSUE TITLE
希望在 merge_lora_and_save 时能够从本地加载模型参数

### ISSUE THREAD

**Issue by ShuMengZ** [modelscope/swift#222]
我在使用ms-swift==1.4.0
lora训练以后我想merge ，由于远程服务器链接不稳定，下载Qwen-72B-chat会中断，所以 我想从本地加载参数。
在我的使用中，即使infer 的参考文件中没有写明可以使用 model_cache_dir 但如果不开启 merge_lora_and_save 是可以使用 model_cache_dir 从本地加载参数的，所以我进行了多次尝试，期间我误以为是我选择了Master版本，才导致并没有从本地加载。
但是，事实是 infer 并不完全支持（这在 命令行参数.md 并没有写明可以使用，但在 infer 的实现中却支持），当你开启merge_lora_and_save时会使用 model_id_or_path 来加载模型，跳过了    kwargs['model_dir'] = args.model_cache_dir  这一步。

在 模型版本 中也有一个小建议，在使用时抛出了 Using the master branch is fragile, please use it with caution! 但是当我想排查本地模型的版本时，我没有找到任何可以告诉我模型版本的信息，这让我难以排查错误。

在 ms-swift == 1.5.0.dev0 时，gradio 会有版本问题： from gradio.events import Changeable ，gradio> 4.0.0会出现这种问题。

swift非常好用，帮我节省了很多时间也让我学习很多，谢谢你们的工作！

**Comment by Jintao-Huang** [comment]
好的 感谢你的建议～

**Comment by KimballCai** [comment]
确实，在加载本地模型上，我并没有找到一个很好的教程。

但是swift确实帮助了我很多，非常感谢。
