### ISSUE TITLE
No sanity check was performed by LazyLLMDataset when truncation_strategy was set to 'delete'.

### ISSUE THREAD

**Issue by WeiXiaoSummer** [modelscope/swift#226]
In LazyLLMDataset the __get_item__ method will return None if the truncation_strategy was set to 'delete' and the sample at the target idx has a length longer than max_length.

If lazy_tokenize was not activated then before initializing the LLMDataset all the None samples were explicitly removed (in the **dataset_map** method). However LazyLLMDataset lacks this check since it encodes samples on the fly.

https://github.com/modelscope/swift/blob/ead35228b4d028438fcbb1619b767f3a75dfebc0/swift/llm/utils/utils.py#L250-L266

**Comment by Jintao-Huang** [comment]
I understand what you mean. Thank you very much. 😊

**Comment by Jintao-Huang** [comment]
Currently, a random algorithm is being used to address this issue, but there is still a small probability of encountering problems. For example, if 1% of the content does not satisfy the max_length requirement, there is a probability of $0.01^{20}$ of encountering an error. I cannot think of a better method to solve this problem.

**Comment by WeiXiaoSummer** [comment]
Got you! I think the provided solution is enough for now, thanks!
