### ISSUE TITLE
训练微调生成模型到魔搭的模型库之后，模型库中的自己创建的模型，怎么使用？

### ISSUE THREAD

**Issue by s861092982** [modelscope/swift#23]

**Comment by Jintao-Huang** [comment]
使用远程仓库中的模型, 需要先下载到本地, 再使用. 可以使用snapshot_download函数, 函数返回model_dir

**Comment by Mike4Ellis** [comment]
> 使用远程仓库中的模型, 需要先下载到本地, 再使用. 可以使用snapshot_download函数, 函数返回model_dir

您好，返回model_dir后将MODEL_MAPPING处相应的model_id替换为model_dir路径，就可以调用该本地模型了是吧？

**Comment by Jintao-Huang** [comment]
> > 使用远程仓库中的模型, 需要先下载到本地, 再使用. 可以使用snapshot_download函数, 函数返回model_dir
> 
> 您好，返回model_dir后将MODEL_MAPPING处相应的model_id替换为model_dir路径，就可以调用该本地模型了是吧？

是的哈
