### ISSUE TITLE
LoRA微调的一些疑问

### ISSUE THREAD

**Issue by lingen** [modelscope/swift#236]
您好,使用swift对Qwen-7B-Chat进行LoRA微调, sfh以及infer cli一切都顺利. 

数据是用的网上的数据来测试.  链接是: https://www.modelscope.cn/datasets/huangjintao/medical_zh/file/view/master/test_zh_0.jsonl?id=6198&status=2

```shell
PYTHONPATH=../../.. \
CUDA_VISIBLE_DEVICES=0 \
python llm_sft.py \
    --model_id_or_path qwen/Qwen-7B-Chat \
    --model_revision master \
    --sft_type lora \
    --tuner_backend swift \
    --template_type chatml \
    --dtype AUTO \
    --output_dir output \
    --custom_train_dataset_path test_zh_0.jsonl \
    --train_dataset_sample -1 \
    --num_train_epochs 1 \
    --max_length 2048 \
    --check_dataset_strategy warning \
    --lora_rank 8 \
    --lora_alpha 32 \
    --lora_dropout_p 0.05 \
    --lora_target_modules ALL \
    --gradient_checkpointing true \
    --batch_size 1 \
    --weight_decay 0.01 \
    --learning_rate 1e-4 \
    --gradient_accumulation_steps 16 \
    --max_grad_norm 0.5 \
    --warmup_ratio 0.03 \
    --eval_steps 100 \
    --save_steps 100 \
    --save_total_limit 2 \
    --logging_steps 10 \
    --use_flash_attn false \
    --push_to_hub false \
    --self_cognition_sample 500 \
    --model_name 小A 'AI' \
    --model_author 测试 Test \
    --hub_model_id qwen-7b-chat-lora \
    --hub_private_repo true \
    --hub_token 'your-sdk-token' \
```

训练后实际感觉效果好像几乎没有. 请问下, 我的期望是通过LoRA训练能够让AI获取一些更专业的知识. 
比如,其中有一条数据
```jsonl
{"instruction": "足月妊娠合并胎膜早破的推荐药有些什么？", "input": "", "output": "米索前列醇"}
```

但infer的效果是:
<img width="493" alt="image" src="https://github.com/modelscope/swift/assets/2062865/3ed37559-7048-4430-b278-11b46e8aad48">

请问我对微调是有理解上的问题么, 微调是否能增加AI的专业知识? 还是微调只是风格或语气上能对AI有所改变?

**Comment by Jintao-Huang** [comment]
请使用`--lora_target_modules ALL`😊

更多的提示可以查看: https://github.com/modelscope/swift/blob/main/docs/source/LLM/LLM%E5%BE%AE%E8%B0%83%E6%96%87%E6%A1%A3.md#%E6%9B%B4%E5%A4%9Ash%E8%84%9A%E6%9C%AC

**Comment by lingen** [comment]
@Jintao-Huang 非常感谢你的回复. 

我也仔细阅读过相关的文档, 你看我贴的CLI, 其实lora_target_modules的值是ALL

<img width="453" alt="image" src="https://github.com/modelscope/swift/assets/2062865/65053cc5-eeae-4929-9861-2904e8300605">

请问还有哪里设置有误么

**Comment by Jintao-Huang** [comment]
你好 请加一下swift的微信群方便交流哈, 在readme中

**Comment by Jintao-Huang** [comment]
你看看能不能拉取一下最新的代码, 再试试

**Comment by lingen** [comment]
好的,我再更新下代码试下,有问题再咨询你. 

非常感谢
