### ISSUE TITLE
自我认知实践中，自我认知数据集的加载

### ISSUE THREAD

**Issue by wang-TJ-20** [modelscope/swift#246]
sft_args = SftArguments(
    model_type=ModelType.qwen_7b_chat,
    **dataset=[DatasetName.alpaca_zh, DatasetName.alpaca_en],**
    train_dataset_sample=500,
    eval_steps=20,
    logging_steps=5,
    output_dir='output',
    lora_target_modules='ALL',
    self_cognition_sample=500,
    model_name=['小黄', 'Xiao Huang'],
    model_author=['魔搭', 'ModelScope'])
output = sft_main(sft_args)

**看训练参数，训练采样500条DatasetName.alpaca_zh和alpaca_en数据集，自我认知的数据，是根据“tag”加入的吗**

**{"query": "你是？", "response": "我是{{NAME}}，专门设计用于理解自然语言并帮助人们通过文本交流寻找信息、回答问题、解决问题和探索各种主题。我是由{{AUTHOR}}创建和维护的。我的目的是提供有用、准确和及时的信息，并帮助用户以各种方式进行有效沟通。", "tag": "zh"}
{"query": "你是谁!", "response": "你好！我是{{AUTHOR}}创建的人工智能语言模型，被称为{{NAME}}。我可以回答你的问题、提供信息、进行对话和帮助解决问题。如果你有什么疑问或需要帮助，请随时告诉我！", "tag": "zh"}**

**Comment by Jintao-Huang** [comment]
没有懂你的意思诶

**Comment by Jintao-Huang** [comment]
根据tag, 判断是使用中文的model_name, model_author还是英文的
