### ISSUE TITLE
[问题反馈]SFT后的checkpoint加载目录

### ISSUE THREAD

**Issue by hunter-xue** [modelscope/swift#249]
做Qwen-7B的SFT后，输出目录如下：
![image](https://github.com/modelscope/swift/assets/4905312/114a4be7-285d-4a98-a1f2-f2068ecf7ffd)
然后通过`swift app-ui --ckpt_dir`进行推理测试：
1. 如果ckpt_dir设置为/data/Qwen/output-Qwen/qwen-7b-chat/v4-20231224-173846，可以正常启动，但模型使用的仍然是原始模型
2. 如果ckpt_dir设置为/data/Qwen/output-Qwen/qwen-7b-chat/v4-20231224-173846/checkpoint-100，则可以正常加载SFT之后的checkpoint

可否在启动过程打印一个提示，告知加载的是原始模型还是SFT之后的checkpoint. 或者在文档中说明一下加载哪个目录是正确的。

**Comment by tastelikefeet** [comment]
好的，这个我添加一下提示防止出错
