### ISSUE TITLE
请教：使用qwen-7b-chat full微调的模型，加载速度感觉非常慢

### ISSUE THREAD

**Issue by kaer1990** [modelscope/swift#252]
使用qwen-7b-chat full微调的模型，ckpt 15G ，infer时，加载速度感觉很慢。
但是，lora微调后，infer时加载ckpt和base模型 感觉速度很快。

**Comment by Jintao-Huang** [comment]
full保存的ckpt大, 加载慢是正常的哈

**Comment by kaer1990** [comment]
> full保存的ckpt大, 加载慢是正常的哈

@Jintao-Huang  full的ckpt 对比 lora ckpt + qwen-7b-chat原始模型 大小差不多。加载速度应该也差不多吧，但是感觉是慢好多，实现上不一样是吧？

**Comment by Jintao-Huang** [comment]
可能和缓存有关系, 速度瓶颈应该在磁盘IO
