### ISSUE TITLE
V100 full SFT训练不支持fp16?

### ISSUE THREAD

**Issue by LeafBrightDay** [modelscope/swift#257]
utils.argument.py代码里

elif self.sft_type == 'full':
            assert 0 <= self.freeze_parameters < 1
            assert self.quantization_bit == 0, 'not supported'
            assert self.dtype != 'fp16', 'please use bf16 or fp32'

请问一下，为什么full sft不支持fp16微调呢？

**Comment by Jintao-Huang** [comment]
会出现nan, inf, loss会不收敛

**Comment by LeafBrightDay** [comment]
> 会出现nan, inf, loss会不收敛

got, thanks.
