### ISSUE TITLE
增量训练

### ISSUE THREAD

**Issue by Moon502** [modelscope/swift#26]
请问后边会支持千问模型的增量训练吗？

**Comment by Jintao-Huang** [comment]
哈咯, 现在应该支持从chat后继续微调了.

**Comment by Xu-Chen** [comment]
@Jintao-Huang 大佬，按照教程，全量微调，发现 2 卡，和8卡速度差别不大，这个啥原因呢

**Comment by Xu-Chen** [comment]
大佬，swift，有计划支持吗？现在有卡，发现速度不太行

**Comment by Jintao-Huang** [comment]
有的, 不过最近手头事情有点多, 估计得2星期后支持

**Comment by Jintao-Huang** [comment]
如果优先级提高一点的话, 一周后支持吧

**Comment by Xu-Chen** [comment]
感谢 @Jintao-Huang 回复，期待上新功能

**Comment by Jintao-Huang** [comment]
MP+DDP: https://github.com/modelscope/swift/pull/68
