### ISSUE TITLE
微调后如何简单的调用模型

### ISSUE THREAD

**Issue by Emily53469** [modelscope/swift#273]
微调之后通过infer相关的sh文件可以推理成功，但是我想把模型部署到别的机器上，有没有简单的推理代码能够不安装swift的源码和工程就可以推理，例如pip install modelscope和swift之后使用pipeline或者chat方法直接能够推理？

**Comment by Jintao-Huang** [comment]
pip install ms-swift -U

**Comment by Jintao-Huang** [comment]
可以参考这里: https://github.com/modelscope/swift/blob/main/docs/source/LLM/VLLM%E6%8E%A8%E7%90%86%E5%8A%A0%E9%80%9F%E4%B8%8E%E9%83%A8%E7%BD%B2.md
