### ISSUE TITLE
是否支持AMD显卡的加速？

### ISSUE THREAD

**Issue by purefire** [modelscope/swift#274]
使用消费级顶级，或者AMD的AI卡，在rocm 5.7/6.0环境下，是否支持微调等加速？

**Comment by tastelikefeet** [comment]
目前AMD和昇腾显卡的适配已经进入排期，预计2月版本会测试支持

**Comment by radna0** [comment]
Any Update on this? @tastelikefeet

**Comment by jinyizhang184** [comment]
Any update on AMD? @tastelikefeet
