### ISSUE TITLE
AnimateDiff微调时加载的基础模型的选择

### ISSUE THREAD

**Issue by JoshonSmith** [modelscope/swift#310]
aniamtediff 的代码里面，在训练时采用的是 stable diffusion 1.5的权重。

但是在swift的实现中，训练的脚本，无论是全量还是lora方式，均是采用的 一个个性化模型的权重：Realistic_Vision_V5.1_noVAE。

请问有什么考量吗？

**Comment by JoshonSmith** [comment]
@tastelikefeet @Jintao-Huang 感谢模搭社区的swift框架集成AnimateDiff

**Comment by tastelikefeet** [comment]
这个follow了源animatediff github的repo的做法，源repo应该是使用了该基模型训练了Motion-Adapter
