### ISSUE TITLE
请问swift支持Pre-Training吗

### ISSUE THREAD

**Issue by Betai18n** [modelscope/swift#315]
请问swift支持Pre-Training吗，看了下example里面的sh脚本，只有sft和dpo的

**Comment by Jintao-Huang** [comment]
支持的, pre-training的流程和sft的流程是一致的, 除了数据集构建上有一些区别, 只需要提供response, 而不需要提供query.

**Comment by Betai18n** [comment]
感谢回复，所以脚本还是沿用sft的sh，其中--sft_type改为full，即可做Pre-Training吗

**Comment by Jintao-Huang** [comment]
可以参考这里, 自定义数据集中的pretrain部分. https://github.com/modelscope/swift/blob/main/docs/source/LLM/%E8%87%AA%E5%AE%9A%E4%B9%89%E4%B8%8E%E6%8B%93%E5%B1%95.md#%E8%87%AA%E5%AE%9A%E4%B9%89%E6%95%B0%E6%8D%AE%E9%9B%86
