### ISSUE TITLE
Qwen-vl-chat单机多卡遇到Expected all tensors to be on the same device问题

### ISSUE THREAD

**Issue by zodiacg** [modelscope/swift#323]
命令：
```bash
CUDA_VISIBLE_DEVICES=0,1,2,3 \
swift sft \
    --model_type qwen-vl-chat \
    --sft_type full \
    --train_dataset_sample -1 \
    --eval_steps 100 \
    --output_dir output \
    --num_train_epochs 1 \
    --max_length 2048 \
    --learning_rate 2e-5 \
    --use_flash_attn true \
    --save_only_model true \
    --dataset coco-mini-en \
    --push_to_hub false
```
会出现
```
(前略)
  File "/home/zodiacg/miniconda3/envs/swift/lib/python3.10/site-packages/torch/nn/modules/module.py", line 296, in forward
    x = x + self.mlp(self.ln_2(x))
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:2 and cuda:3!
```
错误。

尝试了下模型似乎不能拆到双卡以上，双卡LoRA正常，开四卡也会遇到一样的错误。我是3090，双卡全量装不下（好吧四卡其实也装不下但现在还没到那一步就炸了）

**Comment by zodiacg** [comment]
看了下应该是device_map分配有问题，单层被拆到不同device了。但我好像没找到swift能合理常规的插入自定义device_map的地方

**Comment by Jintao-Huang** [comment]
> 看了下应该是device_map分配有问题，单层被拆到不同device了。但我好像没找到swift能合理常规的插入自定义device_map的地方

只能改源代码了, device_map auto的地方改一下

**Comment by zodiacg** [comment]
> > 看了下应该是device_map分配有问题，单层被拆到不同device了。但我好像没找到swift能合理常规的插入自定义device_map的地方
> 
> 只能改源代码了, device_map auto的地方改一下

自定义了一下device_map确实能跑了。但是效率很低（只有单卡运作那种）。deepspeed zero3加载模型好像拆分更不可控。swift有比较方便整合的流水线方法吗？

**Comment by Jintao-Huang** [comment]
mp+ddp的方案可以尝试.

**Comment by yttas** [comment]
> mp+ddp的方案可以尝试.

请教一下，具体怎么实现mp+ddp呢？找了一些方案，都挺复杂，需要改模型源码

**Comment by zodiacg** [comment]
> > 该指令就是使用mp+ddp方式训练的吗？
> > swift-main\examples\pytorch\llm\scripts\qwen_audio_chat\full_mp_ddp\sft.sh
> > 是的

通过可见设备数和NPROC_PER_NODE的关系来实现mp_ddp？这种情况下模型是由accelerate自动切分的，有什么办法能让它不切错导致主楼的错误吗……

**Comment by yttas** [comment]
> > > 该指令就是使用mp+ddp方式训练的吗？
> > > swift-main\examples\pytorch\llm\scripts\qwen_audio_chat\full_mp_ddp\sft.sh
> > > 是的
> 
> 通过可见设备数和NPROC_PER_NODE的关系来实现mp_ddp？这种情况下模型是由accelerate自动切分的，有什么办法能让它不切错导致主楼的错误吗……

好奇这种mp+ddp方式的具体切分，swift-main\examples\pytorch\llm\scripts\qwen_audio_chat\full_mp_ddp\sft.sh指令执行后，node=2, 所以model被copy了两份，然后其中一份auto切开分布在01上，另一份auto切开分布在23上？所以ddp分组为[01,23]。不知道这么理解对不对。

**Comment by Jintao-Huang** [comment]
是的～

**Comment by Jintao-Huang** [comment]
> > > 该指令就是使用mp+ddp方式训练的吗？
> > > swift-main\examples\pytorch\llm\scripts\qwen_audio_chat\full_mp_ddp\sft.sh
> > > 是的
> 
> 通过可见设备数和NPROC_PER_NODE的关系来实现mp_ddp？这种情况下模型是由accelerate自动切分的，有什么办法能让它不切错导致主楼的错误吗……

mp4卡报错是因为 qwen-vl的代码bug, 和mp+ddp无关的

**Comment by ZSharp7** [comment]
请问这个现在有好的解决方法吗

**Comment by Jintao-Huang** [comment]
没有哇, 实在不行用zero3训练吧, vl只能mp2卡, 或者mp2+ddp/2/4

**Comment by sunyrain** [comment]
想问问如果按照上面的理解，模型被复制了两份，一份在01上，一份在23上，那么训练结果会合并吗？会不会相当于训了两个模型？
