### ISSUE TITLE
执行qalora训练报错, 应该怎么解决

### ISSUE THREAD

**Issue by linguoqi** [modelscope/swift#334]
assertionError: qalora must be used with auto_gptq

**Comment by linguoqi** [comment]
![微信截图_20240122194846](https://github.com/modelscope/swift/assets/157370038/00ff219d-844c-489d-9e28-3c0676425995)

**Comment by tastelikefeet** [comment]
qa-lora用于在auto-gptq量化后的模型上，因此在使用前需要pip install auto-gptq -U

**Comment by linguoqi** [comment]
> qa-lora用于在auto-gptq量化后的模型上，因此在使用前需要pip install auto-gptq -U

安装过的auto-gptq=0.6.0

**Comment by linguoqi** [comment]
没有量化的模型，不能直接使用是吧

**Comment by tastelikefeet** [comment]
是的

**Comment by linguoqi** [comment]
好的，谢谢
