### ISSUE TITLE
除了lora系列的微调方法，其他诸如p-tuning和adapter的微调方法，也提供样例

### ISSUE THREAD

**Issue by linguoqi** [modelscope/swift#337]
除了lora系列的微调方法，其他诸如p-tuning和adapter的微调方法，是否也可以提供样例
理由如下：
1、目前私有化部署或i越来越多，那么10b左右的模型会是重点（不然硬件成本会很高）
2、针对10b的微调将会是重点，比对各种微调方法在业务数据的效果会很有必要
基于上述考虑，麻烦大佬提供一下llama2-7b的系列微调样例（lora、p-tuning、adapter等）

**Comment by tastelikefeet** [comment]
ptuning方法和LLM适配性较差，目前使用人数很少
