### ISSUE TITLE
Yi-VL finetune error

### ISSUE THREAD

**Issue by Yimi81** [modelscope/swift#346]
运行的脚本
```
# Experimental environment: V100, A10, 3090
# 18GB GPU memory
CUDA_VISIBLE_DEVICES=0 \
swift sft \
    --model_type yi-vl-6b-chat \
    --model_cache_dir /home/ci/ygf/Yi/VL/Yi-VL-6B\
    --sft_type lora \
    --tuner_backend swift \
    --template_type AUTO \
    --dtype AUTO \
    --output_dir /home/ci/ygf/swift/outputs \
    --dataset coco-mini-en \
    --train_dataset_sample -1 \
    --num_train_epochs 1 \
    --max_length 2048 \
    --check_dataset_strategy warning \
    --lora_rank 8 \
    --lora_alpha 32 \
    --lora_dropout_p 0.05 \
    --lora_target_modules DEFAULT \
    --gradient_checkpointing true \
    --batch_size 2 \
    --weight_decay 0.01 \
    --learning_rate 1e-4 \
    --gradient_accumulation_steps 8 \
    --max_grad_norm 0.5 \
    --warmup_ratio 0.03 \
    --eval_steps 100 \
    --save_steps 100 \
    --save_total_limit 2 \
    --logging_steps 10 \
    --use_flash_attn true \
```
打印了train_dataset[0]，里面并没有images字段

[INFO:swift] system: This is a chat between an inquisitive human and an AI assistant. Assume the role of the AI assistant. Read all the images carefully, and respond to the human's questions with informative, helpful, detailed and polite answers. 这是一个好奇的人类和一个人工智能助手之间的对话。假设你扮演这个AI助手的角色。仔细阅读所有的图像，并对人类的问题做出信息丰富、有帮助、详细的和礼貌的回答。
[INFO:swift] args.lazy_tokenize: True
train_dataset[0] {'query': 'Picture 1:<img>https://xingchen-data.oss-cn-zhangjiakou.aliyuncs.com/coco/2014/train2014/COCO_train2014_000000047347.jpg</img>\nplease describe the image.', 'response': 'A group of people with umbrellas on a side walk.'}
Traceback (most recent call last):
  File "/home/ci/ygf/swift/swift/cli/sft.py", line 5, in <module>
    sft_main()
  File "/home/ci/ygf/swift/swift/utils/run_utils.py", line 31, in x_main
    result = llm_x(args, **kwargs)
  File "/home/ci/ygf/swift/swift/llm/sft.py", line 145, in llm_sft
    td0, tkwargs0 = template.encode(train_dataset[0])
  File "/home/ci/ygf/swift/swift/llm/utils/template.py", line 521, in encode
    images_path = example['images']
KeyError: 'images'

**Comment by Yimi81** [comment]
Default ft sh dataset selection error, #347

**Comment by Jintao-Huang** [comment]
thanks ~
