### ISSUE TITLE
「模型id或路径」不能更改吗？

### ISSUE THREAD

**Issue by miandai** [modelscope/swift#350]
![image](https://github.com/modelscope/swift/assets/4371622/7e357efc-c12f-4b38-b6a8-cfbccf329c44)
「模型id或路径」框是死的，无法编辑。为什么要限制不能更改呢？

**Comment by ye7love7** [comment]
> ## This is a direct consequence of our model mapping. We are discussing to support a local model dir.
> Can you share me the reason of loading a local model dir please?
> 我们的Model Mapping机制导致了这个问题，我们在讨论支持本地文件夹加载。 可否说明下为何要加载本地模型文件夹呢？

我本地已经下载了模型，难道又重新下载一次吗。。。

**Comment by Jintao-Huang** [comment]
我猜测是web-ui训练没有 model_cache_dir参数  @tastelikefeet

**Comment by Sui-Xing** [comment]
web-ui这个设计确实不友好，没有设置model_cache_dir的选项，不能加载本地模型

**Comment by a2382625920** [comment]
目前有一个方法，将hf路径换成自己本地模型的路径重新注册模型

**Comment by xudongguan202** [comment]
离线环境中需要加载本地模型，希望可以加上该功能

**Comment by tastelikefeet** [comment]
功能已添加
