### ISSUE TITLE
ValueError: model_type: 'yi-vl-6b-chat' is not registered.

### ISSUE THREAD

**Issue by dandanW91** [modelscope/swift#356]
微调yi-vl-6b-chat模型一直说未注册

**Comment by Jintao-Huang** [comment]
是使用的main分支嘛

**Comment by dandanW91** [comment]
是的啊

**Comment by Jintao-Huang** [comment]
我这里可以跑哇, sh脚本可以发一下不
或者直接跑这里的scripts: https://github.com/modelscope/swift/tree/main/examples/pytorch/llm/scripts/yi_vl_6b_chat/lora

**Comment by dandanW91** [comment]
我就是跑的这个sh脚本
CUDA_VISIBLE_DEVICES=6 \
swift sft \
    --model_type yi-vl-6b-chat \
    --sft_type lora \
    --tuner_backend swift \
    --template_type AUTO \
    --dtype AUTO \
    --output_dir output \
    --custom_train_dataset_path /data/home/wangdan02-ghq/projects/data/yi-vl/train_0130.json \
    --train_dataset_sample -1 \
    --num_train_epochs 10 \
    --max_length 1024 \
    --check_dataset_strategy warning \
    --lora_rank 8 \
    --lora_alpha 32 \
    --lora_dropout_p 0.05 \
    --lora_target_modules DEFAULT \
    --gradient_checkpointing true \
    --batch_size 10 \
    --weight_decay 0.01 \
    --learning_rate 1e-4 \
    --gradient_accumulation_steps 1 \
    --max_grad_norm 0.5 \
    --warmup_ratio 0.03 \
    --eval_steps 100 \
    --save_steps 100 \
    --save_total_limit 10 \
    --logging_steps 10 \
    --use_flash_attn false \

这是我的sh脚本，这个和我装的ms-swift版本有关系吗

**Comment by dandanW91** [comment]
![1](https://github.com/modelscope/swift/assets/35364339/00deea76-0b26-4a6c-bb7c-c4a3273f23ce)
显示这个cuow错误

**Comment by dandanW91** [comment]
![image](https://github.com/modelscope/swift/assets/35364339/39c3fd94-8379-465a-8a82-6784d9c73172)
显示这个错误

**Comment by Jintao-Huang** [comment]
pip install -e .
安装一下main分支哈, 或者可能需要更新一下main分支, 重新拉一下
