### ISSUE TITLE
sft可以支持离线模式么

### ISSUE THREAD

**Issue by Tourbillon** [modelscope/swift#36]
我看到微调脚本需要加载hub_token的验证，是只能联网使用的意思么

**Comment by Xu-Chen** [comment]
有一个参数，可以去除
Seq2SeqTrainer 中的 check_model 置为 false 就可以

**Comment by Jintao-Huang** [comment]
> 我看到微调脚本需要加载hub_token的验证，是只能联网使用的意思么

hub_token是可以不设置的, hub_token是如果你将push_to_hub设置为True, 才会被使用的. push_to_hub的意思是是否需要将训练的模型推送到modelscope hub中.

**Comment by Tourbillon** [comment]
@Jintao-Huang @Xu-Chen 感谢两位大佬，在sft的时候，是有指定一起进行微调的数据集保持通用能力么？如果只使用自己的数据集性能应该会下降吧？

**Comment by Jintao-Huang** [comment]
一般lora对通用能力的修改是比较少的, 不用太担心这个问题. 你也可以将lora_alpha降低些, 会对原模型的调整会小一些(一般不太用改). 如果是全参数微调的话, 建议降低学习率, 或者freeze一些层. 

你可以看看agent的数据集, 那个数据集包含挺多的通用对话的数据集, 是整合在一起的. 你可能需要过滤一下

**Comment by Tourbillon** [comment]
@Jintao-Huang 大佬，我再问一下，我查了一下这个agent好像是damo-agent-zh这个么？我看他好像是一个纯文本的数据集，我是想用sft微调一些多模态的数据，这个有对应的数据集推荐么？

**Comment by Jintao-Huang** [comment]
现在只支持coco-en, 你可以自定义多模态的数据集哈 (你可以参考一下coco-en的构造方式), 你可以构造成default-generation的template格式(训练qwen-vl), 也可以是chatml的格式(训练qwen-vl-chat)
