### ISSUE TITLE
Feature Request: FSDP and Deepspeed integration

### ISSUE THREAD

**Issue by HaisongDing** [modelscope/swift#37]
Since peft already support FSDP/DeepSpeed's ZERO, it would be nice if swift also provides such supports to train very large models.

**Comment by Xu-Chen** [comment]
You can try [accelerate](https://huggingface.co/docs/transformers/accelerate)

**Comment by Jintao-Huang** [comment]
Hello, I will support this as soon as possible. I have been on an outing recently.

**Comment by HaisongDing** [comment]
#39

**Comment by summerbuild** [comment]
这个什么时候合并到main？

**Comment by Jintao-Huang** [comment]
国庆期间合, 需要先验证一下性能, 稍等
