### ISSUE TITLE
重新训练结果无法复现

### ISSUE THREAD

**Issue by tiandiweizun** [modelscope/swift#380]
按照官方提供的自我认知训练过程，仅对self_cognition.py新增了一些样例，sft.py 有了seed_everything，但是仍然无法复现，且随着训练过程的持续，差别越来越大

**Comment by Jintao-Huang** [comment]
你说的是效果还是 loss呢

**Comment by tiandiweizun** [comment]
效果和loss都不一样，即eval_acc、eval_loss、train_loss都不一样

**Comment by Jintao-Huang** [comment]
是的 我们在self_cognition.jsonl中增加过一些数据
不过, 对效果的影响应该不大

**Comment by Sakura-not-sleep** [comment]
您好，看到这个问题被关闭了，请问您解决了吗，我也是结果无法复现，每次的结果都不一样，根本没法调参。

**Comment by tiandiweizun** [comment]
> 您好，看到这个问题被关闭了，请问您解决了吗，我也是结果无法复现，每次的结果都不一样，根本没法调参。

没有解决，无法复现，每次都不一样

**Comment by Sakura-not-sleep** [comment]
> > 您好，看到这个问题被关闭了，请问您解决了吗，我也是结果无法复现，每次的结果都不一样，根本没法调参。
> 
> 没有解决，无法复现，每次都不一样

是的，我修改了源码，我把seed_everying都修改了，甚至使用transformer库里面固定所有那个函数都不行，只能保证每次初始化一样，后面就飘的没边了。。。。
