### ISSUE TITLE
docker 使用web_ui时无法打开tensorboard

### ISSUE THREAD

**Issue by xs818818** [modelscope/swift#401]
使用镜像registry.cn-hangzhou.aliyuncs.com/modelscope-repo/modelscope:ubuntu20.04-cuda11.8.0-py38-torch2.0.1-tf2.13.0-1.9.1
ValueError: Duplicate plugins for name projector\n
尝试删除tensorboardX无效

**Comment by Jintao-Huang** [comment]
可以参考这里哈: https://stackoverflow.com/questions/57228487/valueerror-duplicate-plugins-for-name-projector
