### ISSUE TITLE
CPT和SFT的混合训练时只有response的数据集是否会被跳过？

### ISSUE THREAD

**Issue by WSC741606** [modelscope/swift#406]
在使用SFT训练的过程中，注意到日志中显示类似下述文本
[INFO:swift] check_dataset_strategy: 'warning'
[INFO:swift] train_dataset: Dataset({
    features: ['system', 'history', 'query', 'response'],
    num_rows: 378889
})
[INFO:swift] val_dataset: Dataset({
    features: ['system', 'history', 'query', 'response'],
    num_rows: 3727
})
根据自定义数据集部分的介绍，进行CPT训练时只需要提供response列
那么这样的话，在混合数据集训练时，只有response列的数据会被省略吗？能否加一个选项，使其只使用所有的数据集的response列进行预训练？
另外，能否分别统计在输入的数据集中，用于CPT的（没有query列）、用于单轮对话的（query+response）、用于多轮对话的（query+response+history）的数据量？

**Comment by Jintao-Huang** [comment]
建议 分开进行CPT和SFT哈, 先CPT, 再SFT

**Comment by WSC741606** [comment]
好的好的，谢谢建议，我也是新手:)
