### ISSUE TITLE
希望能添加HuggingFace数据集支持和多机多卡并行支持

### ISSUE THREAD

**Issue by WSC741606** [modelscope/swift#407]
手动下再作为自定义数据集还是麻烦了点，能加上直接调用HF的数据集的接口吗，走镜像也能正常访问
目前看到的是单机多卡的支持，不知道能否实现同样简便的多机多卡并行支持？另外现在看似乎单机多卡也是每个卡上放完整模型的数据并行，能否实现自动把整个模型的各个block拆开来，按参数量平均放到各个卡的并行？
感谢！

**Comment by Jintao-Huang** [comment]
多机多卡可以查看这里: https://github.com/modelscope/swift/blob/main/docs/source/LLM/LLM%E5%BE%AE%E8%B0%83%E6%96%87%E6%A1%A3.md#%E4%BD%BF%E7%94%A8cli

mp+ddp是支持的. 只需要卡数和进程数成比例就好了, 会自动开启device_map + ddp

**Comment by Jintao-Huang** [comment]
数据集这里支持hf repo, 会进行兼容 稍等

**Comment by WSC741606** [comment]
好的，感谢回复~
