### ISSUE TITLE
qwen/Qwen-VL-Chat中的bin格式需要如何得到

### ISSUE THREAD

**Issue by xs818818** [modelscope/swift#410]
求教全参数微调能直接得到bin格式或者lora微调后怎么得到bin格式

**Comment by xs818818** [comment]
目前inference推理需要bin格式的，请问full微调可以得到bin格式的吗

**Comment by Jintao-Huang** [comment]
为什么推理需要bin格式呢, 推理可以使用safetensors的. 现在hf推荐使用safetensors格式.
你可以指定`--save_safetensors false`来解决

**Comment by xs818818** [comment]
成功了，谢谢，我试试vllm能不能推理
