### ISSUE TITLE
求助大佬：预训练和继续预训练是不是用全参数量微调的脚本就可以

### ISSUE THREAD

**Issue by uuuidada** [modelscope/swift#418]
求助大佬：预训练和继续预训练是不是用全参数量微调的脚本就可以。

**Comment by Jintao-Huang** [comment]
是哒, 数据集格式可以参考 https://github.com/modelscope/swift/blob/main/docs/source/LLM/%E8%87%AA%E5%AE%9A%E4%B9%89%E4%B8%8E%E6%8B%93%E5%B1%95.md#%E8%87%AA%E5%AE%9A%E4%B9%89%E6%95%B0%E6%8D%AE%E9%9B%86

**Comment by uuuidada** [comment]
感谢
