### ISSUE TITLE
执行sft.sh （Mixtral-8x7B-v0.1）报错

### ISSUE THREAD

**Issue by linguoqi** [modelscope/swift#419]
配置如图
![image](https://github.com/modelscope/swift/assets/157370038/2bda7628-f9ab-4236-858a-86cb383da048)

报错如下
![image](https://github.com/modelscope/swift/assets/157370038/d7fb3f1a-7616-498a-b478-5e16e474dddc)

**Comment by Jintao-Huang** [comment]
model_cache_dir中的模型文件 没有下载完整, 重新下载一下

**Comment by linguoqi** [comment]
![image](https://github.com/modelscope/swift/assets/157370038/a8c8f7c6-8e5e-4b42-aa48-7e1251c839f0)
断开连接后，会在断点继续下载码，还是重新下载
