### ISSUE TITLE
微调模型的本地化保存和加载？

### ISSUE THREAD

**Issue by lj163ucas** [modelscope/swift#42]
你好，
微调后权重只有增量权重，如何直接合并和保存全部权重，然后类似HF指定保存后的本地目录进行模型加载？

**Comment by Jintao-Huang** [comment]
模型的增量权重的结合, 可以使用infer.sh进行拼接和推理哈

**Comment by ZamboLin** [comment]
> 

其实是想问 如何直接合并checkpoint导出模型？

**Comment by Jintao-Huang** [comment]
参考llm_infer.py中的代码拼接, 然后调用PreTrainedModel.save_pretrained保存全部的参数就可以了
