### ISSUE TITLE
qlora微调后的模型，部署推理报错

### ISSUE THREAD

**Issue by linguoqi** [modelscope/swift#422]
![226f22adfa05ca1a08694a4fe0d88f5](https://github.com/modelscope/swift/assets/157370038/bad4b4f4-7994-4bfc-a140-ffa34d980a72)
使用qlora进行微调后的模型文件，相对于lora微调后的模型文件
少了config.json等文件，在部署服务中出现下面的错误
![934b57c27ade17887a4742154980b24](https://github.com/modelscope/swift/assets/157370038/3a08901e-a2a3-4d87-9ad5-aef5e4f5af24)

**Comment by Jintao-Huang** [comment]
qlora和lora的checkpoint中的确不含config.json文件. config.json会从基模型的加载中载入.
