### ISSUE TITLE
merge经过去Lora微调后的模型报错

### ISSUE THREAD

**Issue by linguoqi** [modelscope/swift#424]
使用下面的命令报错
swift merge-lora --ckpt_dir '/tf/python/output/llama2-7b-chat/v6-20240205-075623/checkpoint-21000' --model_cache_dir '/tf/model/Llama-2-7b-chat-ms'
![7650720a8d8a3478273642d8cedd871](https://github.com/modelscope/swift/assets/157370038/c54d6d81-3c60-4865-86f3-608ea582d884)

根据错误提示，加上--do_sample True还是草同样的错

**Comment by Jintao-Huang** [comment]
你先 直接把 model_cache_dir中的 generation_config.json文件改一下, 是基模型的generation_config文件不合理
