### ISSUE TITLE
qwen1.5 int4量化模型lora微调后没法使用merge_lora 合并参数

### ISSUE THREAD

**Issue by Sui-Xing** [modelscope/swift#435]
大佬们，swift merge-lora --ckpt_dir 'xxx/vx_xxx/checkpoint-xxx'这条命令合并int4模型报错不支持Int4模型量化，请问是技术上无法实现，还是功能未开发

**Comment by Jintao-Huang** [comment]
技术上无法实现, 因为会造成较大的误差.
