### ISSUE TITLE
使用swift infer命令或者web-ui怎么输入图片给qwen-vl进行图片推理

### ISSUE THREAD

**Issue by Sui-Xing** [modelscope/swift#439]

**Comment by Jintao-Huang** [comment]
参考这里的输入格式哈
<img width="1029" alt="截屏2024-02-22 10 51 44" src="https://github.com/modelscope/swift/assets/45290347/1d09bc02-63fe-49cf-9ed1-9d94587288fa">

**Comment by Jintao-Huang** [comment]
https://github.com/modelscope/swift/blob/main/docs/source/LLM/%E8%87%AA%E5%AE%9A%E4%B9%89%E4%B8%8E%E6%8B%93%E5%B1%95.md
