### ISSUE TITLE
安装后提示swift: command not found

### ISSUE THREAD

**Issue by kingkong2019** [modelscope/swift#443]
python3 -m pip install -e .[all]
...
Requirement already satisfied: tomli>=2.0.1 in /usr/local/python3/lib/python3.10/site-packages (from yapf->modelscope>=1.9.3->ms-swift==1.6.0.dev0) (2.0.1)
Requirement already satisfied: platformdirs>=3.5.1 in /usr/local/python3/lib/python3.10/site-packages (from yapf->modelscope>=1.9.3->ms-swift==1.6.0.dev0) (4.2.0)
Installing collected packages: ms-swift
  Attempting uninstall: ms-swift
    Found existing installation: ms-swift 1.6.1
    Uninstalling ms-swift-1.6.1:
      Successfully uninstalled ms-swift-1.6.1
  Running setup.py develop for ms-swift
Successfully installed ms-swift-1.6.0.dev0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
WARNING: You are using pip version 21.2.4; however, version 24.0 is available.
You should consider upgrading via the '/usr/bin/python3 -m pip install --upgrade pip' command.
[root@jumpersever-code swift-main]# swift
-bash: swift: command not found

**Comment by Jintao-Huang** [comment]
使用main分支呢, 没有遇到过这个问题诶

**Comment by kingkong2019** [comment]
知道原因了，安装了多个python版本，命令执行前指定python3 -m就可以了。

**Comment by Jintao-Huang** [comment]
python -m swift.cli.main web-ui

python -m swift.cli.main sft/infer ...
