### ISSUE TITLE
lora微调internlm_xcomposer2在merge后报错

### ISSUE THREAD

**Issue by seifer08ms** [modelscope/swift#448]
先lora微调了internlm_xcomposer2_7b_chat，在infer时，选择merge lora，出现`propability tensor contains either inf nan or element < 0`的错误，于是把 do sample设置为false。模型能运行，但是答案全部是一堆`<unk>`
![image](https://github.com/modelscope/swift/assets/506463/b7845135-0824-4796-b429-0d0ce4624096)

**Comment by Jintao-Huang** [comment]
不能 merge-lora, 这个模型

**Comment by Jintao-Huang** [comment]
> 不能 merge-lora, 这个模型

你可以看一下原始模型的结构 😊
