### ISSUE TITLE
用qlora微调后，好像没有发现什么变化？附数据集+微调运行结果

### ISSUE THREAD

**Issue by samchaolau** [modelscope/swift#46]
![a268f67c3f588494e4df33206beee7f](https://github.com/modelscope/swift/assets/83342714/862f71f2-4a9c-4088-b8dd-174ca84881d7)
以上是微调的参数。
训练数据集：https://hh-image.oss-cn-beijing.aliyuncs.com/tmp/train.csv
微调后的相关结果：
![image](https://github.com/modelscope/swift/assets/83342714/cc854445-89e8-445f-9879-58f00ae46120)
![image](https://github.com/modelscope/swift/assets/83342714/93ddcbd2-e4ab-4c92-b510-69891e0729c5)
![image](https://github.com/modelscope/swift/assets/83342714/e6c25398-58bc-499a-a6b6-59a6418bfa42)
![image](https://github.com/modelscope/swift/assets/83342714/27ad1164-0ac6-4797-b7cf-40e04f00bf5a)
![image](https://github.com/modelscope/swift/assets/83342714/6c64471c-656e-4996-8df3-5be952c5d087)
![image](https://github.com/modelscope/swift/assets/83342714/2c115fb1-77de-4e73-834f-02844c307d26)
![image](https://github.com/modelscope/swift/assets/83342714/e2ef1161-cb7a-478b-964f-db8a961f46a9)
![image](https://github.com/modelscope/swift/assets/83342714/8633c2e9-429c-43a3-b7b1-3bc28f7c0822)
![image](https://github.com/modelscope/swift/assets/83342714/e728c65e-0213-4743-91dd-d3e2c3305ac9)
![image](https://github.com/modelscope/swift/assets/83342714/4e836c2c-f672-4f10-8b3c-2c7b66b094ab)
![image](https://github.com/modelscope/swift/assets/83342714/492cc839-c7f9-4e60-bd3f-ed238878134f)
![image](https://github.com/modelscope/swift/assets/83342714/ff61a222-1faa-4dab-849d-834f99ab9081)

**Comment by samchaolau** [comment]
微调完成后进行推理，
![image](https://github.com/modelscope/swift/assets/83342714/e19cd20c-e251-4be1-8996-423c978d671b)
问数据集第一个问题：编号18655236.32616的内容是什么？ 
还是回答的不沾边，想知道为什么，哪里出了问题

**Comment by Jintao-Huang** [comment]
我看数据集第一个问题是下面这样, 好像数据集不太对嘛, 你看看

编号18655236.32616的内容是什么,,"目前支持的meta文件格式为csv或者jsonl。如果是csv格式的，需要用逗号分隔来组织元数据，如果是jsonl格式的，则每行是一个合法有效的json串。元数据用于描述数据文件的一些其他属性，标签等。meta文件统一上传到“元数据文件”tab下。 以csv格式为例，首行为header， 采用 逗号分隔， 每个字段 采用 {字段名}:{类型} 作为标识， 类型可选为Value/FILE，可缺省， 默认文本（Value）, 字段名不允许有重复。 第二行开始为具体的数据，依然采用逗号分隔，字段数和header保持一致，如果类型为FILE，则填写文件在zip包中的相对路径，如果不是zip包（而是一个文件夹或者散装文件），也可以填写相对数据文件根目录的相对路径。"

**Comment by samchaolau** [comment]
这是我特意写成这样的，我想训练后，我如果问“编号18655236.32616的内容是什么” ， 希望他能够回复我教给他的内容，如：“目前支持的meta文件格式为csv或者jsonl。如果是csv格式的，需要用逗号分隔来组织元数据，如果是jsonl格式的，则每行是一个合法有效的json串。元数据用于描述数据文件的一些其他属性，标签等。meta文件统一上传到“元数据文件”tab下。 以csv格式为例，首行为header， 采用 逗号分隔， 每个字段 采用 {字段名}:{类型} 作为标识， 类型可选为Value/FILE，可缺省， 默认文本（Value）, 字段名不允许有重复。 第二行开始为具体的数据，依然采用逗号分隔，字段数和header保持一致，如果类型为FILE，则填写文件在zip包中的相对路径，如果不是zip包（而是一个文件夹或者散装文件），也可以填写相对数据文件根目录的相对路径。"”

**Comment by evanguard** [comment]
我也遇到了類似的問題， QLora SFT過程一切順利， Infer時也成功加載ckpt， 但答案就和完全沒學習過一樣。。。 不知道是什麼原因

**Comment by Jintao-Huang** [comment]
可以贴一下infer的图片嘛

**Comment by Jintao-Huang** [comment]
我想看一下效果情况，我这里测试都是正常的
