### ISSUE TITLE
merge_lora_weights_to_model.py 不能使用本地模型，配置--model_id_or_path，还是走ModelScope Hub下载

### ISSUE THREAD

**Issue by smart-geng** [modelscope/swift#464]
python tools/merge_lora_weights_to_model.py --model_id_or_path /home/user01/llm/models/Qwen1.5-14B-Chat --model_revision master --ckpt_dir /home/user01/llm/swift/examples/pytorch/llm/output/qwen1half-14b-chat/v1-20240227-160104/checkpoint-100
2024-02-27 16:42:38,920 - modelscope - INFO - PyTorch version 2.2.1 Found.
2024-02-27 16:42:38,921 - modelscope - INFO - Loading ast index from /home/user01/.cache/modelscope/ast_indexer
2024-02-27 16:42:38,950 - modelscope - INFO - Loading done! Current index file version is 1.12.0, with md5 983b3f0bb2d13fba963e04f180f13a2c and a total number of 964 components indexed
[INFO:swift] Start time of running main: 2024-02-27 16:42:40.373861
[INFO:swift] ckpt_dir: /home/user01/llm/swift/examples/pytorch/llm/output/qwen1half-14b-chat/v1-20240227-160104/checkpoint-100
[INFO:swift] Setting self.eval_human: True
[INFO:swift] Setting overwrite_generation_config: True
[INFO:swift] replace_if_exists: True
[INFO:swift] merged_lora_path: `/home/user01/llm/swift/examples/pytorch/llm/output/qwen1half-14b-chat/v1-20240227-160104/checkpoint-100-merged`
[INFO:swift] Setting args.sft_type: 'full'
[INFO:swift] Setting args.ckpt_dir: /home/user01/llm/swift/examples/pytorch/llm/output/qwen1half-14b-chat/v1-20240227-160104/checkpoint-100-merged
[INFO:swift] Downloading the model from ModelScope Hub, model_id: qwen/Qwen1.5-14B-Chat
Downloading:   0%|                                                                                                          | 0.00/3.67G [00:00<?, ?B/s]

**Comment by smart-geng** [comment]
ls /home/user01/llm/models/Qwen1.5-14B-Chat
config.json             model-00001-of-00008.safetensors  model-00005-of-00008.safetensors  model.safetensors.index.json  vocab.json
configuration.json      model-00002-of-00008.safetensors  model-00006-of-00008.safetensors  README.md
generation_config.json  model-00003-of-00008.safetensors  model-00007-of-00008.safetensors  tokenizer_config.json
merges.txt              model-00004-of-00008.safetensors  model-00008-of-00008.safetensors  tokenizer.json

**Comment by Jintao-Huang** [comment]
已经fix了
