### ISSUE TITLE
deepspeek 分布式训练报错

### ISSUE THREAD

**Issue by linguoqi** [modelscope/swift#474]
代码如下：
`CUDA_VISIBLE_DEVICES=5,6 \
swift sft \
    --model_cache_dir /tf/model/deepseek-ai/deepseek-moe-16b-chat \
    --model_type deepseek-moe-16b-chat \
    --max_length 4096 \
    --gradient_checkpointing true \
    --eval_steps 100 \
    --use_flash_attn true \
    --num_train_epochs 10 \
    --save_steps 1000 \
    --output_dir output \
    --custom_train_dataset_path /tf/data/train_data/black_start_case14_versionA.jsonl `
    
    报错如下：
    
![image](https://github.com/modelscope/swift/assets/157370038/23743107-1191-4919-915b-c458ad607831)

**Comment by Jintao-Huang** [comment]
fixed
