### ISSUE TITLE
在云服务时进行web推理时，显示无法访问

### ISSUE THREAD

**Issue by Egber1t** [modelscope/swift#475]
[INFO:swift] system: You are a helpful assistant.
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.

单击后显示127.0.0.1 拒绝了我们的连接请求

**Comment by Jintao-Huang** [comment]
你使用的是 web-ui还是app-ui呢

**Comment by tastelikefeet** [comment]
看下本地网络是否有防火墙
