### ISSUE TITLE
deepspeed设置会导致lr_scheduler_type 参数设置失效

### ISSUE THREAD

**Issue by ShuMengZ** [modelscope/swift#491]
deepspeed设置会导致lr_scheduler_type 参数设置失效，默认为常数。
轻松复现：仅需设置     
--deepspeed default-zero2 \
--lr_scheduler_type cosine \
lr 将保持为常数直至完成训练

**Comment by Jintao-Huang** [comment]
我修复一下

**Comment by Jintao-Huang** [comment]
已经修改了默认的ds_config.json. 不过lr_scheduler_type失效是正常的, 需要修改ds_config.json.
https://deepspeed.readthedocs.io/en/latest/schedulers.html
