### ISSUE TITLE
TP并行报错

### ISSUE THREAD

**Issue by linguoqi** [modelscope/swift#493]
报错如下：
![image](https://github.com/modelscope/swift/assets/157370038/31e8b0cc-a099-4f64-b3ff-c0c867d282b8)

代码如下：
![image](https://github.com/modelscope/swift/assets/157370038/9b5c0823-7f3e-4dd7-acd1-c902a00067b5)

单卡是没问题的

**Comment by zhangfan-algo** [comment]
我也遇到了
