### ISSUE TITLE
请教一下如何在已有硬件基础上尽可能提高微调训练的速度？

### ISSUE THREAD

**Issue by WSC741606** [modelscope/swift#495]
如题，使用的设备是32G的V100*8（有多台同配置节点），除了多机多卡并行之外，如何尽可能提高训练速度？

内存基本用不到，感觉就吃显存，Qwen1.8B单机训练差不多10.53it/s（带验证的实际耗时），进度条显示5.81it/s（Train），使用了 --deepspeed "default-zero3" 和 --dtype "fp16"，V100本身不支持flash_attn，还有什么方法能尽可能加速训练呢？

训练使用的--max_length "8192"，--batch_size "1"，测试了batch size为2时会OOM，显卡的利用率基本在100%，但功耗只有100W左右而不是满载的300W（供电本身是充足的），不知道有没有这方面的原因？

为了支持断点续训开了--save_only_model "False"，不过一个checkpoint也就4G不到，而且通信是IB网（40Gb），应该不是太大的瓶颈？但是验证的速度（由进度条看）只有2.44it/s，这个不知道会不会是一个性能瓶颈呢？

期待回复~

**Comment by Jintao-Huang** [comment]
增大 eval_steps. 取消使用zero3(很慢). batch_size对速度影响不大, 因为增大batch_size需要padding, 会增大计算量.

**Comment by WSC741606** [comment]
感谢回复！batch_size我在Swift参数那里有看到描述，说只要占用率够高就行，padding这个我记得前面有个issue建议按不同Token长度切分batch的，麻烦问一下这个实现了吗，怎么调用？
deepspeed这个是要选zero2吗？我记得之前看到deepspeed会提高速度
eval_steps我现在是1k步输出一次，我增大到10k看看

**Comment by WSC741606** [comment]
另外请教一下，对于长文本一般是怎么放进去做CPT的呢？我现在是按段落切分为一个个短的response，但直觉上会导致段落之间上下文信息的丢失，这个能怎么处理呢？做段落间的Overlap吗_(:з」∠)_

**Comment by Jintao-Huang** [comment]
我个人感觉这个影响不大

**Comment by WSC741606** [comment]
emmm，您说的这个是指？

**Comment by Jintao-Huang** [comment]
做段落间的Overlap 对效果的影响不大～ 你可以尝试一下叭😊

**Comment by WSC741606** [comment]
好的呢~后面我试试
