### ISSUE TITLE
Finetune - Running on different gpu configurations

### ISSUE THREAD

**Issue by babla9** [modelscope/swift#499]
How would I change the sft scripts to run on different gpu configurations?

For example, this [cogagent script](https://github.com/modelscope/swift/blob/main/examples/pytorch/llm/scripts/cogagent_18b_chat/lora/sft.sh) is configured to run on 2x A100. How could I change this to run on 4x or 8x V100?

Thanks!

**Comment by Jintao-Huang** [comment]
To specify which GPUs to use, you can use the CUDA_VISIBLE_DEVICES environment variable.

**Comment by babla9** [comment]
Thanks @Jintao-Huang , what if I need to change the memory configuration? For example, 1 V100 != 1 A100. So how do I account for the differences in memory?

**Comment by Jintao-Huang** [comment]
V100 does not support bf16, and fp16 cannot be used as trainable parameters. Therefore, the model can only be loaded as fp32 and trained using mixed precision, which results in more than double the memory consumption compared to A100.
