### ISSUE TITLE
sh脚本传参问题

### ISSUE THREAD

**Issue by lisenjie757** [modelscope/swift#501]
--custom_train_dataset_path: 默认值为[]. 具体的含义参考[自定义与拓展](https://github.com/modelscope/swift/blob/main/docs/source/LLM/%E8%87%AA%E5%AE%9A%E4%B9%89%E4%B8%8E%E6%8B%93%E5%B1%95.md).
--resume_from_checkpoint: 用于断点续训, 默认为None. 你可以将其设置为checkpoint的路径, 例如: 'output/qwen-7b-chat/vx-xxx/checkpoint-xxx', 来进行断点续训.

两个传参问题：
1. 自定义数据集如何传递多个数据集，传--custom_train_dataset_path [xxx.jsonl,yyy.jsonl]，报错
2. 如何传递none这个参数，传--resume_from_checkpoint None，报错

**Comment by Jintao-Huang** [comment]
--custom_train_dataset_path xxx.jsonl yyy.jsonl  (使用空格)
resume_from_checkpoint默认为None, 如果是None就不传递

**Comment by lisenjie757** [comment]
> --custom_train_dataset_path xxx.jsonl yyy.jsonl (使用空格) resume_from_checkpoint默认为None, 如果是None就不传递

明白了，感谢回复！
