### ISSUE TITLE
qwen1.5-0.5B, normal use before fine-tuning, after fine-tuning, swift deploy --infer_backend vllm is not compatible (but swift deploy --infer_backend pt is compatible)

### ISSUE THREAD

**Issue by chuanzhubin** [modelscope/swift#507]
## Phenomenon: Reasoning cannot be stopped, regardless of the stop signal from the client.
Continuous GPU usage, followed by a 502 error on the server side. No content.

![c553cf357ca8ab43bb4d2d6e75b0f0e](https://github.com/modelscope/swift/assets/2813798/d3b68fab-7ee8-4d19-8baa-bbc0ce80fdeb)

## Fine-tuning Script, Independent of the Dataset:
># Experimental environment: A100
># 80GB GPU memory
>    #--dataset codefuse-evol-instruction-zh \
>    #--custom_train_dataset_path openai_format.jsonl \
>    #--custom_val_dataset_path openai_format_marked_404.jsonl \
>CUDA_VISIBLE_DEVICES=0 \
>swift sft \
>    --model_type qwen1half-0_5b-chat \
>    --sft_type full \
>    --dataset agent-instruct-all-en \
>    --train_dataset_sample -1 \
>    --eval_steps 100 \
>    --output_dir output \
>    --num_train_epochs 1 \
>    --max_length 4096 \
>    --learning_rate 1e-5 \
>    --use_flash_attn false \
>    --save_only_model true \
>    --preprocess_num_proc 4 \
>

## Startup Command:
>CUDA_VISIBLE_DEVICES=0 swift deploy --ckpt_dir /gpdata/ideal/bin/output/qwen1half-0_5b-chat/v0-20240219-143823/checkpoint-2804 --infer_backend vllm --host 0.0.0.0

## Client Code Snippet:
>url = "/v1/chat/completions"
>data = {
>"model": "qwen",
>"messages": openai_bot.messages_base + [
>{
>"role": "user",
>"content": prompt
>}
>],
>"temperature": 0,
>"top_p": 1,
>"max_length": 100,
>"stream": False,
>\# "stop": ["<|im_start|>", "<|im_end|>"],
>\# "stop": ["151645","151643"]
>"add_generation_prompt": True,
>}
>

**Comment by chuanzhubin** [comment]
鱼老板，安排上呗， 我生产要用      @Jintao-Huang

**Comment by Jintao-Huang** [comment]
好的 我今明天看

**Comment by Jintao-Huang** [comment]
save_safetensors 设置为False 试试

**Comment by chuanzhubin** [comment]
@Jintao-Huang 鱼老板，好像是管用的。 是升级修复过了吗？ 还是原本加上这个参数就是好的？
--save_safetensors false

--------
我记得当时查到过原因：
qwen1.5的0.5b的lm_head和embedding weight是共享权重的. 
transformers为了节约磁盘 只存了一份. (model.save_pretrained)
但是vllm不兼容这种情况, 因为大模型一般都不共享lm_head和embedding weight的权重的.
vllm加载权重的时候 lm_head为全0
