### ISSUE TITLE
[Question] 在哪里可以修改 WANDB 配置

### ISSUE THREAD

**Issue by rover5056** [modelscope/swift#51]
直接使用 sft.sh 的时候会自动启动 wandb，
但是没找到具体的wandb config 配置。想训练的时候调整wandb的project名之类的，求教~

**Comment by drinkingxi** [comment]
请问找到怎么修改了么

> 直接使用 sft.sh 的时候会自动启动 wandb， 但是没找到具体的wandb config 配置。想训练的时候调整wandb的project名之类的，求教~
