### ISSUE TITLE
BaiChuan2 训练问题

### ISSUE THREAD

**Issue by Xu-Chen** [modelscope/swift#52]
https://github.com/baichuan-inc/Baichuan2/issues/15#issuecomment-1709486875
可以关注上面的 issues

**Comment by Xu-Chen** [comment]
@Jintao-Huang 大佬看下？

**Comment by Jintao-Huang** [comment]
好嘞 我看看哈

**Comment by Xu-Chen** [comment]
百川2 更新了代码，已经 ok 了
