### ISSUE TITLE
如何加载lora训练后的模型进行新的训练？

### ISSUE THREAD

**Issue by WSC741606** [modelscope/swift#525]
如题，在进行LoRA训练后，通过swift merge 合并了权重，准备进行下一阶段的训练，但是在加载数据的过程中频繁报错如下

[ERROR:swift] Authentication token does not exist, failed to access model unknown which may not exist or may be                 private. Please login first.
[ERROR:swift] Authentication token does not exist, failed to access model unknown which may not exist or may be                 private. Please login first.
[ERROR:swift] Authentication token does not exist, failed to access model unknown which may not exist or may be                 private. Please login first.

但是似乎没影响进入训练过程？这个Error在之前从qwen模型直接开始微调的时候没出现过，合并后的权重可以正常推理；是这个操作过程中有什么问题吗？如果希望微调后的模型换其他数据集继续微调，我下面的这个操作过程是对的吗？

合并脚本：swift merge-lora --model_id_or_path qwen/Qwen-1_8B-Chat --ckpt_dir 路径/checkpoint-62000 --merge_lora True

推理脚本：swift infer --model_cache_dir 路径/checkpoint-62000-merged/ --model_type qwen-1_8b-chat 

再继续训练的脚本：
swift sft --model_cache_dir 路径/checkpoint-62000-merged/ \
 --model_type qwen-1_8b-chat \
其他参数

感谢回复！

**Comment by Jintao-Huang** [comment]
这个方式没有问题哈～

**Comment by Jintao-Huang** [comment]
[ERROR:swift] Authentication token does not exist, failed to access model unknown which may not exist or may be private. Please login first.

@tastelikefeet 帮忙看下是什么原因呀

**Comment by WSC741606** [comment]
好的！辛苦了这么晚还在回复~

**Comment by WSC741606** [comment]
另外刚刚跑完了第二步训练，但是推理的结果看，似乎是在原始模型上训练的；之前注入的自我认知也丢失了，回到了原生的阿里云的回答；前面的checkpoint和merge后的模型都是有正常的自我认知的；

推理脚本 swift infer --ckpt_dir 路径/checkpoint-2613

**Comment by WSC741606** [comment]
一阶段CPT注入的领域知识也都无了:(

**Comment by Jintao-Huang** [comment]
完成的第一步和第二步的训练脚本发一下呗

**Comment by WSC741606** [comment]
CPT脚本 

俩节点多机多卡训练 都是V100*8，跑的任务在两个节点上分别启动，只有NODE_RANK=0 和NODE_RANK=1的区别，其他完全一致

NNODES=2 \
NODE_RANK=0 \ 
MASTER_ADDR=主计算节点的IP \
MASTER_PORT=7777 \
NPROC_PER_NODE=$(nvidia-smi --list-gpus | wc -l) swift sft --seed 0\
 --use_flash_attn "False"\
 --sft_type "lora" \
 --dtype "fp16"\
 --neftune_noise_alpha "5"\
 --model_id_or_path $model_id \
 --template_type "qwen"\
 --system $SYSTEM\
 --dataset wikipedia-zh \
 --custom_train_dataset_path $四个自定义数据集\
 --train_dataset_sample -1\
 --eval_steps "1000"\
 --save_steps "1000"\
 --check_dataset_strategy 'warning'\
 --lora_target_modules ALL\
 --lora_rank "32"\
 --batch_size "1"\
 --learning_rate "1e-5"\
 --max_length "8192"\
 --num_train_epochs "3"\
 --self_cognition_sample "9999"\
 --model_name $NAME\
 --model_author $AUTHOR\
 --warmup_ratio "0.1"\
 --preprocess_num_proc 16\
 --add_output_dir_suffix False\
 --save_only_model "False"\
 --output_dir $new_folder --logging_dir $new_folder/runs > $new_folder/runs/run.log 2>&1


SFT脚本

俩节点多机多卡训练 都是V100*8，跑的任务在两个节点上分别启动，只有NODE_RANK=0 和NODE_RANK=1的区别，其他完全一致

NNODES=2 \
NODE_RANK=0 \
MASTER_ADDR=主计算节点的IP \
MASTER_PORT=7777 \
NPROC_PER_NODE=$(nvidia-smi --list-gpus | wc -l) swift sft --seed 0\
 --model_cache_dir "$CPT路径/checkpoint-62000-merged" \
 --model_type qwen-1_8b-chat \
 --use_flash_attn "False"\
 --sft_type "lora" \
 --dtype "fp16"\
 --neftune_noise_alpha "5"\
 --template_type "qwen"\
 --system $SYSTEM\
 --custom_train_dataset_path $两个自定义数据集 \
 --train_dataset_sample -1\
 --eval_steps "1000"\
 --save_steps "1000"\
 --check_dataset_strategy 'warning'\
 --lora_target_modules ALL\
 --lora_rank "32"\
 --batch_size "1"\
 --learning_rate "1e-5"\
 --max_length "8192"\
 --num_train_epochs "3"\
 --self_cognition_sample "9999"\
 --model_name $NAME\
 --model_author $AUTHOR\
 --warmup_ratio "0.1"\
 --preprocess_num_proc 16\
 --add_output_dir_suffix False\
 --save_only_model "False"\
 --output_dir $new_folder --logging_dir $new_folder/runs > $new_folder/runs/run.log 2>&1


这是两次训练的脚本，您看看

**Comment by Jintao-Huang** [comment]
swift infer --ckpt_dir "$CPT路径/checkpoint-62000-merged" 是正常的嘛

**Comment by WSC741606** [comment]
swift infer --ckpt_dir "$CPT路径/checkpoint-62000-merged" 是正常的

**Comment by WSC741606** [comment]
我试试~感谢回答

> 合并脚本：swift merge-lora --ckpt_dir 路径/checkpoint-62000
> 
> 推理脚本：swift infer --ckpt_dir 路径/checkpoint-62000-merged/
> 
> 再继续训练的脚本： swift sft --model_id_or_path 路径/checkpoint-62000-merged/ --model_type qwen-1_8b-chat ...

**Comment by WSC741606** [comment]
合并和推理都正常；
再继续训练脚本swift sft --model_id_or_path 路径/checkpoint-62000-merged/
--model_type qwen-1_8b-chat ...报错
AssertionError: `model_type` and `model_id_or_path` can only specify one of them.

swift sft --model_id_or_path 路径/checkpoint-62000-merged/...（去掉model_type ）
报错
ValueError: model_id_or_path: '路径/checkpoint-62000-merged' is not registered. Please use `--model_type <model_type> --model_cache_dir <local_path>` or `--model_id_or_path <model_id> --model_cache_dir <local_path>`to specify the local cache path for the model.

--model_cache_dir <local_path> --model_type <model_type>如前所述，能训练但似乎调用了原生模型，且报错[ERROR:swift] Authentication token does not exist, failed to access model unknown which may not exist or may be                 private. Please login first.

--model_id_or_path <model_id> --model_cache_dir <local_path>能训练，但调用了原生模型，且报错[ERROR:swift] Authentication token does not exist, failed to access model unknown which may not exist or may be                 private. Please login first.

麻烦大佬再看一眼了T^T

**Comment by Jintao-Huang** [comment]
更新一下swift

pip install ms-swift[llm]

**Comment by WSC741606** [comment]
我试试

**Comment by WSC741606** [comment]
悲报 ms-swift更新到1.7.2还是一样

--model_id_or_path <model_id> --model_cache_dir <local_path>能训练，但调用了原生模型，且报错[ERROR:swift] Authentication token does not exist, failed to access model unknown which may not exist or may be private. Please login first.

swift sft --model_id_or_path 路径/checkpoint-62000-merged/
--model_type qwen-1_8b-chat ... 能训练，但调用了原生模型，且报错[ERROR:swift] Authentication token does not exist, failed to access model unknown which may not exist or may be private. Please login first.

我白天更新ms-swift[all]试试_(:з」∠)_

**Comment by WSC741606** [comment]
哦对了，我测试的时候是加载了第二次训练后的checkpoint，会不会是这个原因啊，就是 我没指定她先跟第一次训练结果合并，推理脚本 swift infer --ckpt_dir 路径2/checkpoint-1000

我试试merge后推理看看

**Comment by WSC741606** [comment]
推理swift merge-lora --model_id_or_path 路径/checkpoint-62000-merged --model_type qwen-1_8b-chat --ckpt_dir 路径2/checkpoint-2613 --merge_lora True 报错

ValueError: Please use `--ckpt_dir vx-xxx/checkpoint-xxx` to use the checkpoint.

**Comment by WSC741606** [comment]
> 悲报 ms-swift更新到1.7.2还是一样
> 
> --model_id_or_path <model_id> --model_cache_dir <local_path>能训练，但调用了原生模型，且报错[ERROR:swift] Authentication token does not exist, failed to access model unknown which may not exist or may be private. Please login first.
> 
> swift sft --model_id_or_path 路径/checkpoint-62000-merged/ --model_type qwen-1_8b-chat ... 能训练，但调用了原生模型，且报错[ERROR:swift] Authentication token does not exist, failed to access model unknown which may not exist or may be private. Please login first.
> 
> 我白天更新ms-swift[all]试试_(:з」∠)_

即使更新了ms-swift[all]并加上了--check_model_is_latest False \ 还是一样:(

**Comment by Jintao-Huang** [comment]
我知道了... --model_id_or_path 路径/checkpoint-62000-merged 这个 改个名字 比如叫 `pretrained-model`...

**Comment by Jintao-Huang** [comment]
我修复一下... 还有这个问题...

**Comment by WSC741606** [comment]
乐，我建立了个软连接到checkpoint-62000-merged，真就没有[ERROR:swift] Authentication token does not exist, failed to access model unknown which may not exist or may be private. Please login first.了

**Comment by WSC741606** [comment]
训练还要几分钟，有结果给您汇报~

**Comment by WSC741606** [comment]
> 乐，我建立了个软连接到checkpoint-62000-merged，真就没有[ERROR:swift] Authentication token does not exist, failed to access model unknown which may not exist or may be private. Please login first.了

说早了）还是有这个提示
等训练结果吧（）

**Comment by WSC741606** [comment]
emmmmmm，--model_id_or_path到软连接还是一样，看着是从原生模型上训练了

**Comment by WSC741606** [comment]
> emmmmmm，--model_id_or_path到软连接还是一样，看着是从原生模型上训练了

swift sft --model_id_or_path CPTModel0 --model_type qwen-1_8b-chat ...

**Comment by Jintao-Huang** [comment]
swift infer --model_id_or_path CPTModel0 --model_type qwen-1_8b-chat

你先推理一下试试

**Comment by WSC741606** [comment]
这个没问题，是CPT后的样子

> swift infer --model_id_or_path CPTModel0 --model_type qwen-1_8b-chat
> 
> 你先推理一下试试

**Comment by WSC741606** [comment]
应该不是多机多卡导致的 新测试的CPT和SFT都是单机8卡训练的 但还是存在原先微调上去的自我认知和知识丢失的情况，通过推理得出，返回了原先通义千问的认知

> 这个会不会和多机多卡训练有关呢？俩节点我分别输出到了两个文件夹，前面的checkpoint-62000是NODE_RANK为0的节点的输出文件夹下的checkpoint

**Comment by Jintao-Huang** [comment]
你要不试试 微调10步，然后infer以下呢

你第二次微调后是怎么推理的呢

**Comment by WSC741606** [comment]
SFT微调后推理脚本
swift infer --ckpt_dir 路径/checkpoint-10/

--max_steps=10
Infer结果和原生qwen_1.8b完全一致

**Comment by WSC741606** [comment]
我傻了...

第二次SFT后的推理应该是
swift infer --ckpt_dir SFT路径/checkpoint-2613/ --model_id_or_path CPTModel1 

这样就可以正常在前面CPT后的模型上加上LoRA了，我之前一直以为base模型的信息是包含在SFT后的Checkpoint里面的_(:з」∠)_

加上后日志里面有[INFO:swift] Loading the model using model_dir: CPTModel1

实在是太麻烦您了，我的锅:)

**Comment by Jintao-Huang** [comment]
好哒～感谢使用swift😊

**Comment by WSC741606** [comment]
Swift还是很好用的，对于我们这种只想快速落地LLM到垂域的来说~应该是我感谢您的团队开发出了这么好上手的框架才是~

**Comment by Summer-nan** [comment]
> 我傻了...
> 
> 第二次SFT后的推理应该是 swift infer --ckpt_dir SFT路径/checkpoint-2613/ --model_id_or_path CPTModel1
> 
> 这样就可以正常在前面CPT后的模型上加上LoRA了，我之前一直以为base模型的信息是包含在SFT后的Checkpoint里面的_(:з」∠)_
> 
> 加上后日志里面有[INFO:swift] Loading the model using model_dir: CPTModel1
> 
> 实在是太麻烦您了，我的锅:)

想问一下您这个CPTModel1 是随便起一个名字就行吗

**Comment by Jintao-Huang** [comment]
不用写 --model_id_or_path

**Comment by zhaolaipeng** [comment]
> 合并脚本：swift merge-lora --ckpt_dir 路径/checkpoint-62000
> 
> 推理脚本：swift infer --ckpt_dir 路径/checkpoint-62000-merged/
> 
> 再继续训练的脚本： swift sft --model_id_or_path 路径/checkpoint-62000-merged/ --model_type qwen-1_8b-chat ...

您好，我基于这种方式第二次lora微调后会影响到第一次的lora微调效果，使得第一次本来正常的，经过两次微调效果出现的偏差。请问这是什么原因导致的？

**Comment by WSC741606** [comment]
> > 我傻了...
> > 第二次SFT后的推理应该是 swift infer --ckpt_dir SFT路径/checkpoint-2613/ --model_id_or_path CPTModel1
> > 这样就可以正常在前面CPT后的模型上加上LoRA了，我之前一直以为base模型的信息是包含在SFT后的Checkpoint里面的_(:з」∠)_
> > 加上后日志里面有[INFO:swift] Loading the model using model_dir: CPTModel1
> > 实在是太麻烦您了，我的锅:)
> 
> 想问一下您这个CPTModel1 是随便起一个名字就行吗

那个是我的文件夹路径

**Comment by WSC741606** [comment]
> > 合并脚本：swift merge-lora --ckpt_dir 路径/checkpoint-62000
> > 推理脚本：swift infer --ckpt_dir 路径/checkpoint-62000-merged/
> > 再继续训练的脚本： swift sft --model_id_or_path 路径/checkpoint-62000-merged/ --model_type qwen-1_8b-chat ...
> 
> 您好，我基于这种方式第二次lora微调后会影响到第一次的lora微调效果，使得第一次本来正常的，经过两次微调效果出现的偏差。请问这是什么原因导致的？

我的理解是多次微调出现了灾难性遗忘的现象，相当于不断往上叠加△W，导致第一次的△W的修改比重变小了

**Comment by WSC741606** [comment]
> > 合并脚本：swift merge-lora --ckpt_dir 路径/checkpoint-62000
> > 推理脚本：swift infer --ckpt_dir 路径/checkpoint-62000-merged/
> > 再继续训练的脚本： swift sft --model_id_or_path 路径/checkpoint-62000-merged/ --model_type qwen-1_8b-chat ...
> 
> 您好，我基于这种方式第二次lora微调后会影响到第一次的lora微调效果，使得第一次本来正常的，经过两次微调效果出现的偏差。请问这是什么原因导致的？

我自己现在考虑的是全部一步LoRA过，就不分多步了

**Comment by answerme11** [comment]
@Jintao-Huang 请教一下我有如下场景改怎么进行训练：
1、有一个basemodel_a，经过lora微调得到了lora权重lora_a，推断的时候就是basemodel_a+lora_a
2、然后我想继续基于basemodel_a+lora_a的基础上继续用dpo训练一个lora权重，但是不希望把basemodel_a+lora_a合并后再训练

**Comment by abcdvzz** [comment]
@answerme11 朋友你问题解决了吗，请问下面的情况怎么办，sft_1: base->lora_a, inference_1: base+lora_a, 假如我merge了，得到base_lora_a_merged, 基础上接着训sft_2，得到lora_b, 这时候怎么inference，base_lora_a_merged + lora_b，还是base+lora_b就行？
