### ISSUE TITLE
vllm endpoint 似乎没有正确暴露

### ISSUE THREAD

**Issue by 1100111GTH** [modelscope/swift#534]
![CleanShot 2024-03-12 at 12 14 38](https://github.com/modelscope/swift/assets/154310050/f9395e6b-74e5-4485-99b7-f9a843362e3f)

**Comment by 1100111GTH** [comment]
略过 swift，直接使用 vllm 驱动时没有问题

**Comment by 1100111GTH** [comment]
```
swift deploy --model_type qwen-7b-chat --model_cache_dir /root/autodl-tmp/Qwen-7B-Chat
```

**Comment by 1100111GTH** [comment]
> ```
> swift deploy --model_type qwen-7b-chat --model_cache_dir /root/autodl-tmp/Qwen-7B-Chat
> ```

@Jintao-Huang

**Comment by 1100111GTH** [comment]
> 部署命令是什么呢

swift deploy --model_type qwen-7b-chat --model_cache_dir /root/autodl-tmp/Qwen-7B-Chat

**Comment by Jintao-Huang** [comment]
客户端呢, 怎么调用呢

**Comment by 1100111GTH** [comment]
> 客户端呢, 怎么调用呢

/etc/prometheus/prometheus.yml:

```
  - job_name: 'vllm'
    static_configs:
    - targets: ['127.0.0.1:8000']
```

**Comment by Jintao-Huang** [comment]
curl http://localhost:8000/v1/chat/completions \
-H "Content-Type: application/json" \
-d '{
"model": "qwen-7b-chat",
"messages": [{"role": "user", "content": "晚上睡不着觉怎么办？"}],
"max_tokens": 256,
"temperature": 0
}'

**Comment by Jintao-Huang** [comment]
这个能跑通嘛
