### ISSUE TITLE
 torch._C._LinAlgError 

### ISSUE THREAD

**Issue by Kk1984up** [modelscope/swift#537]
use gptq int4 quan
get some error as below
 torch._C._LinAlgError : linalg.cholesky: the factorization could not be completed because the input is not positive-definite(
the leading minor of order 24551 is not positive-definite
)

**Comment by Kk1984up** [comment]
Try setting damp_percent to 0.1, or increasing the number of training samples;
how to set damp_percent for gptq at the swift package??

**Comment by Jintao-Huang** [comment]
Try upgrading "optimum"

pip install optimum -U

**Comment by Kk1984up** [comment]
upgrading  optimum version to 1.17.1，but don't solve the issue.
just qwen1.5-72b-chat have the error.

**Comment by Jintao-Huang** [comment]
Try increasing the `quant_n_samples` and see if it helps.
https://github.com/modelscope/swift/blob/main/docs/source/LLM/%E5%91%BD%E4%BB%A4%E8%A1%8C%E5%8F%82%E6%95%B0.md
