### ISSUE TITLE
如何禁用hadoop

### ISSUE THREAD

**Issue by LOGIC-10** [modelscope/swift#54]
qlora微调qwen-chat-7b的时候老是调用hadoop-2.7.4，虽然我只有一个GPU，但是这个会导致权限问题，我能如何在代码中禁止这样的调用？谢谢！

**Comment by Jintao-Huang** [comment]
我记得不会调用这样呀, 你试试卸载这个库试试, 会不会报错

**Comment by LOGIC-10** [comment]
解决了，是做量化时候的bitsandbytes库自动调用了hadoop。我删除了环境变量之后就不会自动调用了，谢谢！
