### ISSUE TITLE
DeepSeek VL finetune vision encoder?

### ISSUE THREAD

**Issue by SinanAkkoyun** [modelscope/swift#543]
Hi! Does finetuning deepseek VL also finetune the vision encoder?

**Comment by Jintao-Huang** [comment]
This model currently only supports fine-tuning of the LLM portion

**Comment by wwzhuang01** [comment]
hi! is finetuning the aligner of deepseek-vl supported?

**Comment by Jintao-Huang** [comment]
I am trying to provide support.

**Comment by SinanAkkoyun** [comment]
@Jintao-Huang Can you please provide pretraining code for the vision encoder, we need to give it new capabilites :)

**Comment by SinanAkkoyun** [comment]
Wow! That was super quick, thank you so so much!!! ❤️

**Comment by SinanAkkoyun** [comment]
In what format must the custom train dataset be? (And what does the val dataset do exactly?)

**Comment by soloice** [comment]
Bro, you really rocks!

**Comment by SinanAkkoyun** [comment]
```jsonl
{"query": "EEEEE", "response": "FFFFF", "history": [["AAAAA", "BBBBB"], ["CCCCC", "DDDDD"]], "images": ["https://qianwen-res.oss-cn-beijing.aliyuncs.com/Qwen-VL/assets/demo.jpeg", "https://qianwen-res.oss-cn-beijing.aliyuncs.com/Qwen-VL/assets/demo.jpeg", "https://qianwen-res.oss-cn-beijing.aliyuncs.com/Qwen-VL/assets/demo.jpeg"]}
```

Is that the right format; would I now need to place `<image_placeholder>` where each image should go?
Also out of curiosity, is it possible to make multi-turn with multiple images?

**Comment by Jintao-Huang** [comment]
Format is similar to this:
```
[PROMPT]<｜begin▁of▁sentence｜>You are a helpful language and vision assistant. You are able to understand the visual content that the user provides, and assist the user with a variety of tasks using natural language.

User: <image_placeholder>please describe the image.

Assistant:[OUTPUT]A large airplane is suspended from the ceiling.<｜end▁of▁sentence｜>
```

**Comment by Jintao-Huang** [comment]
The image will be automatically placed into the image_placeholder to form inputs_embeds. It supports multi-turn conversations with multiple images, but each turn of the conversation can only contain one image.

**Comment by Marcovaldon** [comment]
@Jintao-Huang How to load the local model path when inferencing? I tried with arg model_id_or_path='../exchange/deepseek-vl-7b-chat/', there is an error which seems to be about the original code of DeepSeek-VL.

2024-03-14 06:16:17,762 - modelscope - INFO - PyTorch version 2.0.1+cu118 Found.
2024-03-14 06:16:17,763 - modelscope - INFO - Loading ast index from /root/.cache/modelscope/ast_indexer
2024-03-14 06:16:17,794 - modelscope - INFO - Loading done! Current index file version is 1.13.1, with md5 9160dca331310c9a635ab1783524701f and a total number of 972 components indexed
template_type: deepseek-vl
[INFO:swift] Loading the model using model_dir: ../exchange/deepseek-vl-7b-chat/
>>>>> >>>>> model_dir = ../exchange/deepseek-vl-7b-chat/
Traceback (most recent call last):
  File "inference.py", line 15, in <module>
    model, tokenizer = get_model_tokenizer(model_type, torch.float16,
  File "/Multimodal/dongshiqi/swift/swift/llm/utils/model.py", line 2692, in get_model_tokenizer
    model, tokenizer = get_function(model_dir, torch_dtype, model_kwargs,
  File "/Multimodal/dongshiqi/swift/swift/llm/utils/model.py", line 1754, in get_model_tokenizer_deepseek_vl
    vl_chat_processor = VLChatProcessor.from_pretrained(model_dir)
  File "/usr/local/lib/python3.8/dist-packages/transformers/processing_utils.py", line 465, in from_pretrained
    args = cls._get_arguments_from_pretrained(pretrained_model_name_or_path, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/transformers/processing_utils.py", line 511, in _get_arguments_from_pretrained
    args.append(attribute_class.from_pretrained(pretrained_model_name_or_path, **kwargs))
  File "/usr/local/lib/python3.8/dist-packages/transformers/models/auto/image_processing_auto.py", line 354, in from_pretrained
    config_dict, _ = ImageProcessingMixin.get_image_processor_dict(pretrained_model_name_or_path, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/transformers/image_processing_utils.py", line 334, in get_image_processor_dict
    resolved_image_processor_file = cached_file(
  File "/usr/local/lib/python3.8/dist-packages/transformers/utils/hub.py", line 369, in cached_file
    raise EnvironmentError(
OSError: ../exchange/deepseek-vl-7b-chat/ does not appear to have a file named preprocessor_config.json. Checkout 'https://huggingface.co/../exchange/deepseek-vl-7b-chat//main' for available files.

**Comment by SinanAkkoyun** [comment]
@Jintao-Huang 
Thank you so much :)

I don't quite understand these points:

- How would the training jsonl look like exactly?
- How can I use the llava chat format or any other format for that matter (they use that for the deepseek vl chat models)?
- What's the `val` dataset being used for and is it necessary?


Again thanks for your help!

**Comment by Jintao-Huang** [comment]
```jsonl
{"query": "55555", "response": "66666", "images": ["image_path"]}
{"query": "eeeee", "response": "fffff", "history": [], "images": ["image_path"]}
{"query": "EEEEE", "response": "FFFFF", "history": [["AAAAA", "BBBBB"], ["CCCCC", "DDDDD"]], "images": ["image_path", "image_path2", "image_path3"]}
```

https://github.com/modelscope/swift/blob/main/docs/source/Multi-Modal/deepseek-vl%E6%9C%80%E4%BD%B3%E5%AE%9E%E8%B7%B5.md

**Comment by Jintao-Huang** [comment]
Every multimodal model has its own custom dataset style, and it is demonstrated in best practices. For example, some multimodal models support zero or multiple images in a single conversation, such as qwen-vl. Some multimodal models only allow one image per conversation, like deepseek-vl. And there are multimodal models that require only one image for the entire dialogue, such as cogvlm.

**Comment by Jintao-Huang** [comment]
The val_dataset is used to evaluate the eval_loss. You can also choose to not provide the custom_val_dataset_path and only pass the custom_train_dataset_path.

**Comment by SinanAkkoyun** [comment]
Thank you so so much!!! 🙏❤️

And just to verify: If I need another prompt format I can just change the DeepseekVLTemplate code is that correct?

**Comment by SinanAkkoyun** [comment]
Thank you so so much!!! 🙏❤️

**Comment by SinanAkkoyun** [comment]
Hey @Jintao-Huang , thank you again for implementing the model, I really appreciate your work!

Upon further testing, I realized that DeepSeek VL apparently supports multi-image prompts.
Could you please implement multi-image support for training? I'd love to train the model on some image comparisons

**Comment by daihuangyu** [comment]
This format seems to only support the training method of images + text. Can it be training with plain text data？

**Comment by CudaMem** [comment]
@Jintao-Huang 您好！请问deepseek-vl暂时只能微调llm部分，不能训练aligner（connector）部分吗？谢谢🙏

**Comment by Jintao-Huang** [comment]
> @Jintao-Huang 您好！请问deepseek-vl暂时只能微调llm部分，不能训练aligner（connector）部分吗？谢谢🙏

--lora_target_modules设置为ALL就可以了，可以查看最佳实践哈，里面有写的。包括如何进行全参数训练

**Comment by SinanAkkoyun** [comment]
Thank you so so much! 😊

**Comment by Ven20002** [comment]
I am working on this. New to LLM and is looking for this type of VL for image and reasoning. However, I need to fine-tune it to understand my environment and task. But not fully with this fine-tuning script. I am working in Python and wonder if it's possible even? been investing in this ms-swift but this is completely new to me, are there any more examples? Been looking everywhere.
Thanks!

**Comment by Jintao-Huang** [comment]
https://github.com/modelscope/ms-swift/tree/main/examples/train

**Comment by whcjb** [comment]
> [@Jintao-Huang](https://github.com/Jintao-Huang) How much VRAM is needed to finetune the 7b VL model?
> 
> # Experimental Environment: A100
> # GPU Memory Requirement: 80GB
> # Runtime: 2.5 hours
> CUDA_VISIBLE_DEVICES=0 \
> swift sft \
>     --model_type qwen1half-7b-chat \
>     --dataset blossom-math-zh \
>     --num_train_epochs 5 \
>     --sft_type full \
>     --output_dir output \
>     --eval_steps 500 \
> The docs say one needs 80GB for a normal 7b model, however when I try to train on the research rig with an A100 I get an OOM. When trying to split across 4 GPUs (1 A100 and 3 4090s), it does not utilize the A100 and OOMs with the 3 4090s before training can start

hello， @SinanAkkoyun， have you solve the problem? could you give some practice ? many thanks

**Comment by adoptedirelia** [comment]
> {"query": "55555", "response": "66666", "images": ["image_path"]}
> {"query": "eeeee", "response": "fffff", "history": [], "images": ["image_path"]}
> {"query": "EEEEE", "response": "FFFFF", "history": [["AAAAA", "BBBBB"], ["CCCCC", "DDDDD"]], "images": ["image_path", "image_path2", "image_path3"]}
> https://github.com/modelscope/swift/blob/main/docs/source/Multi-Modal/deepseek-vl%E6%9C%80%E4%BD%B3%E5%AE%9E%E8%B7%B5.md

请问只需要把这些定义好，然后放到jsonl文件中，最后在命令行中定义custom_train_dataset_path就可以了吗，但是我直接运行会报错raise ValueError(f'self.dataset: {self.dataset}, Please input the training dataset.')raise ValueError(f'self.dataset: {self.dataset}, Please input the training dataset.')
