### ISSUE TITLE
微调千问1.5时报错Authentication token does not exist,             

### ISSUE THREAD

**Issue by evyy1234** [modelscope/swift#549]
![image](https://github.com/modelscope/swift/assets/32873018/a527d68f-fbd8-491a-ad19-2b5589d43743)
使用自定义数据集对Qwen1.5-7B-chat训练时报错：
![image](https://github.com/modelscope/swift/assets/32873018/12275d9f-dee8-44c5-afed-54cd1590ce61)
请问需要哪里录入身份信息？？

**Comment by Jintao-Huang** [comment]
Authentication token does not exist
这个问题不需要注意哈
