### ISSUE TITLE
部署微调后的agent模型，报错ValueError: remaining_argv: ['--stop_words', 'Observation:']

### ISSUE THREAD

**Issue by evyy1234** [modelscope/swift#557]
服务端运行命令：
CUDA_VISIBLE_DEVICES=0 swift deploy --ckpt_dir 'swift/output1/qwen1half-7b-chat/v0-20240314-081719/checkpoint-1000'  --stop_words Observation:
报错stop_words Observation:值错误
![image](https://github.com/modelscope/swift/assets/32873018/ec35776f-1791-4869-9862-1d12733cdb4b)

**Comment by Jintao-Huang** [comment]
拉一下最新main分支的代码，再试试
