### ISSUE TITLE
tp并行推理报错

### ISSUE THREAD

**Issue by linguoqi** [modelscope/swift#558]
![image](https://github.com/modelscope/swift/assets/157370038/4d9c514f-c9d3-4b28-8799-1911f6b1d999)

![image](https://github.com/modelscope/swift/assets/157370038/553d558e-da7f-4730-930c-6599339a7b4d)

**Comment by linguoqi** [comment]
根据黄老师指引，修改 gpu_memory_utilization参数，目前也是没有作用，请解决该问题在关闭该issue

**Comment by Jintao-Huang** [comment]
现在可以跑了嘛
