### ISSUE TITLE
对于lora微调输出日志中参数的疑问？

### ISSUE THREAD

**Issue by evyy1234** [modelscope/swift#562]
微调命令如下：
CUDA_VISIBLE_DEVICES=0,1 python llm_sft.py --model_type chatglm3-6b --model_id_or_path /home/chatglm3-6b --model_revision master --sft_type lora --tuner_backend swift --template_type chatglm3 --dtype AUTO --output_dir output --dataset ms-agent  --train_dataset_sample -1  --num_train_epochs 1 --max_length -1 --check_dataset_strategy warning --lora_rank 8 --lora_alpha 32  --lora_dropout_p 0.05  --lora_target_modules DEFAULT  --gradient_checkpointing true --batch_size 1 --weight_decay 0.01 --learning_rate 1e-4 --gradient_accumulation_steps 16 --max_grad_norm 0.5 --max_steps -1 --warmup_ratio 0.03 --eval_steps 100 --save_steps 100 --save_total_limit 2 --logging_steps 5 
微调输出日志：
![image](https://github.com/modelscope/swift/assets/32873018/ed6e3b2c-b569-418a-9c59-0f64739420eb)

选择ms-agent数据集（样本总数3万），参数设置为batch_size 1  ，num_train_epochs 1，train_dataset_sample -1 ，我理解的global_step应该等于训练样本数/batch_size，这里train_dataset_sample -1，没有对数据进行抽样，除去验证集，那么global_step至少也应该是2万多才对啊，但是日志中global_step为1856，不知道该如何理解此间的关系？请求解答

**Comment by evyy1234** [comment]
我知道了  因为gradient_accumulation_steps 16这个参数会造成total_batch_size变化、、、、

**Comment by Jintao-Huang** [comment]
> 我知道了 因为gradient_accumulation_steps 16这个参数会造成total_batch_size变化、、、、

是的
