### ISSUE TITLE
lora merge 出错

### ISSUE THREAD

**Issue by Wq-dd** [modelscope/swift#566]
目的：使用微调后的lora权重进行merge，然后保存。
出错的截图：
<img width="1389" alt="image" src="https://github.com/modelscope/swift/assets/62586707/ea7065bb-cb7b-4824-81ba-ada59ffcd413">
使用的命令：
swift export 
--ckpt_dir llama2-7b-chat/v1-20240303-122630/checkpoint-6250  \
--merge_lora true \
--model_type llama2-7b-chat \
--model_cache_dir llama2-7b-chat/modelscope/Llama-2-7b-chat-ms
尝试过在命令中增加--do_sample true，但是没有起作用。
请问这个问题的原因是什么呢？有什么解决方案呢？

**Comment by Jintao-Huang** [comment]
你可以把`llama2-7b-chat/modelscope/Llama-2-7b-chat-ms`这里的generation_config.json改一下

**Comment by Wq-dd** [comment]
非常感谢，我按照您的方法更改了对应文件，现在可以merge lora并且save到本地了。我还有一个小小的疑问，我查看了文档，好像没有看到如何使用merge后的权重进行推理的示例，请问可以提供一个使用merge后的权重进行推理的方法吗？

**Comment by Jintao-Huang** [comment]
https://github.com/modelscope/swift/blob/main/docs/source/LLM/LLM%E5%BE%AE%E8%B0%83%E6%96%87%E6%A1%A3.md#%E6%8E%A8%E7%90%86
