### ISSUE TITLE
RuntimeError: Error building extension 'fused_adam'

### ISSUE THREAD

**Issue by Z-Diviner** [modelscope/swift#569]
您好，在微调deepseek-coder-33b-instruct时候出现以下问题：
![image](https://github.com/modelscope/swift/assets/130019806/81151989-9a81-410f-bf89-0b76c21518c8)
![image](https://github.com/modelscope/swift/assets/130019806/19503c29-beab-46ec-9a5e-a8ff268ee90e)
![image](https://github.com/modelscope/swift/assets/130019806/890439e5-678c-4548-b232-ebf3222679ce)
![image](https://github.com/modelscope/swift/assets/130019806/a16dec58-88a2-4c20-ab37-e847341a6a08)
下面是我启动的脚本：
![image](https://github.com/modelscope/swift/assets/130019806/37358a2f-350a-4c3a-aece-a86daaa6e5e9)

**Comment by Jintao-Huang** [comment]
pip install deepspeed -U 试试

**Comment by Z-Diviner** [comment]
> pip install deepspeed -U 试试

但是我已经安装了deepspeed库了，请问还是哪里可能出了问题？
![image](https://github.com/modelscope/swift/assets/130019806/9b122659-68a9-407c-b110-d09cb59e06f4)

**Comment by Jintao-Huang** [comment]
不知道 你看看 deepspeed的版本和cuda版本是否对应, 可以去deepspeed的issue中找找原因

**Comment by 1223243** [comment]
现在解决了吗
