### ISSUE TITLE
请问离线加载本地多模态的数据集代码改如何修改？数据集放到哪个目录下？

### ISSUE THREAD

**Issue by liuzhengzheng123** [modelscope/swift#57]

**Comment by Jintao-Huang** [comment]
这个都可以的, 你只需要定义一个get_*_dataset()的函数就好了, 数据集的位置随意的. 不过get_*_dataset()的函数需要有固定的返回接口, 可以参考其他数据集的定义(e.g. coco-en). 在`utils/dataset.py`文件中

**Comment by Jintao-Huang** [comment]
https://github.com/modelscope/swift/issues/111
建议通过注册的方式自定义
