### ISSUE TITLE
deepspeed不支持断点续训？

### ISSUE THREAD

**Issue by zodiacg** [modelscope/swift#574]
会提示 `ValueError: Can't find a valid checkpoint at XXXX` 错误。checkpoint的格式不支持deepspeed加载的意思？

库版本：
* swift: 1.7.2
* transformers 4.36.2
* deepspeed 0.12.6

**Comment by Jintao-Huang** [comment]
save_only_model 设置为False

**Comment by kratorado** [comment]
文档中对 save_only_model 这个参数的解释是，使用了 deepspeed 就设置成True，那就是只要用了deepspeed就不保存断点续训所需要的状态？

**Comment by NancyFyong** [comment]
你好，想请问下您最后解决了吗，我现在也遇到deepspeed lora不能断点续训的情况
