### ISSUE TITLE
chatglm3进行lora微调的时候报错

### ISSUE THREAD

**Issue by sjsj102323** [modelscope/swift#575]
之前可以运行，换一个服务器之后就发生报错。输出信息如下：
[INFO:swift] Model file configuration.json is different from the latest version `v1.0.2`,This is because you are using an older version or the file is updated manually.
/home/zyz/anaconda3/envs/uniem/lib/python3.10/site-packages/accelerate/accelerator.py:432: FutureWarning: Passing the following arguments to `Accelerator` is deprecated and will be removed in version 1.0 of Accelerate: dict_keys(['dispatch_batches', 'split_batches', 'even_batches', 'use_seedable_sampler']). Please pass an `accelerate.DataLoaderConfiguration` instead: 
dataloader_config = DataLoaderConfiguration(dispatch_batches=None, split_batches=False, even_batches=True, use_seedable_sampler=True)
  warnings.warn(
  0%|                                                                               | 0/618 [00:00<?, ?it/s]`use_cache=True` is incompatible with gradient checkpointing. Setting `use_cache=False`...
  0%|                                                                     | 1/618 [00:07<1:15:55,  7.38s/it]Traceback (most recent call last):
  File "/home/zyz/uniem/swift/examples/pytorch/llm/llm_sft.py", line 7, in <module>
    output = sft_main()
  File "/home/zyz/uniem/swift/swift/llm/utils/utils.py", line 199, in x_main
    return llm_x(args, **kwargs)
  File "/home/zyz/uniem/swift/swift/llm/sft.py", line 273, in llm_sft
    trainer.train(training_args.resume_from_checkpoint)
  File "/home/zyz/anaconda3/envs/uniem/lib/python3.10/site-packages/transformers/trainer.py", line 1624, in train
    return inner_training_loop(
  File "/home/zyz/anaconda3/envs/uniem/lib/python3.10/site-packages/transformers/trainer.py", line 2029, in _inner_training_loop
    self._maybe_log_save_evaluate(tr_loss, grad_norm, model, trial, epoch, ignore_keys_for_eval)
TypeError: SwiftMixin._maybe_log_save_evaluate() takes 6 positional arguments but 7 were given
  0%|                                                                     | 1/618 [00:07<1:18:09,  7.60s/it]
(uniem) zyz@aa-ESC8000-G4:~/uniem/swift/examples/pytorch/llm$

**Comment by Jintao-Huang** [comment]
pip install ms-swift[llm] -U

**Comment by sjsj102323** [comment]
> pip install ms-swift[llm] -U

在重新安装虚拟环境并只使用 pip install ms-swift[llm] -U安装swift还是出现类似的报错。报错信息如下：
[INFO:swift] Model file configuration.json is different from the latest version `v1.0.2`,This is because you are using an older version or the file is updated manually.
/home/zyz/anaconda3/envs/py311/lib/python3.11/site-packages/accelerate/accelerator.py:432: FutureWarning: Passing the following arguments to `Accelerator` is deprecated and will be removed in version 1.0 of Accelerate: dict_keys(['dispatch_batches', 'split_batches', 'even_batches', 'use_seedable_sampler']). Please pass an `accelerate.DataLoaderConfiguration` instead: 
dataloader_config = DataLoaderConfiguration(dispatch_batches=None, split_batches=False, even_batches=True, use_seedable_sampler=True)
  warnings.warn(
  0%|                                                                               | 0/618 [00:00<?, ?it/s]`use_cache=True` is incompatible with gradient checkpointing. Setting `use_cache=False`...
  0%|                                                                       | 1/618 [00:04<50:19,  4.89s/it]Traceback (most recent call last):
  File "/home/zyz/llm/swift/examples/pytorch/llm/llm_sft.py", line 7, in <module>
    output = sft_main()
             ^^^^^^^^^^
  File "/home/zyz/llm/swift/swift/llm/utils/utils.py", line 199, in x_main
    return llm_x(args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/zyz/llm/swift/swift/llm/sft.py", line 273, in llm_sft
    trainer.train(training_args.resume_from_checkpoint)
  File "/home/zyz/anaconda3/envs/py311/lib/python3.11/site-packages/transformers/trainer.py", line 1624, in train
    return inner_training_loop(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/zyz/anaconda3/envs/py311/lib/python3.11/site-packages/transformers/trainer.py", line 2029, in _inner_training_loop
    self._maybe_log_save_evaluate(tr_loss, grad_norm, model, trial, epoch, ignore_keys_for_eval)
TypeError: SwiftMixin._maybe_log_save_evaluate() takes 6 positional arguments but 7 were given
  0%|                                                                       | 1/618 [00:05<52:39,  5.12s/it]
(py311) zyz@aa-ESC8000-G4:~/llm/swift/examples/pytorch/llm$

**Comment by sjsj102323** [comment]
使用的脚本如下：
# Experimental environment: V100, A10, 3090
# 16GB GPU memory
PYTHONPATH=../../.. \
CUDA_VISIBLE_DEVICES=0 \
python llm_sft.py \
    --model_id_or_path ZhipuAI/chatglm3-6b \
    --model_cache_dir /home/zyz/.cache/modelscope/hub/ZhipuAI/chatglm3-6b\
    --model_revision master \
    --sft_type lora \
    --tuner_backend swift \
    --template_type chatglm3 \
    --dtype AUTO \
    --output_dir output \
    --dataset blossom-math-zh \
    --train_dataset_sample -1 \
    --num_train_epochs 1 \
    --max_length 2048 \
    --check_dataset_strategy warning \
    --lora_rank 8 \
    --lora_alpha 32 \
    --lora_dropout_p 0.05 \
    --lora_target_modules DEFAULT \
    --gradient_checkpointing true \
    --batch_size 1 \
    --weight_decay 0.01 \
    --learning_rate 1e-4 \
    --gradient_accumulation_steps 16 \
    --max_grad_norm 0.5 \
    --warmup_ratio 0.03 \
    --eval_steps 100 \
    --save_steps 100 \
    --save_total_limit 2 \
    --logging_steps 10 \

**Comment by Jintao-Huang** [comment]
将 PYTHONPATH=../../.. 去除
