### ISSUE TITLE
Mixtral-8*7-MOE模型微调error错误

### ISSUE THREAD

**Issue by WALLE-AI** [modelscope/swift#576]
# 2 * 60GB GPU memory
PYTHONPATH=../../.. \
CUDA_VISIBLE_DEVICES=0,1,2,3 \
python llm_sft.py \
    --model_id_or_path /data/models/Mixtral-8x7B-Instruct-v0.1 \
    --model_revision master \
    --model_type mixtral-moe-7b \
    --sft_type lora \
    --tuner_backend swift \
    --template_type AUTO \
    --dtype AUTO \
    --output_dir output_mixtral \
    --custom_train_dataset_path /data/datasets/agent/ms_agent/train_agent_react.jsonl  \
    --train_dataset_sample -1 \
    --num_train_epochs 1 \
    --max_length 2048 \
    --use_loss_scale true \
    --check_dataset_strategy warning \
    --lora_rank 8 \
    --lora_alpha 32 \
    --lora_dropout_p 0.05 \
    --lora_target_modules q_proj k_proj v_proj o_proj \
    --gradient_checkpointing false \
    --batch_size 1 \
    --weight_decay 0.01 \
    --learning_rate 1e-4 \
    --gradient_accumulation_steps 16 \
    --max_grad_norm 0.5 \
    --warmup_ratio 0.03 \
    --eval_steps 100 \
    --save_steps 100 \
    --save_total_limit 2 \
    --logging_steps 10 \
    --use_flash_attn false \
    --save_only_model true \

![image](https://github.com/modelscope/swift/assets/141505611/92ae71c0-a570-49f5-922f-a367eade9806)

**Comment by Jintao-Huang** [comment]
--model_type mixtral-moe-7b-instruct

**Comment by ninglonglong** [comment]
@Jintao-Huang  请问下这个模型可以支持专家并行的微调吗
