### ISSUE TITLE
使用qlora微调internlm_20b_chat/报错’AttributeError: eos_token_id‘

### ISSUE THREAD

**Issue by sjsj102323** [modelscope/swift#578]
出错信息：
Traceback (most recent call last):
  File "/home/zyz/llm/swift/examples/pytorch/llm/llm_sft.py", line 7, in <module>
    output = sft_main()
             ^^^^^^^^^^
  File "/home/zyz/llm/swift/swift/llm/utils/utils.py", line 199, in x_main
    return llm_x(args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/zyz/llm/swift/swift/llm/sft.py", line 56, in llm_sft
    model, tokenizer = get_model_tokenizer(args.model_type, args.torch_dtype,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zyz/llm/swift/swift/llm/utils/model.py", line 944, in get_model_tokenizer
    model, tokenizer = get_function(model_dir, torch_dtype, model_kwargs,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zyz/llm/swift/swift/llm/utils/model.py", line 303, in get_model_tokenizer_internlm
    del tokenizer.__class__.eos_token_id
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'InternLM2TokenizerFast' has no attribute 'eos_token_id'
(py311) zyz@aa-ESC8000-G4:~/llm/swift/examples/pytorch/llm$

**Comment by Jintao-Huang** [comment]
sh脚本发一下

**Comment by sjsj102323** [comment]
sh脚本如下：
```

# Experimental environment: A10
# 18GB GPU memory
PYTHONPATH=../../.. \
CUDA_VISIBLE_DEVICES=0 \
python llm_sft.py \
    --model_id_or_path Shanghai_AI_Laboratory/internlm-chat-20b \
    --model_cache_dir /home/zyz/.cache/modelscope/hub/Shanghai_AI_Laboratory/internlm2-chat-20b\
    --model_revision master \
    --sft_type lora \
    --tuner_backend swift \
    --template_type internlm \
    --dtype AUTO \
    --output_dir output \
    --dataset sql-create-context-en \
    --train_dataset_sample 20000 \
    --num_train_epochs 1 \
    --max_length 2048 \
    --check_dataset_strategy warning \
    --quantization_bit 4 \
    --bnb_4bit_comp_dtype AUTO \
    --lora_rank 8 \
    --lora_alpha 32 \
    --lora_dropout_p 0.05 \
    --lora_target_modules DEFAULT \
    --gradient_checkpointing true \
    --batch_size 1 \
    --weight_decay 0.01 \
    --learning_rate 1e-4 \
    --gradient_accumulation_steps 16 \
    --max_grad_norm 0.5 \
    --warmup_ratio 0.03 \
    --eval_steps 100 \
    --save_steps 100 \
    --save_total_limit 2 \
    --logging_steps 10 \
```

**Comment by Jintao-Huang** [comment]
# Experimental environment: A10
# 18GB GPU memory
CUDA_VISIBLE_DEVICES=0 \
swift sft \
    --model_id_or_path Shanghai_AI_Laboratory/internlm-chat-20b \
    --model_revision master \
    --sft_type lora \
    --tuner_backend swift \
    --template_type internlm \
    --dtype AUTO \
    --output_dir output \
    --dataset sql-create-context-en \
    --train_dataset_sample 20000 \
    --num_train_epochs 1 \
    --max_length 2048 \
    --check_dataset_strategy warning \
    --quantization_bit 4 \
    --bnb_4bit_comp_dtype AUTO \
    --lora_rank 8 \
    --lora_alpha 32 \
    --lora_dropout_p 0.05 \
    --lora_target_modules DEFAULT \
    --gradient_checkpointing true \
    --batch_size 1 \
    --weight_decay 0.01 \
    --learning_rate 1e-4 \
    --gradient_accumulation_steps 16 \
    --max_grad_norm 0.5 \
    --warmup_ratio 0.03 \
    --eval_steps 100 \
    --save_steps 100 \
    --save_total_limit 2 \
    --logging_steps 10 \

**Comment by Jintao-Huang** [comment]
我这么跑没问题啊, 你确认一下是否是最新的ms-swift版本
pip install ms-swift[llm]

然后确认一下下载的模型是chat模型

**Comment by sjsj102323** [comment]
好的，谢谢
