### ISSUE TITLE
微调qwen vl的时候，出现OOM

### ISSUE THREAD

**Issue by sunyrain** [modelscope/swift#581]
对所有linear含vision模型部分都进行微调，不知道为什么会先把一个GPU跑到OOM(3卡4090)
![image](https://github.com/modelscope/swift/assets/89635780/93459789-6681-43df-9c28-850f7dc148bc)
![image](https://github.com/modelscope/swift/assets/89635780/26cb5c79-b0c1-44c4-b2f4-db8be3c6192e)

**Comment by Jintao-Huang** [comment]
我猜测是qwen-vl的vision 部分不支持 gradient_checkpointing造成的

**Comment by sunyrain** [comment]
感谢回复，此外，切换到四卡后，出现了数据不在同一设备上的问题RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:2 and cuda:3! (when checking argument for argument mat2 in method wrapper_CUDA_mm)
启动脚本是CUDA_VISIBLE_DEVICES=0,1,2,3 swift sft \
    --model_type qwen-vl-chat --custom_train_dataset_path pic_data.json --lora_target_modules ALL --train_dataset_sample=-1

**Comment by Jintao-Huang** [comment]
这个是正常的, 建议换个模型.
