### ISSUE TITLE
Yi-VL-6B模型载入时提示Some weights of the model checkpoint were not used when initializing LlavaLlamaForCausalLM

### ISSUE THREAD

**Issue by deepmo24** [modelscope/swift#585]
如题，在载入Yi-VL模型进行推理时，提示这个是否是正常的？
![image](https://github.com/modelscope/swift/assets/19352002/6d1bb7f1-fa3f-462c-a87d-0d22f699bc83)

**Comment by Jintao-Huang** [comment]
正常的, 这步之后会load_vision_tower
