### ISSUE TITLE
使用webui训练完后进行推理部署，报错you need to merge lora

### ISSUE THREAD

**Issue by chuanSir123** [modelscope/swift#595]
训练采用的qalora模式

**Comment by chuanSir123** [comment]
使用lora模式训练的，在提示下加了--merge_lora true，部署还是报错int4 model is not supported

**Comment by Jintao-Huang** [comment]
是的 qlora是不支持merge的，你可以选择使用infer_backend='pt'的方式进行推理与部署

**Comment by chuanSir123** [comment]
> 是的 qlora是不支持merge的，你可以选择使用infer_backend='pt'的方式进行推理与部署

好的，多谢大佬解答，另外lora模式训练的推理部署会报错int4 model is not supported，是不支持int4当做基础模型去微调么

**Comment by Jintao-Huang** [comment]
是的 int4+lora 其实就是qlora啦. 在显存充足的情况下，建议训练完后量化，而不是量化着训练
