### ISSUE TITLE
汇报一个可能存在异常的细节，请校验一下

### ISSUE THREAD

**Issue by CairoLee** [modelscope/swift#598]
## 测试版本

- main 分支，散列：aec1dab74539d4f38aa1c71aacb5b18e1f9f1d39
- v1.7.0 版本，散列：0855df7c9d14cc22647756901b321cb477644c06

## 测试材料

- 使用代码安装的方式来安装 swift（而不是直接通过 `pip install ms-swift[llm] -U`）
- 使用 https://www.modelscope.cn/docs/Agent%E5%BE%AE%E8%B0%83%E6%9C%80%E4%BD%B3%E5%AE%9E%E8%B7%B5 提到的训练代码，如下所示：

```
# Experimental environment: A100
nproc_per_node=8

PYTHONPATH=../../.. \
torchrun \
    --nproc_per_node=$nproc_per_node \
    --master_port 29500 \
    llm_sft.py \
    --model_id_or_path qwen/Qwen-7B-Chat \
    --model_revision master \
    --sft_type lora \
    --tuner_backend swift \
    --dtype AUTO \
    --output_dir output \
    --dataset ms-agent \
    --train_dataset_mix_ratio 2.0 \
    --train_dataset_sample -1 \
    --num_train_epochs 2 \
    --max_length 2048 \
    --check_dataset_strategy warning \
    --lora_rank 8 \
    --lora_alpha 32 \
    --lora_dropout_p 0.05 \
    --lora_target_modules ALL \
    --self_cognition_sample 3000 \
    --model_name 卡卡罗特 \
    --model_author 陶白白 \
    --gradient_checkpointing true \
    --batch_size 2 \
    --weight_decay 0.01 \
    --learning_rate 5e-5 \
    --gradient_accumulation_steps $(expr 32 / $nproc_per_node) \
    --max_grad_norm 0.5 \
    --warmup_ratio 0.03 \
    --eval_steps 100 \
    --save_steps 100 \
    --save_total_limit 2 \
    --logging_steps 10
```

## 差异

- 使用 main 分支加载执行上述脚本，探索到的 step 是 506 个，耗时 20分钟
- 使用 v1.7.0 执行上述脚本，探索到的 step 是 2508 个，耗时 2小时以上

## 疑问

- 根据文档中的描述，我认为 v1.7.0 的结果应该更加正确，我不确定为什么 main 分支的 step 这么少
- 这中间可能会存在某些问题，毕竟差异太大了

## 猜测

在 main 分支中，我加载的数据集数量好像比较少：

```
train_dataset: Dataset({
    features: ['system', 'history', 'query', 'response'],
    num_rows: 16359
})
[INFO:swift] val_dataset: Dataset({
    features: ['system', 'history', 'query', 'response'],
    num_rows: 45
})
```

在 v1.7.0 版本中，我加载的数据量比较符合文档描述预期：

```
[INFO:swift] train_dataset: Dataset({
    features: ['system', 'history', 'query', 'response'],
    num_rows: 81216
})
[INFO:swift] val_dataset: Dataset({
    features: ['system', 'history', 'query', 'response'],
    num_rows: 264
})
```

可能是数据集的获取上存在某些问题，麻烦开发者有空留意一下哈~

**Comment by CairoLee** [comment]
[main分支执行日志.txt](https://github.com/modelscope/swift/files/14734240/main.txt)
[v1.7.0执行日志.txt](https://github.com/modelscope/swift/files/14734243/v1.7.0.txt)

备注：
在 1.7.0 版本中我为了排查问题，清空了缓存，所以数据集重新下载了一下

**Comment by Jintao-Huang** [comment]
好的 感谢 我看看

**Comment by Jintao-Huang** [comment]
[INFO:swift] train_dataset: Dataset({
    features: ['system', 'history', 'query', 'response'],
    num_rows: 92100
})
[INFO:swift] val_dataset: Dataset({
    features: ['system', 'history', 'query', 'response'],
    num_rows: 300
})
我这里main分支跑出来是这样的

**Comment by Jintao-Huang** [comment]
你检查试一下是否是当前最新的main分支代码
以及当前目录是否存在 ms-bench或者ms-agent的文件夹
