### ISSUE TITLE
生成结果|endoftext|后面很奇怪，不知道贼干啥

### ISSUE THREAD

**Issue by htw2012** [modelscope/swift#6]
![image](https://github.com/modelscope/swift/assets/2667700/09ecc5ef-a3b9-4980-ab6a-d82e13529daa)

**Comment by Jintao-Huang** [comment]
推理qwen-7b-chat可以参考: https://modelscope.cn/models/qwen/Qwen-7B-Chat/summary
examples/pytorch/llm目录下的llm_infer.py文件是推理llm_sft.py微调产生的模型的.

**Comment by Jintao-Huang** [comment]
哈咯, 我们排查了一下，是因为generate_config中没有增加eos_token_id造成的, 该bug已经修复啦 ~
