### ISSUE TITLE
有关MP DDP的疑问

### ISSUE THREAD

**Issue by sunyrain** [modelscope/swift#602]
命令行参数文件中说默认采样比例是0.01，我有一个大小为200k的数据集，4卡训练，NPROC_PER_NODE=2\ CUDA_VISIBLE_DEVICES=0,1,2,3 \那么模型验证的时候，验证的数量为1000是正常的吗？还是说1000并不代表1000条数据？谢谢
![image](https://github.com/modelscope/swift/assets/89635780/9d7c23f5-00da-4959-989c-9f0e79125400)

**Comment by Jintao-Huang** [comment]
设置 --train_dataset_sample -1

**Comment by sunyrain** [comment]
感谢答复，但是我已经设置了 --train_dataset_sample -1，否则总进度条大约在1250左右，谢谢。我怀疑是ddp造成的？是不是他只在一个节点上抽取了0.01的数据进行验证？
