### ISSUE TITLE
swift infer/deploy --model_type mistral-7b-v2  --model_id_or_path /data/models/Mistral-7B-v0.2-hf

### ISSUE THREAD

**Issue by WALLE-AI** [modelscope/swift#609]
**Describe the bug**
 使用 swift infer/deploy --model_type mistral-7b-v2  --model_id_or_path /data/models/Mistral-7B-v0.2-hf   --eval_human true --ckpt_dir /data/swift-main/examples/pytorch/llm/output_mistral_v2/mistral-7b-v2/v0-20240325-225702/checkpoint-8 --merge_lora true --stop_words Observation: --infer_backend pt
![image](https://github.com/modelscope/swift/assets/141505611/d996190c-4e63-48a5-95cf-b933b5886737)

看你commit中infer和deploy这块的代码应该不全吧

**Comment by Jintao-Huang** [comment]
pip install -e .[llm]
使用main分支就好了
