### ISSUE TITLE
使用ms-agent微调得agent模型部署时如何处理一个问题需调用多个工具串行完成得情况？

### ISSUE THREAD

**Issue by evyy1234** [modelscope/swift#612]
看文档部分时客户端每次询问一个问题，调用一个工具完成回答，如果客户端得一个问题需要多个工具联合处理，这种情况该如何部署模型呢？

**Comment by tastelikefeet** [comment]
1. 数据集中要有多个工具联用的case
2. 我们在结合modelscope-agent框架，预计下月初可以将swift训练的ckpt用于modelscopeagent中

**Comment by tastelikefeet** [comment]
已经结合modelscope-agent框架，可以查看: https://github.com/modelscope/swift/blob/main/docs/source/LLM/Agent%E5%BE%AE%E8%B0%83%E6%9C%80%E4%BD%B3%E5%AE%9E%E8%B7%B5.md
