### ISSUE TITLE
【关于训练与微调】我想知道不同的训练说明之间的区别

### ISSUE THREAD

**Issue by zzisbeauty** [modelscope/swift#617]
仔细看了项目，初步有一个疑问请教老师

【第一部分】
- 项目首页 readme：https://github.com/modelscope/swift/blob/main/README_CN.md  有很多微调的脚本
- 微调文档页面：https://github.com/modelscope/swift/blob/main/docs/source/LLM/LLM%E5%BE%AE%E8%B0%83%E6%96%87%E6%A1%A3.md#merge-lora 也有很多微调的脚本

我没有看懂这些脚本之间有什么区别啊。

【我的需求是这样的 - 需求说明】

我已经基于其他方案微调了一个GLM3-32k的模型，但是推理速度过慢（因为我的sft的上下文很长，prompt有 5-6k字，生成的大概也有1k字的样子吧。A100推理的话7-20s都是会出现，所以太慢了）。因此为了提升推理速度找到了swift，我想的是我基于swift再次对glm3-32k进行训练，然后想训练完后量化，以提升模型的推理速度。

【我的理解】
请问老师我的上述目标应该怎么实现呢？ 我不太懂很多技术细节，因此我想请教老师的是：
1. 我有一张A100的卡；
2. 我是不是可以先执行lora微调，如果是，那我就有上述【第一部分】的疑问；
3. 我是不是应该在lora之后，再执行量化：https://github.com/modelscope/swift/blob/main/docs/source/LLM/LLM%E9%87%8F%E5%8C%96%E6%96%87%E6%A1%A3.md#%E5%BE%AE%E8%B0%83%E5%90%8E%E6%A8%A1%E5%9E%8B
4. 最后再执行推理加速：https://github.com/modelscope/swift/blob/main/docs/source/LLM/VLLM%E6%8E%A8%E7%90%86%E5%8A%A0%E9%80%9F%E4%B8%8E%E9%83%A8%E7%BD%B2.md  。 比如我正在使用的glm3 我看到不支持 Flash Attn，我是不是就只能使用基于vllm的模型推理加速。
5. 最后还想确认的是，基于我在【需求说明】部分说的实际情况，就是推理时间过长，请问老师swift的上述过程有助于解决我的问题吗？

**最后，感谢老师，期待得到老师的答复！**

**Comment by tastelikefeet** [comment]
1. 可以先lora微调，README的和文档中的只是配置的参数不一样，而参数可以根据自己的需求进行配置
2. 量化会引起模型效果变差，建议使用vllm看下是否满足推理速度，如果非要用量化，可以在训练后量化，并建议使用awq
3. swift提供的是训练推理部署一站式解决方案框架，可以用我们的框架尝试训练和提升推理速度。如果有其他疑问，请参考README中的二维码进群答疑

**Comment by zzisbeauty** [comment]
> Collaborator

感谢老师的答复。 麻烦这个issue**先不要**closed。

感恩！

**Comment by xiaolvtongxue-zt** [comment]
> 1. 可以先lora微调，README的和文档中的只是配置的参数不一样，而参数可以根据自己的需求进行配置
> 2. 量化会引起模型效果变差，建议使用vllm看下是否满足推理速度，如果非要用量化，可以在训练后量化，并建议使用awq
> 3. swift提供的是训练推理部署一站式解决方案框架，可以用我们的框架尝试训练和提升推理速度。如果有其他疑问，请参考README中的二维码进群答疑

你好，这里的【2. 量化会引起模型效果变差，】应该是指训练后再进行量化会变差（所以推荐使用awq），如果一开始就是使用量化训练的话，这种情况应该也降低很多吧？

**Comment by zzisbeauty** [comment]
老师您好：

- 我现在想要merge一下我lora训练得到的模型；
- 我在微调文档中看到的merge脚本是https://github.com/modelscope/swift/blob/main/docs/source/LLM/LLM%E5%BE%AE%E8%B0%83%E6%96%87%E6%A1%A3.md#merge-lora    但是这个方法我没看懂
- 我又在 issue 中看到有人使用的merge命令：https://github.com/modelscope/swift/issues/525
```
合并脚本：swift merge-lora --model_id_or_path qwen/Qwen-1_8B-Chat --ckpt_dir 路径/checkpoint-62000 --merge_lora True
```

我想请问老师的是，为什么微调文档的merge命令和issue中的完全不一样，我甚至都看不懂微调文档的merge命令是在如何执行的。

其实swift是个好的项目，但是文档写的对于新手并不清晰，很混乱，可能是我太菜了。
希望得到老师的答复。
