### ISSUE TITLE
请问qwen-vl模型full微调OOM

### ISSUE THREAD

**Issue by DexterGuo** [modelscope/swift#62]
环境：8*A100-80G

微调方法：
1、直接full模式，OOM
2、deepspeed+freeze visual+finetune LLM，能跑起来
问题：finetune visual + freeze LLM，报错OOM，看了一圈visual的代码，没发现啥问题？希望大佬解答下。

**Comment by Jintao-Huang** [comment]
qwen-vl的全参数的ddp脚本已经书写:
https://github.com/modelscope/swift/tree/main/examples/pytorch/llm/scripts/qwen_vl_chat/full_mp_ddp

qwen-audio的全参数的ddp也可以参考: 
https://github.com/modelscope/swift/tree/main/examples/pytorch/llm/scripts/qwen_audio_chat/full_mp_ddp
