### ISSUE TITLE
是否可以微调llava 1.6 34B

### ISSUE THREAD

**Issue by Mr-Loevan** [modelscope/swift#632]
**Describe the feature**
Please describe the feature requested here(请在这里描述需求)

**Paste any useful information**
Paste any useful information, including papers, github links, etc.(请在这里描述其他有用的信息，比如相关的论文地址，github链接等)

**Additional context**
Add any other context or information here(其他信息可以写在这里)

**Comment by hjh0119** [comment]
近期会接入

**Comment by FoolishMao** [comment]
插眼

**Comment by hjh0119** [comment]
现已支持 请拉取最新代码

**Comment by Mr-Loevan** [comment]
> 现已支持 请拉取最新代码
在微调34b时，使用custom的数据集，batchsize超过1就会报错。
template.py中的res['images'] = torch.concat([b['images'] for b in batch])这一行代码
RuntimeError: Sizes of tensors must match except in dimension 0. Expected size 5 but got size 3 for tensor number 1 in the list.

**Comment by hjh0119** [comment]
> 在微调34b时，使用custom的数据集，batchsize超过1就会报错。

用支持的数据集有这个问题吗
