### ISSUE TITLE
ImportError: cannot import name 'get_vllm_engine' from 'swift.llm'

### ISSUE THREAD

**Issue by lvjianxin** [modelscope/swift#637]
Traceback (most recent call last):
  File "/home/admin/workspace/aop_lab/app_source/app.py", line 5, in <module>
    from swift.llm import (
ImportError: cannot import name 'get_vllm_engine' from 'swift.llm' (/home/admin/miniconda3/lib/python3.10/site-packages/swift/llm/__init__.py)

我的requirements.txt是：ms-swift[llm] @ git+https://github.com/modelscope/swift@v1.6.0

**Comment by Jintao-Huang** [comment]
安装一下 vllm
