### ISSUE TITLE
【为什么显存变化会这么剧烈】关于Lora微调的实现

### ISSUE THREAD

**Issue by zzisbeauty** [modelscope/swift#642]
**Your hardware and system info**

- cuda-11.8
- 单张A100
- Ubuntu
- 容器中运行，使用的是项目自带的镜像启动的容器

**Describe the bug**

- chatglm3-32k model
- 自己的数据集，不到9000条的指令单论对话；
- prompt 很长：每一条数据都是 5 - 6 k字；
- 生成也很长，生成的也在 2k字左右

【训练使用的配置信息如下】

```
import os
os.environ['CUDA_VISIBLE_DEVICES'] = '0'
proPath = os.getcwd()
import torch
from swift.llm import DatasetName, InferArguments, ModelType, SftArguments, infer_main, sft_main, app_ui_main, merge_lora
batch_size = 1
max_length = 10000
predict_with_generate = True # 评估时的batch_size, 默认为None, 即当predict_with_generate为True时, 设置为1, 为False时, 设置为batch_size
if predict_with_generate:
    eval_batch_size = 1
    max_new_tokens = 5000  # 当 predict_with_generate = True 时生效 
else:
    eval_batch_size = batch_size
max_steps = -1  # 训练的max_steps数, 默认为-1. 如果max_steps >= 0, 则覆盖num_train_epochs
num_train_epochs = 10
if max_steps <= 0:
    num_train_epochs = num_train_epochs
# low  gpu
sft_type = 'lora'
# deepspeed='default-zero2'
# deepspeed = os.path.join(proPath, 'swift/llm/ds_config/zero2.json')
# deepspeed = os.path.join(proPath, 'swift/llm/ds_config/zero2.json')
# lora_target_modules=['ALL', 'EMBEDDING'] # ['DEFAULT']
lora_target_modules=['DEFAULT'] # ['DEFAULT']
# 模型和训练参数
sft_args = SftArguments(
    # low gpu
    sft_type=sft_type,
    # deepspeed=deepspeed,
    lora_target_modules=lora_target_modules,
    # model and train action
    model_type='chatglm3-6b-32k',
    model_id_or_path = os.path.join(proPath, 'chatglm3_6b_32k'),
    batch_size=batch_size,
    max_length=max_length,
    max_new_tokens=max_new_tokens,
    eval_batch_size=eval_batch_size,
    max_steps=max_steps,
    num_train_epochs=num_train_epochs,
    # dataset
    train_dataset_sample=-1, # 对训练集的采样数, 默认是-1, 即使用完整的训练集进行训练.
    dataset=[],
    # dataset=[DatasetName.blossom_math_zh],
    custom_train_dataset_path = os.path.join(proPath, 'datasets/giikin_jsonl_data/chatml.jsonl'),
    output_dir='output'
)
result = sft_main(sft_args) # 先进入 run_utils，接下来才会真正进入 sft （即 start run sft）
best_model_checkpoint = result['best_model_checkpoint']
print(f'best_model_checkpoint: {best_model_checkpoint}')
torch.cuda.empty_cache()
print('SFT结束')
```

- 在训练的最开始阶段，模型直接把A100显存拉满：总共80G的显存占用到 79G上下，就是A100刚好跑起来；
- 然后过了一会我再看显存占用，如下图，显存只占用了50G的样子：

![image](https://github.com/modelscope/swift/assets/137602905/4d9b61a5-d50c-44ce-ba6c-d4e7d466d5a2)

- 在我发现显存明显降低时，看到训练进度在 2% 左右，如下图：
- 使用的是  epochs =5 而不是 steps，且 lora 模型层也配置的是 DEFAULT，没有其他 embedding 层的微调；

![image](https://github.com/modelscope/swift/assets/137602905/ce5c5acd-32e8-4462-983f-ebee8a8b6f35)

【**因此想请问，为什么这个显存会这样子变化。变化的这么剧烈？？？**】

**Additional context**

**期待得到老师的答复。**
感恩 ！

**Comment by vivixx1** [comment]
感觉是正常的吧，测试结果如何？我印象中多卡跑qwen72b，总共也会空余个几十gb出来

**Comment by zzisbeauty** [comment]
> 感觉是正常的吧，测试结果如何？我印象中多卡跑qwen72b，总共也会空余个几十gb出来

在公司电脑，下午跑起来的，下班回来，还没看结果。 

这个现存不正常吧我觉得

- 首先这是一个 6b 的模型，一个 lora 在最开始阶段能把一张A100跑完我就很匪夷所思
- 其次开始训练一段时间后，现存就落到三分之二，为什么会有这么大的差别。

不知道上面的两点是为什么。

**Comment by Jintao-Huang** [comment]
https://github.com/modelscope/swift/blob/main/docs/source/LLM/Benchmark.md#model-type--max-length

可以查看这里显存的benchmark

**Comment by zzisbeauty** [comment]
> https://github.com/modelscope/swift/blob/main/docs/source/LLM/Benchmark.md#model-type--max-length
> 
> 可以查看这里显存的benchmark

感谢回复。

我看了评测，再介绍一下我的i情况：

1. 我这个在训练过程中（就是过了训练最开始的一小会）， 显存维持的情况如下图差不多

![image](https://github.com/modelscope/swift/assets/137602905/f5e3adea-9eb8-4201-aed8-ed2236303e61)

2. **但是最开始的时候模型是跑满状态。不知道为什么。**

3. 然后我今天早上来看程序，我发现先程序显存又到了将近拉满的程度，如下图，**一个6b-lora，能占用这么大的显存吗？**

![image](https://github.com/modelscope/swift/assets/137602905/86b875e2-d6ea-4be4-95c9-8c5de0e384f6)

4. **我的数据的长度确实长，但是都很均匀，不存在哪一条很短，哪一条很长的情况。 为什么显存波动会这么剧烈。**

5. **还有就是评测在测试速度，是按照 samples/s 统计的，请问这个 samples/s 是怎么统计出来的呢？**


【我很费解】

**Comment by vivixx1** [comment]
> > 感觉是正常的吧，测试结果如何？我印象中多卡跑qwen72b，总共也会空余个几十gb出来
> 
> 在公司电脑，下午跑起来的，下班回来，还没看结果。
> 
> 这个显存不正常吧我觉得
> 
> * 首先这是一个 6b 的模型，一个 lora 在最开始阶段能把一张A100跑完我就很匪夷所思
> * 其次开始训练一段时间后，现存就落到三分之二，为什么会有这么大的差别。
> 
> 不知道上面的两点是为什么。

第一点是正常的，就是会把能用的显存都用上

**Comment by Jintao-Huang** [comment]
<img width="583" alt="截屏2024-04-02 17 46 22" src="https://github.com/modelscope/swift/assets/45290347/070a81b8-adb2-40d4-9bd0-a8bb8b08178c">

**Comment by zzisbeauty** [comment]
> <img alt="截屏2024-04-02 17 46 22" width="583" src="https://private-user-images.githubusercontent.com/45290347/318727163-070a81b8-adb2-40d4-9bd0-a8bb8b08178c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwNTE1MzcsIm5iZiI6MTcxMjA1MTIzNywicGF0aCI6Ii80NTI5MDM0Ny8zMTg3MjcxNjMtMDcwYTgxYjgtYWRiMi00MGQ0LTliZDAtYThiYjhiMDgxNzhjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAyVDA5NDcxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJmMGM0OTVmMjZmYTVkMzZmYTFmNTMwYWU2YTFlYmFhZmRiZmY5NmYzYWQ5Nzk3MjY5ZGJhOTBjMGM3M2YyMDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lXehXFzcY0Tamzf4X-L0bo2Ddv7EhV48C18YKBIX2U4">

其实老师你这个截图没有解决我的问题。 但是算了。 要是这个问题真要刨根问底可能很难到头。

另外我想说的是，其实 swift 确实很好。我虽然拉取了镜像，但是我只是想用容器的环境。

我没有用容器中安装好的 swift 程序，我是用源码跑的我的任务，但是总是觉得用起来怪怪的，尤其是第一眼用起来的时候。

我说不上哪里不对。虽然swift很好，但是不是那么容易上手。
