### ISSUE TITLE
训练用 web-ui 有两组重复的设置项目，只有一组有效

### ISSUE THREAD

**Issue by CairoLee** [modelscope/swift#644]
**Describe the bug**

当我启用 web-ui 之后，可以看到如下图所示的两组设置项，只有第二组的 ddp 勾选后有效果

<img width="1643" alt="image" src="https://github.com/modelscope/swift/assets/4458917/08ed2d23-faae-4e70-bf89-2b4af2fb7f1b">

**Your hardware and system info**

- Hash:033809f92f7bfa22f25bdbcd2346de031f08c348
- GPU: NVIDIA-A100 x 8
- CUDA: 12.1
- Ubuntu 22.04 + Python3.10

**Comment by tastelikefeet** [comment]
已知bug，今天会修复

**Comment by CairoLee** [comment]
好的，感谢！

**Comment by CairoLee** [comment]
确认最新版本中已经被修正，关闭此问题
