### ISSUE TITLE
期望增加自动识别原模型路径

### ISSUE THREAD

**Issue by xx-Jiangwen** [modelscope/swift#656]
**Describe the feature**
现有推理机制是从魔搭缓存路径去加载下载好的模型，再加载用户训练好的。但用户一般会自己缓存模型至本地，因此不应该再去魔搭下载模型了

**Paste any useful information**
Paste any useful information, including papers, github links, etc.(请在这里描述其他有用的信息，比如相关的论文地址，github链接等)

**Additional context**
Add any other context or information here(其他信息可以写在这里)

**Comment by rcejzibjks38** [comment]
你们，目前是否能通过命令行参数指定路径的方式指定已经下载到本地的大模型权重呢？

**Comment by tastelikefeet** [comment]
Supported，拉下最新的代码

**Comment by tastelikefeet** [comment]
> Reference

可以的，--model_id_or_path
