### ISSUE TITLE
No module named swift.llm

### ISSUE THREAD

**Issue by duisuangsheng** [modelscope/swift#657]
After install "ms-swift[llm]", executing lora sft training, this error occurred (No module named swift.llm)
But there is nothing wrong with importing directly. Why is this happening and how should I fix it?
![20240403-181856](https://github.com/modelscope/swift/assets/150005647/72748ad1-1236-4e3d-9708-89796500c0ed)

lora sft training command:
CUDA_VISIBLE_DEVICES=0 swift sft --model_type deepseek-vl-7b-chat --dataset coco-mini-en-2

**Comment by cchowc** [comment]
hi，I am facing the same issue, how did you fix it?

**Comment by Jintao-Huang** [comment]
Please install ms-swift using the command: `pip install ms-swift[llm] -U`.
