### ISSUE TITLE
swift web-ui启动后访问UI渲染bug

### ISSUE THREAD

**Issue by LeonG7** [modelscope/swift#658]
**Describe the bug**
What the bug is, and how to reproduce, better with screenshots(描述bug以及复现过程，最好有截图)
使用官方提供的docker : registry.cn-hangzhou.aliyuncs.com/modelscope-repo/modelscope:ubuntu22.04-cuda12.1.0-py310-torch2.1.2-tf2.14.0-1.13.1
通过命令swift web-ui启动后，访问页面渲染有问题，没有框框。

**Your hardware and system info**
Write your system info like CUDA version/system/GPU/torch version here(在这里给出硬件信息和系统信息，如CUDA版本，系统，GPU型号和torch版本等)

**Additional context**
Add any other context about the problem here(在这里补充其他信息)
![Snipaste_2024-04-03_18-51-12](https://github.com/modelscope/swift/assets/35190237/03015818-2d93-484e-b6a3-f23b7ccaa3dc)

**Comment by tastelikefeet** [comment]
如果是vscode启动，尝试去掉http链接中的'ide'部分，如果不是，尝试使用gradio==3.50.2版本

**Comment by XiaoCC** [comment]
请问一下怎么通过docker容器来使用swift  官方文档只提供了一个pull 没有任何详细说明，能不能说下怎么具体使用这个镜像来创建容器，需要映射什么端口   绑定什么目录   执行什么命令
