### ISSUE TITLE
希望有Hugging Face 数据集直接支持

### ISSUE THREAD

**Issue by WSC741606** [modelscope/swift#661]
**Describe the feature**
希望能从HuggingFace直接加载数据集，而不是需要手动下载再指定

**Paste any useful information**
如https://huggingface.co/datasets/m-a-p/COIG-CQIA

**Comment by tastelikefeet** [comment]
下个迭代（四月）会支持hf模型和数据集

**Comment by WSC741606** [comment]
好嘞，期待尽快看到swift2.0~
