### ISSUE TITLE
训练过程无法使用GPU

### ISSUE THREAD

**Issue by qiuxuezhe123** [modelscope/swift#664]
显卡类型：A800
训练脚本如下
PYTHONPATH=../../.. \
CUDA_VISIBLE_DEVICES=2 \
python llm_sft.py \
    --model_type qwen-14b-chat \
    --model_id_or_path /work/LLM_project/LLaMA-Factory-main/Qwen-14B-Chat \
    --sft_type lora \
    --tuner_backend swift \
    --dtype AUTO \
    --output_dir output \
    --dataset data/pt_data_shuf_train_tmp_v2.jsonl \
    --train_dataset_sample -1 \
    --num_train_epochs 1 \
    --max_length 2048 \
    --check_dataset_strategy warning \
    --lora_rank 8 \
    --lora_alpha 16 \
    --lora_dropout_p 0.05 \
    --lora_target_modules ALL \
    --gradient_checkpointing true \
    --batch_size 1 \
    --weight_decay 0.1 \
    --learning_rate 1e-4 \
    --gradient_accumulation_steps 16 \
    --max_grad_norm 0.5 \
    --warmup_ratio 0.03 \
    --eval_steps 1000 \
    --save_steps 1000 \
    --save_total_limit 2 \
    --logging_steps 10 \
    --use_flash_attn false

**Comment by qiuxuezhe123** [comment]
已解决

**Comment by zouyubin** [comment]
请问如何解决的，我也有这个问题
