### ISSUE TITLE
DPO ref_model不支持本地路径

### ISSUE THREAD

**Issue by LeonG7** [modelscope/swift#666]
**Describe the bug**
What the bug is, and how to reproduce, better with screenshots(描述bug以及复现过程，最好有截图)
我想在qwen15-14b-chat微调后的模型上进行DPO训练
调用脚本  llm_dpo.py
通过model_id_or_path指定了local_sft_model，但是ref_model没法指定本地模型，当ref_model_type指定相同的模型类型qwen1half-14b-chat时，脚本会自动从官网下载模型，但我希望进行离线训练不要联网下载模型，想问一下ref_model可以指定本地路径吗，或者和model_id_or_path指定的模型一致。

**Your hardware and system info**
Write your system info like CUDA version/system/GPU/torch version here(在这里给出硬件信息和系统信息，如CUDA版本，系统，GPU型号和torch版本等)

**Additional context**
Add any other context about the problem here(在这里补充其他信息)

**Comment by gaojing8500** [comment]
相同问题 dpo ref model并没有注册在配置文件中

**Comment by waltonfuture** [comment]
cy 相同问题，等待解答

**Comment by tastelikefeet** [comment]
Supported, 拉下最新代码
