### ISSUE TITLE
用自己的数据集，使用shell脚本训练报错

### ISSUE THREAD

**Issue by yxq9710** [modelscope/swift#672]
当前swift版本为1.7.3，accelerate版本为0.29.1。
运行脚本为
CUDA_VISIBLE_DEVICES=0 \
swift sft \
    --model_type 'chatglm2-6b' \
    --custom_train_dataset_path '../llm_datas/train.json' \
    --num_train_epochs 5 \
    --sft_type 'lora'  \
    --output_dir 'output' \
    --per_device_train_batch_size 2 \
  报错信息为：
  from swift.llm import sft_main
ImportError: No module named swift.llm
一开始swift版本为1.6.1，参考之前的issue，将swift升级到1.7.3，还是报错了

**Comment by hjh0119** [comment]
which swift看看

**Comment by yxq9710** [comment]
您好，which swift的结果是：
.pylib/bin/swift
是一个文件

**Comment by yxq9710** [comment]
> which swift看看
您好，which swift的结果是：
.pylib/bin/swift
是一个文件

**Comment by hjh0119** [comment]
> 您好，which swift的结果是： .pylib/bin/swift 是一个文件
如果使用的是虚拟环境，确保先激活。
试下 pip install ms-swift[llm] -U

**Comment by hjh0119** [comment]
> 使用的就是当前环境，然后一开始安装过swift的

请提供下安装环境的指令
尝试以下方式重装环境
```bash
conda create -n my_env python==3.9
conda activate my_env
git clone https://github.com/modelscope/swift.git
cd swift
pip install -e .[all]
```
