### ISSUE TITLE
报错提示 swift 未找到命令

### ISSUE THREAD

**Issue by Liudong-FITC** [modelscope/swift#679]
想请教下老师，对模型进行merged和量化

CUDA_VISIBLE_DEVICES=0 swift export \
    --ckpt_dir 'xxx' \
    --merge_lora true --quant_bits 4

报错提示 swift：未找到命令  这种怎么解决呢

**Comment by hjh0119** [comment]
```
export PYTHONPATH = /path/to/swift
```

**Comment by Liudong-FITC** [comment]
试了上面的方法，并没有解决问题，能再解释一下吗

**Comment by hjh0119** [comment]
> 试了上面的方法，并没有解决问题，能再解释一下吗

参考[文档](https://github.com/modelscope/swift/blob/main/docs/source/GetStarted/SWIFT%E5%AE%89%E8%A3%85.md)安装环境

如果安装后仍然报错，手动设置swift路径，将下面`/path/to/swift`改为本地的swift路径
```bash
export PYTHONPATH = /path/to/swift
```

**Comment by tastelikefeet** [comment]
尝试pip install ms-swift[llm]或者clone repo后pip insstall . 如果还是不行，尝试检查下自己的环境变量是否有冲突
