### ISSUE TITLE
希望可以添加Chinese-LLaMA-Alpaca-2 模型微调的支持

### ISSUE THREAD

**Issue by jackyangjie** [modelscope/swift#680]
**Describe the feature**
Please describe the feature requested here(请在这里描述需求)

**Paste any useful information**
Paste any useful information, including papers, github links, etc.(请在这里描述其他有用的信息，比如相关的论文地址，github链接等)
https://github.com/ymcui/Chinese-LLaMA-Alpaca-2

**Additional context**
Add any other context or information here(其他信息可以写在这里)

**Comment by hjh0119** [comment]
done 
https://github.com/modelscope/swift/pull/763
