### ISSUE TITLE
数据预处理的并行希望能逐个文件并行

### ISSUE THREAD

**Issue by WSC741606** [modelscope/swift#682]
**Describe the feature**
preprocess_num_proc参数控制的预处理过程，在提供多个数据集的时候，希望能可以在并行的时候一次加载一个数据集或者数据集的一部分去处理，而不是同时全加载进去，太吃内存了

**Paste any useful information**
比如一个csv文件有20k行，有10个这种文件开8进程并行，那每次加载一个文件在主进程，切分一个进程2.5k行，处理完再加载下一个文件
现在几百MToken的处理两个进程就吃了快800G内存，太多了

**Comment by Jintao-Huang** [comment]
可以试试`--lazy_tokenize` 参数

**Comment by WSC741606** [comment]
纯文本的LLM，加上--lazy_tokenize不会影响训练速度吗？感觉本来GPU就吃不满，再在流水线里面插入这个还不如开始的时候单线程做的样子

**Comment by WSC741606** [comment]
好的，我试试，感谢大佬~

**Comment by WSC741606** [comment]
啊，前面忘了回来回复了_(:з」∠)_
切换成训练中tokenize后，内存峰值从700+GB降低到了100GB不到，训练速度提升了1/3，就离谱
这个是在相同的环境和Swift版本下测试的 模型是llama3-8B
