### ISSUE TITLE
raise HTTPError('Response details: %s' % message) from error

### ISSUE THREAD

**Issue by Fasuiker** [modelscope/swift#69]
requests.exceptions.HTTPError: Response details: {'Code': 10010200001, 'Message': '获取模型版本失败，信息：获取模失败', 'RequestId': '0cd0246f-b2da-48c0-accf-4095da6b30a6', 'Success': False}

**Comment by Jintao-Huang** [comment]
什么模型呀, 你换个模型试试呗

**Comment by Fasuiker** [comment]
通义千问，换了llm倒是可以了，不知道具体什么问题呢

**Comment by Fasuiker** [comment]
通义千问，换了llama没问题了，不知道什么问题

**Comment by DTliudong** [comment]
遇到了同样的问题，哭了。

**Comment by Xu-Chen** [comment]
@Jintao-Huang 好像千问，在 hf 和 魔塔都搜不到了

**Comment by evanguard** [comment]
像是模型版本都找不到了。。。
