### ISSUE TITLE
关于Grok-1的tokenizer

### ISSUE THREAD

**Issue by Di-Zayn** [modelscope/swift#693]
我看到grok-1的微调说明中提到项目团队“额外准备了符合transformers标准的tokenizer”。请问它与原生的grok-1 tokenizer有什么不同呢？

**Comment by tastelikefeet** [comment]
使用transformers库的接口对原生tokenizer进行了封装。之所以这么做是因为原模型repo没有符合该接口的tokenizer：https://www.modelscope.cn/models/colossalai/grok-1-pytorch/files
