### ISSUE TITLE
是否支持一次Lora的基础上再次Lora

### ISSUE THREAD

**Issue by todayplusplus** [modelscope/swift#696]
我当前的任务准备分**多个阶段**注入数据，每个阶段都准备使用lora进行微调,
> 我正在使用的是Qwen-VL-Chat

想请教下，对于原始模型M, 是否可以在第一阶段使用lora，并进行合并，得到合并后的模型M_1。
在第二阶段，能否在M_1的基础上再次注入新的数据进行lora，得到模型M_2?

**Comment by kratorado** [comment]
qwen-vl没试过，chat模型可以，设置好参数 --model_id_or_path 为你合并后的模型，--model_type 为你的基础模型的model_type
