### ISSUE TITLE
swift deploy 传参可以加上部署的端口号吗？

### ISSUE THREAD

**Issue by HJT9328** [modelscope/swift#700]
**Describe the feature**
Please describe the feature requested here(请在这里描述需求)

**Paste any useful information**
Paste any useful information, including papers, github links, etc.(请在这里描述其他有用的信息，比如相关的论文地址，github链接等)

**Additional context**
Add any other context or information here(其他信息可以写在这里)

**Comment by JasonGuo1** [comment]
是的

**Comment by HJT9328** [comment]
> https://github.com/modelscope/swift/blob/main/docs/source/LLM/%E5%91%BD%E4%BB%A4%E8%A1%8C%E5%8F%82%E6%95%B0.md#deploy-%E5%8F%82%E6%95%B0

thanks！

**Comment by JasonGuo1** [comment]
谢谢
