### ISSUE TITLE
lora_ft多模态chat时不支持png格式的灰度图输入，抛出维度错误，

### ISSUE THREAD

**Issue by hardlipay** [modelscope/swift#701]
**Describe the bug**
RuntimeError: output with shape [1, 210, 446] doesn't match the broadcast shape [3, 210, 446]

**Your hardware and system info**
CUDA11.8 pytorch2.2 A100-40g

**Additional context**
暂时尝试数据全转rgb格式，希望后期添加遇到单通道灰度图处理的函数

**Comment by Jintao-Huang** [comment]
可以提供复现的脚本嘛

哪一个模型呢

**Comment by hardlipay** [comment]
> 可以提供复现的脚本嘛
> 
> 哪一个模型呢

https://github.com/modelscope/swift/blob/main/docs/source/Multi-Modal/minicpm-v%E6%9C%80%E4%BD%B3%E5%AE%9E%E8%B7%B5.md#%E5%BE%AE%E8%B0%83

脚本只指定了一些其他参数，数据集：https://huggingface.co/datasets/BAAI/CMMU/tree/main

**Comment by Jintao-Huang** [comment]
已经修复了
