### ISSUE TITLE
微调多模态模型的时候，如何设置是否训练vision encoder

### ISSUE THREAD

**Issue by ultrazhl98** [modelscope/swift#705]
请问使用swift微调多模态模型的时候，在哪里设置vision encoder是否参与训练

**Comment by Jintao-Huang** [comment]
--lora_target_modules ALL

**Comment by Jintao-Huang** [comment]
可以参考我们的多模态最佳实践，那里有标注是否支持全参数和vision encoder

**Comment by Jintao-Huang** [comment]
多模态最佳实践：https://github.com/modelscope/swift/blob/main/docs/source/Multi-Modal/index.md

**Comment by ultrazhl98** [comment]
谢谢回复，如果采用全参数微调时，可以设置vision encoder是否参与训练吗，我看lora_target_modules设置的是采用lora的模块

**Comment by Jintao-Huang** [comment]
全参数 就都参与训练了

**Comment by ultrazhl98** [comment]
如果只想全参数训练llm，不训练vision encoder呢？

**Comment by Jintao-Huang** [comment]
`--freeze_parameters 1 --additional_trainable_parameters <你想训练的层>`

https://github.com/modelscope/swift/blob/main/docs/source/LLM/%E5%91%BD%E4%BB%A4%E8%A1%8C%E5%8F%82%E6%95%B0.md
