### ISSUE TITLE
zsh install swift get error

### ISSUE THREAD

**Issue by nowang6** [modelscope/swift#710]
**Describe the bug**
What the bug is, and how to reproduce, better with screenshots(描述bug以及复现过程，最好有截图)
![image](https://github.com/modelscope/swift/assets/150778393/6ba08462-786d-461a-86a5-3c9cd514d5f8)

You should use below command, please update the readme
pip install '.[llm]'

**Your hardware and system info**
Write your system info like CUDA version/system/GPU/torch version here(在这里给出硬件信息和系统信息，如CUDA版本，系统，GPU型号和torch版本等)

**Additional context**
Add any other context about the problem here(在这里补充其他信息)

**Comment by tastelikefeet** [comment]
#735 fixed.
