### ISSUE TITLE
使用LoRA微调再awq量化后的模型qwen1half-7b-chat推理 速度很慢

### ISSUE THREAD

**Issue by catundchat** [modelscope/swift#722]
**Describe the bug**
LoRA方法微调qwen1half-7b-chat的模型和将其awq int4量化后的模型相比，量化后的模型速度慢好多。和官方给的推理速度不一样
在powershell中运行下述命令来推理量化后的模型
```
$env:CUDA_VISIBLE_DEVICES="0"
swift infer `
    --ckpt_dir "D:\github\swift\output\qwen1half-7b-chat\v11-20240416-113331\checkpoint-1875-merged-awq-int4"
```

**Your hardware and system info**
Windows 10, GPU: A5000, cuda version: 12.4, torch version: '2.0.1+cu118'

**Additional context**
Add any other context about the problem here(在这里补充其他信息)

**Comment by catundchat** [comment]
整体上，微调后推理速度7b model > gptq > awq

**Comment by Jintao-Huang** [comment]
你可以试一下vllm来加速推理
