### ISSUE TITLE
MiniCPM-V-2 link invalid

### ISSUE THREAD

**Issue by yiranyyu** [modelscope/swift#731]
**Describe the bug**
I find the link refer to MiniCPM-V-2 is invalid at [here](https://github.com/modelscope/swift/blob/4676b23be844b7b6e39bd99b9786c7825f7b1e89/docs/source/Multi-Modal/minicpm-v%E6%9C%80%E4%BD%B3%E5%AE%9E%E8%B7%B5.md?plain=1#L19), which should be updated to https://modelscope.cn/models/OpenBMB/MiniCPM-V-2/summary

**Comment by hjh0119** [comment]
Thanks for the feedback
