### ISSUE TITLE
swift app-ui加上lora训练后的数据后，运行会报错，这是啥原因呢

### ISSUE THREAD

**Issue by cjq345994512** [modelscope/swift#732]
运行指定模型开源正常启动
CUDA_VISIBLE_DEVICES=0,1 swift app-ui \
    --model_type qwen1half-7b-chat \
    --model_id /root/autodl-tmp/models/qwen/Qwen1___5-7B-Chat \
    --infer_backend pt --max_model_len 4096 \

加上lora训练后的数据后，运行会报错
CUDA_VISIBLE_DEVICES=0,1 swift app-ui \
    --model_type qwen1half-7b-chat \
    --model_id /root/autodl-tmp/models/qwen/Qwen1___5-7B-Chat \
    --infer_backend pt --max_model_len 4096 \
    --ckpt_dir /root/autodl-tmp/models/swift/output/qwen1half-7b-chat/v0-20240417-183134 \
    --merge_lora true \
返回提示如下
ValueError: Mixed using with peft is not allowed now.

**Comment by Logos23333** [comment]
指定checkpoint-xxx
--ckpt_dir /root/autodl-tmp/models/swift/output/qwen1half-7b-chat/v0-20240417-183134/checkpoint-xxx
