### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb5 in position 128: invalid start byte

### ISSUE THREAD

**Issue by chenzrooo** [modelscope/swift#738]
自我认知微调最佳实践 报错 UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb5 in position 128: invalid start byte，这应该是编码问题，求大佬怎么解决

**Comment by Jintao-Huang** [comment]
你试试删除 本地的ms-bench数据集缓存，然后再运行一下
