### ISSUE TITLE
Value Error("Please setting '--model_type <model_type>'")

### ISSUE THREAD

**Issue by echo-valor** [modelscope/swift#744]
**Describe the bug**
推理llama-3-8B模型显示没有这个类型的模型
![image](https://github.com/modelscope/swift/assets/28260618/5ce84365-e23b-4883-b43d-a37f25e33b6c)

**Your hardware and system info**
这个是因为还未支持llama3吗？看README说已经支持了

**Additional context**

**Comment by Jintao-Huang** [comment]
已经支持了 你的sh是什么呢

**Comment by echo-valor** [comment]
以下是我的脚本，报如上错误：

`
CUDA_VISIBLE_DEVICES=0,1 \
swift infer \
    --ckpt_dir /home/llama3-8b-instruct" \
    --load_dataset_config true \
    --max_new_tokens 2048 \
    --temperature 0.1 \
    --top_p 0.7 \
    --repetition_penalty 1. \
    --do_sample true \
    --merge_lora false \
`

**Comment by Jintao-Huang** [comment]
```
CUDA_VISIBLE_DEVICES=0,1 swift infer \ 
    --model_type llama3-8b-instruct --model_id_or_path /home/llama3-8b-instruct"  ...
