### ISSUE TITLE
Dataset loading error

### ISSUE THREAD

**Issue by Alexie-Z-Yevich** [modelscope/swift#745]
按照 Qwen1.5全流程最佳实践 文档执行自我认知微调，使用对照的格式造了一条数据：
train.json: {"query": "xxx","response": "xxxxxxxxx"}
![image](https://github.com/modelscope/swift/assets/100772629/7f70fcda-328c-4aa9-9068-819962e00c4e)
怀疑是数据集问题，遂执行源文档内容依旧报错：
![image](https://github.com/modelscope/swift/assets/100772629/75f54047-dab4-4116-b79b-0f6561187574)

版本信息如下：
win10 3090 cuda_12.4
torch 2.2.1+cu121

模型为 codeqwen1half_7b_chat = 'codeqwen1half-7b-chat'

**Comment by kratorado** [comment]
ms-bench 数据集的仓库更新了文件，估计是这个更新引发的。同样有问题的数据集貌似还不止这一个

**Comment by hjh0119** [comment]
拉下最新代码

**Comment by Alexie-Z-Yevich** [comment]
> 拉下最新代码

修改之后依然报错，ms-bench-mini数据集依旧和图二一样。换了coig_cqia_chinese_traditional数据集之后又换了一个报错~
![image](https://github.com/modelscope/swift/assets/100772629/f37d1856-fad1-40c3-b5d9-c20584705a49)
![image](https://github.com/modelscope/swift/assets/100772629/0eb4eeec-ad0c-4d16-928c-1d7c43b2e061)

**Comment by Alexie-Z-Yevich** [comment]
> > 修改之后依然报错
> 
> 可以发下完整命令吗

import os

os.environ['CUDA_VISIBLE_DEVICES'] = '0'

from swift.llm import DatasetName, ModelType, SftArguments, sft_main
sft_args = SftArguments(
    model_type=ModelType.qwen1half_0_5b_chat,
    model_id_or_path="F:/AAA/modelscope/qwen/CodeQwen1.5-7B-Chat",
    dataset=[DatasetName.coig_cqia_chinese_traditional],
    train_dataset_sample=1000,
    logging_steps=5,
    max_length=1024,
    learning_rate=5e-5,
    warmup_ratio=0.4,
    output_dir='output',
    lora_target_modules=['ALL'],
    self_cognition_sample=500,
    model_name=['小黄', 'Xiao Huang'],
    model_author=['魔搭', 'ModelScope'])
output = sft_main(sft_args)
best_model_checkpoint = output['best_model_checkpoint']
print(f'best_model_checkpoint: {best_model_checkpoint}')

**Comment by Alexie-Z-Yevich** [comment]
同时还想询问下，如果我自己造数据集的话，按照 自定义与拓展.md 中的格式创建json文件后需要注册数据集吗？
目前我直接将 dataset=["F:/AAA/train.json"],替换成自己的数据集（里面只有一条数据，格式：{"query": "xxx","response": "xxxxxxxxx"}）会报错
![image](https://github.com/modelscope/swift/assets/100772629/7541a206-8b23-47bc-ac3c-3de29b7735b5)

**Comment by hjh0119** [comment]
> 修改之后依然报错

报错命令不完整看不出问题，也没有复现。尝试拉取下最新代码后安装到环境中

> 同时还想询问下，如果我自己造数据集的话，按照 自定义与拓展.md 中的格式创建json文件后需要注册数据集吗？ 

可以不需要，参考https://github.com/modelscope/swift/blob/main/docs/source/LLM/%E8%87%AA%E5%AE%9A%E4%B9%89%E4%B8%8E%E6%8B%93%E5%B1%95.md#%E8%87%AA%E5%AE%9A%E4%B9%89%E6%95%B0%E6%8D%AE%E9%9B%86 
第一种方法，用`--custom_train_dataset_path`参数

**Comment by Alexie-Z-Yevich** [comment]
> > 修改之后依然报错
> 
> 报错命令不完整看不出问题，也没有复现。尝试拉取下最新代码后安装到环境中
> 
> > 同时还想询问下，如果我自己造数据集的话，按照 自定义与拓展.md 中的格式创建json文件后需要注册数据集吗？
> 
> 可以不需要，参考https://github.com/modelscope/swift/blob/main/docs/source/LLM/%E8%87%AA%E5%AE%9A%E4%B9%89%E4%B8%8E%E6%8B%93%E5%B1%95.md#%E8%87%AA%E5%AE%9A%E4%B9%89%E6%95%B0%E6%8D%AE%E9%9B%86 第一种方法，用`--custom_train_dataset_path`参数

谢谢，解决了
