### ISSUE TITLE
InternVL-1.5 希望可以支持

### ISSUE THREAD

**Issue by parasol-ry** [modelscope/swift#750]
https://huggingface.co/OpenGVLab/InternVL-Chat-V1-5 希望可以支持一下微调，实际使用下来效果确实很好

**Comment by Jintao-Huang** [comment]
好的 我支持一下

**Comment by Jintao-Huang** [comment]
https://github.com/modelscope/swift/issues/545

**Comment by zhangfan-algo** [comment]
InternVL-2已经出来了

**Comment by Jintao-Huang** [comment]
@hjh0119

**Comment by zhangfan-algo** [comment]
> @hjh0119

大佬什么时候可以支持一下呀

**Comment by hjh0119** [comment]
> 大佬什么时候可以支持一下呀

收到 马上接入

**Comment by 2132660698** [comment]
同求，感谢！

**Comment by hjh0119** [comment]
InternVL-Chat-V1.5 已支持，参考https://github.com/modelscope/swift/tree/main/docs/source/Multi-Modal/internvl最佳实践.md
