### ISSUE TITLE
qwen1.5-72b-chat 作  lora sft后  出现个别字符的 错误，直接用qwen1.5 生成没有问题

### ISSUE THREAD

**Issue by yezhongxiuchan** [modelscope/swift#751]
**Describe the bug**
用一堆 GPT-4 生成的文本， 有prompt 和  answer  大约 2万条，给到  qwen1.5-72b-chat 模型 作  lora 的 sft，微调后，deploy  进行推理的时候，出现个别性的 字符乱码错误。
直接拿  prompt 调用原始模型没有问题
<img width="299" alt="微调的" src="https://github.com/modelscope/swift/assets/86962593/c000026c-7fc2-4d71-b168-56b6a4cfec6b">
<img width="392" alt="正常的" src="https://github.com/modelscope/swift/assets/86962593/6061eded-153b-45fd-b3e0-ffe288f46b9f">

上面是微调的，下面是正常的，用的一样的prompt ，生成出来这样的效果，该如何解啊？ 有人遇到过类似的问题么？

**Your hardware and system info**
Write your system info like CUDA version/system/GPU/torch version here(在这里给出硬件信息和系统信息，如CUDA版本，系统，GPU型号和torch版本等)

微调的系统是  GPU  A800*4   CUDA  12.1   centos7.9 系统，torch   2.12

sft的 脚本是
CUDA_VISIBLE_DEVICES=0,1,2,3 \
NPROC_PER_NODE=4 \
swift sft \
    --model_type qwen1half-72b-chat \
    --sft_type lora \
    --output_dir output \
    --dataset ner-jave-zh \
    --custom_train_dataset_path   /data/formatis_pro03062.jsonl /data/formatis_pro03272.jsonl /data/formatabstract0306.jsonl  /data/formatabstract0327.jsonl \
    --train_dataset_sample 20000 \
    --num_train_epochs 3 \
    --max_length 8192 \
    --lora_rank 8 \
    --lora_alpha 32 \
    --lora_dropout_p 0.05 \
    --lora_target_modules ALL \
    --gradient_checkpointing true \
    --batch_size 1 \
    --weight_decay 0.1 \
    --learning_rate 1e-5 \
    --gradient_accumulation_steps 16 \
    --max_grad_norm 0.5 \
    --warmup_ratio 0.03 \
    --eval_steps 50 \
    --save_steps 50 \
    --save_total_limit 5 \
    --logging_steps 10 \
    --use_flash_attn true \
    --deepspeed default-zero3 \

**Comment by Jintao-Huang** [comment]
swift的版本是什么呢 用最新的试试 这个bug应该已经修复了

**Comment by yezhongxiuchan** [comment]
> swift的版本是什么呢 用最新的试试 这个bug应该已经修复了

哦，我用的是  swift 1.7.3  刚刚升级了一下，现在最新的是 2.0.2 是么？ 1
<img width="1151" alt="swift版本" src="https://github.com/modelscope/swift/assets/86962593/34437d5a-5161-490d-bd5c-81ff372a1aa5">

**Comment by Jintao-Huang** [comment]
最新版本的 swift依旧有这个问题么

**Comment by yezhongxiuchan** [comment]
> 最新版本的 swift依旧有这个问题么

刚刚试过了，最新的 swift 没有这个问题了，感谢老师
