### ISSUE TITLE
gptq, awq模型支持deepspeed-zero2, zero3吗？

### ISSUE THREAD

**Issue by ghost** [modelscope/swift#767]
请问load awq模型支持zero3吗？

**Comment by Jintao-Huang** [comment]
支持的, 信息已添加至readme. awq, gptq支持zero2, zero3

**Comment by mxjmtxrm** [comment]
您好，awq模型用zero3是不是无法进行参数切分？每个GPU在训练的时候都加载完整的参数，nvidia-smi的时候看显存占用是完整模型的显存用量。
