### ISSUE TITLE
有没有一个关于训练log表示含义的详细文档？

### ISSUE THREAD

**Issue by changqinyao** [modelscope/swift#770]
**Describe the feature**
Please describe the feature requested here(请在这里描述需求)

**Paste any useful information**
Paste any useful information, including papers, github links, etc.(请在这里描述其他有用的信息，比如相关的论文地址，github链接等)

**Additional context**
Add any other context or information here(其他信息可以写在这里)

**Comment by tastelikefeet** [comment]
可以参考下transformers的官方文档，我们的大部分log来自于transformers.trainer，如果是我们自己的log，可以截图在这里，我给你解释下
