### ISSUE TITLE
部署能否指定模型名

### ISSUE THREAD

**Issue by WSC741606** [modelscope/swift#795]
**Describe the feature**
希望swift deploy 添加一个参数，从而允许自定义模型ID和所有者，即IP:8000/v1/models中的"id"和"owned_by"

**Comment by Jintao-Huang** [comment]
已经支持了owned_by的修改

**Comment by WSC741606** [comment]
收到，感谢大佬

**Comment by WSC741606** [comment]
> 已经支持了owned_by的修改

id支持修改了吗，如果不是用vllm-lora的话
