### ISSUE TITLE
webui点击开始训练之后一晚上没有出任何结果

### ISSUE THREAD

**Issue by AlexJJJChen** [modelscope/swift#799]
**Describe the bug**
What the bug is, and how to reproduce, better with screenshots(描述bug以及复现过程，最好有截图)
<img width="1212" alt="image" src="https://github.com/modelscope/swift/assets/126591882/079f865a-7154-45b2-bcb3-c64ad1c94ea4">

**Your hardware and system info**
Write your system info like CUDA version/system/GPU/torch version here(在这里给出硬件信息和系统信息，如CUDA版本，系统，GPU型号和torch版本等)

**Additional context**
Add any other context about the problem here(在这里补充其他信息)

**Comment by tastelikefeet** [comment]
web-ui是命令行的封装，查看下运行中任务的命令行，找到logging_dir部分，直接看下log
