### ISSUE TITLE
测试官方提供的代码，报错，建议修改

### ISSUE THREAD

**Issue by Viserion-nlper** [modelscope/swift#817]
**Describe the bug**
What the bug is, and how to reproduce, better with screenshots(描述bug以及复现过程，最好有截图)
在运行使用tuner章节的时候，运行官方提供的[代码](https://github.com/modelscope/swift/blob/main/docs/source/GetStarted/%E4%BD%BF%E7%94%A8tuners.md#%E5%AE%8C%E6%95%B4%E7%9A%84%E8%AE%AD%E7%BB%83%E4%BB%A3%E7%A0%81)，报错：
![image](https://github.com/modelscope/swift/assets/48983651/0214f712-ba35-4522-9dd8-9e1ac63f1bd0)

去modelscope包里找，是有to_hf_dataset这个方法的，这里出错的原因是什么？

**Your hardware and system info**
Write your system info like CUDA version/system/GPU/torch version here(在这里给出硬件信息和系统信息，如CUDA版本，系统，GPU型号和torch版本等)

**Additional context**
Add any other context about the problem here(在这里补充其他信息)

**Comment by tastelikefeet** [comment]
这里我修改一下，可以直接去掉to_hf_dataset，modelscope版本更新后这个方法去掉了，你可以直接去掉该方法使用
