### ISSUE TITLE
微调时候的acc代表什么，如何选择最优的模型

### ISSUE THREAD

**Issue by Jintao-Huang** [modelscope/swift#822]

**Comment by Jintao-Huang** [comment]
微调时候的acc是在teaching force情况下的token级别的准确率，并不能代表acc最高的模型就是最优的。

通常情况下，指标最优的模型在acc最大/loss最小的后几个epoch处 （例如在第一个epoch后loss最小，但可能评测最优的模型在第3个epoch后，甚至第5个epoch后）。毕竟teaching force的token生成和step by step生成的情况相比，后一个会更难。

建议使用`swift eval`或者使用ROUGE来对模型进行评估。

**Comment by Jintao-Huang** [comment]
When fine-tuning, the accuracy (acc) is at the token level under teaching force conditions and cannot represent that the model with the highest acc is the best. Typically, the optimal model is found in the later epochs where the accuracy is highest/loss is lowest (for example, the lowest loss may occur after the first epoch, but the model with the best performance may be evaluated after the 3rd or even the 5th epoch). After all, token generation with teaching force is more challenging than step-by-step generation. We recommend using `swift eval` or ROUGE to evaluate the model.

**Comment by evyy1234** [comment]
如何让模型在微调的时候就直接输出ROUGE BLEU这些更佳的评价指标呢

**Comment by Betty-J** [comment]
> 微调时候的acc是在teaching force情况下的token级别的准确率，并不能代表acc最高的模型就是最优的。
> 
> 通常情况下，指标最优的模型在acc最大/loss最小的后几个epoch处 （例如在第一个epoch后loss最小，但可能评测最优的模型在第3个epoch后，甚至第5个epoch后）。毕竟teaching force的token生成和step by step生成的情况相比，后一个会更难。
> 
> 建议使用`swift eval`或者使用ROUGE来对模型进行评估。
> 
> English:
> 
> When fine-tuning, the accuracy (acc) is at the token level under teaching force conditions and cannot represent that the model with the highest acc is the best. Typically, the optimal model is found in the later epochs where the accuracy is highest/loss is lowest (for example, the lowest loss may occur after the first epoch, but the model with the best performance may be evaluated after the 3rd or even the 5th epoch). After all, token generation with teaching force is more challenging than step-by-step generation. We recommend using `swift eval` or ROUGE to evaluate the model.

您好，我在微调时发现eval acc在持续上升的同时，eval loss也在上升了，评测结果是 eval acc 更高时效果更好，该如何理解这种现象呢，是过拟合需要early stop 还是说按照现在的实验结果来选择最佳模型。
