### ISSUE TITLE
多模态模型的部署

### ISSUE THREAD

**Issue by wuweinero** [modelscope/swift#826]
多模态模型后面有计划提供部署脚本吗？

**Comment by Jintao-Huang** [comment]
有的，5月份完成

**Comment by Jintao-Huang** [comment]
已经支持多模态部署：https://github.com/modelscope/swift/blob/main/docs/source/Multi-Modal/MLLM%E9%83%A8%E7%BD%B2%E6%96%87%E6%A1%A3.md
