### ISSUE TITLE
lisa可训练参数计算异常

### ISSUE THREAD

**Issue by WSC741606** [modelscope/swift#829]
**Describe the bug**
yi-6B-chat可训练参数在`lisa_activated_layers设置1/2/4都显示`[INFO:swift] LlamaForCausalLM: 6061.0355M Params (524.2921M Trainable [8.6502%]), 33.5565M Buffers.`，这个计算是不是有问题？

**Comment by tastelikefeet** [comment]
是的，这个我后续修复一下

**Comment by WSC741606** [comment]
或者给一个区间？而且原论文说主要也是首尾的层激活的多，大概给个值加上error bar也就差不多
主要是和LoRA之类方法对比的时候 如果她动的参数多很多，感觉这种对比不是太公平

**Comment by tastelikefeet** [comment]
目前我给出的计算方法是按照每次训练的激活参数来算 #891

**Comment by WSC741606** [comment]
好嘞，辛苦大佬
