### ISSUE TITLE
Support for ORPO training

### ISSUE THREAD

**Issue by zodiacg** [modelscope/swift#831]
**Describe the feature**
Please consider adding support for ORPO training. It extends preference optimization into sft stage and shows promising results.

**Paste any useful information**
[Paper](https://arxiv.org/abs/2403.07691) and [Support from Huggingface TRL](https://huggingface.co/docs/trl/main/en/orpo_trainer)

**Comment by hjh0119** [comment]
调研中，尽快完成

**Comment by hjh0119** [comment]
已经支持啦 拉下最新代码
