### ISSUE TITLE
sft.py: error: argument --tuner_backend: invalid choice: 'unsloth' (choose from 'swift', 'peft')

### ISSUE THREAD

**Issue by zhly0** [modelscope/swift#833]
执行pip install 'ms-swift[llm]' -U
安装Successfully installed ms-swift-2.0.3.post1
运行命令中添加--lisa_activated_layers 2 --tuner_backend unsloth
出现sft.py: error: argument --tuner_backend: invalid choice: 'unsloth' (choose from 'swift', 'peft')

**Comment by hjh0119** [comment]
```
git clone https://github.com/modelscope/swift.git
cd swift
pip install -e .
```
