### ISSUE TITLE
Questions about finetunning internlm_xcomposer2_7b_chat. 

### ISSUE THREAD

**Issue by piqiuni** [modelscope/swift#837]
Hello,
1. we want to finetune the model with our own dataset(pics + txt), and with 2 RTX4090, the following setting leads to Error as follows, does that mean the model doesn't support it:
setting `os.environ['CUDA_VISIBLE_DEVICES'] = '0, 1'
    os.environ['NPROC_PER_NODE'] = '2'`
Error: `RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:1! (when checking argument for argument tensors in method wrapper_CUDA_cat)`

2. Then we tried to run with one card, and it led to OOM, also we tried the deepspeed but it met error blow, which seems caused by the version of transformers.
`AttributeError: 'DummyOptim' object has no attribute 'step'`

3. And we also tried the qlora but seems it doesn't support?
`TypeError: Linear4bit.forward() takes 2 positional arguments but 3 were given`

We are wondering if the OOM caused by our own dataset(with demo it works), and what can we do to avoid the OOM ?

**Comment by Jintao-Huang** [comment]
device_map:
```sh
# device_map2
CUDA_VISIBLE_DEVICES=0,1 swift sft \
    --model_type internlm-xcomposer2-7b-chat \
    --dataset coco-mini-en \

# device_map4
CUDA_VISIBLE_DEVICES=0,1,2,3 swift sft \
    --model_type internlm-xcomposer2-7b-chat \
    --dataset coco-mini-en \
```


zero2:
```sh
CUDA_VISIBLE_DEVICES=0,1,2,3 NPROC_PER_NODE=4 swift sft \
    --model_type internlm-xcomposer2-7b-chat \
    --dataset coco-mini-en \
    --deepspeed default-zero2
```

**Comment by piqiuni** [comment]
Thanks for the fix

But with the new code, I still got the error below when fine-tuning with my own dataset.
Error: `RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:1! (when checking argument for argument tensors in method wrapper_CUDA_cat)`

The official command `CUDA_VISIBLE_DEVICES=0,1 swift sft     --model_type internlm-xcomposer2-7b-chat     --dataset coco-mini-en ` works. But change to `CUDA_VISIBLE_DEVICES=0,1 swift sft     --model_type internlm-xcomposer2-7b-chat     --custom_train_dataset_path ~/pi_code/swift/pi_code/my_data.json` lead to ERROR.

**Comment by piqiuni** [comment]
The `my_data.json` is like:
```
{"conversations": [
        {"from": "user", "value": "Picture 1:<img>./resources/banner.png</img>\n11111"},
        {"from": "assistant", "value": "22222"}
    ]},
*n
```
The error is caused by the picture loadding
