### ISSUE TITLE
vllm推理不支持多GPU

### ISSUE THREAD

**Issue by szdengdi** [modelscope/swift#848]
推理选择vllm，不支持多卡加载

**Comment by tastelikefeet** [comment]
支持的，指定--tensor_parallel_size 可以查看 https://github.com/modelscope/swift/blob/main/docs/source/LLM/VLLM%E6%8E%A8%E7%90%86%E5%8A%A0%E9%80%9F%E4%B8%8E%E9%83%A8%E7%BD%B2.md
