### ISSUE TITLE
llama3-70b-instuct finetune

### ISSUE THREAD

**Issue by KimballCai** [modelscope/swift#856]
Do you have any suggestions for configuration or resources for fine-tuning the llama3-70b-instruct? 

Why 8*V100-32 G cannot run the finetuning in 4 bit ?

**Comment by KimballCai** [comment]
if directly sft with llama3-70b-instruct-int8.

It will raise error.

ValueError: You have entered a string value for dataset. You can only choose between
                        ['wikitext2','c4','c4-new','ptb','ptb-new'], but we found sharegpt-gpt4-mini

**Comment by Jintao-Huang** [comment]
fixed
