### ISSUE TITLE
sharegpt-gpt4数据集缺失V3_format和zh_38K子集

### ISSUE THREAD

**Issue by WSC741606** [modelscope/swift#857]
**Describe the bug**
https://modelscope.cn/datasets/AI-ModelScope/sharegpt_gpt4/files 中有sharegpt_gpt4.jsonl、sharegpt_V3_format.jsonl、sharegpt_zh_38K_format.jsonl，但加载sharegpt_gpt4数据集时仅有default能被正常下载，另外俩报错
```
site-packages/modelscope/msdatasets/utils/dataset_utils.py", line 61, in get_target_dataset_structure
    raise ValueError(
ValueError: subset_name V3_format not found. Available: dict_keys(['default'])
```
测试了ds = MsDataset.load('AI-ModelScope/sharegpt_gpt4', split='train', download_mode=DownloadMode.FORCE_REDOWNLOAD)  
一样只能下载default

**Comment by Jintao-Huang** [comment]
fixed

**Comment by WSC741606** [comment]
测试`ds = MsDataset.load('AI-ModelScope/sharegpt_gpt4',subset_name='V3_format', split='train', download_mode=DownloadMode.FORCE_REDOWNLOAD)`成功加载58674条数据，辛苦大佬五一假期加班~
