### ISSUE TITLE
Deployment of multimodal models is currently not supported

### ISSUE THREAD

**Issue by lukywangwang** [modelscope/swift#878]
**Describe the bug**
What the bug is, and how to reproduce, better with screenshots(描述bug以及复现过程，最好有截图)
多模态模型部署不了吗？
怎么部署到服务器上？

尝试部署这个模型。
internlm-xcomposer2-7b-chat

**Your hardware and system info**
Write your system info like CUDA version/system/GPU/torch version here(在这里给出硬件信息和系统信息，如CUDA版本，系统，GPU型号和torch版本等)

**Additional context**
Add any other context about the problem here(在这里补充其他信息)

**Comment by tastelikefeet** [comment]
是的，目前多模态模型还不支持部署，我们本月会支持

**Comment by RYWei** [comment]
请问，现在支持了吗？

**Comment by Jintao-Huang** [comment]
已经支持多模态部署：https://github.com/modelscope/swift/blob/main/docs/source/Multi-Modal/MLLM%E9%83%A8%E7%BD%B2%E6%96%87%E6%A1%A3.md
