### ISSUE TITLE
使用swift web-ui进行推理时，如何上传图片呢

### ISSUE THREAD

**Issue by BurrowsWang** [modelscope/swift#889]
使用swift web-ui启动gradioweb界面，在LLM推理tab页，选择了多模态vl模型之后，怎么在界面上或者对话框中传入图片呢？

**Comment by tastelikefeet** [comment]
目前还不支持多模态，建议使用swift infer方式命令行调用

**Comment by BurrowsWang** [comment]
> 目前还不支持多模态，建议使用swift infer方式命令行调用

是否有支持的计划呢？
Is it on the TODO list?
