### ISSUE TITLE
V100推理internVL-1.5-Int8问题

### ISSUE THREAD

**Issue by rTrQqgH74lc2PT5k** [modelscope/swift#890]
**Describe the bug**
What the bug is, and how to reproduce, better with screenshots(描述bug以及复现过程，最好有截图)

1. 使用最新代码后，使用int8模型后会报错 RuntimeError: probability tensor contains either `inf`, `nan` or element < 0
2. 如果不使用命令行，使用推理脚本
则推理出来后response是乱码
``` bash
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
FlashAttention is not installed.
Unused kwargs: ['quant_method']. These kwargs are not used in <class 'transformers.utils.quantization_config.BitsAndBytesConfig'>.
Loading checkpoint shards: 100%|██████████████████████| 6/6 [00:58<00:00,  9.77s/it]
[INFO:swift] model.max_model_len: None
[INFO:swift] Global seed set to 42
query: How far is it from each city?
response:  <unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk>
query: Which city is the farthest?
response: The data</s>
history: [['How far is it from each city?', ' <unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk>], ['Which city is the farthest?', 'The data</s>']]
```
**Your hardware and system info**

Pytorch 2.2, CUDA 11.8

**Comment by hjh0119** [comment]
贴下执行命令

**Comment by rTrQqgH74lc2PT5k** [comment]
执行命令1：CUDA_VISIBLE_DEVICES=0 swift infer --model_type internvl-chat-v1_5-int8  --use_flash_attn false
模型可以成功加载，加载后输入prompt + image url， 就会报错 RuntimeError: probability tensor contains either inf, nan or element < 0


执行命令2： python test_int8.py

``` python
import os
os.environ['CUDA_VISIBLE_DEVICES'] = '0'

from swift.llm import (
    get_model_tokenizer, get_template, inference, ModelType,
    get_default_template_type, inference_stream
)
from swift.utils import seed_everything
import torch

model_type = ModelType.internvl_chat_v1_5_int8
template_type = get_default_template_type(model_type)
print(f'template_type: {template_type}')
model, tokenizer = get_model_tokenizer(model_type, torch.float16,
                                        model_kwargs={'device_map': 'auto'},
                                        use_flash_attn = False)

model.generation_config.max_new_tokens = 256
template = get_template(template_type, tokenizer)
seed_everything(42)

images = ['http://modelscope-open.oss-cn-hangzhou.aliyuncs.com/images/road.png']
query = 'How far is it from each city?'
response, history = inference(model, template, query, images=images)  # chat with image
print(f'query: {query}')
print(f'response: {response}')

query = 'Which city is the farthest?'
gen = inference_stream(model, template, query, history)  # chat withoud image
print_idx = 0
print(f'query: {query}\nresponse: ', end='')
for response, history in gen:
    delta = response[print_idx:]
    print(delta, end='', flush=True)
    print_idx = len(response)
print()
print(f'history: {history}')
```

执行后结果有点异常

``` bash
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
FlashAttention is not installed.
Unused kwargs: ['quant_method']. These kwargs are not used in <class 'transformers.utils.quantization_config.BitsAndBytesConfig'>.
Loading checkpoint shards: 100%|██████████████████████| 6/6 [00:58<00:00,  9.77s/it]
[INFO:swift] model.max_model_len: None
[INFO:swift] Global seed set to 42
query: How far is it from each city?
response:  <unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk>
query: Which city is the farthest?
response: The data</s>
history: [['How far is it from each city?', ' <unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk><unk>], ['Which city is the farthest?', 'The data</s>']]
```

**Comment by hjh0119** [comment]
@rTrQqgH74lc2PT5k  你好 swift infer 用示例中的图片url会报错吗 比如http://modelscope-open.oss-cn-hangzhou.aliyuncs.com/images/cat.png

**Comment by hjh0119** [comment]
结果异常有什么报错信息吗？ 没能复现
![image](https://github.com/modelscope/swift/assets/112739147/d3779442-e288-4848-8ace-c7df427f0b06)

**Comment by rTrQqgH74lc2PT5k** [comment]
我用的是huggingface上下载的int8模型，没有用modelscope上的。请问有可能是这个原因吗

**Comment by rTrQqgH74lc2PT5k** [comment]
![企业微信截图_17152509956502](https://github.com/modelscope/swift/assets/7837172/285ea917-625a-4b08-8c40-6edb06c8d660)

不使用图片，可以得到正常的输出，
加了图片，输出就异常了

**Comment by hjh0119** [comment]
swift infer 正常推理是先输入query内容回车，然后会提示输入Input a media path or URL，再输入图片路径或者链接
![image](https://github.com/modelscope/swift/assets/112739147/31b6cd8e-76e8-4caf-9f61-21de6823a3a4)

我的执行命令
```
CUDA_VISIBLE_DEVICES=0 swift infer --model_type internvl-chat-v1_5-int8  --use_flash_attn false
```

**Comment by rTrQqgH74lc2PT5k** [comment]
![image](https://github.com/modelscope/swift/assets/169340290/dc60dc53-3e89-4a4d-b330-8c241ab46b94)

相同的做法，但还是报错了。

**Comment by hjh0119** [comment]
@rTrQqgH74lc2PT5k  我推测可能是运行的时候OOM了，你能找一张比较小的图片或者多卡推理试下吗

**Comment by NLP-Learning** [comment]
> @rTrQqgH74lc2PT5k 我推测可能是运行的时候OOM了，你能找一张比较小的图片或者多卡推理试下吗。运行的时候关注一下显存占用

int8我和题主遇到了一样的报错，我按您说的使用了两张32G卡加载int8，确定没有oom。

**Comment by hjh0119** [comment]
@NLP-Learning @rTrQqgH74lc2PT5k  如果传--dtype bf16 可以正常跑吗 ref: https://github.com/OpenGVLab/InternVL/issues/144

**Comment by NLP-Learning** [comment]
> @NLP-Learning @rTrQqgH74lc2PT5k 如果传--dtype bf16 可以正常跑吗 ref: [OpenGVLab/InternVL#144](https://github.com/OpenGVLab/InternVL/issues/144)

可以的，Int8加上这个参数就可以正常跑了！感谢！不管是单卡还是多卡都可以正常跑，一张32G的V100显存基本可以用满。
![image](https://github.com/modelscope/swift/assets/130777620/002005bb-1ea2-4abe-bdc3-05e6f7130c41)

**Comment by hjh0119** [comment]
@NLP-Learning  方便测试一下--dtype bf16 下sft可以正常运行吗

**Comment by BIGBALLON** [comment]
> @NLP-Learning 方便测试一下--dtype bf16 下sft可以正常运行吗

bf16 is only supported on Ampere GPU,  ``--dtype bf16`` will will cause an error on V100 GPU
but if   ``--dtype bf16``  is not setted,  it may cause some other problem(e.g. The result of the inference mentioned above is garbled code).

**Comment by hjh0119** [comment]
> bf16 is only supported on Ampere GPU, `--dtype bf16` will cause an error on V100 GPU but if `--dtype bf16` is not setted, it may cause some other problem(e.g. The result of the inference mentioned above is garbled code).

It is a bit strange, have you figured out the reason?

**Comment by NLP-Learning** [comment]
> @NLP-Learning 方便测试一下--dtype bf16 下sft可以正常运行吗

我刚拉取了最新代码安装了最新依赖，分别试了一下：
（1）用了5张32G V100，4张会报OOM
```shell
CUDA_VISIBLE_DEVICES=1,2,4,5,6 swift sft \
    --model_type  internvl-chat-v1_5 \
    --dataset coco-mini-en-2 \
    --model_id_or_path /data/InternVL-Chat-V1-5 \
    --use_flash_attn false
``` 
最后会报错：
```
RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cuda:1)
Train:   0%|                                                                                                                                            | 0/1250 [00:04<?, ?it/s]
``` 
（2）
```shell
CUDA_VISIBLE_DEVICES=1,2,5,6 swift sft \
    --model_type  internvl-chat-v1_5 \
    --dataset coco-mini-en-2 \
    --model_id_or_path /data/InternVL-Chat-V1-5 \
    --use_flash_attn false \
    --deepspeed default-zero2
``` 
会报错：
```
ValueError: DeepSpeed is not compatible with MP. n_gpu: 4, local_world_size: 1.
``` 
（3）
```shell
CUDA_VISIBLE_DEVICES=1,2,4,5,6 swift sft \
    --model_type  internvl-chat-v1_5 \
    --dataset coco-mini-en-2 \
    --model_id_or_path /data/InternVL-Chat-V1-5 \
    --use_flash_attn false \
    --dtype bf16
``` 
会报错：
```
ValueError: Your setup doesn't support bf16/gpu. You need torch>=1.10, using Ampere GPU with cuda>=11.0
``` 

就尝试了这么多，但前两个错误应该是好解决的，此外V100确实不支持bf16，但推理的时候加上`--dtype bf16`就可以正常推理，不知道是什么原因。

**Comment by hjh0119** [comment]
> 就尝试了这么多，但前两个错误应该是好解决的，此外V100确实不支持bf16，但推理的时候加上`--dtype bf16`就可以正常推理，不知道是什么原因。

感谢测试！
第一个原因是模型device map对五张卡这种支持不友好，2/4卡应该没问题
第二个原因是device map和deepspeed不能联用
第三个看来V100微调还是不能用bf16，那我还是将默认的dtype去掉好了，sft用float16应该没问题

**Comment by MVP-D77** [comment]
@hjh0119 您好，我拉了一下最新的代码，有什么额外的依赖需要安装码？我测试的微调 1.5int8的命令仍然出现了错误，我的显卡是A6000：
```
CUDA_VISIBLE_DEVICES=4,5,6,7 swift sft --model_type  internvl-chat-v1_5-int8 --dataset coco-mini-en-2 --model_id_or_path  /xxxx/InternVL/pretrained/InternVL-Chat-V1-5-Int8 
```
报错是`RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cuda:1)`
2卡 和4卡 都会报这个相同的错误

**Comment by hjh0119** [comment]
@MVP-D77 fixed https://github.com/modelscope/swift/pull/937
