### ISSUE TITLE
swift export指定输出路径要--啥

### ISSUE THREAD

**Issue by eigen2017** [modelscope/swift#894]
如题谢谢

**Comment by tastelikefeet** [comment]
目前不支持指定路径，如果是原模型导出会放入：'{model_type}-{quant_method}-int{quant_bits}'文件夹中，如果是ckpt_dir，则会放入相同目录下的'{ckpt_name}-{quant_method}-int{quant_bits}'文件夹中

**Comment by Jintao-Huang** [comment]
现在已支持`--quant_output_dir`

**Comment by RQfreefly** [comment]
@Jintao-Huang 你好，--quant_output_dir 这个命令我没有在文档中找到
