### ISSUE TITLE
开了flash_attention 后 3090提示  dim > 64 

### ISSUE THREAD

**Issue by wstart** [modelscope/swift#9]
微调的过程中 出现 Head dim > 64 backward requires A100 or H100 

问题同 https://github.com/Dao-AILab/flash-attention/issues/190

建议加上参数可以开关是否使用 flash_attention

**Comment by Jintao-Huang** [comment]
已解决: [PR#11](https://github.com/modelscope/swift/pull/11)

**Comment by Jintao-Huang** [comment]
哈咯, 我们在参数中增加了flash_attention传入开关, 默认是None('auto'), 可以通过设置成False来避免使用flash attention
