### ISSUE TITLE
自定义训练集（custom_train_dataset_path）与验证集（custom_val_dataset_path）错误得按照dataset_test_ratio进行分割

### ISSUE THREAD

**Issue by tiandiweizun** [modelscope/swift#902]
**Describe the bug**
SftArguments 数据参数如下设置，其他无关均省略
dataset=[f'{DatasetName.alpaca_zh}#100', f'{DatasetName.alpaca_en}#50', f'{DatasetName.self_cognition}#250']
custom_train_dataset_path=["./data/faq_train.jsonl"],
custom_val_dataset_path=["./data/faq_valid.jsonl"],

dataset_test_ratio 默认为0.01，这导致了 custom_train_dataset_path和custom_val_dataset_path传入路径时，均按照0.01进行了切分，且把custom_train_dataset_path和custom_val_dataset_path里面99%的内容作为训练，1%的内容作为验证集，不合符逻辑设定。

swift版本：commitId:845ac0ce46c4b904a809e3570e8dfb830f9b4e00

**Comment by tastelikefeet** [comment]
建议使用--custom_dataset_info 传入一个额外的数据集配置，并且指定--val_dataset 直接制定验证集。custom_dataset_info的文件格式仿照：https://github.com/modelscope/swift/blob/main/swift/llm/data/dataset_info.json

**Comment by tiandiweizun** [comment]
那还不如把 custom_val_dataset_path 加入到 val_dataset ，sft_args.val_dataset.append("./data/faq_train.jsonl")
