### ISSUE TITLE
API support for multi-modal model inference

### ISSUE THREAD

**Issue by babla9** [modelscope/swift#913]
Current code only supports single or batch inference for multi-modal models (Llava1.6, cogvlm etc) due to lack of vllm support. Any plans to add feature support to enable API support for these models? Maybe with something like https://github.com/sgl-project/sglang?

**Comment by tastelikefeet** [comment]
Sure, we will record this request to improve the performance of inference.

**Comment by Jintao-Huang** [comment]
Already supported.
