### ISSUE TITLE
微调后，回答结果被上下文影响该怎么解决

### ISSUE THREAD

**Issue by cjq345994512** [modelscope/swift#918]
微调大模型后，没有历史上下文时，问训练集中的问题，能回答正确。
但当有历史上下文时，再问训练集种的问题，会按历史上下文的回答内容格式去回答
这种情况需要怎么解决

**Comment by tastelikefeet** [comment]
增加数据集多样性，混合一些其他数据集一起训练

**Comment by cjq345994512** [comment]
尝试了增加到5000条和10000条  仍然有这个问题，而且是千问、百川、chatGLm、yi、这些模型都有这个问题。
还有其他解决办法吗
