### ISSUE TITLE
关于继续预训练的问题

### ISSUE THREAD

**Issue by Rundong-Li** [modelscope/swift#921]
使用垂直领域数据（书籍、论文等，非对话格式）进行继续预训练，在base model上还是chat model上进行会更好呢？

**Comment by tastelikefeet** [comment]
base model

**Comment by Rundong-Li** [comment]
> base model

那在CPT之后，是不是还需要大量的对话格式数据进行instruction fine-tuning呢？以及通过RLHF进行偏好对齐？
