### ISSUE TITLE
多任务微调

### ISSUE THREAD

**Issue by YoshuaBengio** [modelscope/swift#928]
大佬们，对于多种类型的任务，不同的任务，需要不同的system提示词，看了'命令行参数.md'文档，system参数如何针对多个任务的不同的system提示词进行设置呢？还是说如果要针对多个任务，只能将每种任务类型的system提示词和用户输入拼起来，作为数据集中的整个query字段呢？麻烦解答下哈，多谢了

**Comment by tastelikefeet** [comment]
数据集支持system字段的，可以构造带有system的数据集

**Comment by YoshuaBengio** [comment]
好的，感谢大佬
来自 Outlook<http://aka.ms/weboutlook>
________________________________
发件人: tastelikefeet ***@***.***>
发送时间: 2024年5月14日 14:28
收件人: modelscope/swift ***@***.***>
抄送: wqainlp777 ***@***.***>; Author ***@***.***>
主题: Re: [modelscope/swift] 多任务微调 (Issue #928)


数据集支持system字段的，可以构造带有system的数据集

―
