### ISSUE TITLE
自我认知 KeyError: 'self-cognition#500'

### ISSUE THREAD

**Issue by hydra-bu** [modelscope/swift#931]
**Describe the bug**
What the bug is, and how to reproduce, better with screenshots(描述bug以及复现过程，最好有截图)

使用UI 生成的命令行使用 `--self_cognition_sample` 参数（用这个参数是可以微调成功的），但是文档里又说该参数已经废弃，请使用`--dataset` , 使用新参数是报错的。

![image](https://github.com/modelscope/swift/assets/37682426/552a8324-d0e9-40e2-946b-8103e05e4723)

**Your hardware and system info**
Write your system info like CUDA version/system/GPU/torch version here(在这里给出硬件信息和系统信息，如CUDA版本，系统，GPU型号和torch版本等)

**Additional context**
Add any other context about the problem here(在这里补充其他信息)

执行的命令如下:

```
CUDA_VISIBLE_DEVICES=0 
swift sft \
    --sft_type lora \
    --model_id_or_path "AI-ModelScope/WizardLM-2-7B-AWQ" \
    --template_type "wizardlm2-awq" \
    --dataset alpaca-zh#500 alpaca-en#500 self-cognition#500 \
    --logging_steps 5 \
    --max_length 2048 \
    --learning_rate 5e-5 \
    --warmup_ratio 0.4 \
    --output_dir output \
    --lora_target_modules ALL \
    --model_name 小黄 'Xiao Huang' \
    --model_author 魔搭 ModelScope \
```

感觉文档内容更新不及时，照着敲也无法完成，指定自定义数据集也是各种报错，不是key_error就是column error...

**Comment by hjh0119** [comment]
文档是源码版本的，对应版本是2.1.0.dev0 
wheel包还没更新

**Comment by kratorado** [comment]
更新源码。
