### ISSUE TITLE
可以支持一下RoPE外推不

### ISSUE THREAD

**Issue by zhangfan-algo** [modelscope/swift#948]
对于比较长的长下文微调帮助挺大的

**Comment by tastelikefeet** [comment]
调研中，其他有用的长文本训练也会一起支持

**Comment by tastelikefeet** [comment]
rope-scaling已经支持，参考文档：https://github.com/modelscope/swift/blob/main/docs/source/LLM/%E5%91%BD%E4%BB%A4%E8%A1%8C%E5%8F%82%E6%95%B0.md
