### ISSUE TITLE
微调internvl-v1.5报错KeyError: 'input_ids'

### ISSUE THREAD

**Issue by sunzx8** [modelscope/swift#951]
**Describe the bug**
What the bug is, and how to reproduce, better with screenshots(描述bug以及复现过程，最好有截图)
<img width="1168" alt="image" src="https://github.com/modelscope/swift/assets/136688632/be2eb940-9544-43b2-ae58-cce84041ce44">

运行指令
CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 swift sft     --model_type internvl-chat-v1_5 --model_id_or_path /dev/shm/shawn/hf_ms_model/InternVL-Chat-V1-5     --dataset /dev/shm/shawn/data/ftoy.jsonl     --sft_type full 

数据格式为
{"query": "输出图片内容的markdown内容，如果有表格，则输出为html格式", "response": "```markdown\nAdaptive Quotient Filters\n\nConference '17, July 2017, Washington, DC, USA\n\n[34] Russell Housley, Warwick Ford, William Polk, and David Solo. 1999. Internet X.509 public key infrastructure certificate and CRL profile. Technical Report.  M. Frans Kaashoek. 2002. The case for application-specific protocols. In Proceedings of the 19th ACM Symposium on Operating Systems Principles (SOSP).", "images": ["/dev/shm/shawn/data/input/2405.10253v1/2405.10253v1-p16.png"]}

**Your hardware and system info**
Write your system info like CUDA version/system/GPU/torch version here(在这里给出硬件信息和系统信息，如CUDA版本，系统，GPU型号和torch版本等)
8*L20
<img width="733" alt="image" src="https://github.com/modelscope/swift/assets/136688632/9be24de5-7a06-4126-94cf-7be5d44f7bb0">

**Additional context**
Add any other context about the problem here(在这里补充其他信息)

**Comment by sunzx8** [comment]
我查了一下这个batch返回的是图片
<img width="937" alt="image" src="https://github.com/modelscope/swift/assets/136688632/f093d61d-5841-41fb-aae3-5c53d0eb7353">
<img width="717" alt="image" src="https://github.com/modelscope/swift/assets/136688632/5e5460f8-f522-4934-b325-c4098fce4edf">
<img width="726" alt="image" src="https://github.com/modelscope/swift/assets/136688632/04b796d1-ecd0-4d5b-af7c-1a036c347c63">

**Comment by hjh0119** [comment]
八卡device map可能会有问题，试下2/4卡

**Comment by sunzx8** [comment]
您好，我这里测出来是max_length的问题，请问为什么我设置max_length从2048到4096过后就会报错
RuntimeError: CUDA error: unspecified launch failure
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

**Comment by sunzx8** [comment]
还有我想问一下如果需要16卡两台机器一起微调需要怎么设置？

**Comment by hjh0119** [comment]
CUDA报错，可能是OOM或者CUDA环境问题

多机多卡readme里有样例

**Comment by sunzx8** [comment]
> CUDA报错，可能是OOM或者CUDA环境问题
> 
> 多机多卡readme里有样例

谢谢您，请问多机多卡是只要能ping通且两机都clone了swift和对应的模型文件就可以进行了吗

**Comment by sunzx8** [comment]
> CUDA报错，可能是OOM或者CUDA环境问题
> 
> 多机多卡readme里有样例

还有个问题，我发现用您给的lora微调方式虽然param显示只训练了很少的参数，但是显存消耗和全参数一模一样，请问这是不是实际没有转换过来？
<img width="471" alt="image" src="https://github.com/modelscope/swift/assets/136688632/9bea049d-451b-4a34-af3b-6f835bbcb664">

实际消耗显存和全参数微调coco-mini的一样是241gb

**Comment by sunzx8** [comment]
> > CUDA报错，可能是OOM或者CUDA环境问题
> > 多机多卡readme里有样例
> 
> 还有个问题，我发现用您给的lora微调方式虽然param显示只训练了很少的参数，但是显存消耗和全参数一模一样，请问这是不是实际没有转换过来？ <img alt="image" width="471" src="https://private-user-images.githubusercontent.com/136688632/331958604-9bea049d-451b-4a34-af3b-6f835bbcb664.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxODUwNzMsIm5iZiI6MTcxNjE4NDc3MywicGF0aCI6Ii8xMzY2ODg2MzIvMzMxOTU4NjA0LTliZWEwNDlkLTQ1MWItNGEzNC1hZjNiLTZmODM1YmJjYjY2NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMFQwNTU5MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMmM1ZjQ1Mzg4YTBmN2Y2ZTE4N2JiZDBmM2NiN2JlMjRjMDIzMTNjYTZiZWE5MzNlYmM1MDY2NWY3NDIwOGZiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.qKVW5_i8NdPA2kiVKIrVyNXWcE8-A4IEs4_hwB4eQ4U">
> 
> 实际消耗显存和全参数微调coco-mini的一样是241gb

CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 swift sft     --model_type internvl-chat-v1_5 --model_id_or_path /dev/shm/shawn/hf_ms_model/InternVL-Chat-V1-5     --dataset coco-mini-en-2  --sft_type lora

**Comment by hjh0119** [comment]
> 八卡device map可能会有问题，试下2/4卡
