### ISSUE TITLE
能否支持多卡DDP部署

### ISSUE THREAD

**Issue by WSC741606** [modelscope/swift#956]
**Describe the feature**
swift deploy，能否在多张卡上DDP部署同个模型，从而支持在对同个API有多个并发请求时并发处理？请求完全一样，但自动调度分配到不同卡上运算

**Comment by tastelikefeet** [comment]
DDP是训练技术，推理场景可以考虑用k8s封装一下

**Comment by WSC741606** [comment]
明白了，那能否把k8s封装也整合在deploy里面呢？一键部署太香了~
