### ISSUE TITLE
模型微调后不停止回答<|im_end|>

### ISSUE THREAD

**Issue by againcui** [modelscope/swift#960]
请问微调InternVL-Chat-V1-5后模型不停止的输出<|im_end|>是是为什么呢?
![image](https://github.com/modelscope/swift/assets/96865628/6cb66cee-06a2-4a25-90aa-70a05c8c3a55)

**Comment by hjh0119** [comment]
最新代码会有这个问题吗 正常会将<im_end>作为stop word

**Comment by againcui** [comment]
是的，只要微调后这个stop word就不会起到作用了

**Comment by againcui** [comment]
> 最新代码会有这个问题吗 正常会将<im_end>作为stop word
是的，只要微调后这个stop word就不会起到作用了

**Comment by againcui** [comment]
> 最新代码会有这个问题吗 正常会将<im_end>作为stop word

**Comment by dacian7** [comment]
> 请问微调InternVL-Chat-V1-5后模型不停止的输出<|im_end|>是是为什么呢? ![image](https://private-user-images.githubusercontent.com/96865628/331844682-6cb66cee-06a2-4a25-90aa-70a05c8c3a55.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk1NTY0ODAsIm5iZiI6MTcxOTU1NjE4MCwicGF0aCI6Ii85Njg2NTYyOC8zMzE4NDQ2ODItNmNiNjZjZWUtMDZhMi00YTI1LTkwYWEtNzBhMDVjOGMzYTU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI4VDA2Mjk0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlhOTgxNGQ4MDBhMzMyYmU3ZWYxNTY5NjY5N2VhYTMxMjE3ZmUwZjAwZDJiMDA5NmEzNjFkY2VmNWIwYzQxODUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gS5aZTPTXZfA0__SHVEbQQbPP2_yZu6dvC4ufrOCRig)

@againcui 请问你解决这个问题了吗?

**Comment by lylala8** [comment]
请问解决了吗，llama2 也有这个问题
