### ISSUE TITLE
TypeError: Subscripted generics cannot be used with class and instance checks

### ISSUE THREAD

**Issue by Hsu5918** [modelscope/swift#961]
hi, I installed the required environment following the steps, and then directly ran the Lora fine-tuning script for llama3-8b-instruct, but the following error occurred:
Traceback (most recent call last):
  File "/home/ubuntu/D/swift/swift/cli/sft.py", line 5, in <module>
    sft_main()
  File "/home/ubuntu/D/swift/swift/utils/run_utils.py", line 21, in x_main
    args, remaining_argv = parse_args(args_class, argv)
  File "/home/ubuntu/D/swift/swift/utils/utils.py", line 94, in parse_args
    parser = HfArgumentParser([class_type])
  File "/home/ubuntu/anaconda3/envs/swift/lib/python3.9/site-packages/transformers/hf_argparser.py", line 137, in __init__
    self._add_dataclass_arguments(dtype)
  File "/home/ubuntu/anaconda3/envs/swift/lib/python3.9/site-packages/transformers/hf_argparser.py", line 264, in _add_dataclass_arguments
    self._parse_dataclass_field(parser, field)
  File "/home/ubuntu/anaconda3/envs/swift/lib/python3.9/site-packages/transformers/hf_argparser.py", line 172, in _parse_dataclass_field
    field.type.__args__[0] if isinstance(None, field.type.__args__[1]) else field.type.__args__[1]
  File "/home/ubuntu/anaconda3/envs/swift/lib/python3.9/typing.py", line 720, in __instancecheck__
    return self.__subclasscheck__(type(obj))
  File "/home/ubuntu/anaconda3/envs/swift/lib/python3.9/typing.py", line 723, in __subclasscheck__
    raise TypeError("Subscripted generics cannot be used with"
TypeError: Subscripted generics cannot be used with class and instance checks

how to fix this? thx!

**Comment by JamePeng** [comment]
same problem i meet

**Comment by xlx777** [comment]
Use ```pip install 'ms-swift[all]' -U``` to solve my problem

**Comment by WEIC-7** [comment]
same problem i meet

**Comment by WEIC-7** [comment]
> Use `pip install 'ms-swift[all]' -U` to solve my problem

I am new, and I am trying to fine-tune DeepSeekv1, and I have done so following your instructions, but nothing  changed. How can I solve this problem? Are there any other methods I could try? Thank you!

**Comment by xlx777** [comment]
> > Use `pip install 'ms-swift[all]' -U` to solve my problem
> 
> I am new, and I am trying to fine-tune DeepSeekv1, and I have done so following your instructions, but nothing changed. How can I solve this problem? Are there any other methods I could try? Thank you!

The following is my solution. I hope it will be useful to you:
1. uninstall swift ```pip uninstall ms-swift```
2. use ```pip install 'ms-swift[all]' -U``` to install swift

**Comment by WEIC-7** [comment]
> > > Use `pip install 'ms-swift[all]' -U` to solve my problem
> > 
> > 
> > I am new, and I am trying to fine-tune DeepSeekv1, and I have done so following your instructions, but nothing changed. How can I solve this problem? Are there any other methods I could try? Thank you!
> 
> The following is my solution. I hope it will be useful to you:
> 
> 1. uninstall swift `pip uninstall ms-swift`
> 2. use `pip install 'ms-swift[all]' -U` to install swift

Thank you ! It works !!!

**Comment by WEIC-7** [comment]
> > > > Use `pip install 'ms-swift[all]' -U` to solve my problem
> > > 
> > > 
> > > I am new, and I am trying to fine-tune DeepSeekv1, and I have done so following your instructions, but nothing changed. How can I solve this problem? Are there any other methods I could try? Thank you!
> > 
> > 
> > The following is my solution. I hope it will be useful to you:
> > 
> > 1. uninstall swift `pip uninstall ms-swift`
> > 2. use `pip install 'ms-swift[all]' -U` to install swift
> 
> Thank you ! It works !!!

I find that:
1. `pip uninstall ms-swift`  : uninstalling ms-swift-2.1.0.dev0
2. `pip install 'ms-swift[all]' -U` : Successfully installed ms-swift-2.0.4 peft-0.10.0

It is possible that the problem appears on the version？
