### ISSUE TITLE
swift export  指定 --tensor_parallel_size     --gpu_memory_utilization   感觉不管用

### ISSUE THREAD

**Issue by LIUKAI0815** [modelscope/swift#969]
swift export  对百川2进行awq量化 指定 --tensor_parallel_size     --gpu_memory_utilization  感觉根本不管用，指定4张卡，只会用两张卡，然后就是爆显存

**Comment by Jintao-Huang** [comment]
quant_device_map是cpu吗

**Comment by LIUKAI0815** [comment]
这个也修改了。baichuan2-7B-chat和openbuddy-llama3-8b在24+22+15这三张卡工61G显存的情况下(第四张卡就不到5G显存)，肯定会爆显存。前者最多3轮，后者到16轮，

**Comment by LIUKAI0815** [comment]
@Jintao-Huang 目前来看，gptq没问题，awq不行。估计这也是huggingface上baichuan2里给出的大部分都是gptq的量化结果的原因吧，后者显存需要太高了？？？

**Comment by LIUKAI0815** [comment]
但使用tensorRT都没问题

**Comment by LIUKAI0815** [comment]
指定  --quant_n_samples 256  --quant_seqlen 1024   最大显存回到23-24G之间，4090最多只能到这个参数

**Comment by Jintao-Huang** [comment]
你的量化命令是什么呀

**Comment by LIUKAI0815** [comment]
@Jintao-Huang 也就是官网提供的，我在钉钉群里问了一下，修改quant_n_samples和--quant_seqlen变小一些。还有就是我自己试了最好指定一张卡，不要多卡
