### ISSUE TITLE
peft加载qwen1half_72b_chat的lora模型报错

### ISSUE THREAD

**Issue by jhjiang10** [modelscope/swift#975]
While copying the parameter named "base_model.model.model.layers.78.self_attn.v_proj.lora_B.default.weight", whose dimensions in the model are torch.Size([8192, 8]) and whose dimensions in the checkpoint are torch.Size([8192, 8]), an exception occurred : ('get_p2p_access:torch_npu/csrc/core/npu/NPUPeerToPeerAccess.cpp:80 NPU error, error code is 107000\n[ERROR] 2024-05-21-17:32:47 (PID:61348, Device:0, RankID:-1) ERR00100 PTA call acl api failed\n[Error]: Parameter verification failed.\n        Check whether the input parameters of the interface are correct.\nEE1001: The argument is invalid.Reason: rtDeviceCanAccessPeer execute failed, reason=[invalid value]\n        Solution: 1.Check the input parameter range of the function. 2.Check the function invocation relationship.\n        TraceBack (most recent call last):\n        input error:devId 0 is err:0x7110001[FUNC:DeviceCanAccessPeer][FILE:api_error.cc][LINE:1330]\n        The argument is invalid.Reason: rtDeviceCanAccessPeer execute failed, reason=[invalid value]\n        call rtDeviceCanAccessPeer failed, deviceId = 0, peerPhyId = 4, runtime result = 107000[FUNC:ReportCallError][FILE:log_inner.cpp][LINE:161]\n',).
	While copying the parameter named "base_model.model.model.layers.79.self_attn.q_proj.lora_A.default.weight", whose dimensions in the model are torch.Size([8, 8192]) and whose dimensions in the checkpoint are torch.Size([8, 8192]), an exception occurred : ('get_p2p_access:torch_npu/csrc/core/npu/NPUPeerToPeerAccess.cpp:80 NPU error, error code is 107000\n[ERROR] 2024-05-21-17:32:47 (PID:61348, Device:0, RankID:-1) ERR00100 PTA call acl api failed\n[Error]: Parameter verification failed.\n        Check whether the input parameters of the interface are correct.\nEE1001: The argument is invalid.Reason: rtDeviceCanAccessPeer execute failed, reason=[invalid value]\n        Solution: 1.Check the input parameter range of the function. 2.Check the function invocation relationship.\n        TraceBack (most recent call last):\n        input error:devId 0 is err:0x7110001[FUNC:DeviceCanAccessPeer][FILE:api_error.cc][LINE:1330]\n        The argument is invalid.Reason: rtDeviceCanAccessPeer execute failed, reason=[invalid value]\n        call rtDeviceCanAccessPeer failed, deviceId = 0, peerPhyId = 4, runtime result = 107000[FUNC:ReportCallError][FILE:log_inner.cpp][LINE:161]\n',).
	While copying the parameter named "base_model.model.model.layers.79.self_attn.q_proj.lora_B.default.weight", whose dimensions in the model are torch.Size([8192, 8]) and whose dimensions in the checkpoint are torch.Size([8192, 8]), an exception occurred : ('get_p2p_access:torch_npu/csrc/core/npu/NPUPeerToPeerAccess.cpp:80 NPU error, error code is 107000\n[ERROR] 2024-05-21-17:32:47 (PID:61348, Device:0, RankID:-1) ERR00100 PTA call acl api failed\n[Error]: Parameter verification failed.\n        Check whether the input parameters of the interface are correct.\nEE1001: The argument is invalid.Reason: rtDeviceCanAccessPeer execute failed, reason=[invalid value]\n        Solution: 1.Check the input parameter range of the function. 2.Check the function invocation relationship.\n        TraceBack (most recent call last):\n        input error:devId 0 is err:0x7110001[FUNC:DeviceCanAccessPeer][FILE:api_error.cc][LINE:1330]\n        The argument is invalid.Reason: rtDeviceCanAccessPeer execute failed, reason=[invalid value]\n        call rtDeviceCanAccessPeer failed, deviceId = 0, peerPhyId = 4, runtime result = 107000[FUNC:ReportCallError][FILE:log_inner.cpp][LINE:161]\n',).
	While copying the parameter named "base_model.model.model.layers.79.self_attn.k_proj.lora_A.default.weight", whose dimensions in the model are torch.Size([8, 8192]) and whose dimensions in the checkpoint are torch.Size([8, 8192]), an exception occurred : ('get_p2p_access:torch_npu/csrc/core/npu/NPUPeerToPeerAccess.cpp:80 NPU error, error code is 107000\n[ERROR] 2024-05-21-17:32:47 (PID:61348, Device:0, RankID:-1) ERR00100 PTA call acl api failed\n[Error]: Parameter verification failed.\n        Check whether the input parameters of the interface are correct.\nEE1001: The argument is invalid.Reason: rtDeviceCanAccessPeer execute failed, reason=[invalid value]\n        Solution: 1.Check the input parameter range of the function. 2.Check the function invocation relationship.\n        TraceBack (most recent call last):\n        input error:devId 0 is err:0x7110001[FUNC:DeviceCanAccessPeer][FILE:api_error.cc][LINE:1330]\n        The argument is invalid.Reason: rtDeviceCanAccessPeer execute failed, reason=[invalid value]\n        call rtDeviceCanAccessPeer failed, deviceId = 0, peerPhyId = 4, runtime result = 107000[FUNC:ReportCallError][FILE:log_inner.cpp][LINE:161]\n',).
	While copying the parameter named "base_model.model.model.layers.79.self_attn.k_proj.lora_B.default.weight", whose dimensions in the model are torch.Size([8192, 8]) and whose dimensions in the checkpoint are torch.Size([8192, 8]), an exception occurred : ('get_p2p_access:torch_npu/csrc/core/npu/NPUPeerToPeerAccess.cpp:80 NPU error, error code is 107000\n[ERROR] 2024-05-21-17:32:47 (PID:61348, Device:0, RankID:-1) ERR00100 PTA call acl api failed\n[Error]: Parameter verification failed.\n        Check whether the input parameters of the interface are correct.\nEE1001: The argument is invalid.Reason: rtDeviceCanAccessPeer execute failed, reason=[invalid value]\n        Solution: 1.Check the input parameter range of the function. 2.Check the function invocation relationship.\n        TraceBack (most recent call last):\n        input error:devId 0 is err:0x7110001[FUNC:DeviceCanAccessPeer][FILE:api_error.cc][LINE:1330]\n        The argument is invalid.Reason: rtDeviceCanAccessPeer execute failed, reason=[invalid value]\n        call rtDeviceCanAccessPeer failed, deviceId = 0, peerPhyId = 4, runtime result = 107000[FUNC:ReportCallError][FILE:log_inner.cpp][LINE:161]\n',).
	While copying the parameter named "base_model.model.model.layers.79.self_attn.v_proj.lora_A.default.weight", whose dimensions in the model are torch.Size([8, 8192]) and whose dimensions in the checkpoint are torch.Size([8, 8192]), an exception occurred : ('get_p2p_access:torch_npu/csrc/core/npu/NPUPeerToPeerAccess.cpp:80 NPU error, error code is 107000\n[ERROR] 2024-05-21-17:32:47 (PID:61348, Device:0, RankID:-1) ERR00100 PTA call acl api failed\n[Error]: Parameter verification failed.\n        Check whether the input parameters of the interface are correct.\nEE1001: The argument is invalid.Reason: rtDeviceCanAccessPeer execute failed, reason=[invalid value]\n        Solution: 1.Check the input parameter range of the function. 2.Check the function invocation relationship.\n        TraceBack (most recent call last):\n        input error:devId 0 is err:0x7110001[FUNC:DeviceCanAccessPeer][FILE:api_error.cc][LINE:1330]\n        The argument is invalid.Reason: rtDeviceCanAccessPeer execute failed, reason=[invalid value]\n        call rtDeviceCanAccessPeer failed, deviceId = 0, peerPhyId = 4, runtime result = 107000[FUNC:ReportCallError][FILE:log_inner.cpp][LINE:161]\n',).
	While copying the parameter named "base_model.model.model.layers.79.self_attn.v_proj.lora_B.default.weight", whose dimensions in the model are torch.Size([8192, 8]) and whose dimensions in the checkpoint are torch.Size([8192, 8]), an exception occurred : ('get_p2p_access:torch_npu/csrc/core/npu/NPUPeerToPeerAccess.cpp:80 NPU error, error code is 107000\n[ERROR] 2024-05-21-17:32:47 (PID:61348, Device:0, RankID:-1) ERR00100 PTA call acl api failed\n[Error]: Parameter verification failed.\n        Check whether the input parameters of the interface are correct.\nEE1001: The argument is invalid.Reason: rtDeviceCanAccessPeer execute failed, reason=[invalid value]\n        Solution: 1.Check the input parameter range of the function. 2.Check the function invocation relationship.\n        TraceBack (most recent call last):\n        input error:devId 0 is err:0x7110001[FUNC:DeviceCanAccessPeer][FILE:api_error.cc][LINE:1330]\n        The argument is invalid.Reason: rtDeviceCanAccessPeer execute failed, reason=[invalid value]\n        call rtDeviceCanAccessPeer failed, deviceId = 0, peerPhyId = 4, runtime result = 107000[FUNC:ReportCallError][FILE:log_inner.cpp][LINE:161]\n',).

**Comment by tastelikefeet** [comment]
似乎不是lora的报错，是NPU驱动报错了，能看下NPU是否可用吗

**Comment by jhjiang10** [comment]
> 似乎不是lora的报错，是NPU驱动报错了，能看下NPU是否可用吗

npu是可用的，我用前四张卡是可以加载的，换别的卡就不行
