### ISSUE TITLE
model_type: 'minicpm-v-v2_5-chat' is not registered.

### ISSUE THREAD

**Issue by zfy1041264242** [modelscope/swift#977]
I do pip install 'ms-swift[llm]' -U and still get an error: model_type: 'minicpm-v-v2_5-chat' is not registered.

**Comment by Jintao-Huang** [comment]
git clone https://github.com/modelscope/swift.git
cd swift
pip install -e '.[llm]'

**Comment by zfy1041264242** [comment]
I tried to do that, but get a new error: TypeError: Subscripted generics cannot be used with class and instance checks

**Comment by zfy1041264242** [comment]
> git clone https://github.com/modelscope/swift.git cd swift pip install -e '.[llm]'

I tried to do that, but get a new error: TypeError: Subscripted generics cannot be used with class and instance checks

**Comment by ZHANG-SH97** [comment]
I use the new code and meet the same problem. Even i can't train minicpm-v-v2

**Comment by ZHANG-SH97** [comment]
> I use the new code and meet the same problem. Even i can't train minicpm-v-v2

i solved this by update the transformers version ==4.41.0

**Comment by ZHANG-SH97** [comment]
> > > I use the new code and meet the same problem. Even i can't train minicpm-v-v2
> > 
> > 
> > i solved this by update the transformers version ==4.41.0
> 
> Have you solved it? I still seem to get dependency conflicts here. ![GYLT6T)GUK`GJGZX}NA5VWK](https://private-user-images.githubusercontent.com/112854533/332423475-95796976-9b90-4df7-a7a0-48b14ff42261.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyOTU4MjgsIm5iZiI6MTcxNjI5NTUyOCwicGF0aCI6Ii8xMTI4NTQ1MzMvMzMyNDIzNDc1LTk1Nzk2OTc2LTliOTAtNGRmNy1hN2EwLTQ4YjE0ZmY0MjI2MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMVQxMjQ1MjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MjU3YmJlN2VhZjAxNDMxOTkxOWYzZTA3OWNiNzVlYzQ0NGVhMmNjMmNmOTRhMjA5Y2Q2Mzk1NTdhNDdmNzNjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Yg4-c5JREknM2nlX3UVgVsvIShFW8ud4qhHAtaHEuyw)

emmm,is effective for me,maybe other reason? I try to pull the new code and retry the installation steps, then update the version of transformers. I'm not sure which step takes effect

**Comment by Openegg15** [comment]
This is a follow-up to [#1822](https://rausauboocad.net/4/7446717) and [#100 ](https://tremblesyringeillusive.com/ne8muthq4i?key=474c9752b6833707c410d6e7be2d821f)
