### ISSUE TITLE
Support RLAIF-V

### ISSUE THREAD

**Issue by choyakawa** [modelscope/swift#981]
**Describe the feature**
Please describe the feature requested here(请在这里描述需求)

RLAIF-V  effectively reduce the hallucination of different MLLMs

**Paste any useful information**
Paste any useful information, including papers, github links, etc.(请在这里描述其他有用的信息，比如相关的论文地址，github链接等)

https://github.com/RLHF-V/RLAIF-V/

**Comment by hjh0119** [comment]
support
