### ISSUE TITLE
自我认知微调失败

### ISSUE THREAD

**Issue by Talbot5** [modelscope/swift#984]
微调前
`import os
os.environ['CUDA_VISIBLE_DEVICES'] = '0'

from swift.llm import ModelType, InferArguments, infer_main
infer_args = InferArguments(model_type=ModelType.qwen1half_0_5b_chat)
infer_main(infer_args)`
微调
`import os
os.environ['CUDA_VISIBLE_DEVICES'] = '0'

from swift.llm import DatasetName, ModelType, SftArguments, sft_main

sft_args = SftArguments(
    model_type=ModelType.qwen1half_0_5b_chat,
    dataset=[DatasetName.alpaca_zh, DatasetName.alpaca_en],
    train_dataset_sample=1000,
    logging_steps=5,
    max_length=2048,
    learning_rate=5e-5,
    warmup_ratio=0.4,
    output_dir='output',
    lora_target_modules=['ALL'],
    self_cognition_sample=500,
    model_name=['小黄', 'Xiao Huang'],
    model_author=['魔搭', 'ModelScope'])
output = sft_main(sft_args)
best_model_checkpoint = output['best_model_checkpoint']
print(f'best_model_checkpoint: {best_model_checkpoint}')`

微调后

`import os
os.environ['CUDA_VISIBLE_DEVICES'] = '0'

from swift.llm import InferArguments, merge_lora, infer_main

best_model_checkpoint = 'output/qwen1half-0_5b-chat/v4-20240522-133722/checkpoint-50'
infer_args = InferArguments(ckpt_dir=best_model_checkpoint)
merge_lora(infer_args, device_map='auto')
result = infer_main(infer_args)
`

output:
<<<  你是谁
我是来自阿里云的大规模语言模型，我叫通义千问。
--------------------------------------------------

全流程都是按照官方文档来的，环境配置：ubuntu22.04-cuda12.1.0-py310-torch2.1.2-tf2.14.0-1.14.0

**Comment by sherry085** [comment]
是的，我也是同样的问题

**Comment by sherry085** [comment]
你好，现在self_cognition_sample 废弃了，你试下dataset=[f'{DatasetName.alpaca_zh}#500', f'{DatasetName.alpaca_en}#500', f'{DatasetName.self_cognition}#500']  [[](url)](https://github.com/modelscope/swift/blob/744c7b21086a97ccf725f7f9ce401547163ac411/docs/source/LLM/%E5%91%BD%E4%BB%A4%E8%A1%8C%E5%8F%82%E6%95%B0.md)
