### ISSUE TITLE
grok-1载入时间过长

### ISSUE THREAD

**Issue by Di-Zayn** [modelscope/swift#988]
你好，我已按照说明将ColossalAI版本的grok-1下载到本地，并使用项目脚本训练。然而，我发现模型载入时间很长（50分钟左右），而我使用ColossalAI的载入脚本只需要20分钟左右。请问这是为什么？我应该如何调整以快速载入？脚本设置如下：
nproc_per_node=8
PYTHONPATH=../../.. \
model_dir=""
data_dir=""
torchrun \
    --nproc_per_node=$nproc_per_node \
    --master_port 29500 \
    llm_sft.py \
    --model_type grok-1 \
    --model_id_or_path $model_dir \
    --sft_type lora \
    --tuner_backend peft \
    --dtype bf16 \
    --output_dir output \
    --ddp_backend nccl \
    --dataset $data_dir \
    --train_dataset_sample -1 \
    --num_train_epochs 1 \
    --max_length 512 \
    --check_dataset_strategy warning \
    --lora_rank 8 \
    --lora_alpha 32 \
    --lora_dropout_p 0.05 \
    --lora_dtype AUTO \
    --lora_target_modules DEFAULT \
    --gradient_checkpointing true \
    --batch_size 2 \
    --weight_decay 0.1 \
    --learning_rate 1e-4 \
    --gradient_accumulation_steps $(expr 16 / $nproc_per_node) \
    --max_grad_norm 0.5 \
    --warmup_ratio 0.03 \
    --eval_steps 100 \
    --save_steps 100 \
    --save_total_limit 2 \
    --logging_steps 10 \
    --deepspeed zero3-offload

**Comment by tastelikefeet** [comment]
一般第一次加载会慢一些，这是hf load模型的特性导致的，第二次会快很多
