### ISSUE TITLE
Can I deploy SWIFT-trained models without using SWIFT inference?

### ISSUE THREAD

**Issue by babla9** [modelscope/swift#989]
Thanks for your work! Since SWIFT doesn't support deployment (API server) for multimodal models, can I train models using SWIFT and deploy to other frameworks such as LMDeploy? Thanks!

**Comment by tastelikefeet** [comment]
We are writing the code of deployment of VLM models, it will be available in a few days: )

**Comment by babla9** [comment]
Great, thanks so much, that will be great! 

More generally, are VLMs fine-tuned by SWIFT structurally modified in anyway? Is the structure of the fine-tuned SWIFT model (checkpoint directory etc) the same as the code provided from the original model, are there optimizations made by SWIFT? 

I'm looking into deploying via other frameworks like LMDeploy (which supports some VLMs) and wanted to know if I could deploy there as well. 

Thanks, looking forward to deployment code support!

**Comment by Jintao-Huang** [comment]
maybe merge-lora

**Comment by tastelikefeet** [comment]
LMDeploy is a great framework, it's in our schedule already. Meanwhile multi-modal deployment has been supported, both command-line and web-ui
