### ISSUE TITLE
VLLM added support for MultiModal LLaVa - can SWIFT support LLaVa via API?

### ISSUE THREAD

**Issue by babla9** [modelscope/swift#990]
Thanks for your work! Since VLLM has support for LLaVa now, is it possible to support LLaVa inference via API endpoint? https://github.com/vllm-project/vllm/blob/main/examples/llava_example.py

**Comment by tastelikefeet** [comment]
You mean deployment? We are writing code of deployment, it will be merged in a few days

**Comment by Jintao-Huang** [comment]
Already supported.
